fix: "User not found" error when an authorized user is trying to navigate to the root page tm-95
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #100
Opened 2024-02-16 16:17 UTC by ShadowOfTheSpace

2024-02-16 16:44 UTC, what1s1ove approved these changes

2024-02-16 17:30 UTC, GEOFARL commented on apps/frontend/src/libs/helpers/check-if-show-loader/check-if-show-loader.helper.ts
> +import { ValueOf } from "~/libs/types/value-of.type.js";
```suggestion
import { ValueOf } from "~/libs/types/types.js";
```

2024-02-16 18:12 UTC, fshabanov requested changes

2024-02-16 18:12 UTC, fshabanov commented on apps/frontend/src/libs/components/app/app.tsx
> +	if (checkIfShowLoader(authDataStatus)) {
We don't need a helper for that, it is only used in one file

2024-02-16 19:11 UTC, GEOFARL approved these changes

2024-02-17 10:04 UTC, YourTeaChan approved these changes

2024-02-17 10:08 UTC, Vfivew approved these changes

2024-02-17 12:39 UTC, Oleksandra-Masiuk approved these changes

2024-02-17 14:19 UTC, merged