feat: add friends screen tm-94
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #103
Opened 2024-02-16 22:19 UTC by GEOFARL

![demo](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/f810cec7-2d43-4ccf-ba32-e2b486c2d04a)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/418475e3-bcff-4d36-a8f0-cbaf5e2ad18d)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/45f73d0b-0a42-46c1-b249-cb555c8b8d47)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/9fe3f663-1e43-4931-8bb3-c4c8de72cbaa)

2024-02-17 06:47 UTC, ShadowOfTheSpace requested changes

2024-02-17 06:47 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/button/button.tsx
> +				<Link className={buttonStyles} onClick={onClick} to={href}>
Why do we need `onClick` handler for `Link`? We already have it in button variant of `Button` component

2024-02-17 06:47 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/link/link.tsx
> +			onClick={onClick}
Same here

2024-02-17 06:47 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +			/>
Here you use `Button` component, but you use it like a button, not like a `link` (because it should contain a `href` prop to render as a link). So why do we need onClick for Link component?

2024-02-17 12:18 UTC, YourTeaChan approved these changes

2024-02-17 12:33 UTC, Oleksandra-Masiuk requested changes

2024-02-17 12:33 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +					status === "invited" ? styles["actions-invited"] : "",
```suggestion
					status === "invited"&& styles["actions-invited"] 
```

2024-02-17 12:33 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/friends/friends.tsx
> +			sortOrder[a.status] - sortOrder[b.status] > SortOrder.EQUAL
Can you please add a separate constant with a descriptive name for this condition?

2024-02-17 12:33 UTC, Oleksandra-Masiuk commented on packages/shared/src/libs/enums/sort-order.enum.ts
> +const SortOrder = {
you have `sortOrder` and `SortOrder` which is a bit confusing

2024-02-17 12:33 UTC, Oleksandra-Masiuk commented on packages/shared/src/modules/friends/libs/types/friend-response-dto.type.ts
> +	firstUser?: {
Please, liaise with @ShadowOfTheSpace regarding the naming of `firstUser` and `secondUser`. ([comment](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/105#discussion_r1493288649))

2024-02-17 15:12 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/friends/friends-api.ts
> +				contentType: ContentType.JSON,
```suggestion
```
I think if you don't send any data to server, you don't need to specify, what ContentType is it. It is optional in load method now

2024-02-17 15:14 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/types/friend.type.ts
> +	status: "friend" | "invited" | "requested" | "unknown";
Maybe it should be extracted to another enum?

2024-02-17 15:20 UTC, fshabanov requested changes

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/modules/friends/slices/actions.ts
> +	};
Why do we need `currentUserId` here?

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/modules/friends/slices/actions.ts
> +		}
This will be handled by authorization plugin in Backend

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/modules/friends/slices/actions.ts
> +	{ currentUserId: number | undefined; friendRequest: FriendAddNewResponseDto },
You don't need to send `currentUserId` to the Backend. Backend will already know the user from the token

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/modules/friends/slices/actions.ts
> +		}
Remove all these token errors

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/modules/friends/slices/friends.slice.ts
> +			friend.status = "friend";
Use map instead

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/modules/friends/slices/friends.slice.ts
> +			}
```suggestion
```

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +	friend: TFriend;
```suggestion
	friend: FriendDto;
```

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/pages/friends/libs/enums/status-rank.enum.ts
> +	UNKNOWN: 4,
We don't need it

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/pages/friends/hooks/use-friend-interactions/use-friend-interactions.ts
> +		sendRequest,
```suggestion
		handleAcceptRequest,
		handleDenyRequest,
		handleSendRequest,
```

2024-02-17 15:20 UTC, fshabanov commented on apps/frontend/src/pages/friends/friends.tsx
> +		return [...friends].sort((a, b) =>
For now let's keep in the same order as they come from Backend

2024-02-17 15:22 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/friends/slices/actions.ts
> +	const userId = auth.user?.id;
Maybe cast user type to UserAuthResponseDto, because we know that user is not null, if he already has access to friend page

2024-02-17 15:24 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/friends/slices/actions.ts
> +		if (!hasToken) {
Do we need that check here? If user on friend page, he is already authenticated because we have ProtectedRoute wrapper

2024-02-17 15:26 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/friends/slices/actions.ts
> +		}
Same here

2024-02-17 15:26 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/friends/slices/actions.ts
> +		}
And here

2024-02-17 15:27 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/friends/slices/friends.slice.ts
> +			friend.status = "friend";
Yes, I think using enum for friend status is better approach here

2024-02-17 15:33 UTC, GEOFARL commented on apps/frontend/src/modules/friends/slices/actions.ts
> +	{ currentUserId: number | undefined; friendRequest: FriendAddNewResponseDto },
I don't send it to the backend
I need currentUserId to be able to transform response from the backend and be able to identify who has sent a request to me, and who I've sent a request to.
For example, we can receive 
```
{ firstUserId: 2, secondUserId: 3, isInvitationAccepted: false }
```
and  
```
{ firstUserId: 3, secondUserId: 2, isInvitationAccepted: false }
 ```
 in the reducer I need to know my currentId to be able to give that friend record a proper status
 
 If my id is 2, then in the first case it's a request from me and I won't have 'accept' and 'deny' buttons ('request sent')
 in the second case I'll be able to accept or deny a friend request

2024-02-17 16:19 UTC, GEOFARL commented on apps/frontend/src/modules/friends/slices/actions.ts
> +	};
[described here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/103#discussion_r1493357574)

2024-02-17 16:25 UTC, what1s1ove requested changes

2024-02-17 16:25 UTC, what1s1ove commented on apps/frontend/src/modules/friends/libs/helpers/handle-friends-case.helper.ts
> +const handleFriendsCase = (
you do not need to write any mock functionality. only real, remove all mock functionality
work with who works on the backend

2024-02-17 16:51 UTC, GEOFARL commented on apps/frontend/src/modules/friends/libs/helpers/handle-friends-case.helper.ts
> +const handleFriendsCase = (
We don't have upload image functionality for know, so I mocked only imageUrl, all other data is real

2024-02-18 05:42 UTC, Ann-Maksay approved these changes

2024-02-18 06:59 UTC, fshabanov reviewed
When there are buttons in a card, there's a white line below the green section, make it all green

2024-02-18 07:17 UTC, what1s1ove requested changes
remove everything that we will not use. a lot of things depends on the backend

2024-02-18 07:17 UTC, what1s1ove commented on apps/frontend/src/libs/types/friend-dto.type.ts
> +type FriendDto = {
it should not be only on the frontend

2024-02-18 07:17 UTC, what1s1ove commented on apps/frontend/src/modules/friends/libs/helpers/handle-friends-case.helper.ts
> +				status: FriendStatus.FRIEND,
we will not have status or someting like this

2024-02-18 07:17 UTC, what1s1ove commented on apps/frontend/src/pages/friends/hooks/use-friend-interactions/use-friend-interactions.ts
> +const useFriendInteractions = (friend: FriendDto) => {
we do not need custom hooks

2024-02-18 07:58 UTC, GEOFARL commented on apps/frontend/src/modules/friends/libs/helpers/handle-friends-case.helper.ts
> +				status: FriendStatus.FRIEND,
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/b7374d6e-d78e-47e5-9941-6c0552de2129)

The data comes from the backend in the format that is really difficult to work on the frontend part. So I've decided to save in the redux store its transformed version to be able to work with it in components more easily.

Status is supposed to make it easier to work with combinations of (recipientUserId, isInvitationAccepted and senderUserId). It is problematic to determine in which relationships the users are.

Should I anyway remove this preprocessing and then move that logic to components?

2024-02-18 08:47 UTC, GEOFARL commented
> When there are buttons in a card, there's a white line below the green section, make it all green

fixed this

2024-02-19 08:07 UTC, fshabanov commented on apps/frontend/src/modules/friends/libs/helpers/handle-friends-case.helper.ts
> +				status: FriendStatus.FRIEND,
@GEOFARL In the list of friends we will not show the requests that we have sent, so there's no need to add this logic. We will only see our friends (accepted invitations) and people, who sent us a request to be friends.

2024-02-19 16:15 UTC, YourTeaChan approved these changes

2024-02-19 16:37 UTC, fshabanov requested changes

2024-02-19 16:37 UTC, fshabanov commented on apps/frontend/src/libs/modules/notification/libs/enums/notification-messages.enum.ts
> +const NotificationMessages = {
Enum names should be singular

2024-02-19 16:37 UTC, fshabanov commented on apps/frontend/src/modules/friends/slices/friends.slice.ts
> +			notification.success(NotificationMessages.FRIEND_INVITE_DENY_SUCCESS);
Should be in action

2024-02-19 19:05 UTC, fshabanov requested changes
In the video that you have attached:
1. I think we shouldn't remove a user from the view when we send a request. Keep it there and show that the request is sent
2. When you press "Accept" the size of the green part changes

2024-02-20 06:45 UTC, GEOFARL commented
> In the video that you have attached:
> 
> 1. I think we shouldn't remove a user from the view when we send a request. Keep it there and show that the request is sent
> 2. When you press "Accept" the size of the green part changes

fixed this

2024-02-20 11:28 UTC, Sytnikovakatya approved these changes

2024-02-20 15:34 UTC, what1s1ove requested changes

2024-02-20 15:34 UTC, what1s1ove commented on apps/frontend/package.json
> +		"react-tabs": "6.0.2",
```suggestion
```
you do not need an additional package for it

2024-02-20 15:34 UTC, what1s1ove commented on apps/frontend/src/libs/helpers/helpers.ts
> +export { createSelector } from "@reduxjs/toolkit";
```suggestion
```
let's avoid selector for now

2024-02-20 15:34 UTC, what1s1ove commented on apps/frontend/src/modules/friends/slices/friends.ts
> +const allSelectors = {
```suggestion
```
we will not use followers for now

2024-02-20 15:34 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/components.ts
> -export { Friend } from "./friend/friend.js";
apps/frontend/src/pages/friends/libs/components/components.ts

2024-02-20 15:34 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +		})();
```suggestion
			await dispatch(actions.follow({ id: friend.id })).unwrap().then(() => {
			setIsFollowing(true);
						});

```

2024-02-20 15:34 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +		void (async () => {
same

2024-02-20 15:34 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +	const imageUrl =
add this image to public for now

2024-02-20 15:34 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/potential-friends/potential-friends.tsx
> +		void dispatch(actions.getPotentialFriends());
let's do all load actions on page-level

2024-02-20 18:49 UTC, GEOFARL commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +		})();
Promise-returning function provided to attribute where a void return was expected  @typescript-eslint/no-misused-promises

2024-02-20 19:55 UTC, GEOFARL commented on apps/frontend/src/modules/friends/slices/friends.ts
> +const allSelectors = {
I don't quite understand what you mean by 'not use followers for now'
I need  a selector for now because I need a way to find out whether I currently follow a user or not, I can move that logic directly to the component, if necessary

2024-02-21 10:56 UTC, GEOFARL commented
Haven't seen new changes, one moment

2024-02-21 11:00 UTC, GEOFARL commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +				() => {},
> not sure that this is a required thing by linter

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/fba2ecb5-876f-48cb-8588-431000350a45)

2024-02-21 11:07 UTC, GEOFARL commented on apps/frontend/src/pages/friends/friends.tsx
> +			<Tabs tabs={TABS} />
should I remove tabs completely now?

2024-02-21 15:34 UTC, fshabanov requested changes

2024-02-21 15:34 UTC, fshabanov commented on apps/frontend/src/libs/components/tabs/styles.module.css
> +.tab--selected {
```suggestion
.tab-selected {
```

2024-02-21 15:51 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +			<Tabs tabs={TABS} />
yes, you should

2024-02-21 15:51 UTC, what1s1ove commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +				() => {},
Got it, thanks

2024-02-21 15:52 UTC, what1s1ove commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +				() => {},
add a `void` operator instead

2024-02-21 15:54 UTC, what1s1ove requested changes

2024-02-21 15:54 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +			<Tabs tabs={TABS} />
yes, you should

2024-02-21 15:54 UTC, what1s1ove commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +				<p className={styles["fullName"]}>{fullName}</p>
you do not have this styles 🤔

2024-02-21 15:54 UTC, what1s1ove commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +					alt={`portrait of ${fullName}`}
```suggestion
					alt={`User avatar`}
```

2024-02-21 15:54 UTC, what1s1ove commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +	const fullName = `${friend.firstName} ${friend.lastName}`;
```suggestion
```
write it without a variable

2024-02-21 17:20 UTC, GEOFARL commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +				<p className={styles["fullName"]}>{fullName}</p>
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/1a1511ab-5a9b-42fe-b5ee-030b76bb3525)
here they are

2024-02-22 06:32 UTC, GEOFARL commented on apps/frontend/src/modules/friends/slices/actions.ts
> +	notification,
I do not understand what you mean, can you clarify please?

2024-02-22 08:21 UTC, what1s1ove requested changes

2024-02-22 08:21 UTC, what1s1ove commented on apps/frontend/src/libs/components/link/link.tsx
> +	searchParams?: string;
```suggestion
```
not sure that you need it

2024-02-22 08:21 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +	const categoryToFriends = {
it should not be a query params of categories. it should be a separate route. ex
`friends/followers`, `friends/followings`
something similar to `auth/sign-up` and `auth/sign-in`

2024-02-22 09:35 UTC, Ann-Maksay commented on apps/frontend/src/modules/friends/slices/actions.ts
> +	notification,
`const { friendsApi, notification } = extra;`
Anywhere you need it @GEOFARL

2024-02-22 10:54 UTC, what1s1ove requested changes

2024-02-22 10:54 UTC, what1s1ove commented on apps/frontend/src/libs/enums/app-route.enum.ts
> +	FOLLOWINGS: "/friends/followings",
```suggestion
	FRIENDS_FOLLOWERS: "/friends/followers",
	FRIENDS_FOLLOWINGS: "/friends/followings",
```

2024-02-22 10:54 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +	const categoryToFriends = {
create a render function similar to that we have on the auth page

2024-02-22 11:33 UTC, Ann-Maksay commented on apps/frontend/src/libs/enums/app-route.enum.ts
>  	FRIENDS: "/friends",
Perhaps we should add a link to this page to menu items on the sidebar?

2024-02-22 11:50 UTC, GEOFARL commented on apps/frontend/src/libs/enums/app-route.enum.ts
>  	FRIENDS: "/friends",
Great point, but I'm not 100% sure that it is the part of my task

2024-02-22 15:44 UTC, what1s1ove requested changes

2024-02-22 15:44 UTC, what1s1ove commented on apps/frontend/src/libs/enums/app-route.enum.ts
>  	FRIENDS: "/friends",
let's do it

2024-02-22 15:44 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +	const getScreen = (screen: string): React.ReactNode => {
```suggestion
	const handleScreenRender = (screen: string): React.ReactNode => {
```

2024-02-22 15:44 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +	const getScreen = (screen: string): React.ReactNode => {
and I will change it on the auth screen

2024-02-22 16:42 UTC, fshabanov requested changes

2024-02-22 16:42 UTC, fshabanov commented on apps/frontend/src/modules/friends/slices/actions.ts
> +import { type UserAuthResponseDto } from "../../auth/auth.js";
```suggestion
import { type UserAuthResponseDto } from "~/modules/auth/auth.js";
```

2024-02-22 18:15 UTC, GEOFARL commented on apps/frontend/src/libs/enums/app-route.enum.ts
>  	FRIENDS: "/friends",
<img width="268" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/8f606358-6cba-429c-9506-0f0b41f6582e">

I have added a new item to sidebar, however it needs some changes, should I make them here, or will it be a separate task?

2024-02-22 20:13 UTC, fshabanov commented on apps/frontend/src/libs/enums/app-route.enum.ts
>  	FRIENDS: "/friends",
@GEOFARL just add some margin 👀

2024-02-23 06:20 UTC, GEOFARL commented on apps/frontend/src/libs/enums/app-route.enum.ts
>  	FRIENDS: "/friends",
@fshabanov there is no need in margin according to the Figma design, the active sidebar item should be highlighted depending on the current page
<img width="396" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/5e9fe61a-2440-4d84-8045-270e857f9347">

2024-02-23 07:03 UTC, what1s1ove approved these changes
Please, resolve conflicts and I will merge it

2024-02-23 08:24 UTC, fshabanov approved these changes

2024-02-23 08:25 UTC, merged