feat: create friends functionality tm-39
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #105
Opened 2024-02-17 08:44 UTC by Vfivew

2024-02-17 09:13 UTC, YourTeaChan approved these changes

2024-02-17 09:19 UTC, GEOFARL commented on apps/backend/src/modules/auth/auth.controller.ts
> +					}>,
Probably unnecessary change

2024-02-17 09:19 UTC, GEOFARL commented on apps/backend/src/modules/friends/friend.controller.ts
> +import { UserAuthResponseDto } from "../users/users.js";
```suggestion
import { type UserAuthResponseDto } from "../users/users.js";
```

2024-02-17 09:19 UTC, GEOFARL commented on apps/backend/src/modules/friends/friend.repository.ts
> +		return friendInvite || null;
```suggestion
		return friendInvite ?? null;
```
```suggestion
		return friendInvite || null;
```

2024-02-17 09:19 UTC, GEOFARL commented on packages/shared/src/modules/friends/libs/exceptions/friend-error/friend-error.exception.ts
> +
Probably this imports should be changed

2024-02-17 09:19 UTC, GEOFARL commented on packages/shared/src/modules/friends/libs/types/frined-response-dto.type.ts
> +import { UserAuthResponseDto } from "src/modules/users/users.js";
```suggestion
import { type UserAuthResponseDto } from "~/modules/users/users.js";
```

2024-02-17 09:19 UTC, GEOFARL commented on packages/shared/src/modules/friends/libs/types/frined-response-dto.type.ts
> +import { FriendAcceptResponseDto } from "../../friends.js";
```suggestion
import { type FriendAcceptResponseDto } from "../../friends.js";
```

2024-02-17 09:26 UTC, YourTeaChan commented on packages/shared/src/modules/friends/libs/exceptions/friend-error/friend-error.exception.ts
> +
I wanted to add this comment as well, but in `auth-error.exeption.ts` imports look the same as here

2024-02-17 09:51 UTC, ShadowOfTheSpace approved these changes

2024-02-17 10:00 UTC, Vfivew commented on apps/backend/src/modules/auth/auth.controller.ts
> +					}>,
I just keep code in one style
![style](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/a761b136-6f51-40a5-8e31-1b39128c8843)

2024-02-17 10:06 UTC, Vfivew commented on packages/shared/src/modules/friends/libs/types/frined-response-dto.type.ts
> +import { UserAuthResponseDto } from "src/modules/users/users.js";
As for the type - thank you. As for “~”, we don’t have a definition in shared/tsconfig.json
![Uploading mod1.png…]()

2024-02-17 10:31 UTC, Oleksandra-Masiuk requested changes

2024-02-17 10:31 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/friends/friend.controller.ts
> +	 *      description: Send friend invite and take this invite obj
```suggestion
	 *      description: Send friend invite and return this invite obj
```

2024-02-17 10:31 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/friends/friend.repository.ts
> +			throw new FriendError(
Please, throw errors from service

2024-02-17 10:31 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/friends/friend.repository.ts
> +			throw new FriendError(
Overall, all business logic is supposed to be handled in services, while in repos we mostly just make requests. Please, review this function

2024-02-17 10:31 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/friends/friend.repository.ts
> +	public async createFriendshipInvite(
Please, check my comment regarding the `respondRequest` function in this repository

2024-02-17 10:34 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.repository.ts
> +	public async searchFriendsByValue(
if you use value to search users by name, rename function to `searchFriendsByName`

2024-02-17 14:56 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +	public async createFriendshipInvite(
I'm really sorry, but I didn't quite understand what exactly is wrong here. If it's about error handling, then createFriendshipInvite in the repository doesn't handle them (it simply returns null). If the feedback is about poorly chosen names, I'll correct that.

2024-02-17 15:32 UTC, fshabanov requested changes

2024-02-17 15:32 UTC, fshabanov commented on apps/backend/src/db/migrations/20240215141622_create_friends_table.ts
> +			.notNullable()
Let's make it nullable. `null` means that there's no response to the invitation (it wasn't accepted or denied)

2024-02-17 15:32 UTC, fshabanov commented on apps/backend/src/libs/modules/server-application/base-server-application.ts
> +import { type FriendService } from "~/modules/friends/friend.service.js";
```suggestion
import { type FriendService } from "~/modules/friends/friends.js";
```

2024-02-17 15:32 UTC, fshabanov commented on apps/backend/src/db/migrations/20240215141622_create_friends_table.ts
> +	});
Add a unique constraint to `[ColumnName.SENDER_USER_ID, ColumnName.RECIPIENT_USER_ID]`

2024-02-17 15:32 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +		}
The business logic should be in service

2024-02-17 15:32 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +	public async getFriendInviteById(
```suggestion
	public async getFriendInvitationById(
```

2024-02-17 15:32 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +		if (!friendRequest || friendRequest.recipientUserId !== userId) {
Remove all logic from repository

2024-02-17 15:32 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +import { FriendError, HTTPCode } from "shared";
Imports from shared should be done in libs folder files

2024-02-17 15:32 UTC, fshabanov commented on apps/backend/src/modules/users/user.controller.ts
> +			limit = RequestSetting.DEFAULT_LIMIT,
```suggestion
			limit = PaginationDefaultValue.DEFAULT_LIMIT,
```

2024-02-17 15:32 UTC, fshabanov commented on apps/backend/src/modules/users/user.controller.ts
> +			offset = RequestSetting.DEFAULT_OFFSET,
Receive `page` instead of offset

2024-02-17 15:32 UTC, fshabanov commented on packages/shared/src/libs/enums/api-path.enum.ts
> +	FRIEND: "/friends",
```suggestion
	FRIENDS: "/friends",
```

2024-02-17 15:32 UTC, fshabanov commented on packages/shared/src/modules/friends/libs/enums/friend-api-path.enum.ts
> +const FriendApiPath = {
```suggestion
const FriendsApiPath = {
```

2024-02-17 15:32 UTC, fshabanov commented on packages/shared/src/modules/friends/libs/exceptions/friend-error/friend-error.exception.ts
> +
It is okay in shared folder

2024-02-17 15:32 UTC, fshabanov commented on packages/shared/src/modules/friends/libs/types/frined-response-dto.type.ts
> +import { type UserAuthResponseDto } from "src/modules/users/users.js";
Fix file name

2024-02-17 15:32 UTC, fshabanov commented on packages/shared/src/modules/users/libs/enums/users-api-path.enum.ts
> +	SEARCH: "/search",
Should be a part of Friends

2024-02-17 15:41 UTC, Vfivew commented on packages/shared/src/modules/users/libs/enums/users-api-path.enum.ts
> +	SEARCH: "/search",
Okay, that's not a problem.
But it seemed to me that custom search refers to user logic. If we need to search for a user elsewhere in our application, we will have to turn to a friendly service. Will this be the right decision?

2024-02-17 17:18 UTC, fshabanov commented on packages/shared/src/modules/users/libs/enums/users-api-path.enum.ts
> +	SEARCH: "/search",
In this case we are searching for friends and will use userService for that. Searching for friends and searching for a user elsewhere most probably will have a different logic, so we will need a new API endpoint for that

2024-02-18 14:23 UTC, GEOFARL approved these changes

2024-02-19 07:59 UTC, fshabanov requested changes

2024-02-19 07:59 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +			path: FriendsApiPath.SEARCH,
Why is /search a POST request?

2024-02-19 07:59 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +			page = PaginationDefaultValue.DEFAULT_OFFSET,
```suggestion
			page = PaginationDefaultValue.DEFAULT_PAGE,
```

2024-02-19 07:59 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +			isInvitationAccepted: false,
Should be null when we just create it

2024-02-19 07:59 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +	public async createFriendInvite(
```suggestion
	public async createFriendInvitation(
```

2024-02-19 07:59 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +				isInvitationAccepted: isAccepted ? true : false,
```suggestion
				isInvitationAccepted: isAccepted,
```

2024-02-19 08:07 UTC, what1s1ove requested changes

2024-02-19 08:07 UTC, what1s1ove commented on packages/shared/src/modules/friends/libs/types/friend-response-dto.type.ts
> +import { type FriendAcceptResponseDto } from "../../friends.js";
specify path

2024-02-19 08:07 UTC, what1s1ove commented on packages/shared/src/modules/friends/libs/types/friend-response-dto.type.ts
> +import { type UserAuthResponseDto } from "src/modules/users/users.js";
we do not have an alias in shared folder

2024-02-19 08:07 UTC, what1s1ove commented on apps/backend/src/modules/friends/friend.controller.ts
> +			limit = PaginationDefaultValue.DEFAULT_LIMIT,
let's do not add pagination for now

2024-02-19 08:07 UTC, what1s1ove commented on apps/backend/src/modules/friends/friend.service.ts
> +			// if you try delete not your request you will get error too
```suggestion
```

2024-02-19 08:12 UTC, fshabanov requested changes

2024-02-19 08:12 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +	}
We don't need to return the requests that the current user have sent (the ones that are not accepted)

2024-02-19 08:15 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +	}
Also, we don't need to fetch the data for current user

2024-02-19 10:37 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +			isInvitationAccepted: false,
Im use Entity for now add it will be null

2024-02-19 10:37 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +	public async createFriendInvite(
Now im use Repo create

2024-02-19 17:34 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +	}
I'll leave this question unresolved, but I'll open a review.
I solved the first question.
Regarding the second remark, I did not seem to return the current user, this does not happen.
Only the user is returned - which we need for display
![here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/9c083c3b-e7b4-4d65-9477-81a409117194)

2024-02-19 17:35 UTC, GEOFARL commented on apps/backend/src/modules/friends/friend.service.ts
> +import { UserAuthResponseDto } from "shared";
```suggestion
import { type UserAuthResponseDto } from "~/modules/users/users.js";
```

2024-02-19 19:08 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +	}
About the second point - you are right, I missed that. Resolving the conversation

2024-02-19 19:30 UTC, fshabanov requested changes

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/db/migrations/20240215141622_create_friends_table.ts
> +			.inTable("users")
```suggestion
			.references(ColumnName.ID)
			.inTable(TableName.USERS)
```

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/db/migrations/20240215141622_create_friends_table.ts
> +			.onDelete("CASCADE");
```suggestion
			.onDelete(DELETE_STRATEGY);
```
Create a constant for that

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +				this.respondToFriendRequestt(
```suggestion
				this.respondToFriendRequest(
```

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +			method: "POST",
I think PATCH would be more correct here

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +	private async getPotentialFriends(
Add swagger docs for this as well

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +			status: HTTPCode.OK,
Status should be 201 here

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +			.query()
userModel should be used in user repository
Here you can use userService

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +			);
What are the structures of `friendsFoSenderUser`, `user.senderUser` and `user.recipientUser`? I'm not sure to understand this logic

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +		const allFriend = [...friendsForSenderUser, ...friendsForRecipientUser];
```suggestion
		const friends = [...friendsForSenderUser, ...friendsForRecipientUser];
```

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +			.withGraphFetched("senderUser.userDetails(selectFirstNameLastName)");
I think we will see the invitations that we have rejected

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +		}
Not sure if we want to delete, @what1s1ove what do you think?

2024-02-19 19:30 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +	async respondToFriendRequestt({
```suggestion
	async respondToFriendRequest({
```

2024-02-19 21:32 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +			.withGraphFetched("senderUser.userDetails(selectFirstNameLastName)");
I'm currently removing rejected requests from the database. If we decide not to do this, I will refactor this function.

2024-02-19 22:21 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +			);
Each user has an array
recipientUser and senderUser.
Each entry has a recipientUserId and a senderUserId.
The task that this function solves is to return an array of users with whom the current user (id field) has no relationship.
Structure - I'll add it.
I’ll also add refactoring (this is not the final version, as I understand it, we still need to get rid of UserModel.
![better](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/739dd035-1c5d-47b4-988e-23a15ecf804a)
![ex](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/491ed3ae-bb55-4a86-aafe-fc66c3f4cb8b)

2024-02-20 06:50 UTC, GEOFARL commented
Sorry, confused this PR with mine

2024-02-20 08:45 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +			.query()
I don't quite understand this. The function looks for potential friends and returns me exactly the UserModel.
Our userService does not check the relationship between two users.
Would you like me to return all users from UserService and check in FriendRepo if they could potentially be friends?

2024-02-20 11:25 UTC, Sytnikovakatya approved these changes

2024-02-20 15:35 UTC, what1s1ove requested changes

2024-02-20 15:35 UTC, what1s1ove commented on packages/shared/src/modules/friends/libs/types/friend-response-dto.type.ts
> +	recipientUser?: {
please, apply all changes that are related to `follow` functionaity and remove all useless things

2024-02-20 19:26 UTC, GEOFARL commented on packages/shared/src/modules/friends/libs/types/friend-follow-succes-response-dto.type.ts
> +type FriendFollowSuccesResponseDto = {
```suggestion
type FriendFollowSuccessResponseDto = {
```

2024-02-20 20:46 UTC, Vfivew commented on packages/shared/src/modules/friends/libs/types/friend-response-dto.type.ts
> +	recipientUser?: {
I refactor the code. 
May be i should rename friend modul to subscribers module or something like this?

2024-02-21 10:12 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +		}
I update it for now.

2024-02-21 10:26 UTC, what1s1ove commented on apps/backend/src/modules/friends/friend.repository.ts
> +	public async searchUserByName({
```suggestion
```
we do not need to implement filter in this task

2024-02-21 10:27 UTC, what1s1ove commented on apps/backend/src/modules/friends/friend.service.ts
> +	public async searchUserByName({
```suggestion
```

2024-02-21 10:27 UTC, what1s1ove commented on apps/backend/src/modules/users/user-details/user-details.model.ts
> +			selectFirstNameLastName(builder): QueryBuilder<UserDetailsModel> {
```suggestion
```

2024-02-21 10:27 UTC, what1s1ove commented on apps/backend/src/modules/users/user.entity.ts
> +	public getFirstName(): string {
```suggestion
```

2024-02-21 10:27 UTC, what1s1ove commented on apps/backend/src/modules/users/user.entity.ts
> +	public getLastName(): string {
```suggestion
```

2024-02-21 10:28 UTC, what1s1ove commented on apps/backend/src/modules/users/user.model.ts
> +	public senderUser!: FriendModel[];
```suggestion
```
it should be  part of user model

2024-02-21 10:28 UTC, what1s1ove commented on apps/backend/src/modules/users/user.model.ts
> +	public static override get modifiers(): Modifiers<QueryBuilder<UserModel>> {
```suggestion
```

2024-02-21 10:28 UTC, what1s1ove commented on packages/shared/src/modules/friends/libs/enums/friend-api-path.enum.ts
> +	SEARCH: "/search",
```suggestion
```

2024-02-21 10:55 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +	public async searchUserByName({
I have a task to implement a search functionality for users. That why i create this func.
At the meeting, I asked how the search should work (return data depending on the current filter or not). So i use filter here.
What kind of search does the task require of me, if thats func is wrong?  (screen added)
P.S. if I need to search by name, then I have to consider the current filter when looking up the user in the database (as discussed in the meeting)
![search](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/3ee2cdda-4b66-4a3f-a8d3-d8549abfad3a)

2024-02-21 15:01 UTC, Vfivew commented on packages/shared/src/modules/friends/libs/enums/friend-api-path.enum.ts
> +const FriendApiPath = {
I use it everywhere "friend"
need to go to "friends" ?

2024-02-21 15:59 UTC, what1s1ove requested changes

2024-02-21 16:35 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/friends/friend.repository.ts
> +		const deletedSubscribe = await this.friendModel.query().deleteById(id);
I think `deletedSubscribe` breaks rule B19. Maybe you should rename it to `isSubscriptionDeleted` or something like that

2024-02-21 17:19 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/friends/friend.repository.ts
> +}
I think you should extract business logic from the repository to service and create only a query here. And it is not so obvious that the `update` method updates some fields under the hood without receiving what to update

2024-02-21 17:26 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/friends/friend.service.ts
> +		const subscribeExist = await this.friendRepository.getSubscribeByUserId(
```suggestion
		const isSubscribeExist = await this.friendRepository.getSubscribeByUserId(
```

2024-02-21 17:28 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/friends/friend.service.ts
> +			FriendErrorMessage.FRIEND_REQUEST_EXIST,
```suggestion
			FriendErrorMessage.FRIEND_REQUEST_ALREADY_EXISTS,
```

2024-02-21 17:46 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/friends/friend.service.ts
> +		}
```suggestion

		if (!updatedSubscription) {
			throw new FriendError(
				FriendErrorMessage.FRIEND_UPDATE_ERROR,
				HTTPCode.BAD_REQUEST,
			);
		}
		return updatedSubscription.toObject();
```

2024-02-21 19:19 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +			.query()
My bad, let's keep it

2024-02-21 19:43 UTC, fshabanov requested changes

2024-02-21 19:43 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +		const deletedSubscribe = await this.friendModel.query().deleteById(id);
But its value is `number` not `boolean`

2024-02-21 19:43 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +		return deletedSubscribe ? true : false;
```suggestion
		return Boolean(deletedSubscribe);
```

2024-02-21 19:43 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +	async getSubscribeByRequestId(
```suggestion
	async getSubscriptionByRequestId(
```
Change everywhere

2024-02-21 19:43 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +		const subscribeExist = await this.friendRepository.getSubscribeByUserId(
Again, it's not a boolean

2024-02-21 19:43 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +		}
Do this in other places as well

2024-02-21 19:43 UTC, fshabanov commented on packages/shared/src/modules/friends/libs/enums/friend-error-message.enum.ts
> +	FRIEND_REQUEST_ERROR: "You are not subscribed to this user",
Put dot at the end of each so that we have the same style everywhere

2024-02-21 19:43 UTC, fshabanov commented on packages/shared/src/modules/friends/libs/enums/friend-api-path.enum.ts
> +	POTENTIAL_FOLLOWING: "/potential-following",
```suggestion
	POTENTIAL_FOLLOWINGS: "/potential-followings",
```
I think we will receive more than one?

2024-02-21 21:09 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/friends/friend.repository.ts
> +		const deletedSubscribe = await this.friendModel.query().deleteById(id);
@fshabanov I got it, sorry)

2024-02-22 18:06 UTC, Vfivew commented on apps/backend/src/modules/users/user.model.ts
> +			},
Now i got only user_followers without model and entity.
So now UserModel have userFollowers.
![userss](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/443d4085-4945-42a4-8c9d-b77282d80634)

2024-02-23 06:23 UTC, GEOFARL approved these changes

2024-02-23 14:20 UTC, what1s1ove requested changes

2024-02-23 14:20 UTC, what1s1ove commented on apps/backend/src/libs/types/repository.type.ts
> +	findAll(id: number): Promise<T[]>;
```suggestion
	delete(id: number): Promise<boolean>;
	find(id: number): Promise<T | null>;
	findAll(): Promise<T[]>;
```
you can not modify this things here. since this is a general, for all repositories they should be reusable

2024-02-23 14:20 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240215141622_create_friends_table.ts
> +	USER_FOLLOWERS: "user_followers",
```suggestion
	USER_FOLLOWERS: "user_friends",
```
please use it everywhere (in all files). if you want to change `friends` to `followers`, than you also need to change frontend part of the app

2024-02-23 14:36 UTC, fshabanov requested changes

2024-02-23 14:36 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +				following_id: userId,
```suggestion
				followerId: id,
				followingId: userId,
```

2024-02-23 14:36 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +	public async getSubscriptionByRequestId(
```suggestion
	public async getIsSubscribedByRequestId(
```
You return Boolean

2024-02-23 14:36 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +				updatedAt: this.userModel.raw("?", [new Date()]),
Abstract Model already does that

2024-02-23 14:36 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +		const isSubscribeExist =
```suggestion
		const isSubscriptionExist =
```

2024-02-23 14:36 UTC, fshabanov commented on apps/backend/src/modules/users/user.model.ts
> +						from: "user_followers.follower_id",
```suggestion
						from: "DatabaseTableName.TABLE_NAME.follower_id",
```

2024-02-23 14:36 UTC, fshabanov commented on packages/shared/src/modules/friends/libs/enums/friend-error-message.enum.ts
> +	FRIEND_IS_ALREADY_TRACKING: "You already follow this user.",
```suggestion
	FRIEND_IS_ALREADY_FOLLOWING: "You already follow this user.",
```

2024-02-23 14:36 UTC, fshabanov commented on packages/shared/src/modules/friends/libs/validation-schemas/friend-request-parameters.validation-schema.ts
> +		}),
`z.number().int()`

2024-02-23 15:00 UTC, Vfivew commented on packages/shared/src/modules/friends/libs/validation-schemas/friend-request-parameters.validation-schema.ts
> +		}),
Actually, I had to split it into two checks. When I pass a number in the params, it throws an error because it's treated as a string.

2024-02-23 17:20 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.repository.ts
> +				updatedAt: this.userModel.raw("?", [new Date()]),
I wouldn't actually implement this func. This update cannot update anything other than the date or id.
We also have a userRepo for the updated user.
Or do we need to update the ID? This will be fine?

2024-02-23 17:20 UTC, Vfivew commented on apps/backend/src/db/migrations/20240215141622_create_friends_table.ts
> +	USER_FOLLOWERS: "user_followers",
I corrected the table.
But I have my doubts.
Maybe we should really rename everything to friend -> follower?
If you agree with me, I will do it right now.

2024-02-23 17:55 UTC, ShadowOfTheSpace requested changes

2024-02-23 17:55 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/friends/friend.repository.ts
> +				id: id,
```suggestion
				id,
```

2024-02-24 07:51 UTC, fshabanov requested changes

2024-02-24 07:51 UTC, fshabanov commented on apps/backend/src/db/migrations/20240215141622_create_friends_table.ts
> +	USER_FOLLOWERS: "user_friends",
Key and value should be the same

2024-02-24 07:51 UTC, fshabanov commented on apps/backend/src/libs/modules/database/libs/enums/database-table-name.enum.ts
> +	USER_FOLLOWERS: "user_friends",
Same here

2024-02-24 07:51 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +import { type UserModel } from "../users/user.model.js";
Combine import from ~/modules/users

2024-02-24 16:18 UTC, what1s1ove requested changes

2024-02-24 16:18 UTC, what1s1ove commented on apps/backend/src/libs/types/repository.type.ts
> +	create(payload: unknown): Promise<T | null>;
```suggestion
	create(payload: unknown): Promise<T>;
```
it should always returns T

2024-02-24 16:18 UTC, what1s1ove commented on apps/backend/src/modules/users/user.model.ts
> +			userFollowers: {
```suggestion
			userFriends: {
```

2024-02-24 16:18 UTC, what1s1ove commented on packages/shared/src/modules/friends/libs/enums/friends-api-path.enum.ts
> +	ID: "/:id",
```suggestion
	$ID: "/:id",
```
for all dynamic params

2024-02-24 16:18 UTC, what1s1ove commented on packages/shared/src/modules/friends/libs/enums/friends-api-path.enum.ts
> +	UNFOLLOW_BY_ID: "/unfollow/:id",
```suggestion
	UNFOLLOW_BY_$ID: "/unfollow/:id",
```

2024-02-24 16:18 UTC, what1s1ove commented on packages/shared/src/modules/friends/libs/exceptions/friend-error/friend-error.exception.ts
> +	public constructor(message: string, status: ValueOf<typeof HTTPCode>) {
should be an object in constructor''s params
please, follow the style of the rest of application

2024-02-24 17:07 UTC, Vfivew commented on packages/shared/src/modules/friends/libs/exceptions/friend-error/friend-error.exception.ts
> +	public constructor(message: string, status: ValueOf<typeof HTTPCode>) {
Actually, I tried. But I saw such a structure in the adjacent folder and did the same. It turned out I used the wrong structure. I'm sorry.
![tryint](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/472c8f23-538e-463b-b04d-62828b8c6c54)

2024-02-24 17:41 UTC, fshabanov requested changes

2024-02-24 17:41 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +			handler: (options) =>
B27

2024-02-24 18:41 UTC, fshabanov requested changes

2024-02-24 18:41 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +		});
```suggestion
		return followings.map((user) => user.toObject());
```
Should be inline, this is an exception in B27

2024-02-24 18:41 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +			handler: (options) =>
Not resolved

2024-02-24 18:43 UTC, fshabanov requested changes

2024-02-24 18:43 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +			UserEntity.initialize({
Not resolved

2024-02-25 06:23 UTC, what1s1ove requested changes

2024-02-25 06:23 UTC, what1s1ove commented on packages/shared/src/modules/friends/libs/exceptions/friend-error/friend-error.exception.ts
> +class FriendError extends HTTPError {
Please, do the following
<img width="546" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/42296182/9d280b6a-bc59-4720-a93b-8e8002a6e3c3">

2024-02-25 06:23 UTC, what1s1ove commented on packages/shared/src/modules/friends/libs/enums/friend-request-validation-message.enum.ts
> +const FriendRequestValidationMessage = {
```suggestion
const FriendValidationMessage = {
```
do not forget about file-name
please, follow the style of the rest of the application

2024-02-25 08:49 UTC, fshabanov requested changes

2024-02-25 14:04 UTC, KrasKa2 requested changes

2024-02-25 14:04 UTC, KrasKa2 commented on packages/shared/src/modules/friends/libs/validation-schemas/friend.validation-schema.ts
Name of file has to correspond  name of constant `addFriend`

2024-02-25 15:02 UTC, what1s1ove requested changes
Fix all @KrasKa2  comments

2024-02-25 16:48 UTC, fshabanov requested changes

2024-02-25 16:48 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +				message: FriendErrorMessage.FRIEND_UPDATE_ERROR,
```suggestion
				message: FriendErrorMessage.FRIEND_DELETE_ERROR,
```

2024-02-25 16:48 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +		const isDeletedSuccess = await this.friendRepository.delete(id);
```suggestion
		const isDeleted = await this.friendRepository.delete(id);
```

2024-02-25 16:48 UTC, fshabanov commented on apps/backend/src/modules/users/user.model.ts
> +			userFriends: {
```suggestion
			friends: {
```

2024-02-25 18:52 UTC, what1s1ove approved these changes

2024-02-25 18:53 UTC, merged