feat(backend/frontend/shared): add course functionality  tm-27
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #133
Opened 2024-02-20 19:14 UTC by tarmiel

![Screenshot_2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/1236c2b9-8cfe-44e3-ad30-b0cce8b7b721)

2024-02-20 21:27 UTC, MappariChan commented on apps/backend/src/modules/courses/course.controller.ts
> +} from "./libs/types/types.js";
```suggestion
import { type UserAuthResponseDto } from "../users/users.js";
import { type CourseService } from "./course.service.js";
import { CoursesApiPath } from "./libs/enums/enums.js";
import {
	type AddCourseRequestDto,
	type CourseSearchRequestDto,
} from "./libs/types/types.js";
```

2024-02-20 21:38 UTC, Vfivew commented on apps/backend/src/modules/courses/course.controller.ts
> + *            type: string
VendorCourseId is exactly string?

2024-02-20 21:41 UTC, MappariChan commented on apps/backend/src/modules/courses/course.repository.ts
> +import { Repository } from "~/libs/types/types.js";
```suggestion
import { type Repository } from "~/libs/types/types.js";
```

2024-02-20 21:43 UTC, Vfivew commented on apps/backend/src/modules/courses/course.service.ts
> +import { CourseFieldsMapping } from "./libs/types/types.js";
```suggestion
import { type CourseFieldsMapping } from "./libs/types/types.js";
```

2024-02-20 21:44 UTC, Vfivew commented on apps/backend/src/modules/courses/libs/types/course-fields-mapping.type.ts
> +import { CourseDto } from "./types.js";
```suggestion
import { type CourseDto } from "./types.js";
```

2024-02-20 21:45 UTC, Vfivew commented on apps/backend/src/modules/user-courses/user-course.repository.ts
> +import { Repository } from "~/libs/types/types.js";
```suggestion
import { type Repository } from "~/libs/types/types.js";
```

2024-02-20 21:46 UTC, Vfivew commented on apps/backend/src/modules/user-courses/user-course.service.ts
> +import { CourseDto } from "../courses/courses.js";
```suggestion
import { type CourseDto } from "../courses/courses.js";
```

2024-02-20 21:46 UTC, MappariChan commented on apps/backend/src/modules/courses/course.service.ts
> +} from "./libs/types/types.js";
```suggestion
import {
	type CourseDto,
	type CourseFieldsMapping,
	type CourseSearchRequestDto,
	type CourseSearchResponseDto,
	type VendorResponseDto,
} from "./libs/types/types.js";
```

2024-02-20 21:48 UTC, Vfivew commented on apps/backend/src/modules/vendors/udemy.service.ts
> +import { VendorService } from "./libs/types/types.js";
```suggestion
import { type VendorService } from "./libs/types/types.js";
```

2024-02-20 21:48 UTC, MappariChan commented on apps/backend/src/modules/courses/course.service.ts
> +} from "./libs/types/types.js";
```suggestion
import {
        type CourseFieldsMapping,
	type CourseDto,
	type CourseSearchRequestDto,
	type CourseSearchResponseDto,
	type VendorResponseDto,
} from "./libs/types/types.js";
```

2024-02-20 21:55 UTC, MappariChan commented on apps/backend/src/modules/user-courses/user-courses.ts
> +import { UserModel } from "../users/user.model.js";
```suggestion
import { UserModel } from "~/modules/users/users.js";
```

2024-02-20 22:02 UTC, MappariChan commented on apps/backend/src/modules/vendors/vendor.repository.ts
> +import { Repository } from "~/libs/types/types.js";
```suggestion
import { type Repository } from "~/libs/types/types.js";
```

2024-02-20 22:06 UTC, MappariChan commented on apps/backend/src/modules/vendors/vendors.ts
> +import { http } from "../../libs/modules/http/http.js";
```suggestion
import { http } from "~/libs/modules/http/http.js";
```

2024-02-21 09:06 UTC, YourTeaChan commented on apps/frontend/src/pages/overview/overview.tsx
>  import { UserAuthResponseDto } from "~/modules/users/users.js";
```suggestion
import { actions as userCourseActions } from "~/modules/user-courses/user-courses.js";
import { type UserAuthResponseDto } from "~/modules/users/users.js";
```

2024-02-21 09:06 UTC, YourTeaChan commented on apps/frontend/src/libs/components/button/button.tsx
> +	label?: string;
Why do you set `label` as optional? We already have `hasVisuallyHiddenLabel` prop to hide `label`.

2024-02-21 09:22 UTC, GEOFARL commented on apps/frontend/src/pages/overview/libs/constants/constants.ts
> +const SEARCH_COURSES_DELAY_MS = 500;
probably, as separate files

2024-02-21 09:48 UTC, KrasKa2 commented on apps/backend/src/modules/user-courses/user-courses.ts
> +import { UserModel } from "../users/user.model.js";
@fshabanov , щось ми не можемо домовитись)) у нас є таке правило?

2024-02-21 09:55 UTC, tarmiel commented on apps/backend/src/modules/user-courses/user-courses.ts
> +import { UserModel } from "../users/user.model.js";
Within a module, it is preferred to use relative imports. In other cases, it is better to use absolute

2024-02-21 10:14 UTC, fshabanov requested changes

2024-02-21 10:14 UTC, fshabanov commented on apps/backend/src/modules/vendors/udemy.service.ts
> +			.then((course) => course as Record<string, unknown>);
Prefer async await approach

2024-02-21 10:14 UTC, fshabanov commented on apps/backend/src/modules/vendors/udemy.service.ts
> +			throw new ApplicationError({ message: "Wrong response from Udemy API" });
Why ApplicationError everywhere? We should have CourseError and throw it. Also, use ExceptionMessage enum

2024-02-21 10:14 UTC, fshabanov commented on apps/backend/src/modules/vendors/vendor.repository.ts
> +		return vendors.map((vendor) =>
B27

2024-02-21 10:14 UTC, fshabanov commented on apps/frontend/src/libs/components/course/course.tsx
> +	const source = VendorsLogoPath[vendor.key] || "";
```suggestion
	const source = VendorsLogoPath[vendor.key] ?? "";
```

2024-02-21 10:14 UTC, fshabanov commented on apps/frontend/src/libs/components/input/input.tsx
> +	wide?: boolean;
B19

2024-02-21 10:14 UTC, fshabanov commented on apps/frontend/src/libs/components/modal/modal.tsx
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
```suggestion
```

2024-02-21 10:14 UTC, fshabanov commented on apps/frontend/src/libs/enums/vendors-logo-path.enum.ts
> +import UdemyLogo from "~/assets/img/svg/udemy-logo.svg";
```suggestion
import udemyLogo from "~/assets/img/svg/udemy-logo.svg";
```

2024-02-21 10:14 UTC, fshabanov commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +	const { courses, isLoading, vendors } = useAppSelector((state) => ({
B27

2024-02-21 10:14 UTC, fshabanov commented on apps/frontend/src/pages/overview/libs/hooks/use-search-course.hook.ts
> +
I don't think it is a good place for this logic

2024-02-21 10:15 UTC, KrasKa2 commented on apps/backend/src/modules/user-courses/user-courses.ts
> +import { UserModel } from "../users/user.model.js";
ok

2024-02-21 10:17 UTC, what1s1ove requested changes

2024-02-21 10:17 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-app-form/use-app-form.hook.ts
> +	watch: UseFormWatch<T>;
```suggestion
```
do not see any places where you need to use it

2024-02-21 10:17 UTC, what1s1ove commented on apps/frontend/src/libs/components/portal/portal.tsx
> +const noOverflowClass = styles["no-overflow"] as string;
```suggestion
const NO_OVERFLOW_CLASS = styles["no-overflow"] as string;
```

2024-02-21 10:17 UTC, what1s1ove commented on apps/frontend/src/libs/components/modal/modal.tsx
> +/* eslint-disable jsx-a11y/click-events-have-key-events */
```suggestion
```
you can not disable anything just because

2024-02-21 10:17 UTC, what1s1ove commented on apps/frontend/src/libs/components/modal/modal.tsx
> +			<div
just use a `dialog` element

2024-02-21 10:17 UTC, what1s1ove commented on apps/frontend/src/libs/components/input/input.tsx
> +	wide?: boolean;
```suggestion
```
all common component should be 100% width by default

2024-02-21 10:17 UTC, what1s1ove commented on apps/frontend/src/libs/components/input/input.tsx
> +	label?: string;
```suggestion
	errors: FieldErrors<T>;
	label: string;
```
can not be optional

2024-02-21 10:17 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.service.ts
> +		for (const vendor of vendors) {
use `flatMap` instead

2024-02-21 10:17 UTC, what1s1ove commented on apps/backend/src/modules/courses/libs/types/course-fields-mapping.type.ts
> +	keyof Omit<CourseDto, "id" | "vendor">,
do not use omit. write everything explicitly

2024-02-21 10:17 UTC, what1s1ove commented on apps/backend/src/modules/courses/libs/enums/udemy-fields-mapping.enum.ts
> +const UdemyFieldsMapping: CourseFieldsMapping = {
```suggestion
```
just add a new method in `udemy` service to map keys

2024-02-21 10:17 UTC, what1s1ove commented on apps/backend/src/modules/user-courses/user-course.repository.ts
> +		return Promise.resolve(entity);
implement all

2024-02-21 10:17 UTC, what1s1ove commented on apps/backend/src/modules/user-courses/user-courses.ts
> +import { UserModel } from "../users/user.model.js";
should be an alias

2024-02-21 10:17 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/types/vendor-service.type.ts
> +type SearchParameters = {
you do not need to implement pagination in this task

2024-02-21 10:17 UTC, what1s1ove commented on apps/backend/src/modules/vendors/udemy.service.ts
> +			throw new ApplicationError({ message: "Wrong response from Udemy API" });
should be a course error

2024-02-21 10:17 UTC, what1s1ove commented on apps/backend/src/modules/vendors/vendor.repository.ts
> +		return Promise.resolve(true);
implement all methods

2024-02-21 10:26 UTC, tarmiel commented on apps/frontend/package.json
> +		"debounce": "2.0.0",
I tried to implement debounce as hook useDebounce, but @fshabanov recommended to use library and I'm not sure that we really need to create own implementation

2024-02-21 10:29 UTC, tarmiel commented on apps/frontend/src/libs/components/button/button.tsx
> +	style?: "clear" | "filled" | "outlined";
We need just a clickable icon and it was recommended to use button component for that, so I clear variant as just a clickable button element without styles

2024-02-21 10:29 UTC, KrasKa2 commented on apps/backend/src/modules/user-courses/user-courses.ts
> +import { UserModel } from "../users/user.model.js";
fixed in all places

2024-02-21 10:38 UTC, tarmiel commented on apps/frontend/src/pages/overview/libs/hooks/use-search-course.hook.ts
> +const useSearchCourse = (): {
This is the main point. I moved this logic apart to not create a big messy modal component that would be difficult to read and debug. Is it really problem?

2024-02-21 10:50 UTC, KrasKa2 commented on apps/backend/src/db/migrations/20240216111216_add_courses_table.ts
> +const VENDOR_ID = "id";
I agree with "enum TableName". 
But don't think, that it good idea to use ColumnName.ID for vendors table, because it is supposed, that ColumnName - it is list of courses columns and in theory, they can be different.

2024-02-21 11:40 UTC, KrasKa2 commented on apps/backend/src/modules/vendors/udemy.service.ts
> +			throw new ApplicationError({ message: "Wrong response from Udemy API" });
@fshabanov , CourseError or VendorError?
And should I create separate Error for every module (Vendors, Courses, UserCourses)?

2024-02-21 13:30 UTC, KrasKa2 commented on apps/backend/src/modules/courses/course.service.ts
> +		for (const vendor of vendors) {
it is not prettier, because of Promises:
```
const vendorsCourses = Promise.all(vendors.map(async (vendor) => {
	return await this.findAllByVendor(parameters, vendor);
}));
let courses = (await vendorsCourses).flatMap((items) => items); 
```

2024-02-22 06:44 UTC, GEOFARL commented on apps/frontend/src/pages/overview/overview.tsx
> +	const [isAddCourseModalOpen, setIsAddCourseModalOpen] = useState(false);
```suggestion
	const [isAddCourseModalOpen, setIsAddCourseModalOpen] = useState<boolean>(false);
```

2024-02-22 10:58 UTC, tarmiel commented on apps/frontend/src/libs/enums/vendors-logo-path.enum.ts
> +const VendorsLogoPath: Record<string, string> = {
I believe mapper will be more obvious and convenient

2024-02-22 12:30 UTC, Sytnikovakatya approved these changes

2024-02-22 15:26 UTC, YourTeaChan commented on apps/backend/src/modules/vendors/libs/types/vendor-service.type.ts
> +import { CourseDto } from "shared";
```suggestion
import { type CourseDto } from "shared";
```
And maybe import should be from `types.ts`, not from `shared`

2024-02-22 18:25 UTC, GEOFARL approved these changes

2024-02-23 16:57 UTC, fshabanov requested changes

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/courses/course.controller.ts
> + *    schemas:
```suggestion
/**
 * @swagger
 * components:
 *    schemas:
```

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/courses/course.controller.ts
> +						params: { id: number };
From params we always receive a string

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/courses/course.repository.ts
> +			throw new ApplicationError({
```suggestion
			throw new CourseError({
```

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/vendors/libs/types/course-fields-mapping.type.ts
> +import { type CourseDto } from "../../../courses/libs/types/types.js";
```suggestion
import { type CourseDto } from "~/modules/courses/libs/types/types.js";
```

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/vendors/udemy.service.ts
> +// and error "ReferenceError: Cannot access 'UserModel' before initialization"
```suggestion
```

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/vendors/udemy.service.ts
> +	private gethHeaders(): Headers {
```suggestion
	private getHeaders(): Headers {
```

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/vendors/udemy.service.ts
> +				"Wrong response from Udemy API",
Move the message to enum

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/vendors/vendor.repository.ts
> +import { CourseError, HTTPCode } from "shared";
Shouldn't import directly from shared

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/vendors/vendor.service.ts
> +		const vendors = await this.findAll();
Instead of getting everything from DB and then filtering, get only the data you need from DB

2024-02-23 16:57 UTC, fshabanov commented on apps/backend/src/modules/vendors/vendor.service.ts
> +	// todo find
```suggestion
```

2024-02-23 16:57 UTC, fshabanov commented on apps/frontend/src/libs/components/modal/modal.tsx
> +	const contentReference = useRef<HTMLDivElement>(null);
```suggestion
	const contentReference = useRef<HTMLDivElement | null>(null);
```

2024-02-23 16:57 UTC, fshabanov commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +		const formData = getValues();
```suggestion
	const handleSearchCourses = (data: Type): void => {
```
And use `handleSubmit` from `useAppForm`

2024-02-23 16:57 UTC, fshabanov commented on packages/shared/src/libs/enums/notification-message.enum.ts
> +} as const;
We already have NotificationMessage in frontend, shouldn't it be there?

2024-02-23 16:57 UTC, fshabanov commented on packages/shared/src/modules/user-courses/libs/enums/user-courses-api-path.enum.ts
> +	$USER_ID: "/:id",
```suggestion
	$USER_ID: "/:userId",
```

2024-02-23 16:57 UTC, fshabanov commented on packages/shared/src/modules/vendors/libs/enums/vendors-api-path.enum.ts
> +	$VENDOR_ID: "/:id",
```suggestion
	$VENDOR_ID: "/:vendorId",
```

2024-02-23 19:37 UTC, KrasKa2 commented on apps/backend/src/db/migrations/20240221125053_add_vendors_to_table.ts
> +	await knex(TableName.VENDORS).del();
It was needed before adding `.onDelete("CASCADE")`
Now I removed it. Thank you!

2024-02-24 08:21 UTC, fshabanov requested changes

2024-02-24 08:21 UTC, fshabanov commented on apps/backend/src/modules/courses/course.controller.ts
> +		const success = await this.courseService.delete(Number.parseInt(courseId));
```suggestion
		const success = await this.courseService.delete(Number(courseId));
```
You can check in validation if it is an integer or no

2024-02-24 08:21 UTC, fshabanov commented on apps/backend/src/modules/courses/course.service.ts
> +		);
```suggestion
		const vendorsCourses = await Promise.all(
			vendors.map((vendor) => {
				return this.findAllByVendor(search, vendor);
			}),
		);
```
`await Promise.all` should be enough

2024-02-24 08:21 UTC, fshabanov commented on apps/backend/src/modules/courses/libs/types/types.ts
> +	type VendorResponseDto,
Vendor is a separate module

2024-02-24 08:21 UTC, fshabanov commented on apps/backend/src/modules/vendors/libs/enums/udemy/udemy-fields-mapping.enum.ts
> +import { CourseField } from "~/modules/vendors/vendors.js";
I think this will result in circular dependencies

2024-02-24 08:21 UTC, fshabanov commented on apps/backend/src/modules/vendors/libs/enums/udemy/udemy-fields-mapping.enum.ts
> +import { type CourseFieldsMapping } from "../../../libs/types/types.js";
```suggestion
import { type CourseFieldsMapping } from "~/modules/vendors/libs/types/types.js";
```

2024-02-24 08:42 UTC, fshabanov requested changes

2024-02-24 08:42 UTC, fshabanov commented on apps/frontend/src/libs/components/course/course.tsx
> +					/>
Should redirect to the course page on a vendor's website

2024-02-24 09:10 UTC, KrasKa2 commented on apps/backend/src/modules/vendors/libs/enums/udemy/udemy-fields-mapping.enum.ts
> +import { CourseField } from "~/modules/vendors/vendors.js";
Maybe, thank you! 
Changed it to:
`import { CourseField } from "~/modules/vendors/libs/enums/enums.js";`

2024-02-24 16:31 UTC, what1s1ove requested changes

2024-02-24 16:31 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240221125053_add_vendors_to_table.ts
add_udemy_vendor
specify migration name

2024-02-24 16:31 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/types/vendor-service.type.ts
> +			"description" | "image" | "title" | "url" | "vendorCourseId"
you have a type for it `CourseFieldForMap`. reuse it

2024-02-24 16:31 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	style?: "clear" | "filled" | "outlined";
you should use `hasVisuallyHiddenLabel ` and `icon` props intstead

2024-02-24 16:31 UTC, what1s1ove commented on apps/frontend/src/libs/components/courses/courses.tsx
>  		<div className={styles["container"]}>
is not resolved

2024-02-24 16:31 UTC, what1s1ove commented on apps/frontend/src/libs/enums/vendors-logo-path.enum.ts
> +const VendorsLogoPath: Record<string, string> = {
please use my approach instead

2024-02-24 16:31 UTC, what1s1ove commented on apps/frontend/src/libs/enums/vendors-logo-path.enum.ts
> +const VendorsLogoPath: Record<string, string> = {
it even not a enum, but a map

2024-02-24 16:31 UTC, what1s1ove commented on apps/frontend/src/modules/courses/slices/actions.ts
> +const search = createAsyncThunk<
```suggestion
const getAll = createAsyncThunk<
```
because `getAll` always will be a search in the future

2024-02-24 16:31 UTC, what1s1ove commented on packages/shared/src/modules/vendors/libs/exceptions/vendor-error.exception.ts
> +	public constructor(message: string, status: ValueOf<typeof HTTPCode>) {
parameters should be an object. see HTTPError

2024-02-24 16:31 UTC, what1s1ove commented on packages/shared/src/modules/courses/libs/exceptions/course-error.exception.ts
> +	public constructor(message: string, status: ValueOf<typeof HTTPCode>) {
same

2024-02-24 16:31 UTC, what1s1ove commented on packages/shared/src/libs/helpers/debounce/debounce.helper.ts
> +	const clear = (): void => {
you do not use `clear` so delete it

2024-02-24 16:31 UTC, what1s1ove commented on packages/shared/src/libs/helpers/debounce/debounce.helper.ts
> +function debounce<T extends unknown[]>(
```suggestion
const debounce<T extends unknown[]> = (
```

2024-02-24 16:31 UTC, what1s1ove commented on packages/shared/src/libs/helpers/debounce/debounce.helper.ts
> +function debounce<T extends unknown[]>(
```suggestion
function initDebounce<T extends unknown[]>(
```
do not forget about file name

2024-02-24 16:32 UTC, fshabanov requested changes

2024-02-24 16:32 UTC, fshabanov commented on apps/backend/src/db/migrations/20240221125053_add_vendors_to_table.ts
> +	await knex(TableName.VENDORS).del();
I don't think we should delete everything before adding. Migrations are always run in order and only once, so we will never delete anything

2024-02-24 16:32 UTC, fshabanov commented on apps/backend/src/modules/courses/course.controller.ts
> +			handler: (options) =>
B27, fix for all

2024-02-24 16:32 UTC, fshabanov commented on apps/backend/src/modules/courses/course.repository.ts
> +import { DatabaseTableName } from "~/libs/modules/database/libs/enums/enums.js";
```suggestion
import { DatabaseTableName } from "~/libs/modules/database/database.js";
```

2024-02-24 16:32 UTC, fshabanov commented on apps/backend/src/modules/courses/course.service.ts
> +			throw new ApplicationError({
I think it should be VendorError or CourseError

2024-02-24 16:32 UTC, fshabanov commented on apps/frontend/src/libs/components/portal/portal.tsx
> +			if (!wasOverflowHidden) {
`!wasOverflowHidden` means there's no `no-overflow` class, so there's nothing to remove

2024-02-24 16:32 UTC, fshabanov commented on apps/frontend/src/libs/modules/notification/libs/enums/notification-message.enum.ts
> +	COURSE_ADDED: "Course successfully added to your account",
```suggestion
	COURSE_ADDED: "Course successfully added to your account.",
```

2024-02-24 16:32 UTC, fshabanov commented on apps/frontend/src/pages/overview/libs/helpers/get-vendors-from-form.helper.ts
> +		.filter(([, value]) => value)
You never use key, use Object.values

2024-02-24 16:32 UTC, fshabanov commented on apps/frontend/src/pages/overview/overview.tsx
> +	const { courses, isLoading, user } = useAppSelector((state) => ({
B27

2024-02-24 16:32 UTC, fshabanov commented on packages/shared/src/modules/courses/libs/enums/course-error-message.enum.ts
> +	COURSE_IS_ALREADY_ADDED_FOR_USER: "Course was already added for user",
```suggestion
	COURSE_IS_ALREADY_ADDED_FOR_USER: "Course was already added for user.",
```
Same for all

2024-02-24 16:32 UTC, fshabanov commented on packages/shared/src/modules/courses/libs/types/course-search-request-dto.type.ts
> +	vendorsKeys?: string;
```suggestion
	vendorsKey?: string;
```
Or if it should be an array, fix that

2024-02-24 17:00 UTC, tarmiel commented on packages/shared/src/libs/helpers/debounce/debounce.helper.ts
> +	const clear = (): void => {
I use it in add-course-modal

2024-02-24 17:40 UTC, tarmiel commented on apps/frontend/src/pages/overview/libs/helpers/get-vendors-from-form.helper.ts
> +		.filter(([, value]) => value)
I need to filter by true values and return the corresponding keys.

2024-02-24 17:43 UTC, fshabanov commented on apps/frontend/src/pages/overview/libs/helpers/get-vendors-from-form.helper.ts
> +		.filter(([, value]) => value)
You're right, I confused it

2024-02-24 17:54 UTC, tarmiel commented on packages/shared/src/modules/courses/libs/types/course-search-request-dto.type.ts
> +	vendorsKeys?: string;
Here is a problem, because on client I use URLSearchParams to make a request, but array of strings come to backend as string with commas

2024-02-24 18:06 UTC, KrasKa2 commented on packages/shared/src/modules/vendors/libs/exceptions/vendor-error.exception.ts
> +	public constructor(message: string, status: ValueOf<typeof HTTPCode>) {
@what1s1ove should I set `cause`? Maybe, `cause = 'VendorError'`?

2024-02-24 18:59 UTC, KrasKa2 commented on packages/shared/src/modules/courses/libs/types/course-search-request-dto.type.ts
> +	vendorsKeys?: string;
@fshabanov value for this field is vendors keys separated by coma. Can I leave it as it is?

2024-02-24 19:16 UTC, KrasKa2 commented on packages/shared/src/modules/courses/libs/types/course-search-request-dto.type.ts
> +	vendorsKeys?: string;
In order to get array, we have to send `&vendorsKey[]=udemy&vendorsKey[]=coursera`. But in this case in controller I get:
`query Empty <[Object: null prototype] {}> {
  search: 'google',
  'vendorsKey[]': [ 'udemy', 'coursera' ]
}`

2024-02-25 06:19 UTC, what1s1ove commented on packages/shared/src/modules/vendors/libs/exceptions/vendor-error.exception.ts
> +	public constructor(message: string, status: ValueOf<typeof HTTPCode>) {
you do not need to set it. usually the cause is also the Error object

2024-02-25 06:26 UTC, what1s1ove requested changes

2024-02-25 06:26 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.entity.ts
> +		vendor?: VendorEntity | null;
```suggestion
		vendor: VendorEntity | null;
```

2024-02-25 06:26 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.entity.ts
> +		vendor?: VendorEntity | null;
```suggestion
		vendor: VendorEntity | null;
```

2024-02-25 06:30 UTC, what1s1ove requested changes

2024-02-25 06:30 UTC, what1s1ove commented on packages/shared/src/modules/vendors/libs/exceptions/vendor-error.exception.ts
> +	public constructor(arguments_: Constructor) {
<img width="487" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/42296182/c44035a9-964e-45eb-9a11-3e757d5b073d">
please follow the style for arguments

2024-02-25 06:30 UTC, what1s1ove commented on packages/shared/src/modules/courses/libs/exceptions/course-error.exception.ts
> +	public constructor(arguments_: Constructor) {
same

2024-02-25 06:36 UTC, KrasKa2 commented on packages/shared/src/modules/vendors/libs/exceptions/vendor-error.exception.ts
> +	public constructor(arguments_: Constructor) {
Can I change it in `FileError` too?

2024-02-25 06:37 UTC, what1s1ove requested changes

2024-02-25 06:37 UTC, what1s1ove commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +	}, [debouncedSearchCourses]);
```suggestion
```
during component unmount react will kill all things that are related to this component. it meats that you do not need to do it. and btw remove `.clear()` from the debounce function

2024-02-25 06:37 UTC, what1s1ove commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +	const debouncedSearchCourses = initDebounce(
A10

2024-02-25 07:20 UTC, what1s1ove commented on packages/shared/src/modules/vendors/libs/exceptions/vendor-error.exception.ts
> +	public constructor(arguments_: Constructor) {
It's already changed. Merge main into your branch please

2024-02-25 09:14 UTC, KrasKa2 commented on packages/shared/src/modules/courses/libs/types/course-search-request-dto.type.ts
> +	vendorsKeys?: string;
[Here](https://github.com/fastify/fastify/issues/2841) they advise to use [qs lib](https://www.npmjs.com/package/qs). But I think it is not fast to implement this. So, I have just changed name to `vendorsKey`

2024-02-25 13:10 UTC, fshabanov reviewed
I think you don't save course sections in the DB, you should save them as well when adding a course

2024-02-25 15:21 UTC, what1s1ove requested changes

2024-02-25 15:21 UTC, what1s1ove commented on apps/frontend/src/libs/components/courses/courses.tsx
>  		<div className={styles["container"]}>
is not resolved

2024-02-25 19:26 UTC, fshabanov requested changes

2024-02-25 19:26 UTC, fshabanov commented on packages/shared/src/modules/user-courses/libs/validation-schemas/validation-schemas.ts
> +export { userIdParameter } from "./user-id-parameter-validation-schema.js";
```suggestion
export { userIdParameter } from "./user-id-parameter.validation-schema.js";
```

2024-02-25 19:26 UTC, fshabanov commented on packages/shared/src/modules/courses/libs/validation-schemas/validation-schemas.ts
> +export { courseIdParameter } from "./course-id-parameter-validation-schema.js";
```suggestion
export { courseIdParameter } from "./course-id-parameter.validation-schema.js";
```

2024-02-25 19:26 UTC, fshabanov commented on packages/shared/src/modules/courses/libs/enums/course-error-message.enum.ts
> +	COURSE_IS_ALREADY_EXISTS: "Course was already added for user.",
These messages are the same

2024-02-25 19:26 UTC, fshabanov commented on packages/shared/src/modules/courses/libs/enums/course-error-message.enum.ts
> +	NOT_FOUND_COURSE: "Not found course.",
```suggestion
	NOT_FOUND_COURSE: "Course not found.",
```
Do the same for all

2024-02-26 09:52 UTC, what1s1ove requested changes

2024-02-26 09:52 UTC, what1s1ove commented on apps/backend/src/modules/vendors/fields-mapper/fields-mapper.ts
> +class FieldsMapper<FROM_FIELD extends string, TO_FIELD extends string> {
```suggestion
```
you do not need an additional class, it just should be a part of `VendorService` interface (a new method). In the implementation (ex. UdemyService) in the new method just describe all logic of mapping that is related to Udemy

2024-02-27 07:14 UTC, what1s1ove requested changes

2024-02-27 07:14 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/enums/udemy/course-section-field.enum.ts
> +	// CONTENT_SUMMARY: "content_summary",
remove it or uncomment

2024-02-27 07:14 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/enums/enums.ts
> +export { UdemyDefaultPageParameter } from "./udemy/udemy-default-page-parameter.enum.js";
```suggestion
export { ApiPath } from "./api-paths.enum.js";
export { CourseField } from "./course-field.enum.js";
export { CourseSectionField } from "./course-section-field.enum.js";
export { UdemyCourseFieldsMapping } from "./udemy-course-fields-mapping.enum.js";
export { UdemyCourseSectionFieldsMapping } from "./udemy-course-section-fields-mapping.enum.js";
export { UdemyDefaultPageParameter } from "./udemy-default-page-parameter.enum.js";
```
it should be flat

2024-02-27 07:14 UTC, what1s1ove commented on apps/backend/src/modules/vendors/udemy.service.ts
> +const PAGE_STEP = 1;
set of constants = enum
and move it to `libs/enums`

2024-02-27 07:14 UTC, what1s1ove commented on packages/shared/src/modules/course-sections/libs/enums/course-sections-api-path.enum.ts
> +	$ID: "/:courseSectionId",
```suggestion
	$COURSE_SECTION_ID: "/:courseSectionId",
```

2024-02-27 07:33 UTC, fshabanov requested changes

2024-02-27 07:33 UTC, fshabanov commented on apps/backend/src/db/migrations/20240226075220_add_course_sections_table.ts
> +};
```suggestion
const TableName = {
	COURSE_SECTIONS: "course_sections",
	COURSES: "courses",
} as const;
```
It's an enum

2024-02-27 07:33 UTC, fshabanov commented on apps/backend/src/modules/vendors/libs/enums/udemy/api-paths.enum.ts
> +const ApiPath = {
Fix file name (`api-path.enum.ts`)

2024-02-27 07:33 UTC, fshabanov commented on apps/backend/src/modules/vendors/libs/enums/udemy/course-section-field.enum.ts
> +	// CONTENT_SUMMARY: "content_summary",
```suggestion
```

2024-02-27 07:33 UTC, fshabanov commented on packages/shared/src/modules/course-sections/libs/enums/course-sections-api-path.enum.ts
> +	$ID: "/:courseSectionId",
```suggestion
	$COURSE_SECTION_ID: "/:courseSectionId",
```

2024-02-27 07:33 UTC, fshabanov commented on packages/shared/src/modules/courses/libs/enums/course-error-message.enum.ts
> +	COURSE_IS_ALREADY_EXISTS: "Course is already exists.",
```suggestion
	COURSE_IS_ALREADY_EXISTS: "Course already exists.",
```

2024-02-27 08:41 UTC, what1s1ove approved these changes

2024-02-27 08:41 UTC, merged