feat(frontend/backend/shared): add AI integration tm-43
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #134
Opened 2024-02-20 23:45 UTC by YourTeaChan

2024-02-20 23:49 UTC, YourTeaChan commented
Please check only related packages to my PR (open-ai and recommended-courses)

2024-02-21 10:39 UTC, what1s1ove requested changes

2024-02-21 10:39 UTC, what1s1ove commented on apps/backend/src/modules/open-ai/libs/enums/open-ai-properties.enum.ts
> +	MODEL: "gpt-3.5-turbo-0125",
```suggestion
```
move it to env as well

2024-02-21 10:39 UTC, what1s1ove commented on apps/backend/src/modules/open-ai/libs/enums/open-ai-properties.enum.ts
> +	RESPONSE_FORMAT: { type: "text" },
all these properties should be default. so just add them to AI call

2024-02-21 10:39 UTC, what1s1ove commented on apps/backend/src/modules/open-ai/libs/enums/prompt.enum.ts
> +const Prompt = {
i thing you do not need all this prompt is separate file. just add it to the method that will call AI service

2024-02-21 10:39 UTC, what1s1ove commented on apps/backend/src/modules/open-ai/open-ai.controller.ts
> +import { APIPath, HTTPCode } from "~/libs/enums/enums.js";
open ai will not have a separate controller and etc. AI should be just a service with one method for now `call` or similar. inject this service in source module, all courses functionality you need to describe in course module

2024-02-21 11:45 UTC, YourTeaChan commented on apps/backend/src/modules/open-ai/libs/enums/prompt.enum.ts
> +const Prompt = {
Do you mean I don't need all prompt enums and I just should add a large string into the AI call method (`getResponseFromOpenAi`)? Will it look readable?
Or do you mean there must be only a `Prompt` enum, which will contain only a string?

2024-02-21 12:41 UTC, YourTeaChan commented on apps/backend/src/modules/open-ai/open-ai.controller.ts
> +import { APIPath, HTTPCode } from "~/libs/enums/enums.js";
Do you mean I need to keep `OpenAiService` with only one method named `call`, which will call `openAi.chat.completions.create` method? And all other logic I should move to `CourseService` (mapping to another type, etc)?
We discussed in the one of previous meetings about a separate block with recommended courses and why do we need it. But now we will sort all courses that user will search and will display it sorted (and we will not have a recommended courses block now)?

2024-02-21 15:29 UTC, Sytnikovakatya approved these changes

2024-02-21 19:33 UTC, fshabanov requested changes

2024-02-21 19:33 UTC, fshabanov commented on apps/backend/src/modules/open-ai/open-ai.service.ts
> +	constructor({ model, openAi }: Constructor) {
```suggestion
	constructor({ model, openAI }: Constructor) {
```
Change everywhere

2024-02-22 06:39 UTC, GEOFARL approved these changes

2024-02-22 08:09 UTC, ShadowOfTheSpace approved these changes

2024-02-22 08:32 UTC, what1s1ove requested changes

2024-02-22 08:32 UTC, what1s1ove commented on apps/backend/src/modules/open-ai/open-ai.service.ts
> +import { type OpenAI } from "~/libs/modules/open-ai/open-ai.js";
we do not want to have a open-ai as an app module (users, courses, etc). it should be placed in `apps/backend/src/libs/modules/open-ai`

2024-02-22 08:32 UTC, what1s1ove commented on apps/backend/src/modules/open-ai/libs/enums/prompt.enum.ts
> +const Prompt = {
> Do you mean I don't need all prompt enums and I just should add a large string into the AI call method (getResponseFromOpenAi)? Will it look readable?

Yes, let's do this way

but you need to inject `open-ai` service inside `courses` service and add this string while calling `open-ai` service from there

2024-02-22 11:33 UTC, MappariChan approved these changes

2024-02-22 16:38 UTC, fshabanov requested changes

2024-02-22 16:38 UTC, fshabanov commented on apps/backend/src/libs/modules/open-ai/libs/enums/open-ai-error-message.enum.ts
> +	WRONG_RESPONSE: "Wrong response from OpenAI",
```suggestion
	WRONG_RESPONSE: "Wrong response from OpenAI.",
```
Add dot to have the same style everywhere

2024-02-22 16:38 UTC, fshabanov commented on apps/backend/src/libs/modules/open-ai/libs/exceptions/open-ai-error.exception.ts
> +	message: string;
Should we add status as well?

2024-02-22 18:00 UTC, YourTeaChan commented on apps/backend/src/libs/modules/open-ai/libs/exceptions/open-ai-error.exception.ts
> +	message: string;
`OpenAIError` extends `ApplicationError`, not `HTTPError` (we have status only in `HTTPError` and its children). Or I need to extend `HTTPError` instead of `ApplicationError`?

2024-02-22 21:14 UTC, Vfivew approved these changes

2024-02-24 16:34 UTC, what1s1ove requested changes

2024-02-24 16:34 UTC, what1s1ove commented on .github/workflows/ci-pr.yml
>            path: |
please, merge main branch inside your. we should see only your changes

2024-02-24 16:34 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.service.ts
> +		return { courses: sortedCourses.filter(Boolean) };
it should be as a separate call on frontend to get AI courses list. you do not need to change this method

2024-02-24 16:57 UTC, YourTeaChan commented on apps/backend/src/modules/courses/course.service.ts
> +		return { courses: sortedCourses.filter(Boolean) };
At one of previous daily calls you said that I need to remove controller and leave only a openAI module with `call` method. So, how can we make it without openAI controller?
> a separate call on frontend to get AI courses list

Or I need to create separate endpoint at `Course controller`? But if I will do that, I will duplicate the `findAllByVendor` method.

2024-02-24 17:10 UTC, KrasKa2 requested changes

2024-02-25 13:24 UTC, ShadowOfTheSpace approved these changes

2024-02-25 14:54 UTC, GEOFARL approved these changes

2024-02-25 15:12 UTC, KrasKa2 approved these changes

2024-02-25 16:52 UTC, fshabanov requested changes

2024-02-25 16:52 UTC, fshabanov commented on apps/backend/src/modules/courses/course.service.ts
> +			"Given a list of courses in JSON format. Analyze these courses by all fields. Return an array with the same length as the input array. Returned array must contains indexes of sorted courses based
```suggestion
			"Given a list of courses in JSON format. Analyze these courses by all fields. Return an array with the same length as the input array. Returned array must contain indexes of sorted courses based on their overall quality and interest level, from the most recommended courses to the least. The answer should be without any explanation in the format: [index]. The index starts with 0. For example: the input data to analyze is [{0}, {1}, {2}]. After analyzing, the output should be like: [1, 2, 0]. Please make sure that the returned array has the same length as the input array.";
```

2024-02-27 10:42 UTC, what1s1ove approved these changes

2024-02-27 10:45 UTC, merged