feat(backend/shared): chat functionality tm-111
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #135
Opened 2024-02-21 02:46 UTC by ShadowOfTheSpace

2024-02-21 06:34 UTC, Ann-Maksay commented on packages/shared/src/modules/chat/chat.ts
> +} from "./libs/validation-schemas/validation-schemas.js";
Wouldn't it be better to keep the same module names in all directories?
Either `chat` or `chat-message` for both shared and backend (and frontend in the future).

2024-02-21 06:51 UTC, GEOFARL commented on apps/backend/src/modules/chat-message/chat-message.controller.ts
> +	}: APIHandlerOptions<{
I was asked to not use such destructuring and to access id on user obj, as user.id

2024-02-21 06:51 UTC, GEOFARL commented on apps/backend/src/modules/chat-message/chat-message.service.ts
> +const ARRAY_EMPTY_LENGTH = 0;
probably, to constants

2024-02-21 07:15 UTC, Sytnikovakatya approved these changes

2024-02-21 10:10 UTC, MappariChan commented on packages/shared/src/modules/chat/libs/types/chat-item-response-dto.type.ts
> +import { type UserAuthResponseDto } from "../../../users/users.js";
```suggestion
import { type UserAuthResponseDto } from "~/modules/users/users.js";
```

2024-02-21 10:20 UTC, GEOFARL commented on packages/shared/src/modules/chat/libs/types/chat-item-response-dto.type.ts
> +import { type UserAuthResponseDto } from "../../../users/users.js";
> 

If I'm not mistaken, we cannot do that in packages folder

2024-02-21 10:30 UTC, ShadowOfTheSpace commented on packages/shared/src/modules/chat/libs/types/chat-item-response-dto.type.ts
> +import { type UserAuthResponseDto } from "../../../users/users.js";
> 

We can't do it in `package` folder. We have import aliases only for `apps` folder

2024-02-21 10:42 UTC, what1s1ove requested changes

2024-02-21 10:42 UTC, what1s1ove commented on apps/backend/src/modules/chat-message/chat-message.repository.ts
> +		return Promise.resolve(true);
implement all methods

2024-02-21 10:42 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240218085611_add_chat_messages_table.ts
> +import { MessageStatus } from "~/modules/chat-message/libs/enums/enums.js";
```suggestion
```
describe this enum in this file. ask on our daily why 🙂

2024-02-21 10:42 UTC, what1s1ove commented on packages/shared/src/modules/chat-message/libs/types/message-get-all-response-dto.type.ts
> +	messages: MessageResponseDto[];
```suggestion
	items: MessageResponseDto[];
```
soon we will unify all `GetAll` types

2024-02-21 11:06 UTC, fshabanov requested changes

2024-02-21 11:06 UTC, fshabanov commented on apps/backend/src/modules/chat-message/chat-message.repository.ts
> +		const chats = await this.chatMessageModel
Can we use `distinct` instead of all of this? Find chats by user id with distinct chatId and order them as you need

2024-02-21 11:06 UTC, fshabanov commented on apps/backend/src/modules/chat-message/chat-message.service.ts
> +		const userIsChatOwner =
```suggestion
		const isUserChatOwner =
```

2024-02-21 11:06 UTC, fshabanov commented on packages/shared/src/modules/chat-message/libs/enums/chat-message-api-path.enum.ts
> +	CHAT_ID: "/:chatId",
```suggestion
	$CHAT_ID: "/:chatId",
```

2024-02-21 11:06 UTC, fshabanov commented on packages/shared/src/modules/chat-message/libs/enums/chat-validation-message.enum.ts
> +	CHAT_ID_INVALID_TYPE: "The chatId is incorrect uuid",
```suggestion
	CHAT_ID_INVALID_TYPE: "The chatId is incorrect uuid.",
```

2024-02-21 11:15 UTC, ShadowOfTheSpace commented on apps/backend/src/db/migrations/20240218085611_add_chat_messages_table.ts
> +import { MessageStatus } from "~/modules/chat-message/libs/enums/enums.js";
@what1s1ove Probably I understand what you mean...
But how we could use it outside of migration file? We should do not use that enum at all and use type string instead? Or we need to have separate enums in migration file and in shared folder?

2024-02-21 11:21 UTC, MappariChan commented on packages/shared/src/modules/chat/libs/types/chat-item-response-dto.type.ts
> +import { type UserAuthResponseDto } from "../../../users/users.js";
Oh, okay, my bad, sorry

2024-02-21 11:43 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/chat-message/chat-message.model.ts
> +			},
I need it for creating relatedQuery to the same table.

I need to find a number of UNREAD messages for each user chat. So to make it in one db query I need that strange relation. It was the only way that I found to achieve a requested functionality in the same query while finding user's chats. 

If we could have separated "Chat" and "Message" tables, it would be much easier to achieve that (like it was in thread-js with post reactions counting for example), but right now chats and messages are contained in one table.
@fshabanov What do you think about that? Is another way exists?

2024-02-21 12:15 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/chat-message/chat-message.repository.ts
> +		const chats = await this.chatMessageModel
Short answer is no I think

Firstly if you have `distinct on (chat_id)`, you have to specify order by columns in the same order, as in distinct statement

So I cannot simply do something like that
`select distinct (chat_id) from chat_messages order by created_at`
because it throws error that I described before

If I will do that like postgres wants 
`select distinct on (chat_id) * from chat_messages order by chat_id, created_at desc`
I will get all chats, but they will be `sorted by chat_id` and only after that `by created_at`. So we cannot get chats sorted by last message in it with that approach
So for that reason I created `CTE`, which I use to sort user's chats properly

Additionally as I described in your previous comment I need to get not only user's chats, but I need to count unread messages in every chat, so I need subquery for that (that one with strange relation)

I think I cannot find better approach to achieve requested behaviour (for now)

2024-02-21 15:05 UTC, GEOFARL approved these changes

2024-02-22 11:30 UTC, MappariChan approved these changes

2024-02-22 16:31 UTC, fshabanov commented on apps/backend/src/modules/chat-message/chat-message.model.ts
> +			},
@ShadowOfTheSpace try to do something like this. You will not need `selfChatMessages` anymore
<img width="560" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61088675/a5cd97be-30e5-43e6-b2d9-34e63e7c7d4a">

2024-02-22 18:22 UTC, GEOFARL approved these changes

2024-02-26 17:33 UTC, GEOFARL commented on apps/backend/src/modules/chats/chat.model.ts
> +import { ChatMessageModel } from "~/modules/chat-messages/chat-message.model.js";
```suggestion
import { ChatMessageModel } from "~/modules/chat-messages/chat-messages.js";
```

2024-02-26 17:33 UTC, GEOFARL commented on apps/backend/src/modules/chats/chat.repository.ts
> +import { type ChatMessageModel } from "~/modules/chat-messages/chat-message.model.js";
```suggestion
import { ChatMessageEntity } from "~/modules/chat-messages/chat-messages.js";
import { type ChatMessageModel } from "~/modules/chat-messages/chat-messages.js";
```

2024-02-26 17:33 UTC, GEOFARL commented on apps/backend/src/modules/chats/chat.repository.ts
> +import { MessageStatus } from "../chat-messages/chat-message.js";
```suggestion
import { MessageStatus } from "~/modules/chat-messages/chat-messages.js";
```

2024-02-26 17:33 UTC, GEOFARL commented on apps/backend/src/modules/chats/chat.service.ts
> +import { type Service } from "~/libs/types/service.type.js";
```suggestion
import { type Service } from "~/libs/types/types.js";
```

2024-02-26 17:33 UTC, GEOFARL commented on apps/backend/src/modules/chats/chat.service.ts
> +import { type Service } from "~/libs/types/service.type.js";
add it to other import types

2024-02-26 17:33 UTC, GEOFARL commented on packages/shared/src/modules/chat-messages/libs/types/chat-message-item-response-dto.type.ts
> +import { type ValueOf } from "../../../../libs/types/value-of.type.js";
```suggestion
import { type ValueOf } from "../../../../libs/types/types.js";
```

2024-02-26 17:33 UTC, GEOFARL commented on packages/shared/src/modules/chat-messages/libs/types/chat-message-item-response-dto.type.ts
> +import { type MessageStatus } from "../enums/message-status.enum.js";
```suggestion
import { type MessageStatus } from "../enums/enums.js";
```

2024-02-28 06:59 UTC, what1s1ove requested changes

2024-02-28 06:59 UTC, what1s1ove commented on apps/backend/src/libs/types/service.type.ts
> +	delete(id: unknown): Promise<boolean>;
it should be number

2024-02-28 06:59 UTC, what1s1ove commented on apps/backend/src/modules/chats/chat.service.ts
> +		return true;
```suggestion
	const deletedRowsCount = await this.chatRepository.delete(id);

	return Boolean(deletedRowsCount);
```

2024-02-28 06:59 UTC, what1s1ove commented on apps/backend/src/modules/chats/chat.service.ts
> +		void (await this.find(id));
add it to variable

2024-02-28 06:59 UTC, what1s1ove commented on apps/backend/src/modules/friends/friend.repository.ts
> +	public async getIsMutualFollowersByIds(
```suggestion
	public async checkIsMutualFollowersByIds(
```
methods that return boolean should start with `check<is | has>`

2024-02-28 07:40 UTC, fshabanov requested changes

2024-02-28 07:40 UTC, fshabanov commented on apps/backend/src/modules/chat-messages/chat-message.controller.ts
> +				body: chatMessageUpdateValidationSchema,
Add `params` validation

2024-02-28 07:40 UTC, fshabanov commented on apps/backend/src/modules/chat-messages/chat-message.repository.ts
> +		return messagesByUserId.map((messageByUserId) =>
B27

2024-02-28 07:40 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +			.where({ follower_id: firstUserId, following_id: secondUserId })
```suggestion
			.where({ followerId: firstUserId, followingId: secondUserId })
```

2024-02-28 13:29 UTC, fshabanov requested changes

2024-02-28 13:29 UTC, fshabanov commented on apps/backend/src/modules/chats/chat.entity.ts
> +import { type ChatMessageEntity } from "~/modules/chat-messages/chat-message.js";
```suggestion
import { type ChatMessageEntity } from "~/modules/chat-messages/chat-messages.js";
```

2024-02-28 17:16 UTC, what1s1ove approved these changes

2024-02-28 17:16 UTC, merged