fix(frontend/shared): fix user details screen tm-42
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #149
Opened 2024-02-22 21:00 UTC by Sytnikovakatya

- Create a files module for uploading an image
- Fix profile page scroll
- Update styles for button and input
- The profile image on the header navigates to the My Profile page
- Update the height of the Profile section with the user's foto
![Screenshot_8](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/488f10e2-3b8e-4176-b365-34ab37496492)

2024-02-22 21:41 UTC, tarmiel requested changes

2024-02-22 21:41 UTC, tarmiel commented on apps/frontend/src/pages/profile/profile.tsx
>  			}
You don't need this condition. On profile page we always have a user with id

2024-02-22 21:41 UTC, tarmiel commented on apps/frontend/src/modules/auth/slices/auth.slice.ts
> +					: null;
```suggestion
				if (state.user) {
          state.user = {...state.user, avatarUrl: action.payload.url}
        }
```

2024-02-22 21:41 UTC, tarmiel commented on apps/frontend/src/modules/users/libs/enums/enums.ts
> +export { NotificationMessage, UsersApiPath } from "shared";
Maybe it would be better to reexport NotificationMessage in "~/libs/enums/enums.js" as an enum for all our notifications in the app

2024-02-22 21:44 UTC, Vfivew approved these changes

2024-02-23 07:07 UTC, what1s1ove requested changes

2024-02-23 07:07 UTC, what1s1ove commented on apps/frontend/src/modules/files/slices/actions.ts
> +	UserFileResponseDto,
```suggestion
	UserFileResponseDto,
```
here we should use an auth-user type (and add avatar to this type)

2024-02-23 07:07 UTC, what1s1ove commented on apps/frontend/src/modules/auth/slices/auth.slice.ts
> +					: null;
```suggestion
				state.user = action.payload
```

2024-02-23 14:18 UTC, what1s1ove requested changes

2024-02-23 14:18 UTC, what1s1ove commented on .github/workflows/ci-pr.yml
> +        uses: wagoid/commitlint-github-action@v5
please merge main branch into your branch. we should not see all these changes

2024-02-23 18:05 UTC, ShadowOfTheSpace approved these changes

2024-02-24 08:27 UTC, fshabanov requested changes

2024-02-24 08:27 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +						src={DEFAULT_USER_AVATAR}
You already add `avatarUrl` in action, use it here

2024-02-24 08:27 UTC, fshabanov commented on packages/shared/src/modules/users/libs/types/user-file-response-dto.type.ts
> +import { type ContentType, type ValueOf } from "../../../../index.js";
This will result in circular dependencies

2024-02-24 10:53 UTC, MappariChan commented on packages/shared/src/modules/users/libs/types/user-file-response-dto.type.ts
there already is dto which is responsible for that in the `packages\shared\src\modules\files\libs\types\file-upload-response-dto.ts`

2024-02-24 10:55 UTC, Sytnikovakatya commented on packages/shared/src/modules/users/libs/types/user-file-response-dto.type.ts
Yes, I saw it. But it doesn't contain all fields that I need

2024-02-24 12:29 UTC, MappariChan approved these changes

2024-02-24 15:10 UTC, KrasKa2 approved these changes

2024-02-24 16:35 UTC, what1s1ove requested changes

2024-02-24 16:35 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/validation-schemas/user-profile.validation-schema.ts
> +	lastName?: z.ZodOptional<z.ZodString>;
```suggestion
	firstName: z.ZodOptional<z.ZodString>;
	lastName: z.ZodOptional<z.ZodString>;
```
it can not be optional
it should be string or null

2024-02-24 21:04 UTC, Oleksandra-Masiuk approved these changes

2024-02-25 06:21 UTC, what1s1ove requested changes

2024-02-25 06:21 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/validation-schemas/user-profile.validation-schema.ts
> +	lastName: z.ZodOptional<z.ZodString>;
```suggestion
	firstName: z.ZodString;
	lastName: z.ZodString;
```

2024-02-25 06:21 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/validation-schemas/user-profile.validation-schema.ts
> +		.optional(),
```suggestion
```
any keys in DTO can not be optional. if you have same logic while working with forms, please fix it

2024-02-25 06:21 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/validation-schemas/user-profile.validation-schema.ts
> +		.optional(),
```suggestion
```

2024-02-25 07:17 UTC, what1s1ove approved these changes

2024-02-25 08:17 UTC, what1s1ove approved these changes

2024-02-25 08:17 UTC, merged