fix(frontend): make roboto global font style tm-143
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #154
Opened 2024-02-23 15:07 UTC by MappariChan

2024-02-23 15:12 UTC, fshabanov requested changes

2024-02-23 15:12 UTC, fshabanov commented on apps/frontend/src/assets/css/scaffolding.css
> +	font-family: Roboto, sans-serif;
B14

2024-02-23 15:34 UTC, tarmiel commented on apps/frontend/src/assets/css/scaffolding.css
> +	font-family: Roboto, Arial, sans-serif;
Roboto font isn't one of the default fonts in the browser. At this moment, we use Arial or sans-serif instead of Roboto. So, according to rule B13, you should install this font locally

2024-02-23 16:30 UTC, KrasKa2 approved these changes

2024-02-23 17:29 UTC, Vfivew approved these changes

2024-02-23 17:58 UTC, ShadowOfTheSpace approved these changes

2024-02-23 19:07 UTC, YourTeaChan approved these changes

2024-02-23 19:55 UTC, MappariChan commented on apps/frontend/src/assets/css/scaffolding.css
> +	font-family: Roboto, Arial, sans-serif;
If i correctly understand, i should create font localy using `@font-face`

2024-02-23 20:16 UTC, tarmiel commented on apps/frontend/src/assets/css/fonts/roboto.css
At this moment our design has only Roboto regular(400), medium(500), semibold(600), bold(700). So, I'm not sure that we need other variants.

2024-02-23 20:22 UTC, MappariChan commented on apps/frontend/src/assets/css/fonts/roboto.css
I think it will be better to leave it for now.

2024-02-23 20:32 UTC, MappariChan commented on apps/frontend/src/assets/css/fonts/roboto.css
But maybe you are right, i will ask about it in the chat

2024-02-24 11:31 UTC, fshabanov approved these changes

2024-02-24 11:31 UTC, fshabanov commented
@MappariChan merge the main branch into yours

2024-02-24 14:55 UTC, merged