fix(frontend/backend/shared): Auth Page fields validations, error messages and design issues according to the updated specification tm-131
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #155
Opened 2024-02-23 23:03 UTC by GEOFARL

<img width="305" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/35617ca5-65a0-4aac-aaba-6629fe9f5927">

<img width="299" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/85d9d35d-16b4-45c6-b8fa-e3f30c0583ae">

<img width="287" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/8ca2add4-5857-4db1-ad12-ab74a07dd057">

<img width="299" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/1ae679bf-fa9e-471a-b081-b198e125204b">

<img width="293" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/aaeb0982-288c-4b57-90a7-27d8f476b5fd">

<img width="307" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/a6d62cf7-b968-45af-b703-a094cfb3725d">

<img width="296" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/9b089464-1714-4452-8226-10879cd44980">

<img width="291" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/3769033a-979e-402c-aae6-031ad215e2e0">

<img width="293" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/30c33d79-d95f-48b0-a8a1-b6620bcaf4a8">

<img width="287" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/fa814aee-8829-4fe5-887e-8c2d4e4903c2">

<img width="288" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/9d534f33-3e2b-4aa9-b68f-78dff2c1d74d">

<img width="296" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/0cf60855-9fd4-4838-8b74-4f84621a0871">

<img width="287" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/41ed1238-9d43-4f10-b059-b4ca2f589873">

<img width="288" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/63ae6764-2bc4-4be6-8b5e-190b61b019cd">

<img width="287" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/cbbd7161-7ebf-43e9-9d92-73d25605d823">

<img width="287" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/d44245c0-1874-48d7-a6d4-a0783f4f86fb">

<img width="285" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/4a4d5bc9-fdf5-4ae3-8830-f3f44e068e97">

<img width="289" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/9264f749-f3cd-4b93-86af-b374dfe33bf0">

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/6196e744-3a5b-447d-a36b-45ccc8c6023d)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/28c25e30-3eb7-4b3d-935d-2b7481041ff2)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/f7c7cf5f-43ad-4ccc-a882-d8f9b8e7eda8)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/3d9c4659-c08b-4886-8202-7542850a036b)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/35167ad2-3c08-43da-b5fb-f1326d7f80ee)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/90f4e4ad-7118-42e9-a25b-989023d3db21)

<img width="310" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/975314a6-3b3c-4b05-a90f-13dc8dd628af">

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/978ec8c3-e14d-4ed8-a85e-0e324a173c34)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/90275815-1c8a-4faa-bc62-29eef27d8593)

2024-02-24 07:07 UTC, what1s1ove requested changes

2024-02-24 07:07 UTC, what1s1ove commented on apps/frontend/src/libs/components/input/input.tsx
> +	useEffect(() => {
```suggestion
```
we do not want to calculate it. error message can be 1 line height all the time. we need to decrease a length of error message instead

2024-02-24 07:58 UTC, Sytnikovakatya approved these changes

2024-02-24 10:39 UTC, GEOFARL commented on packages/shared/src/modules/users/libs/enums/user-validation-rule.enum.ts
> +	FIRST_NAME_MINIMUM_LENGTH: 2,
It was that way before, decided not to rename

2024-02-24 10:45 UTC, Oleksandra-Masiuk commented on packages/shared/src/modules/users/libs/enums/user-validation-rule.enum.ts
> +	FIRST_NAME_MINIMUM_LENGTH: 2,
I suggest renaming it since you are already updating these messages, and it violates A7 of the quality criteria

2024-02-24 10:48 UTC, YourTeaChan commented
Sorry, I don't know is it issue or not, but maybe you need to enter more real values in your inputs? (screenshots in PR I mean)

2024-02-24 14:40 UTC, YourTeaChan approved these changes

2024-02-24 20:10 UTC, Ann-Maksay approved these changes

2024-02-24 20:52 UTC, Oleksandra-Masiuk commented
Regarding the  `"The "Create an account" button on the "Sign Up" form should be as designed"` point of the task: doesn't that mean that the button should have an orange background?

2024-02-25 06:06 UTC, GEOFARL commented
> Regarding the `"The "Create an account" button on the "Sign Up" form should be as designed"` point of the task: doesn't that mean that the button should have an orange background?

As far as I understand, according to the updates on the design, the button by default should be white and change its background to orange on hover

2024-02-25 06:38 UTC, what1s1ove approved these changes

2024-02-25 07:17 UTC, merged