feat(frontend/backend/shared): Search courses tm-55
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #179
Opened 2024-02-25 14:44 UTC by GEOFARL

![20240225_164259](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/d0e868f1-9d86-4fc1-b1bd-e421ed93cca0)

2024-02-25 15:51 UTC, tarmiel commented on apps/frontend/src/libs/components/search-bar/search-bar.tsx
> +		defaultValues: DEFAULT_SEARCH_COURSE_PAYLOAD,
You do not need vendors in this form

2024-02-25 15:51 UTC, tarmiel commented on apps/frontend/src/pages/overview/libs/constants/constants.ts
> +} from "~/modules/courses/courses.js";
Why did you need to move this to courses module?

2024-02-25 15:51 UTC, tarmiel commented on apps/frontend/src/libs/components/search-bar/search-bar.tsx
> +			<Icon className={styles["search-icon"]} name="search" />
I think icon needs to be part of input component

2024-02-25 16:05 UTC, GEOFARL commented on apps/frontend/src/pages/overview/libs/constants/constants.ts
> +} from "~/modules/courses/courses.js";
SEARCH_COURSES_DELAY_MS I need to be able to use debounce as you do in the modal window, I'll return DEFAULT_SEARCH_COURSE_PAYLOAD

2024-02-25 17:03 UTC, fshabanov requested changes

2024-02-25 17:03 UTC, fshabanov commented on apps/backend/src/modules/courses/course.repository.ts
> +	public async findByUserIdWithSearch(
Should be a part of `findByUserId`, no need to create a separate method

2024-02-25 17:03 UTC, fshabanov commented on apps/frontend/src/modules/user-courses/slices/actions.ts
> +const searchMyCourses = createAsyncThunk<
Use the existing action

2024-02-26 09:55 UTC, MappariChan approved these changes

2024-02-26 15:51 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/courses/course.repository.ts
> +			.where("title", "ilike", `%${search}%`)
Please, use [whereILike](https://knexjs.org/guide/query-builder.html#whereilike)

2024-02-26 15:51 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/input/input.tsx
> +	const icon = iconName ? (
add `const hasIcon  = Boolean(iconName);` and use it here

2024-02-26 15:52 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/input/input.tsx
> +		icon && styles["input-with-icon"],
```suggestion
		hasIcon && styles["input-with-icon"],
```

2024-02-27 07:56 UTC, Oleksandra-Masiuk approved these changes

2024-02-27 09:25 UTC, what1s1ove approved these changes

2024-02-27 09:25 UTC, merged