fix(frontend): sidebar only the button representing active page should be active tm-174
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #182
Opened 2024-02-25 16:07 UTC by Vfivew

![buttons](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/e8b87b6c-1338-4efe-b80c-6aba8e10dfd4)

2024-02-25 16:50 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
>  								key={label}
This should have been spotted in another PR, but I guess it's worth a fix now. 
The key should be on the wrapper, not on the inner element.

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/889cb643-0025-47ea-a2d5-cf779bbb1663)

2024-02-25 18:56 UTC, tarmiel commented on apps/frontend/src/libs/components/button/styles.module.css
> +	fill: var(--color-menu);
I think it would be better to set fill="currentColor" in svg to change such icons through color property in css

2024-02-25 18:56 UTC, tarmiel commented on apps/frontend/src/libs/components/button/styles.module.css
>  .primary.outlined,
I'm not sure that we still need primary outlined variant

2024-02-25 18:56 UTC, what1s1ove requested changes

2024-02-25 18:56 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +								color={
you need to use `activeClassName` prop for the react-router link component instead

2024-02-25 18:56 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/styles.module.css
> +	fill: var(--main-white);
the fill property should be added to the icon component and it should be `currentColor`, so by passing color to the button, the icon should inherit this color

https://css-tricks.com/cascading-svg-fill-color/

2024-02-25 22:15 UTC, Vfivew commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +								color={
It seems to me it does not exist now ( i mean activeClassName ).
But I figured out how to do this more concisely.
https://github.com/tailwindlabs/tailwindcss/discussions/6729

2024-02-26 05:55 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +								color={
https://reactrouter.com/en/main/components/nav-link

2024-02-26 06:17 UTC, GEOFARL approved these changes

2024-02-26 16:43 UTC, MappariChan commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +								activeClassName={styles["active"]}
```suggestion
							<Link
							  key={label}
								activeClassName={styles["active"]}
```
I think you should omit this div and pass key directly into the Link component

2024-02-26 16:47 UTC, fshabanov requested changes

2024-02-26 16:47 UTC, fshabanov commented on apps/frontend/src/libs/components/link/link.tsx
> +import { useCallback } from "react";
```suggestion
import { useCallback } from "~/libs/hooks/hooks.js";
```

2024-02-26 16:49 UTC, MappariChan commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +								activeClassName={styles["active"]}
```suggestion
							<Link
							  key={label}
								activeClassName={styles["active"]}
```
I think you should omit this div and pass key directly into the Link component

2024-02-26 17:22 UTC, GEOFARL commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +	.close .log-out-btn span {
B10 Rule

2024-02-26 20:38 UTC, tarmiel requested changes

2024-02-26 20:38 UTC, tarmiel commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +					hasVisuallyHiddenLabel={false}
```suggestion

```

2024-02-27 08:31 UTC, Sytnikovakatya approved these changes

2024-02-27 08:40 UTC, tarmiel approved these changes

2024-02-27 09:21 UTC, what1s1ove requested changes

2024-02-27 09:21 UTC, what1s1ove commented on apps/frontend/src/libs/components/link/link.tsx
> +	const linkStyles = useCallback(
```suggestion
	const handleLinkStyles = useCallback(
```

2024-02-27 09:21 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	style?: "plain" | "primary" | "secondary";
not sure why you removed `color` prop
could you show how now the button component looks like (with different `style` props)

2024-02-27 09:32 UTC, Vfivew commented on apps/frontend/src/libs/components/button/button.tsx
> +	style?: "plain" | "primary" | "secondary";
![yes here is my buttons](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/306eff7c-13ab-479f-9dd5-266c115a420e)
It seemed to me like the best solution, as now we have only three button styles instead of two colors and three styles (I would have had to add the third style anyway). We can always bring back the color prop if we need it. Or should we bring it back now?

2024-02-27 10:55 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	style?: "plain" | "primary" | "secondary";
I like the idea, but how we need to provide color now? only through the classname prop?

2024-02-27 11:50 UTC, Vfivew commented on apps/frontend/src/libs/components/button/button.tsx
> +	style?: "plain" | "primary" | "secondary";
Currently, the color is determined solely by the style. Before my fix, we were passing the color and then overriding it with the style (I'll add a screenshot). In my opinion, it should be the style first, and if we need to define a new color, we can add a new parameter. Currently, using three styles covers all our needs. 
plain - border/background transparent
primary - we determine color
secondary - with border but background transparent
![refactor](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/b40a707b-ec84-45d4-ab83-eb45b18243d6)

2024-02-27 16:40 UTC, fshabanov requested changes

2024-02-27 16:40 UTC, fshabanov commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +					style="primary"
primary is default in your case, no need to add it again everywhere

2024-02-27 19:38 UTC, YourTeaChan commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +		color: var(--color-menu);
The burger button (icon) should be orange, not dark green on the mobile screen

2024-02-28 06:48 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	style?: "plain" | "primary" | "secondary";
Okay, got it

2024-02-28 06:49 UTC, what1s1ove approved these changes

2024-02-28 06:49 UTC, merged