feat(frontend): Add Friend page tm-40
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #207
Opened 2024-02-27 10:09 UTC by GEOFARL

![20240227_120712](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/db1cacff-48ce-42d8-a5e8-5067bf7c6cbc)

2024-02-27 10:37 UTC, tarmiel requested changes

2024-02-27 10:37 UTC, tarmiel commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +			<RouterLink className={styles["card-content"]} to={`/users/${friend.id}`}>
We already have Link component. If you faced problems with type of href prop with dynamic id,  we have configure-string helper in shared that can solve this

2024-02-27 10:37 UTC, tarmiel commented on apps/frontend/src/pages/user/user.tsx
> +					>{`${user.firstName} ${user.lastName}`}</p>
```suggestion
					>{user.firstName} {user.lastName}</p>
```

2024-02-27 10:41 UTC, GEOFARL commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +			<RouterLink className={styles["card-content"]} to={`/users/${friend.id}`}>
Yeah, couldn't figure out how to make it, thx

2024-02-27 11:27 UTC, what1s1ove requested changes

2024-02-27 11:27 UTC, what1s1ove commented on apps/frontend/src/modules/user-courses/slices/user-courses.slice.ts
> +	userCourses: {},
should be an array

2024-02-27 11:27 UTC, what1s1ove commented on apps/frontend/src/pages/user/libs/components/user-button/user-button.tsx
> +	const handleFollow = useCallback(() => {
this action should be on the `users` page level. you do not need your own wrapper for the button component

2024-02-27 11:27 UTC, what1s1ove commented on apps/frontend/src/pages/user/user.tsx
> +	const user = friends.find((friend) => friend.id === userId);
```suggestion
```
you can open this page directly, so the friends reducer will be empty

2024-02-27 11:27 UTC, what1s1ove commented on apps/frontend/src/pages/user/user.tsx
> +	const userId = +(id as string);
```suggestion
	const userId = Number(id);
```

2024-02-27 12:24 UTC, GEOFARL commented on apps/frontend/src/pages/user/user.tsx
> +	const user = friends.find((friend) => friend.id === userId);
If we don't have friends, I redireact a user to the friends page, where they will be loaded

```ts
	if (!user) {
		return <Navigate to={AppRoute.FRIENDS} />;
	}
```

2024-02-27 14:49 UTC, GEOFARL commented on apps/frontend/src/pages/user/user.tsx
> +	const user = friends.find((friend) => friend.id === userId);
But we need a user object to display its full name, avatar and be able to follow them

2024-02-27 16:15 UTC, fshabanov commented on apps/frontend/src/pages/user/user.tsx
> +	const user = friends.find((friend) => friend.id === userId);
Get user information as well with that request 🤔

2024-02-27 16:58 UTC, GEOFARL commented on apps/frontend/src/pages/user/user.tsx
> +	const user = friends.find((friend) => friend.id === userId);
Okay, but why would we want to do that?

2024-02-27 17:11 UTC, GEOFARL commented on apps/frontend/src/pages/user/user.tsx
> +	const user = friends.find((friend) => friend.id === userId);
Like I do not understand, should I now add a new action to the users slice to load info about a specific user? How can I get user information with a request about courses?
I do load courses by id, but before that I just get user object firstly

2024-02-28 06:47 UTC, what1s1ove requested changes

2024-02-28 06:47 UTC, what1s1ove commented on apps/frontend/src/pages/user/user.tsx
> +	const user = friends.find((friend) => friend.id === userId);
you need to fetch user on this page. not to take it from the `friends` reducer

2024-02-28 07:57 UTC, fshabanov commented on apps/frontend/src/pages/user/user.tsx
> +	const user = friends.find((friend) => friend.id === userId);
You use `friends.find`, what if the user directly enters the Friend screen? In that case `friends` is an empty array, they were not loaded. You can get all needed information with 1 request - get user by id and join courses

2024-02-28 09:48 UTC, fshabanov requested changes

2024-02-28 09:48 UTC, fshabanov commented on apps/frontend/src/pages/user/user.tsx
> +				myId: (state.auth.user as UserAuthResponseDto).id,
```suggestion
				currentUserId: (state.auth.user as UserAuthResponseDto).id,
```

2024-02-28 09:48 UTC, fshabanov commented on apps/frontend/src/pages/user/user.tsx
> +	);
Again, what if the user directly enters this screen and `state.friends.followings` is an empty array?

2024-02-28 09:48 UTC, fshabanov commented on apps/frontend/src/pages/user/user.tsx
> +	const userObject = user as UserAuthResponseDto;
```suggestion
```

2024-02-28 12:56 UTC, fshabanov requested changes

2024-02-28 13:31 UTC, Ann-Maksay commented on apps/frontend/src/modules/users/users-api.ts
> +			this.getFullEndpoint(`${UsersApiPath.ROOT}${id}`, {}),
```suggestion
			this.getFullEndpoint(UsersApiPath.$ID, { id: String(id)}),
```
Isn't it better this way? As far as I understand the second argument is exactly for parameters

2024-02-28 15:37 UTC, Ann-Maksay commented on apps/frontend/src/modules/users/users-api.ts
> +			this.getFullEndpoint(UsersApiPath.ROOT, {
```suggestion
			this.getFullEndpoint(UsersApiPath.$ID, {
```
It works this way

2024-02-29 06:06 UTC, fshabanov requested changes

2024-02-29 06:06 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +		return userFollowings.length > EMPTY_FRIENDS_RESULT;
```suggestion
		return userFollowings.length > EMPTY_ARRAY_LENGTH;
```
We have it in shared folder

2024-02-29 06:06 UTC, fshabanov commented on apps/frontend/src/pages/user/user.tsx
> +			userNotFound: state.users.dataStatus === DataStatus.REJECTED,
B19

2024-02-29 06:59 UTC, fshabanov requested changes

2024-02-29 06:59 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +	 *     description: Returns a boolean indicating whether current user follows another user
Add `tags` property (Check #245)

2024-02-29 07:23 UTC, what1s1ove requested changes

2024-02-29 07:23 UTC, what1s1ove commented on apps/frontend/src/modules/users/slices/users.slice.ts
> +	user: null,
```suggestion
	profileUser: null,
```
specify a name

2024-02-29 08:22 UTC, what1s1ove approved these changes

2024-02-29 08:22 UTC, merged