fix(frontend): add friends screen tm-94
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #214
Opened 2024-02-27 12:50 UTC by GEOFARL

Make the users, who have just been followed by the current user, to disappear after switching to another tab
Make the users, whom the current user has just unfollowed, to stay on the tab until switching to another tab

![20240227_144516](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/50869cca-2245-463f-939d-80511ed3a47a)

2024-02-27 21:16 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/friends/friends.tsx
> +	}, [dispatch, pathname]);
The `pathname` is not used in the `useEffect`.
Why do we have to reload `Followings`, `Followers`, and `PotentialFriends` each time the `pathname` changes?
Why not reload only the type of friends that corresponds to the current value of pathname when it changes?

2024-02-28 06:43 UTC, what1s1ove requested changes

2024-02-28 06:43 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +	}, [dispatch, pathname]);
agreed. we need to do an API call on each page separately

2024-02-28 13:54 UTC, Ann-Maksay approved these changes

2024-02-28 14:32 UTC, ShadowOfTheSpace approved these changes

2024-02-28 17:30 UTC, what1s1ove approved these changes

2024-02-28 17:30 UTC, merged