feat(frontend/backend/shared): add nickname field for user tm-183
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #220
Opened 2024-02-27 17:43 UTC by YourTeaChan

- Nickname by default after sign up (first name + id)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/68c89cd7-77c7-47f0-939c-89a99f9ad339)

- Nullable nickname

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/6d94575b-60c3-4c04-86d6-ea120eb5262a)

- Validation: at least one letter

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/2a6543e1-ace8-4948-b2a5-1702773ebe3c)

- Validation: only a-z, 0-9 and underscores

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/f758fc4c-0d1a-477a-8865-d4361fb6da7e)

- Validation: min 5 characters

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/c9a86db9-921c-44a4-a2c2-e0a74c68b127)

- Validation: max 35 characters

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/98139acf-d637-4d50-bda6-bc74cbdf6337)

- Nickname is already taken error

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/43ef5295-15e4-4f53-9160-cbc6377b3479)

2024-02-27 19:44 UTC, ShadowOfTheSpace requested changes

2024-02-27 19:44 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/users/user.entity.ts
> +			nickname: this.nickname as string,
I think you don't need to cast nickname as string, because nickname can be string or null in Entity

2024-02-27 19:44 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/users/user.entity.ts
> +			nickname: this.nickname as string,
Same here

2024-02-27 19:44 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/profile/profile.tsx
> +			nickname: user.nickname,
```suggestion
			nickname: user.nickname ?? "",
```
It cause error in react-hook-form

2024-02-27 19:44 UTC, ShadowOfTheSpace commented on packages/shared/src/modules/users/libs/types/user-auth-response-dto.type.ts
> +	nickname: string;
```suggestion
	nickname: string | null;
```
Change type here, because you have nickname as string or null in Entity

2024-02-27 20:07 UTC, Ann-Maksay approved these changes

2024-02-27 21:28 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.repository.ts
> +		if (nickname === "") {
why not to use `if (!nickname)`?

2024-02-27 21:30 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.service.ts
> +		const nickname = `${firstName.toLowerCase().replaceAll(/['-]/g, "")}${id}`;
Why not move it to a separate method?

2024-02-27 21:43 UTC, YourTeaChan commented on apps/backend/src/modules/users/user.service.ts
> +		const nickname = `${firstName.toLowerCase().replaceAll(/['-]/g, "")}${id}`;
Do you mean only row №45 or whole logic of inserting nickname?

2024-02-28 06:04 UTC, GEOFARL approved these changes

2024-02-28 06:42 UTC, what1s1ove requested changes

2024-02-28 06:42 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240226103757_add_nickname_column.ts
> +	return knex.schema.alterTable(TABLE_NAME, (table) => {
what about the default value?

2024-02-28 07:17 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.service.ts
> +		const nickname = `${firstName.toLowerCase().replaceAll(/['-]/g, "")}${id}`;
I mean line 45

2024-02-28 09:54 UTC, fshabanov requested changes

2024-02-28 09:54 UTC, fshabanov commented on apps/backend/src/modules/users/user.service.ts
> +		const isSameUser = Boolean(user?.toObject().id === userId);
```suggestion
		const isSameUser =user?.toObject().id === userId;
```
It's already Boolean

2024-02-28 11:30 UTC, ShadowOfTheSpace approved these changes

2024-02-28 16:02 UTC, Vfivew approved these changes

2024-02-28 17:28 UTC, what1s1ove approved these changes

2024-02-28 17:28 UTC, what1s1ove commented
@YourTeaChan resolve conflicts please

2024-02-28 17:30 UTC, YourTeaChan commented
> @YourTeaChan resolve conflicts please

One second, I push my branch right now)

2024-02-28 19:59 UTC, Sytnikovakatya approved these changes

2024-02-29 06:45 UTC, fshabanov approved these changes
Merge main branch into yours

2024-02-29 07:24 UTC, what1s1ove approved these changes

2024-02-29 07:24 UTC, merged