fix(frontend/shared): fix Profile screen tm-42
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #221
Opened 2024-02-27 19:38 UTC by Sytnikovakatya

- Change validation schema according to updated specification
- Cancel button allows the user to undo all changes made
- The user is prevented from leaving the page without saving the changes — the "Please, update your changes before leaving” message appears as a toast-message
-  If the changes are successfully saved, the “Changes are saved.” message appears as a toast-message
-  Update styles of User foto on the header to repeat profile foto's styles
![Screenshot_1](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/4d7be922-f507-4647-a2ea-64a00bb5aad3)
![Screenshot_2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/6c1c2307-eaec-4949-9811-a010cd3897ed)
![Screenshot_3](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/c134443d-b637-47db-a66b-c1397d7a9227)

2024-02-27 20:27 UTC, YourTeaChan approved these changes

2024-02-27 21:36 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/profile/profile.tsx
> +			if (event.target instanceof HTMLInputElement) {
Why do we need this `if`?

2024-02-28 06:40 UTC, what1s1ove requested changes

2024-02-28 06:40 UTC, what1s1ove commented on apps/frontend/src/pages/profile/profile.tsx
> +	const handleCancelChanges = useCallback(() => {
can we just use a button with a type "reset" ?

2024-02-28 07:01 UTC, what1s1ove commented on apps/frontend/src/pages/profile/profile.tsx
> +	const handleCancelChanges = useCallback(() => {
or this use-form API
https://react-hook-form.com/docs/useform/reset

2024-02-28 09:57 UTC, fshabanov requested changes

2024-02-28 09:57 UTC, fshabanov commented on apps/frontend/src/libs/hooks/use-app-form/use-app-form.hook.ts
> +	reset: () => void;
```suggestion
	reset: UseFormReset<T>;
```

2024-02-28 10:34 UTC, Sytnikovakatya commented on apps/frontend/src/pages/profile/profile.tsx
> +			if (event.target instanceof HTMLInputElement) {
Thanks, I've changed it

2024-02-28 15:48 UTC, Vfivew approved these changes

2024-02-28 17:23 UTC, what1s1ove requested changes

2024-02-28 17:23 UTC, what1s1ove commented on apps/frontend/src/pages/profile/profile.tsx
> +	let blocker = useBlocker(
```suggestion
```
let's do not add waring functionality now 
good that you think about it, but not for now. i think you can remove this `useBlocker ` at all

2024-02-28 20:04 UTC, Oleksandra-Masiuk approved these changes

2024-02-28 21:00 UTC, GEOFARL approved these changes

2024-02-29 06:50 UTC, fshabanov commented on apps/frontend/src/pages/profile/profile.tsx
> +								height="133"
Did you test this size in mobile view as well?

2024-02-29 08:22 UTC, what1s1ove commented on apps/frontend/src/pages/profile/profile.tsx
> +								height="133"
it okay to add it in HTML, you just need to change the values in CSS as well

2024-02-29 08:34 UTC, Sytnikovakatya commented on apps/frontend/src/pages/profile/profile.tsx
> +								height="133"
ok, I will change it

2024-02-29 11:31 UTC, fshabanov approved these changes

2024-02-29 11:31 UTC, fshabanov commented
@Sytnikovakatya merge main branch into yours

2024-02-29 14:48 UTC, merged