feat(backend/frontend/shared): add chat functionality tm-112
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #222
Opened 2024-02-27 19:58 UTC by Ann-Maksay

According to the ticket it's possible:
- Create a chat.
- View all existing chats and messages in them.
- Send a message.

Demo:
![create-chat2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/662481bd-0875-414e-9155-844553f128d6)
![answer-chat](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/2bd26558-0163-4475-aa13-9540165f9711)
![show-chat](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/b9aef6c0-c8c3-46fa-a7bb-d527c8a177cf)

UI elements:
![chats-link](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/47dd9d09-1675-412d-a3c2-1f814d967969)
![empty-chat](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/2d8b7c84-9b93-494b-8e55-c86c2d902384)
![chat](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/a4ad04b6-fd2f-45a4-aebd-d1e7a3abed21)
![message-pending](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/02689ce6-8a86-4c66-819c-2d2401e6d054)

2024-02-28 07:14 UTC, what1s1ove requested changes

2024-02-28 07:14 UTC, what1s1ove commented on apps/frontend/src/assets/img/chat-img.png
use `svg` instead

2024-02-28 07:14 UTC, what1s1ove commented on apps/frontend/src/libs/constants/date-format.constants.ts
> +const DATE_FORMAT_VALUES = {
B29

2024-02-28 07:14 UTC, what1s1ove commented on apps/frontend/src/libs/helpers/create-query-link/create-query-link.helper.ts
> +const createQueryLink = (
you need to use the URL/URLSearchParams constructor instead and i am not sure if you really need to have this helper

2024-02-28 07:14 UTC, what1s1ove commented on apps/frontend/src/modules/app/app.ts
> +export { actions, reducer } from "./slices/app.js";
we will not have such module in the APP move it to `src/libs/slices/app`

2024-02-28 07:14 UTC, what1s1ove commented on apps/frontend/src/libs/helpers/format-date/format-date.helper.ts
> +const formatDate = (inputDate: string): string => {
let's install `date-fns` package in the shared module and we will use it instead

2024-02-28 07:14 UTC, what1s1ove commented on apps/frontend/src/modules/chats/slices/chats.slice.ts
> +	interlocutor: UserAuthResponseDto | null;
can we use user from `auth` slice instead?

2024-02-28 07:14 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat-sidebar/chat-sidebar.tsx
> +			{Boolean(chats) && chats.length > ARRAY_EMPTY_LENGTH ? (
```suggestion
const hasMessages = Boolean(chats.length)
			{hasMessages && (
```

2024-02-28 07:14 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat-sidebar/chat-sidebar.tsx
> +				<p className={styles["empty-chat-list"]}>
only `li` elements can be inside the `ul` element

2024-02-28 11:24 UTC, Ann-Maksay commented on apps/frontend/src/pages/chats/libs/components/chat-sidebar/chat-sidebar.tsx
> +			{Boolean(chats) && chats.length > ARRAY_EMPTY_LENGTH ? (
Linter doesn't allow to do it without 0
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/3b45383c-4f13-4cf9-9435-28c549717045)

2024-02-28 11:31 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/chats/libs/types/types.ts
> +	type ChatSingleItemResponseDto,
I changed it to `ChatItemResponseDto` in my PR too

2024-02-28 11:39 UTC, YourTeaChan commented on apps/frontend/src/pages/chats/libs/components/chat/styles.module.css
> +	background-color: #ffffff;
```suggestion
	background-color: var(--main-white);
```

2024-02-28 11:39 UTC, YourTeaChan commented on apps/frontend/src/pages/chats/libs/components/chat-sidebar/styles.module.css
> +	background-color: #ffffff;
```suggestion
	background-color: var(--main-white);
```

2024-02-28 11:39 UTC, YourTeaChan commented on apps/frontend/src/pages/chats/libs/components/chat-form/styles.module.css
> +	background-color: #ffffff;
```suggestion
	background-color: var(--main-white);
```

2024-02-28 12:01 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/chats/libs/components/chat-message/chat-message.tsx
> +		: getValidClassNames(styles["container"], styles["left"]);
```suggestion
	const containerClassNames = getValidClassNames(styles["container"], styles[isCurrentUserSender ? "right" : "left"])
```

2024-02-28 12:02 UTC, ShadowOfTheSpace approved these changes

2024-02-28 17:20 UTC, what1s1ove requested changes
Please repoint your branch to `main` and resolve conflicts

2024-02-28 18:12 UTC, YourTeaChan approved these changes

2024-02-28 19:13 UTC, Ann-Maksay commented on apps/frontend/src/assets/icons/message.svg
![hover](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/c9c04290-cbbd-4f29-a3b7-23a591560d7e)

2024-02-28 20:59 UTC, GEOFARL commented on apps/frontend/src/pages/chats/libs/components/empty-chat/empty-chat.tsx
> +import { AppRoute } from "~/libs/enums/app-route.enum.js";
```suggestion
import { AppRoute } from "~/libs/enums/enums.js";
```

2024-02-29 08:28 UTC, what1s1ove requested changes

2024-02-29 08:28 UTC, what1s1ove commented on apps/frontend/src/modules/chats/slices/chats.slice.ts
> +	interlocutor: UserAuthResponseDto | null;
got it, thank you!

2024-02-29 08:28 UTC, what1s1ove commented on packages/shared/src/libs/enums/date-value.enum.ts
> +};
```suggestion
} as const;
```

2024-02-29 08:28 UTC, what1s1ove commented on packages/shared/src/libs/helpers/format-date/format-date.helper.ts
> +const formatDate = (inputDateString: string): string => {
```suggestion
const formatDate = (inputDateString: string, type: valuesof<FormatDateType> ): string => {
```
add an enum for it and use it to pass to `format` function

2024-02-29 08:28 UTC, what1s1ove commented on packages/shared/src/libs/helpers/format-date/format-date.helper.ts
> +const formatDate = (inputDateString: string): string => {
I am not even sure that you will need a `DateValue` then

2024-03-01 07:10 UTC, GEOFARL approved these changes

2024-03-01 10:23 UTC, what1s1ove approved these changes

2024-03-01 10:24 UTC, merged