feat(backend/frontend/shared): add notifications tm-198
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #259
Opened 2024-02-29 17:55 UTC by MappariChan

![image_2024-02-29_19-44-32](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/f4a4aa36-809f-4158-8631-b2f1d09cf9df)

2024-02-29 19:19 UTC, fshabanov requested changes
What about renaming `sourceUser` to `user`? I think we will not need to fetch information about the current user, because we already have it (`request.user` in Backend and `user` in auth slice in Frontend). For `userId` you can rename it to something like `receiverUserId`

2024-02-29 19:19 UTC, fshabanov commented on apps/backend/src/modules/notifications/notification.entity.ts
> +		this.sourceUserAvtarUrl = sourceUserAvatarUrl;
```suggestion
		this.sourceUserAvatarUrl = sourceUserAvatarUrl;
```

2024-02-29 19:19 UTC, fshabanov commented on apps/backend/src/modules/notifications/notification.service.ts
> +				status: "unread",
```suggestion
				status: NotificationStatus.UNREAD,
```

2024-02-29 19:19 UTC, fshabanov commented on apps/backend/src/modules/user-notifications/user-notification.controller.ts
> +			handler: (options) =>
B27

2024-02-29 19:19 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +								label=""
```suggestion
								label="Notifications"
								hasVisuallyHiddenLabel
```

2024-02-29 19:19 UTC, fshabanov commented on apps/frontend/src/libs/helpers/get-time-ago/get-time-ago.ts
> +const getTimeAgo = (dateString: string): string => {
You can use date-fns instead

2024-02-29 19:19 UTC, fshabanov commented on packages/shared/src/modules/user-notifications/enums/user-notifications-api-path.enum.ts
> +	$ID: "/:notificationId",
```suggestion
	$NOTIFICATION_ID: "/:notificationId",
```

2024-02-29 19:22 UTC, fshabanov requested changes

2024-02-29 19:22 UTC, fshabanov commented on apps/backend/src/modules/notifications/notification.model.ts
> +			},
Do we fetch the current user in notification repository? Couldn't find it

2024-02-29 19:22 UTC, fshabanov commented on apps/backend/src/modules/notifications/notification.repository.ts
> +		);
Use a separate variable

2024-02-29 20:28 UTC, Vfivew approved these changes

2024-02-29 20:28 UTC, Vfivew commented on apps/backend/src/modules/notifications/notification.repository.ts
> +			NotificationEntity.initialize({
B27

2024-02-29 20:28 UTC, Vfivew commented on apps/backend/src/modules/notifications/notification.repository.ts
> +			NotificationEntity.initialize({
B27

2024-02-29 21:41 UTC, Oleksandra-Masiuk requested changes

2024-02-29 21:41 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.repository.ts
> +					.as("unreadNotifcationsCount"),
```suggestion
					.as("unreadNotificationsCount"),
```

2024-02-29 21:41 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.repository.ts
> +					.as("unreadNotifcationsCount"),
```suggestion
					.as("unreadNotificationsCount"),
```

2024-02-29 21:41 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.repository.ts
> +					hasUnreadNotifications: Boolean(+user.unreadNotifcationsCount),
Why do you need to convert user.unreadNotificationsCount to a number?
But if you need it is better not to use unary plus
```suggestion
					hasUnreadNotifications: Boolean(Number(user.unreadNotificationsCount)),
```

2024-02-29 21:41 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.repository.ts
> +					hasUnreadNotifications: Boolean(+user.unreadNotifcationsCount),
unary plus again
```suggestion
					hasUnreadNotifications: Boolean(+user.unreadNotificationsCount),
```

2024-02-29 21:41 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.repository.ts
> +					hasUnreadNotifications: Boolean(+user.unreadNotifcationsCount),
```suggestion
					hasUnreadNotifications: Boolean(+user.unreadNotificationsCount),
```

2024-02-29 21:41 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/header/header.tsx
> +									user.hasUnreadNotifications ? styles["unread"] : "",
As I remember it should give the same result
```suggestion
									user.hasUnreadNotifications && styles["unread"],
```

2024-03-01 09:09 UTC, MappariChan commented on apps/backend/src/modules/users/user.repository.ts
> +					hasUnreadNotifications: Boolean(+user.unreadNotifcationsCount),
When database returns data it returns it of type any and set it to the fields of the model which instance was created, and when I'm trying to cast it to the Boolean, even if there will be 0, it gives me true, so i need to cast it for sure

2024-03-01 09:12 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.repository.ts
> +					hasUnreadNotifications: Boolean(+user.unreadNotifcationsCount),
Okay, then please use `Number(user.unreadNotificationsCount)`

2024-03-01 10:41 UTC, what1s1ove requested changes

2024-03-01 10:41 UTC, what1s1ove commented on apps/backend/src/libs/types/service.type.ts
> +	update(id: number, payload: unknown): Promise<T>;
why it was changed?

2024-03-01 10:41 UTC, what1s1ove commented on apps/frontend/src/pages/notifications/notifications.tsx
> +				<Star height="13px" left="25%" top="10%" />
make it as one image

2024-03-01 10:41 UTC, what1s1ove commented on apps/frontend/src/pages/notifications/libs/components/star/star.tsx
remove it as we discussed

2024-03-01 10:41 UTC, what1s1ove commented on apps/frontend/src/pages/notifications/libs/components/notification-list-item/notification-list-item.tsx
> +import { formatDistanceToNow } from "date-fns";
```suggestion
```
you can not import this directly

2024-03-01 10:41 UTC, what1s1ove commented on apps/frontend/package.json
> +		"date-fns": "3.3.1",
```suggestion
```
we already have it in the shared module

2024-03-01 10:41 UTC, what1s1ove commented on apps/backend/src/modules/users/user.entity.ts
> +	private hasUnreadNotifications: boolean;
i am not sure that we need this flag. because if the have unread messages count then we can easily calculate it where we need it

2024-03-01 10:41 UTC, what1s1ove commented on apps/backend/src/modules/notifications/libs/enums/notification-message.enum.ts
> +	NEW_FOLLOWER_MESSAGE: "started following you.",
not sure that we need this enum

you need to create a method that will review type and payload instead. in this method, by type you can configure notification message

2024-03-01 10:47 UTC, MappariChan commented on apps/frontend/src/pages/notifications/notifications.tsx
> +				<Star height="13px" left="25%" top="10%" />
do you mean to leave the stars but add it to the image, or remove them and leave only character?

2024-03-01 10:50 UTC, MappariChan commented on apps/backend/src/modules/users/user.entity.ts
> +	private hasUnreadNotifications: boolean;
i have another option for it, to make separate request for this information, but I don't know by which route it should be handled

2024-03-02 10:58 UTC, YourTeaChan commented on apps/backend/src/modules/user-notifications/user-notification.controller.ts
> + *           type: number
```suggestion
 *         id:
 *           type: number
 *           minimum: 1
```

2024-03-02 10:58 UTC, YourTeaChan commented on apps/backend/src/modules/user-notifications/user-notification.controller.ts
> + *           type: number
```suggestion
 *         receiverUserId:
 *           type: number
 *           minimum: 1
```

2024-03-02 10:58 UTC, YourTeaChan commented on apps/backend/src/modules/user-notifications/user-notification.controller.ts
> + *           type: number
```suggestion
 *         userId:
 *           type: number
 *           minimum: 1
```

2024-03-02 10:58 UTC, YourTeaChan commented on apps/frontend/src/libs/components/icon/libs/maps/icon-name-to-svg.map.ts
> +import NotificationBell from "~/assets/icons/notification-bell.svg?react";
```suggestion
import NotificationBellIcon from "~/assets/icons/notification-bell.svg?react";
```

And maybe you can simplify it from NotificationBell to Bell

2024-03-02 13:40 UTC, fshabanov requested changes

2024-03-02 13:40 UTC, fshabanov commented on apps/backend/src/db/migrations/20240226182852_add_notifications_table.ts
> +		table.enum(ColumnName.TYPE, ["new_follower"]).notNullable();
Create enum for type

2024-03-02 13:40 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.repository.ts
> +
Remove this empty line

2024-03-02 13:40 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +			type: "new_follower",
Use enum here

2024-03-02 13:40 UTC, fshabanov commented on apps/backend/src/modules/notifications/notification.repository.ts
> +		const emptyArrayLength = 0;
We should already have this const in shared

2024-03-02 13:40 UTC, fshabanov commented on apps/backend/src/modules/user-notifications/user-notification.controller.ts
> +	 * /user-notifications/unread:
```suggestion
	 * /user-notifications/has-unread-notifications:
```

2024-03-02 16:28 UTC, what1s1ove requested changes

2024-03-02 16:28 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240226182852_add_notifications_table.ts
> +	TYPE: "type",
i am just not sure. for what we need this type?

2024-03-02 16:34 UTC, MappariChan commented on apps/backend/src/db/migrations/20240226182852_add_notifications_table.ts
> +	TYPE: "type",
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/259#discussion_r1508811676
So i think we need to store this type of the notification also

2024-03-03 15:56 UTC, GEOFARL commented on apps/backend/src/modules/friends/friend.repository.ts
> -
It seems unnecessary

2024-03-03 16:06 UTC, what1s1ove requested changes

2024-03-03 16:06 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240226182852_add_notifications_table.ts
> +	NEW_FOLLOWER: "new_follower",
```suggestion
	NEW_FOLLOWER: "new-follower",
```

2024-03-03 16:06 UTC, what1s1ove commented on apps/backend/src/modules/notifications/notification.service.ts
> +			new_follower: NotificationMessage.NEW_FOLLOWER_MESSAGE,
use enum here

2024-03-03 16:06 UTC, what1s1ove commented on apps/backend/src/modules/notifications/notification.service.ts
> +			new_follower: NotificationMessage.NEW_FOLLOWER_MESSAGE,
btw it would be better to use `switch` here

2024-03-03 16:06 UTC, what1s1ove commented on apps/backend/src/modules/notifications/notification.service.ts
> +			new_follower: NotificationMessage.NEW_FOLLOWER_MESSAGE,
`started following you.`. that it? Use a better message here

2024-03-03 16:06 UTC, what1s1ove commented on packages/shared/src/modules/notifications/libs/enums/notification-type.enum.ts
> +	NEW_FOLLOWER: "new_follower",
```suggestion
	NEW_FOLLOWER: "new-follower",
```

2024-03-03 16:06 UTC, what1s1ove commented on apps/frontend/src/libs/components/app/app.tsx
> +import { actions as userNotificationsAction } from "~/modules/user-notifications/user-notifications.js";
```suggestion
import { actions as userNotificationsActions } from "~/modules/user-notifications/user-notifications.js";
```

2024-03-03 16:23 UTC, fshabanov requested changes

2024-03-03 16:23 UTC, fshabanov commented on apps/frontend/src/modules/user-notifications/slices/actions.ts
> +const hasUserUnreadNotifications = createAsyncThunk<
Do you handle the case where the user reads notifications?

2024-03-03 18:26 UTC, MappariChan commented on apps/frontend/src/modules/user-notifications/slices/actions.ts
> +const hasUserUnreadNotifications = createAsyncThunk<
for now we don't have this feature, because i thought that it will work on the web sockets, but if I need to add it I will, so waiting answer how would be better

2024-03-03 18:38 UTC, fshabanov commented on apps/frontend/src/modules/user-notifications/slices/actions.ts
> +const hasUserUnreadNotifications = createAsyncThunk<
I don't think we need sockets for that. You can implement it now

2024-03-03 18:38 UTC, MappariChan commented on apps/frontend/src/modules/user-notifications/slices/actions.ts
> +const hasUserUnreadNotifications = createAsyncThunk<
Okay

2024-03-04 08:24 UTC, MappariChan commented on apps/backend/src/modules/notifications/notification.service.ts
> +			new_follower: NotificationMessage.NEW_FOLLOWER_MESSAGE,
linter requires 3 cases for `switch` at least, so maybe leave it in such way for now, and after there will be 3 different types of notifications replace to `switch`?

2024-03-05 08:59 UTC, KrasKa2 requested changes

2024-03-05 08:59 UTC, KrasKa2 commented on apps/backend/src/modules/notifications/notification.repository.ts
> +	public async findAllByUserId(userId: number): Promise<NotificationEntity[]> {
```suggestion
	public async findAllByReceiverUserId(receiverUserId: number): Promise<NotificationEntity[]> {
```

2024-03-05 08:59 UTC, KrasKa2 commented on apps/backend/src/modules/notifications/notification.repository.ts
> +	public async hasUserUnreadNotifications(userId: number): Promise<boolean> {
```suggestion
	public async hasUserUnreadNotifications(receiverUserId: number): Promise<boolean> {
```

2024-03-05 08:59 UTC, KrasKa2 commented on apps/frontend/src/pages/notifications/libs/components/notification-list-item/notification-list-item.tsx
> +			: getFormattedDate(notification.createdAt, FormatDateType.DD_MM_YYYY);
Could it be in a separate helper, for example `getTimeFromNowFormattedDate`? Because, we will need it in comments, I think

2024-03-05 14:15 UTC, KrasKa2 approved these changes

2024-03-05 15:28 UTC, what1s1ove commented on packages/shared/src/modules/user-notifications/validation-schemas/read-notifications-request.validation-schema.ts
> +const minIdValue = 1;
should be a part of vaidation enum

2024-03-05 15:30 UTC, what1s1ove commented on apps/frontend/src/pages/notifications/notifications.tsx
> +				<Image
put this image as a background

2024-03-05 15:31 UTC, what1s1ove commented on apps/frontend/src/pages/notifications/libs/components/notification-list/notification-list.tsx
> +	const setReadNotifications = (): void => {
A10

2024-03-05 15:39 UTC, fshabanov requested changes

2024-03-05 15:39 UTC, fshabanov commented on apps/backend/src/modules/user-notifications/user-notification.controller.ts
> +	public async hasUserUnreadNotifications(
```suggestion
	public async checkHasUserUnreadNotifications(
```

2024-03-05 18:51 UTC, Vfivew commented on apps/backend/src/db/migrations/20240226182852_add_notifications_table.ts
> +} as const;
Maybe we need it?
```suggestion
const NEW_FOLLOWER= "new-follower"
```

2024-03-05 18:51 UTC, Vfivew commented on apps/backend/src/modules/friends/friend.service.ts
> +	NotificationType,
If this is an enum, why do we name it a NotificationType? It's a bit confusing...

2024-03-05 18:51 UTC, Vfivew commented on apps/frontend/src/modules/user-notifications/slices/user-notifications.slice.ts
> +				const updatedNotification = action.payload.items.find(
```
const updatedNotification = action.payload.items.find((notification) => {
	return notification.id === value.id;
});
```

maybe this better way?

2024-03-05 19:51 UTC, MappariChan commented on apps/frontend/src/modules/user-notifications/slices/user-notifications.slice.ts
> +				const updatedNotification = action.payload.items.find(
I need to use this map to merge newly read notifications and other notifications

2024-03-06 07:36 UTC, what1s1ove requested changes

2024-03-06 07:36 UTC, what1s1ove commented on packages/shared/src/modules/user-notifications/enums/read-notifications-validation-messages.enum.ts
> +const ReadNotificationsValidationMessages = {
B23

2024-03-06 07:36 UTC, what1s1ove commented on packages/shared/src/modules/user-notifications/enums/read-notifications-validation-messages.enum.ts
> +const ReadNotificationsValidationMessages = {
and file name

2024-03-06 10:30 UTC, fshabanov requested changes

2024-03-06 10:30 UTC, fshabanov commented on apps/frontend/src/pages/notifications/libs/components/notification-list/notification-list.tsx
> +	const [readNotificationIds, setReadNotificationIds] = useState<number[]>([]);
Maybe make it a Set so that we don't have duplicate ids

2024-03-06 10:30 UTC, fshabanov commented on apps/frontend/src/pages/notifications/notifications.tsx
> +	useAppTitle(AppTitle.NOTIFICATION);
```suggestion
	useAppTitle(AppTitle.NOTIFICATIONS);
```

2024-03-06 10:30 UTC, fshabanov commented on packages/shared/src/modules/user-notifications/enums/enums.ts
> +export { NotificationsValidationMessages } from "./notifications-validation-messages.enum.js";
```suggestion
export { NotificationsValidationMessage } from "./notifications-validation-message.enum.js";
```

2024-03-06 10:30 UTC, fshabanov commented on packages/shared/src/modules/user-notifications/validation-schemas/validation-schemas.ts
> +export { readNotifications } from "./read-notifications-request.validation-schema.js";
File name and exported property names should be the same

2024-03-06 13:35 UTC, what1s1ove requested changes

2024-03-06 13:35 UTC, what1s1ove commented on packages/shared/src/modules/user-notifications/enums/notifications-validation-messages.enum.ts
> +const NotificationsValidationMessages = {
B23

2024-03-06 16:57 UTC, Sytnikovakatya approved these changes

2024-03-06 17:50 UTC, MappariChan commented on packages/shared/src/modules/user-notifications/enums/notification-validation-rule.enum.ts
> +	NOTIFICATION_IDS_ARRAY_MINIMUM_LENGHT: 1,
Sorry for that I should install install this extension earlier

2024-03-06 18:34 UTC, what1s1ove approved these changes
@MappariChan resolve conflicts please

2024-03-06 19:35 UTC, YourTeaChan approved these changes

2024-03-06 20:25 UTC, ShadowOfTheSpace requested changes

2024-03-06 20:25 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/notifications/notification.repository.ts
> +			.where("notifications.receiverUserId", "=", receiverUserId)
```suggestion
			.where({ receiverUserId: receiverUserId })
```

2024-03-06 20:25 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/notifications/notification.repository.ts
> +			.patchAndFetchById(notificationId, payload.toUpdateObject())
Write fields explicitly that you are updating

2024-03-06 20:25 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/users/user.repository.ts
> +			.select("*")
```suggestion
```
All fields are selected by default, you don't need to specify it

2024-03-06 21:13 UTC, ShadowOfTheSpace approved these changes

2024-03-07 06:42 UTC, what1s1ove approved these changes

2024-03-07 06:42 UTC, merged