feat: move test strategy and test plan to the GitHub tm-188
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #262
Opened 2024-03-01 00:13 UTC by MariiaKrasylnykova

2024-03-01 07:25 UTC, what1s1ove requested changes

2024-03-01 07:25 UTC, what1s1ove commented on docs/Test_Plan.md
all files should be in a `kebab-case` notation

2024-03-01 07:25 UTC, what1s1ove commented on docs/Test_Plan.md
> +<br/>
```suggestion

```
you can use new line and it will be as a `br` tag

2024-03-01 07:25 UTC, what1s1ove commented on docs/Test_Plan.md
> +# 1. Feature priorities
h1 (`#`) can be only one in the document

2024-03-01 08:54 UTC, fshabanov requested changes

2024-03-01 08:54 UTC, fshabanov commented on docs/Test_Strategy.md
> +| Test environment not available | Inform JS Couch on Slack, execute the testing process locally                                                                                      | JS Coach    |
```suggestion
| Test environment not available | Inform JS Coach on Slack, execute the testing process locally                                                                                      | JS Coach    |
```

2024-03-01 09:03 UTC, MariiaKrasylnykova commented on docs/Test_Strategy.md
> +| Test environment not available | Inform JS Couch on Slack, execute the testing process locally                                                                                      | JS Coach    |
Sorry for this typo

2024-03-01 09:05 UTC, MariiaKrasylnykova commented on docs/Test_Plan.md
> +# 1. Feature priorities
Got all your remarks, thanks

2024-03-01 13:43 UTC, fshabanov requested changes

2024-03-01 13:43 UTC, fshabanov commented on docs/test-strategy.md
> +**[Test Plan](https://docs.google.com/document/d/1nDmqEXj8gObbec4OoH-uJWdoxemDeMi_a_stn9vAZEI/edit?usp=sharing)** is composed by the QA team and contains:
Should it be a link to the `test-plan.md` file?

2024-03-01 15:29 UTC, what1s1ove approved these changes

2024-03-01 19:19 UTC, MariiaKrasylnykova commented on docs/test-strategy.md
> +**[Test Plan](https://docs.google.com/document/d/1nDmqEXj8gObbec4OoH-uJWdoxemDeMi_a_stn9vAZEI/edit?usp=sharing)** is composed by the QA team and contains:
Good point, thanks, fixed it

2024-03-02 08:10 UTC, fshabanov requested changes

2024-03-02 08:10 UTC, fshabanov commented on docs/test-strategy.md
> +[Test Plan](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/blob/main/docs/test-plan.md)
```suggestion
[Test Plan](./test-plan.md)
```
This should work

2024-03-02 13:45 UTC, fshabanov approved these changes

2024-03-02 13:45 UTC, merged