feat(frontend): search field mobile responsiveness tm-227
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #263
Opened 2024-03-01 01:48 UTC by ShadowOfTheSpace

![search-bar](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61262913/66aa7df6-be82-48d4-a9b8-59f3aacce1da)

2024-03-01 08:01 UTC, fshabanov requested changes

2024-03-01 08:01 UTC, fshabanov commented on apps/frontend/src/libs/components/search-bar/search-bar.tsx
> +	inputClassNames?: string | undefined;
```suggestion
	className?: string | undefined;
	inputClassName?: string | undefined;
```

2024-03-01 09:44 UTC, tarmiel requested changes

2024-03-01 09:44 UTC, tarmiel commented on apps/frontend/src/libs/components/header/styles.module.css
> +@media screen and (width <= 768px) {
```suggestion
@media screen and (--medium-screen) {
```

2024-03-01 09:44 UTC, tarmiel commented on apps/frontend/src/libs/components/search-bar/styles.module.css
> +@media screen and (width <= 768px) {
```suggestion
@media screen and (--medium-screen) {
```

2024-03-01 10:28 UTC, GEOFARL approved these changes

2024-03-01 10:49 UTC, what1s1ove requested changes

2024-03-01 10:49 UTC, what1s1ove commented on apps/frontend/src/libs/constants/pages-without-search-bar.constant.ts
> +const PAGES_WITHOUT_SEARCH_BAR: ValueOf<typeof AppRoute>[] = [
it's better to describe paths where we need it

2024-03-01 11:47 UTC, Vfivew approved these changes

2024-03-01 12:21 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/constants/pages-without-search-bar.constant.ts
> +const PAGES_WITHOUT_SEARCH_BAR: ValueOf<typeof AppRoute>[] = [
I don't get it @what1s1ove, can you explain more what do you mean? 
Do you mean that this constant should be placed in Header component?

2024-03-01 13:48 UTC, fshabanov commented on apps/frontend/src/libs/constants/pages-without-search-bar.constant.ts
> +const PAGES_WITHOUT_SEARCH_BAR: ValueOf<typeof AppRoute>[] = [
@ShadowOfTheSpace instead of `PAGES_WITHOUT_SEARCH_BAR` use `PAGES_WITH_SEARCH_BAR`

2024-03-01 18:45 UTC, Sytnikovakatya approved these changes

2024-03-01 19:44 UTC, YourTeaChan approved these changes

2024-03-02 08:13 UTC, fshabanov requested changes

2024-03-02 08:13 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +import { isPathMatchingPattern } from "~/libs/helpers/helpers.js";
B20

2024-03-02 10:16 UTC, fshabanov approved these changes

2024-03-02 11:56 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/header/styles.module.css
> +	.header:has(.search-bar-input:focus) .navigation {
B11?

2024-03-02 13:17 UTC, MappariChan approved these changes

2024-03-02 16:29 UTC, what1s1ove approved these changes

2024-03-02 16:29 UTC, merged