feat(frontend): add course description screen tm-48
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #267
Opened 2024-03-01 08:37 UTC by Sytnikovakatya

- Fetch the data for a selected course and sections of the selected course
- Create a screen on frontend and display course data

![Screenshot_6](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/c663fe21-b1a8-41cf-8f5d-76f318b9344f)
![Screenshot_7](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/454fbe89-92fb-416d-a4a1-77ad96203ebd)

2024-03-01 10:59 UTC, what1s1ove requested changes

2024-03-01 10:59 UTC, what1s1ove commented on apps/frontend/package.json
> +		"sanitize-html": "2.12.1"
move this package to shared and create yourown wrapper for this function

2024-03-01 10:59 UTC, what1s1ove commented on apps/frontend/src/assets/icons/back-round.svg
you should use CSS to write the circle. svg only for the arrow

2024-03-01 10:59 UTC, what1s1ove commented on apps/frontend/src/pages/course-info/course-info.tsx
> +				{courseSections.length > EMPTY_COURSE_SECTIONS && (
+, and add it to variable - const hasCourseSections = courseSections.length > EMPTY_ARRAY_LENGTH

2024-03-01 10:59 UTC, what1s1ove commented on apps/frontend/src/pages/course-info/libs/components/course-details/course-details.tsx
> +				<input
for working with form element, you can use only `useForm` hook

2024-03-01 10:59 UTC, what1s1ove commented on package.json
> +		"@types/sanitize-html": "2.11.0",
move it to shared as well

2024-03-01 11:07 UTC, tarmiel requested changes

2024-03-01 11:07 UTC, tarmiel commented on apps/frontend/src/modules/course-sections/course-sections-api.ts
> +		};
```suggestion
	public async getAllByCourseId(query: CourseSectionGetAllRequestDto): Promise<CourseSectionGetAllResponseDto> {
```

2024-03-01 11:07 UTC, tarmiel commented on apps/frontend/src/pages/course-info/course-info.tsx
> +		void dispatch(courseActions.getById({ id: Number(id) }));
Here will be a problem when user tries to enter in URL not number (request will go with id=NaN and it will be an error)

2024-03-01 11:19 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/content/libs/constants.ts
> +const MAXIMUM_LENGTH = 400;
```suggestion
const MAXIMUM_CONTENT_LENGTH = 400;
```
I think that you need to name it more detailed, because maximum length is not so obvious

2024-03-01 12:47 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/course/libs/component/course-card/styles.module.css
> +	font-family: Roboto, sans-serif;
Do we have a global font for it?

2024-03-01 12:48 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/course-sections/slices/actions.ts
> +	return courseSectionsApi.getAllByCourseId({ courseId: courseId });
```suggestion
	return courseSectionsApi.getAllByCourseId({ courseId });
```

2024-03-01 12:52 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/course-info/course-info.tsx
> +		}
```suggestion
                const courseId = Number(id);
		if (courseId) {
			void dispatch(courseActions.getById({ id }));
			void dispatch(
				courseSectionsActions.getAllByCourseId({ courseId }),
			);
		}
```

2024-03-01 12:57 UTC, fshabanov requested changes

2024-03-01 13:21 UTC, Sytnikovakatya commented on apps/frontend/src/index.tsx
> +import { CourseInfo } from "./pages/course-info/course-info.js";
But the main component is CourseInfo. And it consists of two other components: CourseDetails and CourseSections

2024-03-01 13:46 UTC, fshabanov commented on apps/frontend/src/index.tsx
> +import { CourseInfo } from "./pages/course-info/course-info.js";
In that case maybe "CourseDescription" or "CourseInformation"? Just don't use "Info" shortened, as you did

2024-03-01 14:19 UTC, Sytnikovakatya commented on apps/frontend/src/index.tsx
> +import { CourseInfo } from "./pages/course-info/course-info.js";
Yes, I agree with you. I wiil change it

2024-03-01 14:31 UTC, Sytnikovakatya commented on apps/frontend/src/pages/course-info/course-info.tsx
> +		}
I have to check "id" because I've got an error in line 27 that "Type 'string | undefined' is not assignable to type 'string'."

2024-03-01 17:28 UTC, tarmiel commented on apps/frontend/src/modules/course-sections/course.sections.ts
course.sections.ts -> course-sections.ts

2024-03-01 18:36 UTC, Sytnikovakatya commented on apps/frontend/src/pages/course-info/libs/components/course-details/course-details.tsx
> +				<input
I want to clarify about this moment. In this component, I'm not handling form submission or validation. I only need to manage the state of the currently selected tab by the radio button. Is it necessary to add useForm for such a situation?

2024-03-01 19:42 UTC, YourTeaChan approved these changes

2024-03-01 20:48 UTC, tarmiel requested changes

2024-03-01 20:48 UTC, tarmiel commented on apps/frontend/src/libs/modules/store/store.module.ts
> +} from "~/modules/course-sections/course.sections.js";
```suggestion
} from "~/modules/course-sections/course-sections.js";
```

2024-03-02 10:11 UTC, ShadowOfTheSpace approved these changes

2024-03-02 10:30 UTC, fshabanov requested changes

2024-03-02 10:30 UTC, fshabanov commented on apps/frontend/src/pages/course-description/course-description.tsx
> +			void dispatch(courseActions.getById({ id: id }));
```suggestion
			void dispatch(courseActions.getById({ id }));
```

2024-03-02 10:30 UTC, fshabanov commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +				<label className={styles["label"]} htmlFor="tab1">
Use more descriptive `htmlFor`

2024-03-02 11:52 UTC, Oleksandra-Masiuk requested changes

2024-03-02 11:52 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/content/content.tsx
> +		return <div dangerouslySetInnerHTML={{ __html: sanitizedString || "" }} />;
```suggestion
		return <div dangerouslySetInnerHTML={{ __html: sanitizedString ?? "" }} />;
```

2024-03-02 11:52 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/content/content.tsx
> +		string.slice(START_INDEX, MAXIMUM_CONTENT_LENGTH) + "...";
I think that we can create a separate helper for this

2024-03-02 11:52 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/course-description/course-description.tsx
> +		return;
```suggestion
		return null;
```

2024-03-02 11:52 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/content/content.tsx
> +		string.slice(START_INDEX, MAXIMUM_CONTENT_LENGTH) + "...";
and "..." should be a constant

2024-03-02 11:52 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/course/course.tsx
> +			{onAddCourse ? (
maybe we should add a separate boolean constant `hasAddCourse` to use?

2024-03-02 11:52 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/course-description/libs/components/course-details/styles.module.css
> +.tabs-radio:checked + .label + .content {
B11

2024-03-02 14:42 UTC, Vfivew commented on apps/frontend/src/libs/components/content/content.tsx
> +		return <div dangerouslySetInnerHTML={{ __html: sanitizedString || "" }} />;
Maybe better use this one.
`return <div dangerouslySetInnerHTML={{ __html: sanitizedString ? sanitizedString : "" }} />;`

2024-03-02 14:43 UTC, Vfivew approved these changes

2024-03-02 16:34 UTC, what1s1ove requested changes

2024-03-02 16:34 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +					onChange={handleCheckboxChange}
```suggestion
```
you can not work with input using `onChange` you can use only `use-form` hook. that it

2024-03-02 16:34 UTC, what1s1ove commented on apps/frontend/src/libs/helpers/get-truncated-content/get-truncated-content.helper.ts
> +	const ELLIPSIS = "...";
move at the top of the file

2024-03-02 16:34 UTC, what1s1ove commented on apps/frontend/src/libs/components/content/content.tsx
> +		return <div dangerouslySetInnerHTML={{ __html: sanitizedString || "" }} />;
it's because `const getSanitizedHtml = (content: string): string => {` always returns string. so you do not need this condition at all

2024-03-03 15:46 UTC, GEOFARL approved these changes

2024-03-03 16:11 UTC, what1s1ove requested changes

2024-03-03 16:11 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +					<input
use <button /> with the state here.

create an enum `Tab`. Use `Object.values(Tab).map((it) => <Tab />)` to render tabs

2024-03-04 07:02 UTC, what1s1ove requested changes

2024-03-04 07:02 UTC, what1s1ove commented on apps/frontend/src/libs/components/tab-item/tab-item.tsx
> +			{selectedTab === tab && tabContents[tab]}
```suggestion
```
content should be outside of the common component (apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx) only

2024-03-04 07:02 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +							label={item === Tab.ABOUT ? "About" : "Details"}
```suggestion
							label={tabToReadable[item]}
```
create a map for it

2024-03-04 07:02 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +							selectedTab={selectedTab}
```suggestion
							isSelected={item  === selectedTab}
```

2024-03-04 07:02 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +							tabContents={tabContents}
```suggestion
```
```jsx
<ul>
// list of tabs
</ul>
<div>
// content
</div>
```

2024-03-04 07:03 UTC, fshabanov requested changes

2024-03-04 07:03 UTC, fshabanov commented on apps/frontend/src/libs/components/tab-item/tab-item.tsx
> +	tabContents: TabContents;
```suggestion
	tabsContent: TabContents;
```
We name arrays in plural

2024-03-04 07:03 UTC, fshabanov commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +	}, COURSE_DETAILS_DELAY_MS);
Why is there debounce on tab change?

2024-03-04 08:22 UTC, Sytnikovakatya commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +	}, COURSE_DETAILS_DELAY_MS);
It doesn't working properly with useCallback.  But with initDebounce everything is ok

2024-03-04 11:10 UTC, what1s1ove requested changes

2024-03-04 11:10 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +	const tabToReadable = {
move it to `apps/frontend/src/pages/course-description/libs/components/course-details/libs/maps/tabToReadable.map.ts`

2024-03-04 11:10 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +	const [selectedTab, setSelectedTab] = useState<string>(Tab.ABOUT);
```suggestion
	const [selectedTab, setSelectedTab] = useState<ValuesOf<Tab>>(Tab.ABOUT);
```

2024-03-04 17:45 UTC, what1s1ove requested changes

2024-03-04 17:45 UTC, what1s1ove commented on apps/frontend/src/libs/components/tab-item/tab-item.tsx
> +			<input
It shout be a button element, not an input element

2024-03-04 17:45 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +type TabValue = {
```suggestion
```
you do not need this type

2024-03-04 17:45 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +	const handleTabChange = (item: TabValue): void => {
```suggestion
	const handleTabChange = (tab: ValueOf<typeof Tab>): void => {
```

2024-03-04 17:46 UTC, what1s1ove requested changes

2024-03-04 17:46 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +			<form onChange={handleFormChange}>
```suggestion
```
not you can remove this form, since you will render only `button`s

2024-03-04 19:53 UTC, GEOFARL commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +	const handleTabContentRender = (selectedTab: string): React.ReactNode => {
```suggestion
	const handleTabContentRender = (selectedTab: ValueOf<typeof Tab>): React.ReactNode => {
```

2024-03-05 06:06 UTC, fshabanov requested changes

2024-03-05 06:06 UTC, fshabanov commented on apps/frontend/src/libs/components/content/content.tsx
> +	const sanitizedString = getSanitizedHtml(content);
```suggestion
	const sanitizedContent = getSanitizedHtml(content);
```

2024-03-05 06:06 UTC, fshabanov commented on apps/frontend/src/pages/course-description/libs/components/course-details/course-details.tsx
> +	const handleTabContentRender = (selectedTab: string): React.ReactNode => {
Not resolved

2024-03-05 07:17 UTC, what1s1ove approved these changes

2024-03-05 07:17 UTC, merged