feat(frontend/backend/shared): add possibility to complete remove completion of a course section tm-161
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #275
Opened 2024-03-01 17:35 UTC by tarmiel

![изображение](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/eb6b36c1-8eba-4a10-9de4-ea90cc02014f)

2024-03-01 18:20 UTC, fshabanov requested changes

2024-03-01 18:20 UTC, fshabanov commented on apps/backend/src/modules/section-statuses/section-status.repository.ts
> +			.andWhere("user_id", userId)
```suggestion
			.whereIn("courseSectionId", function () {
				void this.select("id")
					.from(DatabaseTableName.COURSE_SECTIONS)
					.where("courseId", courseId);
			})
			.andWhere("userId", userId)
```

2024-03-01 18:20 UTC, fshabanov commented on apps/backend/src/modules/section-statuses/section-status.service.ts
> +				userId: payload.userId,
Destructure properties of `payload`

2024-03-01 18:20 UTC, fshabanov commented on apps/frontend/src/modules/section-statuses/slices/section-statuses.slice.ts
> +		builder.addMatcher(
Use `addCase` for each separately

2024-03-01 18:20 UTC, fshabanov commented on packages/shared/src/modules/course-sections/libs/types/course-section-with-status-relation.type.ts
> +type CourseSectionWithStatusRelation = CourseSectionDto & {
```suggestion
type CourseSectionWithStatusDto = CourseSectionDto & {
```

2024-03-01 18:20 UTC, fshabanov commented on packages/shared/src/modules/section-statuses/libs/validation-schemas/section-status-create-body.validation-schema.ts
> +		courseSectionId: z.coerce.number(),
```suggestion
		courseSectionId: z.number(),
```
If it's for body we don't need coerce

2024-03-01 18:20 UTC, fshabanov commented on packages/shared/src/modules/section-statuses/libs/validation-schemas/validation-schemas.ts
> +export { sectionStatusesGetAllQuery } from "./section-statuses-get-all-query.validation-schema.js";
```suggestion
export { sectionStatusesGetAllQuery } from "./section-status-get-all-query.validation-schema.js";
```
Don't forget about the validation object variable name

2024-03-01 18:20 UTC, fshabanov commented on apps/frontend/src/pages/course-description/libs/components/course-sections/course-sections.tsx
> +						userId: user.id,
We don't need userId for create/update/delete, Backend already knows a user who sends requests

2024-03-01 18:20 UTC, fshabanov commented on apps/frontend/src/pages/course-description/libs/components/course-sections/course-sections.tsx
> +			sectionStatusActions.getAll({ courseId: courseId, userId: user.id }),
No need to send userId for the current user, only send it if we are viewing another user's course

2024-03-01 19:14 UTC, Vfivew approved these changes

2024-03-01 19:14 UTC, Vfivew commented on apps/backend/src/modules/section-statuses/section-status.repository.ts
> +		});
The same, but it's up to you to choose
```suggestion
      return sectionStatusModel
          ? SectionStatusEntity.initialize({
                  courseSectionId: sectionStatusModel.courseSectionId,
                  createdAt: sectionStatusModel.createdAt,
                  id: sectionStatusModel.id,
                  status: sectionStatusModel.status,
                  updatedAt: sectionStatusModel.updatedAt,
                  userId: sectionStatusModel.userId,
            })
      : null;
```

2024-03-01 19:32 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/checkbox/styles.module.css
> +	color: #ffffff;
```suggestion
	color: var(--main-white);
```

2024-03-01 19:37 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/section-statuses/section-statuses-api.ts
> +			this.getFullEndpoint(`${SectionStatusesApiPath.ROOT}${id}`, {}),
```suggestion
			this.getFullEndpoint(SectionStatusesApiPath.$ID, {id: String(id)}),
```

2024-03-01 20:41 UTC, tarmiel commented on apps/frontend/src/pages/course-description/libs/components/course-sections/course-sections.tsx
> +			sectionStatusActions.getAll({ courseId: courseId, userId: user.id }),
At this moment, I don't think that we can distinguish our courses from those of other users.

2024-03-02 07:34 UTC, Sytnikovakatya approved these changes

2024-03-02 10:40 UTC, YourTeaChan commented on apps/backend/src/modules/section-statuses/section-status.controller.ts
> +	 *        201:
```suggestion
	 *        200:
```

2024-03-02 16:42 UTC, what1s1ove requested changes

2024-03-02 16:42 UTC, what1s1ove commented on apps/backend/src/modules/section-statuses/libs/constants/relation-name.constant.ts
> +const RELATION_NAME = "courseSections";
use an enum here. think in advance in such cases

2024-03-02 16:42 UTC, what1s1ove commented on apps/backend/src/modules/section-statuses/section-status.repository.ts
> +		});
can be both

2024-03-02 16:42 UTC, what1s1ove commented on packages/shared/src/modules/section-statuses/libs/validation-schemas/section-status-update-body.validation-schema.ts
> +		status: z.enum([SectionStatus.COMPLETED, SectionStatus.IN_PROGRESS]),
```suggestion
		status: z.enum(Object.values(SectionStatus)),
```

2024-03-02 17:53 UTC, tarmiel commented on apps/backend/src/modules/section-statuses/libs/constants/relation-name.constant.ts
> +const RELATION_NAME = "courseSections";
I did this at first, but enum with one field was recommended to convert in constant several times

2024-03-03 08:37 UTC, fshabanov requested changes

2024-03-03 08:37 UTC, fshabanov commented on apps/backend/src/modules/section-statuses/section-status.service.ts
> +				userId: userId,
```suggestion
				courseSectionId,
				status,
				userId,
```

2024-03-03 08:37 UTC, fshabanov commented on apps/frontend/src/pages/course-description/libs/components/course-sections/course-sections.tsx
> +			sectionStatusActions.getAll({ courseId: courseId, userId: user.id }),
As discussed, we will have `/users/:userId/courses/:courseId`, make sure that the current user cannot change the section status for other user's course

2024-03-03 16:30 UTC, fshabanov requested changes

2024-03-03 16:30 UTC, fshabanov commented on apps/frontend/src/pages/course-description/course-description.tsx
> +						courseId={Number(course.id)}
Isn't `course.id` already a number?

2024-03-03 16:30 UTC, fshabanov commented on apps/frontend/src/pages/course-description/libs/components/course-sections/course-sections.tsx
> +import { DataStatus } from "~/libs/enums/data-status.enum.js";
```suggestion
import { DataStatus } from "~/libs/enums/enums.js";
```

2024-03-03 16:40 UTC, what1s1ove requested changes

2024-03-03 16:40 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/course-description.tsx
> +						courseId={Number(course.id)}
from `useParams` it's a string

2024-03-03 16:40 UTC, what1s1ove commented on packages/shared/src/modules/section-statuses/libs/validation-schemas/section-status-create-body.validation-schema.ts
> +		status: z.enum(getZodEnum(Object.values(SectionStatus))),
`Object.values(SectionStatus)` can we just use a type case here ? 

i do not like this helper

2024-03-03 16:42 UTC, fshabanov commented on apps/frontend/src/pages/course-description/course-description.tsx
> +						courseId={Number(course.id)}
Yes, but it is `courseId` from params, `course.id` comes from the `course` that we have in redux store

2024-03-03 16:52 UTC, tarmiel commented on packages/shared/src/modules/section-statuses/libs/validation-schemas/section-status-create-body.validation-schema.ts
> +		status: z.enum(getZodEnum(Object.values(SectionStatus))),
The problem here is that zod.enum requires an array with at least one element, but with object.values we can't guarantee that. Simple solution is to cast Object.values(SectionStatus) as [string, ...string[]], but we lose enum type(attempt to type cast properly looks messy). This issue almost everywhere is solved by using such a helper and I don't actually find cleaner solution

2024-03-04 19:56 UTC, GEOFARL approved these changes

2024-03-05 08:17 UTC, what1s1ove approved these changes

2024-03-05 08:17 UTC, merged