fix(frontend/backend): add course functionality tm-27
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #277
Opened 2024-03-01 20:42 UTC by tarmiel

Fixes for issues:

- Pressing "Enter", when the "Search" field is active, causes the page to reload
- Change the "Add the Course" title of the pop-up window to the "Add course" title
- The "Search" field should display the "Search" icon
- "Error: Unauthorized" server response in Swagger after adding the user-course

2024-03-01 21:27 UTC, Vfivew approved these changes

2024-03-02 07:06 UTC, ShadowOfTheSpace approved these changes

2024-03-02 07:22 UTC, GEOFARL approved these changes

2024-03-02 09:09 UTC, Sytnikovakatya approved these changes

2024-03-02 10:07 UTC, MappariChan approved these changes

2024-03-02 10:23 UTC, YourTeaChan approved these changes

2024-03-02 10:35 UTC, fshabanov approved these changes

2024-03-02 11:05 UTC, Oleksandra-Masiuk approved these changes

2024-03-02 16:36 UTC, what1s1ove requested changes

2024-03-02 16:36 UTC, what1s1ove commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +const handleFormSubmit = (event_: React.FormEvent<HTMLFormElement>): void => {
```suggestion
```
should be a part of the component

2024-03-02 17:51 UTC, tarmiel commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +const handleFormSubmit = (event_: React.FormEvent<HTMLFormElement>): void => {
Linter don't think so.

2024-03-03 16:12 UTC, what1s1ove approved these changes

2024-03-03 16:12 UTC, merged