feat(frontend/backend/shared): Add Progress for courses tm-206
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #282
Opened 2024-03-02 17:24 UTC by GEOFARL

![20240302_190839](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/76f39a11-c8ea-40dc-a96b-b3cd10030f31)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/0f8ca665-3f0e-4a00-9e8c-ff404b7565dd)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/e5fea5d6-04e1-4f47-818e-c6c2ff6eee7f)

2024-03-02 17:43 UTC, fshabanov requested changes

2024-03-02 17:43 UTC, fshabanov commented on apps/backend/src/modules/courses/course.service.ts
> +			});
Do not fetch everything from DB, only get the count of what you need

2024-03-02 17:43 UTC, fshabanov commented on apps/frontend/src/libs/components/course/course.tsx
> +	course: CourseDto | UserCourseDto;
What is the difference between these two?

2024-03-02 17:43 UTC, fshabanov commented on apps/frontend/src/pages/course-description/course-description.tsx
> +	);
But you already have this logic in Backend, why to duplicate it here?

2024-03-02 17:56 UTC, GEOFARL commented on apps/frontend/src/libs/components/course/course.tsx
> +	course: CourseDto | UserCourseDto;
UserCourse includes a progress, plain Course does not. I suppose, we need two different versions of them because courses that will be searched will not include any progress.

2024-03-02 17:58 UTC, GEOFARL commented on apps/frontend/src/pages/course-description/course-description.tsx
> +	);
We need this logic on the frontend side, because we do not refetch a course object every time we mark a course section as completed. The circular progress on the course details page will depend on the number of completed sections

2024-03-02 19:26 UTC, tarmiel commented on apps/backend/src/modules/section-statuses/section-status.repository.ts
> +			.andWhere("status", "completed")
```suggestion
			.andWhere("status", SectionStatus.COMPLETED)
```

2024-03-02 19:26 UTC, tarmiel commented on apps/backend/src/modules/user-courses/user-course.service.ts
> +		return await Promise.all(
Don't you think that it would be too many requests to DB?

2024-03-02 19:26 UTC, tarmiel commented on apps/frontend/src/libs/components/circular-progress/circular-progress.tsx
> +			<svg
We do not use svg in components. I think you can use Icon and change --percentage variable in div above

2024-03-03 06:57 UTC, GEOFARL commented on apps/frontend/src/libs/components/circular-progress/circular-progress.tsx
> +			<svg
Do not see the problem with this approach, I do not think that it should be an icon

2024-03-03 10:20 UTC, Sytnikovakatya approved these changes

2024-03-03 12:49 UTC, fshabanov requested changes

2024-03-03 12:49 UTC, fshabanov commented on apps/backend/src/modules/courses/libs/types/progress-data-item.type.ts
> +	totalSections: number;
```suggestion
	completedSectionsCount: number;
	courseId: number;
	totalSectionsCount: number;
```

2024-03-03 12:49 UTC, fshabanov commented on apps/backend/src/modules/users/user.model.ts
> +import { UserCourseModel } from "~/modules/user-courses/user-course-model.js";
```suggestion
import { UserCourseModel } from "~/modules/user-courses/user-course.model.js";
```

2024-03-03 12:49 UTC, fshabanov commented on apps/frontend/src/libs/components/course/libs/components/course-card/course-card.tsx
> +import { LinearProgress } from "../../../../linear-progress/linear-progress.js";
```suggestion
import { LinearProgress } from "~/libs/components/linear-progress/linear-progress.js";
```

2024-03-03 12:49 UTC, fshabanov commented on apps/frontend/src/pages/course-description/libs/components/course-activities/course-activities.tsx
> +					<span className={styles["tag-name"]}>In Process</span>
```suggestion
					<span className={styles["tag-name"]}>In Progress</span>
```

2024-03-03 13:39 UTC, KrasKa2 requested changes

2024-03-03 13:39 UTC, KrasKa2 commented on apps/backend/src/modules/courses/course.repository.ts
> +	}): Promise<UserCourseEntity[]> {
When user search courses, we need to filter them from courses which user has already added, and for this purpose   we use method `findByUserId` (and do not need user progress). So it is better to create another method, which will return `UserCourseEntity[]` in order to avoid redundant queries when user search courses

2024-03-03 13:39 UTC, KrasKa2 commented on apps/frontend/src/libs/components/course/course.tsx
> +	course: CourseDto | UserCourseDto;
@GEOFARL eventually, in the CourseCard component you cast course to `UserCourseDto`. 
So I think it is better to use only `UserCourseDto`:
` course: UserCourseDto;`

2024-03-03 14:08 UTC, GEOFARL commented on apps/frontend/src/libs/components/course/course.tsx
> +	course: CourseDto | UserCourseDto;
I cast it there, so I could use destructuring and get progress, which in turn can be undefined if we have CourseDto instead of UserCourseDto and then the progress will not be displayed

2024-03-03 16:15 UTC, what1s1ove requested changes

2024-03-03 16:15 UTC, what1s1ove commented on packages/shared/src/libs/helpers/get-percentage/get-percentage.helper.ts
> +function getPercentage({
please, follow the style of the app. use an arrow function

2024-03-03 16:15 UTC, what1s1ove commented on packages/shared/src/modules/user-courses/libs/types/user-course-dto.type.ts
> +type UserCourseDto = { progress: number } & CourseDto;
```suggestion
```
you need to calculate it on frontend only

2024-03-03 16:29 UTC, GEOFARL commented on packages/shared/src/modules/user-courses/libs/types/user-course-dto.type.ts
> +type UserCourseDto = { progress: number } & CourseDto;
I use it on the backend side as well, in `user-course.service`

2024-03-03 20:15 UTC, KrasKa2 commented on apps/frontend/src/libs/components/course/course.tsx
> +	course: CourseDto | UserCourseDto;
I understand, so you need here only `UserCourseDto`. Because, if we pass here `CourseDto` this component don't work correctly. Right?

2024-03-03 21:36 UTC, GEOFARL commented on apps/frontend/src/libs/components/course/course.tsx
> +	course: CourseDto | UserCourseDto;
It will be just a plain course component without progress for now, later if we will add ratings, we can also diferentiate whether to show them based on which type of course obj was passed

2024-03-04 07:08 UTC, fshabanov requested changes

2024-03-04 07:08 UTC, fshabanov commented on apps/frontend/src/libs/components/course/libs/components/course-card/course-card.tsx
> +// eslint-disable-next-line import/no-unresolved
You can't disable rules

2024-03-04 07:09 UTC, GEOFARL commented on apps/frontend/src/libs/components/course/libs/components/course-card/course-card.tsx
> +// eslint-disable-next-line import/no-unresolved
Eslint does not resolve that path, should I make it relative back?

2024-03-04 11:53 UTC, fshabanov commented on apps/frontend/src/libs/components/course/libs/components/course-card/course-card.tsx
> +// eslint-disable-next-line import/no-unresolved
Yes, you can use relative path here

2024-03-04 15:09 UTC, what1s1ove commented on packages/shared/src/modules/user-courses/libs/types/user-course-dto.type.ts
> +type UserCourseDto = { progress: number } & CourseDto;
you do not need anything related to progress on the backend this time

2024-03-04 18:32 UTC, GEOFARL commented on packages/shared/src/modules/user-courses/libs/types/user-course-dto.type.ts
> +type UserCourseDto = { progress: number } & CourseDto;
I do not understand what you mean by 'I do not need anything related to progres on the backend'.
We cannot calculate the progress for all of the user courses on the frontend side, because for this we will need to fetch all of the course sections and all of their statuses, which would be irrational, so we need to send a progress with them from the backend.

2024-03-05 12:37 UTC, what1s1ove requested changes

2024-03-05 12:37 UTC, what1s1ove commented on apps/frontend/src/modules/user-courses/slices/user-courses.slice.ts
> +	myCourses: UserCourseDto[];
add prefix to request/response. it should be added to the shared folder and should be used on both frontend/backend

2024-03-05 12:37 UTC, what1s1ove commented on apps/frontend/src/modules/user-courses/libs/types/user-courses-response-dto.type.ts
> +	courses: UserCourseDto[];
```suggestion
	items: UserCourseDto[];
```
add to to shared folder. use on both backend/frontned

2024-03-05 12:37 UTC, what1s1ove commented on apps/frontend/src/libs/components/courses/courses.tsx
> +	courses: (CourseDto | UserCourseDto)[];
create a separate key for it

2024-03-05 12:37 UTC, what1s1ove commented on apps/frontend/src/libs/components/course/libs/component/course-card/course-card.tsx
> +	const percentage = progress as number | undefined;
can not be undefined if UserCourseDto

2024-03-05 12:37 UTC, what1s1ove commented on apps/frontend/src/libs/components/course/libs/component/course-card/course-card.tsx
> +import { LinearProgress } from "../../../../linear-progress/linear-progress.js";
import from libs

2024-03-05 12:37 UTC, what1s1ove commented on apps/backend/src/modules/user-courses/user-course.service.ts
> +	}): Promise<(CourseDto & { progress: number })[]> {
create a type for it

2024-03-05 12:37 UTC, what1s1ove commented on apps/backend/src/modules/user-courses/user-course.model.ts
> +class UserCourseModel extends AbstractModel {
you do not need a new module for it

2024-03-05 12:37 UTC, what1s1ove commented on apps/backend/src/modules/user-courses/user-course.entity.ts
> +class UserCourseEntity implements Entity {
same. you do not need a new model for it

2024-03-05 12:37 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.repository.ts
> +			)) as unknown as ProgressDataItem[];
bad cast type

2024-03-05 13:19 UTC, GEOFARL commented on apps/frontend/src/libs/components/course/libs/component/course-card/course-card.tsx
> +import { LinearProgress } from "../../../../linear-progress/linear-progress.js";
[there is a problem with that](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/282#discussion_r1510673604)

2024-03-05 13:50 UTC, GEOFARL commented on apps/backend/src/modules/user-courses/user-course.model.ts
> +class UserCourseModel extends AbstractModel {
I need a new model and entity because UserCourse also includes a progress field which I get with a single query instead of [this approach](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/282#discussion_r1510022897) where I've not created a separate model and entity and just calculated a progress using existing ones, which resulted in making a lot of separate requests to DB

2024-03-05 13:51 UTC, GEOFARL commented on apps/backend/src/modules/user-courses/user-course.model.ts
> +class UserCourseModel extends AbstractModel {
Because to calculate a progress we need 2 separate tables besides courses. They are course-sections and section-statuses

2024-03-05 13:52 UTC, GEOFARL commented on apps/backend/src/modules/user-courses/user-course.entity.ts
> +class UserCourseEntity implements Entity {
[explained why I need it here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/282#discussion_r1512856854)

2024-03-05 13:57 UTC, GEOFARL commented on apps/backend/src/modules/courses/course.repository.ts
> +			)) as unknown as ProgressDataItem[];
not sure whether we can do it better here

2024-03-05 15:33 UTC, what1s1ove commented on apps/frontend/src/libs/components/course/libs/component/course-card/course-card.tsx
> +import { LinearProgress } from "../../../../linear-progress/linear-progress.js";
investigate the problem

2024-03-05 15:38 UTC, what1s1ove requested changes

2024-03-05 15:38 UTC, what1s1ove commented on apps/frontend/src/libs/components/courses/courses.tsx
> +	courses?: CourseDto[];
```suggestion
	courses: CourseDto[];
```
for courses should be only one key in props

2024-03-05 17:30 UTC, GEOFARL commented on apps/frontend/src/libs/components/courses/courses.tsx
> +	courses?: CourseDto[];
Did I understand [that](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/282#discussion_r1512752866) incorrectly?

2024-03-05 18:23 UTC, fshabanov requested changes

2024-03-05 18:23 UTC, fshabanov commented on apps/backend/src/modules/courses/course.repository.ts
> +		const progressData = await this.getProgressData(
Can we calculate the progress percentage directly within the DB call? We have too much logic in repository file

2024-03-05 18:36 UTC, Vfivew commented on apps/backend/src/modules/courses/course.repository.ts
> +		return coursesWithProgress.map((model) =>
B27

2024-03-05 18:36 UTC, Vfivew commented on apps/frontend/src/libs/components/course/libs/component/course-card/course-card.tsx
> +		: (userCourse as UserCourseResponseDto);
Are you sure about the safety here, considering that you're casting both types "as"?

2024-03-06 07:39 UTC, what1s1ove requested changes

2024-03-06 07:39 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.repository.ts
> +		const NO_PROGRESS = 0;
move it to a separate file

2024-03-06 07:39 UTC, what1s1ove commented on apps/frontend/src/libs/components/course/libs/component/course-card/course-card.tsx
> +const isUserCourse = (
B20

move it to a separate file

2024-03-06 07:39 UTC, what1s1ove commented on apps/frontend/src/libs/components/course/libs/component/course-card/course-card.tsx
> +	const { progress } = isUserCourse(course) ? course : { progress: null };
`{ progress: null }` bad. find an another solution

2024-03-06 07:40 UTC, fshabanov requested changes

2024-03-06 07:40 UTC, fshabanov commented on apps/frontend/src/libs/components/course/libs/component/course-card/course-card.tsx
> +	const { progress } = isUserCourse(course) ? course : { progress: null };
We should be able to see other users' progress as well

2024-03-06 08:41 UTC, GEOFARL commented on apps/frontend/src/libs/components/course/libs/component/course-card/course-card.tsx
> +	const { progress } = isUserCourse(course) ? course : { progress: null };
yeah, we can do that

2024-03-06 10:33 UTC, fshabanov requested changes

2024-03-06 10:33 UTC, fshabanov commented on apps/backend/src/modules/courses/libs/constants/user-course-without-progress.ts
> +const USER_COURSE_WITHOUT_PROGRESS = 0;
Not a great naming, this name says that it is a course, not a progress

2024-03-06 13:32 UTC, what1s1ove approved these changes

2024-03-06 13:32 UTC, merged