fix(frontend/backend): Add Friend page tm-40
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #284
Opened 2024-03-02 19:00 UTC by GEOFARL

- Updated the "Courses" title to be 20px
- Made the "Back" button to be as on the "Chat" and "Course details" pages and change after hovering
- Made the Follow" and "Following" buttons not to change regarding the user's name length (size should be 120px 32px)
- Made the GET /user-courses/{userId} response body not to be empty even when user has courses

2024-03-02 19:27 UTC, Vfivew commented on apps/frontend/src/pages/user/styles.module.css
> +	background-color: #e0e0e0;
Do we need new varieable for it maybe?

2024-03-03 07:09 UTC, Sytnikovakatya approved these changes

2024-03-03 08:15 UTC, what1s1ove requested changes

2024-03-03 08:15 UTC, what1s1ove commented on apps/frontend/src/pages/user/styles.module.css
> +	width: 120px;
```suggestion
	min-width: 120px;
```
never add a fix width

2024-03-03 11:00 UTC, GEOFARL commented on apps/frontend/src/pages/user/styles.module.css
> +	background-color: #e0e0e0;
I do not think that it is necessary

2024-03-03 12:26 UTC, KrasKa2 commented on apps/frontend/src/pages/user/styles.module.css
> +	background-color: #e0e0e0;
@GEOFARL  Why do you think so? We have a rule, that everything should be the same. So if we use vars for color, we should use it everywhere

2024-03-03 16:15 UTC, what1s1ove approved these changes

2024-03-03 16:16 UTC, merged