feat(frontend/backend/shared): Friends Activity Feed  tm-158
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #285
Opened 2024-03-02 21:01 UTC by KrasKa2

2024-03-02 21:30 UTC, Vfivew requested changes

2024-03-02 21:30 UTC, Vfivew commented on apps/backend/src/modules/activities/activity.repository.ts
> +		return activities.map((activity) =>
B27

2024-03-02 21:30 UTC, Vfivew commented on apps/backend/package.json
> +		"ts-node": "10.9.2"
Are we sure we should add this one? Need clarification.

2024-03-02 21:30 UTC, Vfivew commented on apps/backend/src/modules/activities/activity.repository.ts
> +			.withGraphJoined("user.userDetails.avatarFile")
It might be worth using RelationName.

2024-03-02 21:30 UTC, Vfivew commented on apps/frontend/src/pages/feed/libs/components/feed-activity/feed-activity.tsx
> +import { DEFAULT_USER_AVATAR } from "~/libs/constants/constants.js";
I deleted this avatar. Main branch did not have it.
Now we use this [one](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/blob/main/apps/frontend/src/assets/img/default-avatar.png)
```suggestion
import defaultAvatar from "~/assets/img/default-avatar.png";
```

2024-03-02 21:30 UTC, Vfivew commented on packages/shared/src/index.ts
> +	// type FinishSectionDto,
If you don't need it.
```suggestion
```

2024-03-02 21:30 UTC, Vfivew commented on packages/shared/src/modules/activities/activities.ts
> +	// type FinishSectionDto,
Same. I could be wrong, but maybe you don't need this anymore.
```suggestion
```

2024-03-03 07:01 UTC, KrasKa2 commented on apps/backend/package.json
> +		"ts-node": "10.9.2"
This is fix for run migrations. Maybe, it has to be in separate branch. I will ask

2024-03-03 07:02 UTC, KrasKa2 commented on apps/frontend/src/pages/feed/libs/components/feed-activity/feed-activity.tsx
> +import { DEFAULT_USER_AVATAR } from "~/libs/constants/constants.js";
Thank you!

2024-03-03 08:15 UTC, tarmiel requested changes

2024-03-03 08:15 UTC, tarmiel commented on packages/shared/src/modules/activities/libs/enums/activities-api-path.enum.ts
> +	FINISH_SECTION_$ID: "/finish-section/:actionId",
```suggestion
	FINISH_SECTION_$ACTION_ID: "/finish-section/:actionId",
```

2024-03-03 13:07 UTC, fshabanov requested changes

2024-03-03 13:07 UTC, fshabanov commented on apps/backend/src/modules/section-statuses/section-status.service.ts
> +		course &&
```suggestion
		if (hasCourse)
```

2024-03-03 13:07 UTC, fshabanov commented on apps/backend/src/modules/section-statuses/section-status.service.ts
> +		isDeleted &&
```suggestion
		if (isDeleted)
```

2024-03-03 13:07 UTC, fshabanov commented on apps/frontend/src/pages/feed/libs/components/feed-activity/feed-activity.tsx
> +};
Move it to a separate helper

2024-03-03 13:07 UTC, fshabanov commented on apps/frontend/src/pages/feed/libs/components/feed-activity/styles.module.css
> +@media screen and (width <=768px) {
Use custom media that we have

2024-03-03 14:40 UTC, KrasKa2 commented on apps/backend/src/modules/activities/activity.controller.ts
> +						body: ApplyRequestDto<"FINISH_SECTION">;
@fshabanov , I can make it as enum, but it will be less prettier:
```
type ApplyRequestDto<T extends ValueOf<typeof ActivityType>> = {
	actionId: number;
	payload: ActivityPayloadMap[T];
};

body: ApplyRequestDto<typeof ActivityType.FINISH_SECTION>;
```

2024-03-03 15:37 UTC, GEOFARL commented on apps/frontend/src/pages/feed/libs/components/feed-activity/feed-activity.tsx
> +const FeedAction: React.FC<Properties> = ({ activity }: Properties) => {
Component name does not match file name

2024-03-03 16:22 UTC, KrasKa2 commented on apps/frontend/src/pages/feed/libs/components/feed-activity/feed-activity.tsx
> +const FeedAction: React.FC<Properties> = ({ activity }: Properties) => {
@GEOFARL  Thanks!

2024-03-03 16:31 UTC, what1s1ove requested changes

2024-03-03 16:31 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +		table.enu(ColumnName.TYPE, columnTypeValues);
```suggestion
		table.enum(ColumnName.TYPE, columnTypeValues);
```

2024-03-03 16:31 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +const columnTypeValues = ["FINISH_COURSE", "FINISH_SECTION"];
use enum + kebab-case

2024-03-03 16:31 UTC, what1s1ove commented on apps/backend/src/libs/modules/database/libs/enums/sort-order.enum.ts
> +const SortOrder = {
move it to shared

2024-03-03 16:31 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/validation-schemas/validation-schemas.ts
> +export { actionIdParameter } from "./action-id-parameter.validation-schema.js";
validation schemas should start with `module` name

2024-03-03 16:31 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/activity-type.type.ts
> +type ActivityType = ValueOf<typeof ActivityTypeValue>;
use `ValueOf<typeof ActivityTypeValue>` here you need it

2024-03-03 16:31 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/validation-schemas/apply-finish-section.validation-schema.ts
> +		type: z
you need to validate payload by `type` since it can be different

2024-03-03 16:31 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/enums/activity-type-value.enum.ts
> +	FINISH_COURSE: "FINISH_COURSE",
kebab case

2024-03-03 16:31 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/activity-dto.type.ts
> +type ActivityDto<T extends ActivityType> = {
add response or request

2024-03-03 16:31 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/finish-course-dto.type.ts
> +type FinishCourseDto = {
```suggestion
type ActivityFinishCourseDto = {
```
do not forget about file name

add response or request

2024-03-03 16:31 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/finish-section-dto.type.ts
> +type FinishSectionDto = {
```suggestion
type ActivityFinishSectionDto = {
```
do not forget about file name

add response or request

2024-03-03 16:31 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/feed-activity-list/feed-activity-list.tsx
> +} from "~/modules/activities/libs/types/types.js";
```suggestion
} from "~/modules/activities/activities.js";
```

2024-03-03 16:31 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.entity.ts
> +import { type VendorEntity } from "~/modules/vendors/vendor.entity.js";
not sure that we nee to change it here

2024-03-03 19:25 UTC, KrasKa2 commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +		table.enu(ColumnName.TYPE, columnTypeValues);
I used documentation - https://knexjs.org/guide/schema-builder.html#enum-enu

2024-03-03 19:26 UTC, KrasKa2 commented on apps/backend/src/libs/modules/database/libs/enums/sort-order.enum.ts
> +const SortOrder = {
But we need it only at backend

2024-03-04 11:21 UTC, KrasKa2 commented on packages/shared/src/modules/activities/libs/validation-schemas/apply-finish-section.validation-schema.ts
> +		type: z
we do not need type here at all, because type is defining by url `/activities/finish-section`. I have just forgot to remove it

2024-03-04 19:47 UTC, GEOFARL commented on apps/frontend/src/assets/css/variables.css
> +	--color-container-hover-border: #00000080;
Are you sure that we need this variable?)

2024-03-04 19:47 UTC, GEOFARL commented on packages/shared/src/modules/activities/libs/types/activity-get-activities-response-dto.type.ts
> +type ActivityGetActivitiesResponseDto = {
maybe sth like this will be more readable
```suggestion
type ActivityGetAllResponseDto = {
```

2024-03-04 20:00 UTC, KrasKa2 commented on apps/frontend/src/assets/css/variables.css
> +	--color-container-hover-border: #00000080;
It is using now in two places and I think, number of this places will grows

2024-03-04 20:16 UTC, GEOFARL approved these changes

2024-03-05 07:53 UTC, Sytnikovakatya approved these changes

2024-03-05 12:47 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +const columnTypeValues = {
should be an enum

2024-03-05 12:47 UTC, what1s1ove commented on apps/backend/src/libs/modules/database/libs/enums/sort-order.enum.ts
> +const SortOrder = {
it's a common thing that can be used on both sides. as a debounce and etc

2024-03-05 12:47 UTC, what1s1ove commented on apps/backend/src/modules/activities/activity.controller.ts
> +type ApplyRequestDto<T extends ValueOf<typeof ActivityTypeValue>> = {
file should be clear. without any addition types. move it to libs

2024-03-05 12:47 UTC, what1s1ove commented on apps/backend/src/modules/activities/activity.repository.ts
> +				avatarUrl: activity.user.userDetails.avatarFile?.url || null,
A1. fir for all places

2024-03-05 12:47 UTC, what1s1ove commented on apps/backend/src/modules/activities/activity.service.ts
> +	private mapToDto(
```suggestion
```
u use it only in one place. so there is no need to create this method. use it directly in the map function

2024-03-05 12:47 UTC, what1s1ove commented on apps/frontend/src/modules/activities/libs/helpers/get-activity-title/get-activity-title.helper.ts
> +	const title = activity.payload.title;
```suggestion
	const { title } = activity.payload;
```
prefer descrturing

2024-03-05 12:47 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/activity-payload-map.type.ts
> +	"finish-course": ActivityFinishCourseRequestDto;
```suggestion
	[typeof Enum.KEY]: ActivityFinishCourseRequestDto;
```

2024-03-05 12:47 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/activity-finish-section-request-dto.type.ts
> +		id: null | number;
```suggestion
		id: null | number;
```
it really can be null?

2024-03-05 12:47 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/validation-schemas/activity-apply-finish-section.validation-schema.ts
> +		payload: z
i did not get for what you need this validation. could you describe the flow?

2024-03-05 13:06 UTC, KrasKa2 commented on packages/shared/src/modules/activities/libs/validation-schemas/activity-apply-finish-section.validation-schema.ts
> +		payload: z
In [controller](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/blob/32401248970410696ad3060ec7f45fa90b72c3df/apps/backend/src/modules/activities/activity.controller.ts#L73) we have a route `POST ActivitiesApiPath.FINISH_SECTION`. I had create this route it before merge with Oleg's branch. Now it is not using, but I decided to leave it as technical route (like many other routes, which we don't use)

2024-03-05 13:15 UTC, KrasKa2 commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +const columnTypeValues = {
Why? I thought we don't use enum... In other migrations with enum fields used
```
const columnValues = {
	...
} as const; 
```
For example - https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/blob/32401248970410696ad3060ec7f45fa90b72c3df/apps/backend/src/db/migrations/20240225143100_add_chat_messages_table.ts#L5

2024-03-05 15:47 UTC, what1s1ove requested changes

2024-03-05 15:47 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +const columnTypeValues = {
now it is not an enum. make an enum from it

2024-03-05 15:47 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/validation-schemas/activity-apply-finish-section.validation-schema.ts
> +		payload: z
make it simple then. we need to provide only 1 id i guess

2024-03-05 15:47 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/validation-schemas/activity-apply-finish-section.validation-schema.ts
> +		payload: z
same for type

2024-03-05 18:01 UTC, Vfivew approved these changes

2024-03-05 18:01 UTC, Vfivew commented on apps/backend/src/modules/activities/activity.controller.ts
> +	private async create<T extends ValueOf<typeof ActivityTypeValue>>({
We dont need swager here? Or you missed it?

2024-03-05 19:08 UTC, fshabanov requested changes

2024-03-05 19:08 UTC, fshabanov commented on apps/backend/src/modules/activities/activity.service.ts
> +			const id = existingActivity.toPlainObject().id;
```suggestion
			const { id } = existingActivity.toPlainObject();
```

2024-03-05 19:08 UTC, fshabanov commented on packages/shared/src/modules/activities/libs/enums/activity-type-value.enum.ts
> +const ActivityTypeValue = {
```suggestion
const ActivityType = {
```

2024-03-05 20:17 UTC, KrasKa2 commented on apps/backend/src/modules/activities/activity.controller.ts
> +	private async create<T extends ValueOf<typeof ActivityTypeValue>>({
We do not need swagger here

2024-03-05 20:31 UTC, KrasKa2 commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +const columnTypeValues = {
Maybe, I do not understand what enum do you mean... When I do this:
```
enum columnTypeValues {
	FINISH_COURSE = "finish-course",
	FINISH_SECTION = "finish-section",
}
```
I get lint error - ` TS features are forbidden  no-restricted-syntax`

2024-03-05 20:44 UTC, KrasKa2 commented on apps/backend/src/modules/activities/activity.controller.ts
> +	private async create<T extends ValueOf<typeof ActivityTypeValue>>({
I do not use it as handler

2024-03-05 22:31 UTC, tarmiel commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +const columnTypeValues = {
B23

2024-03-06 02:34 UTC, ShadowOfTheSpace commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +const columnTypeValues = {
I think Vlad talk about naming of enum. I think enum should be named as `ColumnTypeValue`

2024-03-06 10:33 UTC, KrasKa2 commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +const columnTypeValues = {
@ShadowOfTheSpace Thank you!

2024-03-06 11:54 UTC, tarmiel requested changes

2024-03-06 11:54 UTC, tarmiel commented on apps/backend/src/db/migrations/20240301171049_add_activities_table.ts
> +const columnTypeValue = {
```suggestion
const ColumnTypeValue = {
```

2024-03-06 13:14 UTC, Ann-Maksay commented on apps/frontend/src/modules/activities/slices/actions.ts
> +import { type ActivityGetAllResponseDto } from "~/modules/activities/libs/types/types.js";
```suggestion
import { type ActivityGetAllResponseDto } from "../libs/types/types.js";
```

2024-03-06 13:31 UTC, what1s1ove requested changes

2024-03-06 13:31 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/activity-finish-section-request-dto.type.ts
> +	course: {
is not resolved

2024-03-06 13:40 UTC, fshabanov requested changes

2024-03-06 13:40 UTC, fshabanov commented on apps/backend/src/modules/activities/activity.repository.ts
> +			actionId: activity.actionId,
`activity` can be `undefined` here

2024-03-06 13:40 UTC, fshabanov commented on apps/backend/src/modules/activities/activity.repository.ts
> +			.castTo<ActivityModel | null>()
It is not a correct cast, it can be `undefined`

2024-03-06 13:40 UTC, fshabanov commented on apps/backend/src/modules/activities/activity.repository.ts
> +			actionId: updatedActivity.actionId,
Can be `undefined`

2024-03-06 15:34 UTC, what1s1ove requested changes

2024-03-06 15:34 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/activity-finish-section-response-dto.type.ts
> +	course: {
is not resolved

2024-03-06 15:34 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/activity-finish-section-response-dto.type.ts
> +	course: {
remove useless keys, or at lease make the object flat (without the nested object)

2024-03-06 16:08 UTC, fshabanov requested changes

2024-03-06 18:09 UTC, Ann-Maksay approved these changes

2024-03-06 18:31 UTC, what1s1ove approved these changes

2024-03-06 18:32 UTC, merged