feat(backend): add edx vendor tm-211
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #292
Opened 2024-03-03 09:25 UTC by Ann-Maksay

At the moment this is a draft service that is responsible for requests to edX API made based on [swagger documentation](https://courses.edx.org/api-docs/)
And it does not cover all necessary functionality.
Available:
1. Get a list of courses
2. Get course information by ID.

Not Available:
1. Search by course
2. Get course sections.

Displaying the list of courses:
![show_courses](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/3a656f1a-2417-43ad-859b-6ab265580fc3)

Course details:
![deteils](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/d154847f-8c83-45df-b241-1164ff016dd0)

To make it clearer, the data I have on the course. The route with blocks returns an authorisation error, so it is not possible to get the course sections.
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/8e23c1af-c4ca-4083-81ba-d9c023ed2c7c)

2024-03-03 09:26 UTC, Ann-Maksay commented on apps/backend/src/modules/vendors/edx.service.ts
> +		course.image = `${this.baseUrl}${courseImage["uri"] as string}`;
Actually I did it very roughly, as I think, because the object received from the real API is different and the mapping function will be deeply refactored.

2024-03-03 09:26 UTC, Ann-Maksay commented on apps/backend/src/modules/vendors/edx.service.ts
> +		await Promise.resolve(vendorId);
All this is necessary to avoid errors related to types that methods return in VendorService.

2024-03-03 09:38 UTC, Vfivew commented on apps/backend/src/db/migrations/20240302150600_add_edx_vendor.ts
> +};
```suggestion
const TABLE_NAME = "vendors"
```

2024-03-03 10:11 UTC, Sytnikovakatya approved these changes

2024-03-03 12:34 UTC, Vfivew approved these changes

2024-03-03 13:12 UTC, fshabanov requested changes

2024-03-03 13:12 UTC, fshabanov commented on apps/backend/src/modules/vendors/libs/enums/edx-api-path.enum.ts
> +	COURSES_SECTIONS: "api/courses/v1/blocks/",
`api/courses/v1` should be a part of URL in ENV

2024-03-03 13:28 UTC, Ann-Maksay commented on apps/backend/src/modules/vendors/libs/enums/edx-api-path.enum.ts
> +	COURSES_SECTIONS: "api/courses/v1/blocks/",
The URL from .env is also used to create the image path, but there is no part with `api/courses/v1/`. This is the main reason why I split the route this way. I really should change it @fshabanov ?
Image route: `${this.baseUrl}${courseImage["uri"]`

2024-03-03 15:05 UTC, GEOFARL approved these changes

2024-03-03 16:36 UTC, what1s1ove requested changes

2024-03-03 16:36 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240302150600_add_edx_vendor.ts
> +const TableName = "vendors";
it is not a enum

2024-03-03 16:36 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240302150600_add_edx_vendor.ts
> +const row = { key: "edx", name: "edX", url: "https://www.edx.org" };
should be a constant

2024-03-03 16:36 UTC, what1s1ove commented on apps/backend/src/modules/vendors/edx.service.ts
> +	private load(url: string, query: Record<string, unknown>): Promise<Response> {
use real types everywhere in this file. describe fields (at least that we use)

2024-03-03 16:36 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/enums/edx-course-field.enum.ts
> +const EdxCourseField: Record<string, string> = {
```suggestion
const EdxCourseField = {
```

2024-03-04 11:47 UTC, Ann-Maksay commented on apps/backend/src/modules/vendors/edx.service.ts
> +	private load(url: string, query: Record<string, unknown>): Promise<Response> {
I'm not sure how I can best describe the type for query. So far I've got something like this:
```
type EdxCourseQuery = {
  search_term?: string;
  page?: number;
  pageSize?: number;
};
```
But as they say, if I want to make an optional key, it's better to ask how not to make it

2024-03-04 13:44 UTC, what1s1ove requested changes

2024-03-04 13:44 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240302150600_add_edx_vendor.ts
> +const Row = { key: "edx", name: "edX", url: "https://www.edx.org" } as const;
it is not an enum. it's a constant

2024-03-04 13:44 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/types/edx-course-response-dto.type.ts
> +	[key: string]: unknown;
```suggestion
```
do not use an index signature. describe only keys that we need

2024-03-04 13:44 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/types/edx-course-response-dto.type.ts
> +type EdxMedia = {
each type should be in a separate file

2024-03-04 13:44 UTC, what1s1ove commented on apps/backend/src/modules/vendors/edx.service.ts
> +		const result = await this.load(url, query);
make `load` as a generic. Check the http service

2024-03-04 13:44 UTC, what1s1ove commented on apps/backend/src/modules/vendors/edx.service.ts
> +	private async loadResults(
why do we need a separate method for it if we use it only in `getCourses`

2024-03-04 13:44 UTC, what1s1ove commented on apps/backend/src/modules/vendors/edx.service.ts
> +		query: Record<string, unknown>,
use a real type

2024-03-04 13:44 UTC, what1s1ove commented on apps/backend/src/modules/vendors/edx.service.ts
> +		const query: Record<string, unknown> = {
use a real type

2024-03-04 13:44 UTC, what1s1ove commented on apps/backend/src/modules/vendors/edx.service.ts
> +	private load(url: string, query: Record<string, unknown>): Promise<Response> {
you can use an optional keys here

2024-03-05 15:40 UTC, what1s1ove requested changes

2024-03-05 15:40 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/mapper/edx-course-fields.mapper.ts
> +const EdxCourseFieldsMapping: CourseFieldsMapping = {
should be a map, not an enum

2024-03-05 15:40 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/mapper/edx-course-fields.mapper.ts
> +const EdxCourseFieldsMapping: CourseFieldsMapping = {
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/320#discussion_r1513019239

2024-03-05 15:40 UTC, what1s1ove commented on apps/backend/src/modules/vendors/edx.service.ts
> +		await Promise.resolve(vendorId);
return Promise.resolve([]) ?

2024-03-05 17:01 UTC, Ann-Maksay commented on apps/backend/src/modules/vendors/edx.service.ts
> +		await Promise.resolve(vendorId);
I tried it first, but linter won't let it pass. This method must have a string argument, must have an asynchronous operation and must return an array.

2024-03-05 18:33 UTC, Vfivew requested changes

2024-03-05 18:33 UTC, Vfivew commented on apps/backend/src/modules/vendors/libs/mapper/edx-course-fields.mapper.ts
> +const EdxCourseFieldsMap: CourseFieldsMapping = {
Vlad taught me, and now I can pass on this knowledge to you!
https://dev.to/what1s1ove/javascript-naming-conventions-are-important-45n
```suggestion
const edxCourseToCourse: CourseFieldsMapping = {
```

2024-03-06 07:17 UTC, what1s1ove requested changes

2024-03-06 07:17 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/mapper/edx-course-fields.mapper.ts
> +import { EdxCourseField } from "~/modules/vendors/libs/enums/enums.js";
should be in `maps` folder and with `map` prefix

2024-03-06 07:17 UTC, what1s1ove commented on apps/backend/src/modules/vendors/edx.service.ts
> +		await Promise.resolve(vendorId);
you can remove this argument at all

2024-03-06 12:41 UTC, KrasKa2 approved these changes

2024-03-06 13:36 UTC, what1s1ove approved these changes

2024-03-06 13:36 UTC, merged