feat(frontend): course description screen mobile responsiveness tm-63
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #303
Opened 2024-03-03 17:03 UTC by Vfivew

2024-03-03 18:40 UTC, fshabanov requested changes

2024-03-03 18:40 UTC, fshabanov commented on apps/frontend/src/pages/course-description/libs/components/course-sections/styles.module.css
> +}
The previous media query will already handle this case

2024-03-04 10:59 UTC, GEOFARL approved these changes

2024-03-04 15:23 UTC, Ann-Maksay approved these changes

2024-03-05 12:51 UTC, what1s1ove requested changes

2024-03-05 12:51 UTC, what1s1ove commented on .ebextensions/alb-http-to-https-redirection.config
> -  AWSEBV2LoadBalancerListener:
this file should not be changed

2024-03-05 15:17 UTC, what1s1ove approved these changes

2024-03-05 15:17 UTC, merged