feat(frontend): update favicon and page titles tm-295
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #311
Opened 2024-03-04 10:17 UTC by Vfivew

2024-03-04 10:58 UTC, GEOFARL approved these changes

2024-03-04 11:07 UTC, what1s1ove requested changes

2024-03-04 11:07 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-app-titile/use-app-title.hooks.ts
> +		document.title = title;
do not duplicate enum values "TrackMates" should be the default

then if you provide something you need to write the logic for it `${title ? `${title} | ` : ''}TrackMates`

2024-03-04 13:38 UTC, what1s1ove requested changes

2024-03-04 13:38 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-app-titile/use-app-title.hooks.ts
> +		document.title = title ? `${title} | TrackMates` : "TrackMates";
do not duplicate `TrackMates`

2024-03-04 13:38 UTC, what1s1ove commented on apps/frontend/index.html
> +		<link rel="icon" type="image/svg+xml" href="/assets/favicon.ico" />
`.ico` is not enough 
https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs

2024-03-04 16:12 UTC, Vfivew commented on apps/frontend/index.html
> +		<link rel="icon" type="image/svg+xml" href="/assets/favicon.ico" />
Vlad, here I simply added the missing part. In fact, I have a standard set for icons (I'll attach a screenshot). Or do you want 48х48 and 72х72 and others?
![Thi](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/f20ad9fd-2991-4d84-b463-4c12c7152186)
?"

2024-03-04 17:49 UTC, what1s1ove commented on apps/frontend/index.html
> +		<link rel="icon" type="image/svg+xml" href="/assets/favicon.ico" />
Got it, thank you

2024-03-05 07:09 UTC, Ann-Maksay approved these changes

2024-03-05 07:49 UTC, Sytnikovakatya approved these changes

2024-03-05 14:49 UTC, Vfivew commented on apps/frontend/src/libs/hooks/use-app-titile/use-app-title.hooks.ts
> +		document.title = title ? `${title} | TrackMates` : "TrackMates";
This way ${title ? ${title} |  : ''}TrackMates not work. Linter not allowed it.
So i did `document.title = (title ? title + " | " : "") + "TrackMates";`
I hope its good solution.

2024-03-05 15:20 UTC, what1s1ove approved these changes

2024-03-05 15:20 UTC, merged