feat(frontend): Implement Open Graph Protocol tm-304
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #314
Opened 2024-03-04 13:39 UTC by GEOFARL

<img width="647" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/919c7689-6cca-4896-b8c3-2a4b4e3c9235">

2024-03-04 13:46 UTC, what1s1ove requested changes

2024-03-04 13:46 UTC, what1s1ove commented on apps/frontend/index.html
> +			content="Trackmates - monitor your progress and the progress of your friends!"
as QA about the better description

2024-03-04 13:46 UTC, what1s1ove commented on apps/frontend/index.html
> +			content="http://development.eu-central-1.elasticbeanstalk.com/"
we can have more than 1 env

2024-03-04 13:46 UTC, what1s1ove commented on apps/frontend/index.html
> +		<meta property="og:title" content="Trackmates" />
also change the general title and description

2024-03-04 13:46 UTC, what1s1ove commented on apps/frontend/public/assets/screen-desk-1200-630.png
the name should be `socials.png`

2024-03-04 13:46 UTC, what1s1ove commented on apps/frontend/public/assets/screen-desk-1200-630.png
on the screen we should see our logo and that it (we discard it during our today's call)

2024-03-04 22:19 UTC, Vfivew commented
Why do you use large size 1200*630 png? Perhaps you need an SVG or a slightly cropped copy?

2024-03-05 07:19 UTC, what1s1ove requested changes

2024-03-05 07:19 UTC, what1s1ove commented on apps/frontend/index.html
> +		<meta
should be before the og

2024-03-05 15:21 UTC, what1s1ove approved these changes

2024-03-05 15:22 UTC, merged