feat(frontend/backend): quality criteria issues tm-310
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #320
Opened 2024-03-04 16:57 UTC by Vfivew

2024-03-04 20:14 UTC, KrasKa2 approved these changes

2024-03-04 20:17 UTC, GEOFARL approved these changes

2024-03-05 06:00 UTC, Ann-Maksay approved these changes

2024-03-05 06:55 UTC, Sytnikovakatya approved these changes

2024-03-05 07:21 UTC, fshabanov requested changes

2024-03-05 07:43 UTC, what1s1ove requested changes

2024-03-05 07:43 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/mapper/mappers.ts
name should be `apps/backend/src/modules/vendors/libs/maps/maps.ts`

2024-03-05 07:43 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/mapper/mappers.ts
> +export { UdemyCourseFieldsMapping } from "./udemy-course-fields.mapper.js";
naming for maps has it's own rules

https://binary-studio.com/blog/2021/08/04/js-and-everyday-data-structures/

2024-03-05 15:24 UTC, what1s1ove requested changes

2024-03-05 15:24 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/maps/udemy-course-fields-map.map.ts
> +const UdemyCourseFieldsMap: CourseFieldsMapping = {
```suggestion
const UdemyCourseFieldsMap: CourseFieldsMapping = {
```
> A map is a very useful and frequently used data structure in any programming language. For maps in the JavaScript world, there is a specific naming convention. The name should follow the pattern aToB, where a serves as the key for retrieving values from the map, followed by the preposition To, implying the mapping of two things, and then B, which is the mapped value for a.

https://dev.to/what1s1ove/javascript-naming-conventions-are-important-45n

2024-03-05 15:24 UTC, fshabanov requested changes

2024-03-05 15:24 UTC, fshabanov commented on apps/backend/src/modules/vendors/libs/maps/maps.ts
> +export { UdemyCourseSectionFieldsMap } from "./udemy-course-section-map-fields.map.js";
B17

2024-03-05 16:42 UTC, Vfivew commented on apps/backend/src/modules/vendors/libs/maps/udemy-course-fields-map.map.ts
> +const UdemyCourseFieldsMap: CourseFieldsMapping = {
I saw two patterns in the first article: 1) xToY and 2) xMap. I chose the second one because the name UdemyCourseSectionFieldsToCourseSectionTitle seemed too long to me. 
Thanks for the article!

2024-03-05 17:33 UTC, what1s1ove requested changes

2024-03-05 17:33 UTC, what1s1ove commented on apps/backend/src/modules/vendors/libs/maps/maps.ts
> +export { UdemyCourseSectionToCourseSection } from "./udemy-course-section-to-course-section.map.js";
Maps start with the lover case letter

2024-03-05 18:41 UTC, fshabanov approved these changes

2024-03-05 20:20 UTC, Oleksandra-Masiuk approved these changes

2024-03-06 07:08 UTC, what1s1ove approved these changes

2024-03-06 07:08 UTC, merged