feat(frontend/backend/shared): add pagination to overview tm-276
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #322
Opened 2024-03-04 17:43 UTC by tarmiel

![demo](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/a2df3022-9b5d-4caa-a819-3f0fa25028a5)

![Screenshot_2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/803e8c33-a286-448e-90c4-171d50d8bb8f)
![Screenshot_4](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/f8a28ef5-d14b-4e4d-ade0-06c46e06d155)
![Screenshot_3](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/f83c4f65-44fe-46b1-9018-09d0678fb668)

2024-03-04 20:14 UTC, GEOFARL commented on apps/frontend/src/libs/components/pagination/pagination.tsx
> +const ONE_ITEM_COUNT = 1;
You use the same constant in the get-pages-cut.helper

2024-03-04 20:14 UTC, GEOFARL commented on apps/frontend/src/libs/components/pagination/pagination.tsx
> +const NO_ITEMS_PAGE_COUNT = 0;
maybe these are also better be extracted to constants

2024-03-04 20:14 UTC, GEOFARL commented on apps/frontend/src/libs/components/search-bar/search-bar.tsx
> +import { PaginationValue } from "@trackmates/shared";
import from shared

2024-03-04 20:14 UTC, GEOFARL commented on apps/frontend/src/modules/user-courses/slices/actions.ts
> +import { PaginationValue } from "@trackmates/shared";
import from shared

2024-03-04 20:14 UTC, GEOFARL commented on apps/frontend/src/modules/user-courses/slices/user-courses.slice.ts
> +	totalMyCourses: number;
maybe this will be more readable
```suggestion
	totalNumberOfMyCourses: number;
```

2024-03-04 20:30 UTC, tarmiel commented on apps/frontend/src/libs/components/pagination/pagination.tsx
> +const NO_ITEMS_PAGE_COUNT = 0;
I believe that these constants are tightly coupled with the logic and behavior of this component and are not meant to be reused elsewhere, keeping them within the component file can improve code clarity. Just my personal opinion)

2024-03-05 07:46 UTC, what1s1ove requested changes

2024-03-05 07:46 UTC, what1s1ove commented on packages/shared/src/libs/enums/sort/sort-order.enum.ts
there should be no subfolders in `packages/shared/src/libs/enums`. the same for all things in src/libs (types, maps, etc)

2024-03-05 12:56 UTC, what1s1ove requested changes

2024-03-05 12:56 UTC, what1s1ove commented on apps/frontend/src/libs/components/pagination/pagination.tsx
> +	const pagesCount = Math.ceil(totalCount / pageSize);
most of this calculation should be a part of your hook, since pagination can have a different design

2024-03-05 12:56 UTC, what1s1ove commented on apps/frontend/src/libs/components/pagination/libs/helpers/get-pages-cut.helper.ts
> +const getPagesCut = ({
```suggestion
const getPagesCut: FnType = ({
```
combine GetPagesCutParameters and GetPagesCutReturn into one type

2024-03-05 12:56 UTC, what1s1ove commented on apps/frontend/src/libs/components/pagination/libs/helpers/get-pages-cut.helper.ts
> +}: GetPagesCutParameters): GetPagesCutReturn => {
it seems like all this helpers should also me a part of your hook

2024-03-05 15:42 UTC, what1s1ove approved these changes

2024-03-05 15:42 UTC, merged