fix(frontend): Search results should reset after reopening the "Add course" pop-up window tm-315
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #328
Opened 2024-03-04 19:24 UTC by GEOFARL

![20240304_211932](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/75e686f6-bbe0-4af2-9f4f-b5f7edaf617b)

Search results reset after reopening the "Add course" pop-up window, already added course is not shown with the active "Add" button

2024-03-04 21:38 UTC, Oleksandra-Masiuk commented on apps/frontend/src/modules/courses/slices/courses.slice.ts
> +					(payload) =>
B27

2024-03-04 22:53 UTC, Vfivew approved these changes

2024-03-05 05:55 UTC, Ann-Maksay approved these changes

2024-03-05 06:54 UTC, Sytnikovakatya approved these changes

2024-03-05 07:36 UTC, tarmiel commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +	}, [dispatch, addedCourses, onClose]);
I think the main point of your task wasn't to remove added courses, but to reset searched courses to not see them when we reopen modal. We already have lodic to disable add button

2024-03-05 07:47 UTC, GEOFARL commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +	}, [dispatch, addedCourses, onClose]);
I need to remeber somehow which courses were added from that modal window and when we close it just remove them from it, so when we reopen it later, they are not displayed again and we won't have ability to try to add already added course item.

<img width="575" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/f20703f2-db82-4006-a740-ebbaa1ee8c42">

2024-03-05 07:52 UTC, what1s1ove requested changes

2024-03-05 07:52 UTC, what1s1ove commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +	const extendedOnClose = useCallback((): void => {
the name for the handler is not right

2024-03-05 07:52 UTC, what1s1ove commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +			setAddedCourses((previous) => [...previous, payload]);
why we can not handle it just by clearing state on component unmount?

2024-03-05 14:10 UTC, GEOFARL commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +			setAddedCourses((previous) => [...previous, payload]);
great point

2024-03-05 14:13 UTC, GEOFARL commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +			setAddedCourses((previous) => [...previous, payload]);
I guess we probably then will be making more requests to openAPI which is costly

2024-03-05 17:57 UTC, fshabanov approved these changes

2024-03-05 18:35 UTC, Vfivew approved these changes

2024-03-05 18:43 UTC, fshabanov requested changes
Fix CI issues as well

2024-03-05 18:43 UTC, fshabanov commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +	const handleOnClose = useCallback((): void => {
```suggestion
	const handleClose = useCallback((): void => {
```

2024-03-06 02:09 UTC, YourTeaChan approved these changes

2024-03-06 07:07 UTC, what1s1ove approved these changes

2024-03-06 07:07 UTC, merged