fix(frontend): The "Back" button on the "Friend profile" page doesn't navigate to the previous tab on the "Friends" page tm-325
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #351
Opened 2024-03-05 17:38 UTC by GEOFARL

![20240305_181427](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/81ee7c6c-4759-495a-9111-8f88ff40c346)

2024-03-05 18:00 UTC, fshabanov requested changes

2024-03-05 18:00 UTC, fshabanov commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +		>;
I don't like that in URL we will always have `?redirectTo=...`, is there another way to do this?

2024-03-06 07:41 UTC, what1s1ove requested changes

2024-03-06 07:41 UTC, what1s1ove commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +	const Parameters = {
B35

2024-03-06 10:35 UTC, fshabanov approved these changes

2024-03-06 11:55 UTC, Sytnikovakatya approved these changes

2024-03-06 13:20 UTC, what1s1ove requested changes

2024-03-06 13:20 UTC, what1s1ove commented on apps/frontend/src/pages/user/libs/constants/previous-page.constant.ts
> +const PREVIOUS_PAGE = -1;
we have a constant for it `BACK_NAVIGATION_STEP`

2024-03-06 13:57 UTC, fshabanov requested changes

2024-03-06 13:57 UTC, fshabanov commented on apps/frontend/src/pages/user/user.tsx
> +import { BACK_NAVIGATION_STEP } from "../course-description/libs/constants/constants.js";
Move this constant to libs/constants

2024-03-06 14:05 UTC, fshabanov approved these changes

2024-03-06 15:30 UTC, what1s1ove approved these changes

2024-03-06 15:30 UTC, merged