feat(frontend): change button icon on hover tm-319
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #352
Opened 2024-03-05 20:14 UTC by KrasKa2

![task-319](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/153290443/41f6ec2b-e7b6-4a9d-990f-0eec4cf800d2)

2024-03-05 20:36 UTC, Vfivew approved these changes

2024-03-05 21:19 UTC, Sytnikovakatya approved these changes

2024-03-05 21:44 UTC, Oleksandra-Masiuk commented
Please, check out my answer in the chat. Maybe it will be helpful

2024-03-06 07:39 UTC, ShadowOfTheSpace reviewed
Can you use here className prop from the Icon component? I think you can create a new prop for the button (iconClassName) and pass it to the Icon component. I think it can be helpful for styling Icon outside of the Button component.

P.S. I saw answer in chat and I think my comment is not helpful for this situation(

2024-03-06 07:44 UTC, what1s1ove requested changes

2024-03-06 07:44 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +					<div className={styles["hoverIcon"]}>{hoverIcon}</div>
we will not add an additional icon here. find a better solution

you can add the classname prop to the Icon component to try to handle this issue

2024-03-06 11:56 UTC, KrasKa2 commented
> Can you use here className prop from the Icon component? I think you can create a new prop for the button (iconClassName) and pass it to the Icon component. I think it can be helpful for styling Icon outside of the Button component.
> 
> P.S. I saw answer in chat and I think my comment is not helpful for this situation, but if you change icon as Oleksandra said you can style it via iconClassName

@ShadowOfTheSpace your advice works only with Oleksandara's advice))

2024-03-06 12:08 UTC, fshabanov requested changes

2024-03-06 12:08 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +		<Icon className={iconClassName || ""} name={iconName} />
```suggestion
		<Icon className={iconClassName ?? ""} name={iconName} />
```

2024-03-06 13:21 UTC, what1s1ove requested changes

2024-03-06 13:21 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +		<Icon className={iconClassName || ""} name={iconName} />
change props in Icon components

2024-03-06 15:22 UTC, KrasKa2 commented on apps/frontend/src/libs/components/button/button.tsx
> +		<Icon className={iconClassName || ""} name={iconName} />
> change props in Icon components
@what1s1ove  I have done changes suggested by @fshabanov and I don't understand what alse I have to do

2024-03-06 15:30 UTC, Oleksandra-Masiuk approved these changes

2024-03-06 15:34 UTC, what1s1ove approved these changes

2024-03-06 15:34 UTC, merged