fix(frontend): update styles and the back button of course description screen tm-28
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #354
Opened 2024-03-05 21:12 UTC by Sytnikovakatya

- Remove the "Back to overview" text near the "Back" button, 
- The "Back" button navigates to the previous page.
- Delete the extra space between the image and "About"/"Details" tabs
- The orange line doesn't disappear after hovering over active tab
- The "Read more" link is gray and become orange after hovering
- The course title is gray and doesn't change after hovering
![Screenshot_8](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/c06928bb-81ae-438d-9846-d80860df109b)
![Screenshot_9](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/de684673-43f7-4a55-af92-24968d4e68da)

2024-03-05 21:18 UTC, Vfivew approved these changes

2024-03-05 21:40 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/course-description/course-description.tsx
> +		navigate(BACK_NAVIGATION_VALUE);
Maybe we can rename it to `BACK_NAVIGATION_STEP`? I feel that it is more descriptive

2024-03-06 02:02 UTC, YourTeaChan approved these changes

2024-03-06 02:31 UTC, ShadowOfTheSpace approved these changes

2024-03-06 07:06 UTC, Ann-Maksay approved these changes

2024-03-06 07:11 UTC, what1s1ove requested changes

2024-03-06 07:11 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/course-description.tsx
> +		navigate(BACK_NAVIGATION_VALUE);
agreed

2024-03-06 07:18 UTC, what1s1ove approved these changes

2024-03-06 07:18 UTC, merged