feat(backend/shared): UAM (User Access Management) - Groups tm-230
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #364
Opened 2024-03-06 08:10 UTC by YourTeaChan

2024-03-06 08:28 UTC, Vfivew requested changes

2024-03-06 08:28 UTC, Vfivew commented on apps/backend/src/modules/groups/group.repository.ts
> +		return permissions.map((permission) =>
B27

2024-03-06 08:28 UTC, Vfivew commented on packages/shared/src/modules/groups/libs/enums/group-error-message.enum.ts
> +	GROUP_NOT_FOUND: "Group not found",
You misses dot
```suggestion
	GROUP_NOT_FOUND: "Group not found.",
```

2024-03-06 08:40 UTC, tarmiel requested changes

2024-03-06 08:40 UTC, tarmiel commented on apps/backend/src/modules/groups/group.service.ts
> +		userService: UserService,
Pass it as an object and specify type Сonstructor

2024-03-06 08:40 UTC, tarmiel commented on packages/shared/src/modules/groups/libs/enums/group-error-message.enum.ts
> +	GROUP_NOT_FOUND: "Group not found",
```suggestion
	GROUP_NOT_FOUND: "Group not found.",
```

2024-03-06 08:40 UTC, tarmiel commented on apps/backend/src/modules/users/user.repository.ts
> +import { PermissionEntity } from "../permissions/permissions.js";
```suggestion
import { PermissionEntity } from "~/modules/permissions/permissions.js";
```

2024-03-06 08:40 UTC, tarmiel commented on apps/backend/src/modules/users/user.entity.ts
> +import { type GroupEntity, type GroupResponseDto } from "../groups/groups.js";
```suggestion
import { type GroupEntity, type GroupResponseDto } from "~/modules/groups/groups.js";
```

2024-03-06 09:18 UTC, fshabanov requested changes

2024-03-06 09:18 UTC, fshabanov commented on apps/backend/src/modules/permissions/permission.repository.ts
> +import { type Repository } from "~/libs/types/repository.type.js";
```suggestion
import { type Repository } from "~/libs/types/types.js";
```

2024-03-06 09:18 UTC, fshabanov commented on apps/backend/src/modules/permissions/permission.service.ts
> +			PermissionEntity.initializeNew({ key, name }),
What if with update we send key/name of an existing permission?

2024-03-06 09:18 UTC, fshabanov commented on apps/backend/src/modules/permissions/permission.service.ts
> +			PermissionEntity.initializeNew({ key, name }),
Same for groups

2024-03-06 09:18 UTC, fshabanov commented on apps/backend/src/modules/users/user.controller.ts
> +	private async findAll(): Promise<APIHandlerResponse> {
Add swagger docs

2024-03-06 11:51 UTC, Sytnikovakatya commented on apps/backend/src/modules/permissions/permission.service.ts
> +import { type Service } from "~/libs/types/service.type.js";
```suggestion
import { type Service } from "~/libs/types/type.js";
```

2024-03-07 06:47 UTC, GEOFARL approved these changes

2024-03-09 07:43 UTC, what1s1ove approved these changes

2024-03-09 07:43 UTC, what1s1ove commented on apps/backend/src/libs/hooks/check-user-permissions.hook.ts
> +import {
should be in a separate folder

2024-03-09 07:58 UTC, merged