fix(frontend): The element on the Friend profile section move regarding the user name tm-327
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #365
Opened 2024-03-06 09:37 UTC by GEOFARL

<img width="842" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/7f930c59-7daf-47a6-8813-719bf80f2148">

2024-03-06 09:59 UTC, GEOFARL commented
Need to clarify some moments with QAs

2024-03-06 11:11 UTC, Sytnikovakatya approved these changes

2024-03-06 13:23 UTC, what1s1ove requested changes
handle it with https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

2024-03-06 13:50 UTC, GEOFARL commented
> handle it with https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

contacted qa team about it before applying absolute positioning, they said that it is not acceptable

2024-03-06 20:27 UTC, ShadowOfTheSpace approved these changes

2024-03-06 21:55 UTC, Vfivew approved these changes

2024-03-07 07:20 UTC, what1s1ove approved these changes

2024-03-07 07:20 UTC, merged