fix(frontend): The "Add course" pop-up window is closed after pressing the mouse on the window and releasing it outside the window tm-321
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #377
Opened 2024-03-06 14:18 UTC by GEOFARL

2024-03-06 15:38 UTC, what1s1ove requested changes

2024-03-06 15:38 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-handle-click-outside/use-handle-click-outside.hook.tsx
> +		document.addEventListener("mousedown", handleClickOutside);
it should be click

2024-03-06 19:34 UTC, ShadowOfTheSpace approved these changes

2024-03-06 21:48 UTC, Vfivew approved these changes

2024-03-07 06:52 UTC, Sytnikovakatya approved these changes

2024-03-07 09:59 UTC, what1s1ove commented
Canceled https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/issues/321

2024-03-07 09:59 UTC, closed without merging