feat(backend/frontend/shared): add sex property to the user tm-343
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #379
Opened 2024-03-06 15:16 UTC by MappariChan

![2024-03-06 17-05-46](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/b131ad90-665a-42c9-b739-cfa5bc5952d1)

2024-03-06 15:21 UTC, fshabanov requested changes

2024-03-06 15:21 UTC, fshabanov commented on apps/backend/src/modules/auth/auth.controller.ts
> + *            enum: [Male, Female, Prefere not to say]
```suggestion
 *            enum: [Male, Female, Prefer not to say]
```

2024-03-06 15:21 UTC, fshabanov commented on apps/backend/src/modules/users/user.controller.ts
> +	 *                  enum: [Male, Female, Prefere not to say]
```suggestion
	 *                  enum: [Male, Female, Prefer not to say]
```

2024-03-06 15:21 UTC, fshabanov commented on apps/frontend/src/libs/components/select/select.tsx
> +			<select className={selectClasses} {...field} value={deffaulValue}>
```suggestion
			<select className={selectClasses} {...field} value={defaultValue}>
```

2024-03-06 15:21 UTC, fshabanov commented on packages/shared/src/modules/users/libs/validation-schemas/user-profile.validation-schema.ts
> +	sex: z.ZodNullable<z.ZodEnum<["Male", "Female", "Prefer not to say"]>>;
```suggestion
	sex: z.ZodNullable<z.ZodEnum<ValueOf<typeof UserSex>>>;
```

2024-03-06 15:49 UTC, what1s1ove requested changes

2024-03-06 15:49 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240306140243_add_sex_to_the_user_details_table.ts
> +	FEMALE: "Female",
should be kebab case

2024-03-06 15:49 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240306140243_add_sex_to_the_user_details_table.ts
> +			.enum(COLUMN_NAME, [
Object.values

2024-03-06 15:49 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/enums/user-sex.enum.ts
> +	FEMALE: "Female",
should be kebab case

2024-03-06 15:49 UTC, what1s1ove commented on apps/frontend/src/pages/profile/profile.tsx
> +								<option value={UserSex.MALE}>{UserSex.MALE}</option>
Object values for options

2024-03-06 15:49 UTC, what1s1ove commented on apps/frontend/src/libs/components/select/select.tsx
> +				<option disabled hidden value="">
we need to add it only in case if we have `isRequired` = true

2024-03-06 15:49 UTC, what1s1ove commented on apps/frontend/src/libs/components/select/select.tsx
> +	color = "light",
for what need this props?

2024-03-06 15:49 UTC, what1s1ove commented on apps/frontend/src/libs/components/select/select.tsx
> +	children: React.ReactNode;
```suggestion
```

2024-03-06 16:33 UTC, Sytnikovakatya approved these changes

2024-03-06 19:22 UTC, ShadowOfTheSpace approved these changes

2024-03-07 10:08 UTC, Vfivew approved these changes

2024-03-07 12:45 UTC, ShadowOfTheSpace commented on packages/shared/src/modules/users/libs/validation-schemas/user-profile.validation-schema.ts
> +	sex: z.ZodNullable<z.ZodEnum<["Male", "Female", "Prefer not to say"]>>;
Use ZodNativeEnum instead

2024-03-07 13:34 UTC, MappariChan commented on apps/frontend/src/libs/components/select/select.tsx
> +				<option disabled hidden value="">
do you mean to add the default option only when `isRequired = true`?

2024-03-07 14:48 UTC, what1s1ove requested changes

2024-03-07 14:48 UTC, what1s1ove commented on apps/frontend/src/libs/components/select/libs/types/option.type.ts
> +type Option = {
```suggestion
type SelectOption = {
```
should be in `src/libs/types`

2024-03-07 14:48 UTC, what1s1ove commented on apps/frontend/src/libs/components/select/select.tsx
> +				<option disabled hidden value="">
right

2024-03-07 14:48 UTC, what1s1ove commented on apps/frontend/src/pages/profile/profile.tsx
> +				label: convertKebabCaseToRegularString(sex, { capitalize: true }),
you do not need this helper. you need to use a map datastructure

2024-03-07 14:48 UTC, what1s1ove commented on packages/shared/src/libs/helpers/convert-kebab-case-to-regular-string/convert-kebab-case-to-regular-string.helper.ts
> +const convertKebabCaseToRegularString = (
```suggestion
```

2024-03-07 15:26 UTC, fshabanov requested changes

2024-03-07 15:26 UTC, fshabanov commented on packages/shared/src/modules/users/libs/validation-schemas/user-profile.validation-schema.ts
> +	sex: z.nativeEnum(UserSex).nullable(),
Let's use `enum` as we do in other places

2024-03-07 16:00 UTC, MappariChan commented on packages/shared/src/modules/users/libs/validation-schemas/user-profile.validation-schema.ts
> +	sex: z.nativeEnum(UserSex).nullable(),
I can't do as you said before
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/e60168f7-2d9c-4831-8f58-f202e8610656)
There is another way how to do this and it's something like that
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/6e8f8d5e-5bab-469e-8d3e-d3075ab5ea2a)
And for declaring schema types we didn't use ZodEnum before
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/bcf5baa7-28c5-4770-a389-e016e03ed0c9)
So can i leave NativeEnum because it's more readable?

2024-03-07 20:18 UTC, KrasKa2 approved these changes

2024-03-08 06:53 UTC, GEOFARL approved these changes

2024-03-08 07:22 UTC, fshabanov requested changes

2024-03-08 07:22 UTC, fshabanov commented on apps/frontend/src/libs/components/select/styles.module.css
> +	background-image: url("~/assets/icons/select-arrow.svg");
Do we need to have both?

2024-03-08 07:22 UTC, fshabanov commented on packages/shared/src/modules/users/libs/validation-schemas/user-profile.validation-schema.ts
> +	sex: z.nativeEnum(UserSex).nullable(),
I think we already have [type, ...type[]] somewhere else, so it is okay to use it

2024-03-08 08:06 UTC, what1s1ove requested changes

2024-03-08 08:06 UTC, what1s1ove commented on apps/frontend/src/pages/profile/profile.tsx
> +		const userSexToTheSelectLabel: Record<ValueOf<typeof UserSex>, string> = {
```suggestion
		const userSexToTheSelectLabel = {
```
move it to libs

2024-03-08 08:06 UTC, what1s1ove commented on apps/frontend/src/pages/profile/profile.tsx
> +		const userSexToTheSelectLabel: Record<ValueOf<typeof UserSex>, string> = {
```suggestion
		const userSexToReadable: Record<ValueOf<typeof UserSex>, string> = {
```

2024-03-08 08:40 UTC, what1s1ove approved these changes

2024-03-08 08:40 UTC, merged