feat: add protected routing tm-15
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #38
Opened 2024-02-10 15:09 UTC by tarmiel

Resolves #15

2024-02-10 18:02 UTC, fshabanov requested changes

2024-02-10 18:02 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import type { FC, ReactNode } from "react";
Use React.FC and React.ReactNode

2024-02-10 18:02 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import { Navigate } from "react-router-dom";
Export this from libs/components/components

2024-02-10 18:02 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import { AppRoute } from "~/libs/enums/app-route.enum.js";
```suggestion
import { AppRoute } from "~/libs/enums/enums.js";
```

2024-02-10 18:02 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +	const { user } = useAppSelector((state) => state.auth);
Check rule B27

2024-02-10 18:02 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +		return <Navigate replace to={redirectTo} />;
Why do we need `replace` here?

2024-02-10 18:02 UTC, fshabanov commented on apps/frontend/src/modules/auth/slices/auth.slice.ts
> +	user: null;
User can be other than null

2024-02-10 18:26 UTC, tarmiel commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +	const { user } = useAppSelector((state) => state.auth);
The exceptions are single-line arrow functions, which can be used without the required blocks of code

2024-02-10 18:26 UTC, tarmiel commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +		return <Navigate replace to={redirectTo} />;
By using replace, you ensure that the history stack doesn't accumulate unnecessary entries, leading to a cleaner browsing experience and it allows to seamlessly navigate users through the flow without cluttering the history with intermediate steps.

2024-02-10 18:26 UTC, tarmiel commented on apps/frontend/src/modules/auth/slices/auth.slice.ts
> +	user: null;
As I mentioned in the comment to this issue I mocked user as null, because we agreed with my colleague who's working on the related functionallity that he's responsible for adding proper type here

2024-02-10 18:34 UTC, tarmiel commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import { Navigate } from "react-router-dom";
If you mean ProtectedRoute component, it's already been done that way

2024-02-10 18:49 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import { Navigate } from "react-router-dom";
I mean Navigate component

2024-02-10 18:55 UTC, fshabanov commented on apps/frontend/src/modules/auth/slices/auth.slice.ts
> +	user: null;
You can add the type for User on your side as well and use it here. Other people, who will be working on User type will be able to modify it. You can discuss with others a proper naming, file location and other points so that you have same files for User type

2024-02-10 19:01 UTC, tarmiel commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import { Navigate } from "react-router-dom";
Are you sure? Firstly this is a library component and I don`t understand why it is important to do that, and secondly, I think I will get circular dependency if I place Navigate in libs/components/components and try to import it to a protected route component that also exported from there, no?

2024-02-10 19:27 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +import { Navigate } from "react-router-dom";
The reason we put library components in libs/components/components is that we don't import library components directly in a file, unless it won't be used anywhere else. In this case Navigate can be used in other places as well. If we import directly from the library in multiple files and in future we decide to change the library, we would need to change it in all files. When we export from the library in one file only it is much easier.
Regarding circular dependencies, it might cause an issue only when one of the imports is not yet initialized and is being used. In our case we won't have the issue here.

2024-02-11 07:19 UTC, what1s1ove requested changes

2024-02-11 07:19 UTC, what1s1ove commented on apps/frontend/src/modules/auth/slices/auth.slice.ts
> +import { type UserGetAllItemResponseDto as User } from "~/modules/users/users.js";
```suggestion
import { type UserGetAllItemResponseDto } from "~/modules/users/users.js";
```

2024-02-11 07:19 UTC, what1s1ove commented on apps/frontend/src/index.tsx
> +								element: <ProtectedRoute component={"Root"} />,
```suggestion
								element: <ProtectedRoute component="Root" />,
```

2024-02-11 08:53 UTC, fshabanov requested changes

2024-02-11 08:53 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +}: Properties) => {
```suggestion
}) => {
```
`React.FC<Properties>` already handles this

2024-02-11 08:58 UTC, tarmiel commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +}: Properties) => {
No, it does not. There are lint errors with missing react/props and I looked through other components to find this solution with duplicating Properties

2024-02-11 09:20 UTC, fshabanov commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +}: Properties) => {
You're right, sorry for misunderstanding

2024-02-11 09:20 UTC, what1s1ove approved these changes

2024-02-11 09:20 UTC, what1s1ove commented on apps/frontend/src/libs/components/protected-route/protected-route.tsx
> +}: Properties) => {
Right, this is a part of `eslint-react` config

2024-02-11 09:21 UTC, fshabanov approved these changes

2024-02-11 09:25 UTC, merged