feat(frontend/shared): add pagination with query tm-307
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #397
Opened 2024-03-07 10:35 UTC by Vfivew

![here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/8a7a21ff-8c62-4e8f-9d60-46042d2ca2b6)

2024-03-07 13:43 UTC, YourTeaChan commented on packages/shared/src/libs/enums/pagination-value.enum.ts
> +	PAGE_NOT_EXIST: 0,
```suggestion
	PAGE_NOT_EXISTS: 0,
```

2024-03-07 14:51 UTC, what1s1ove requested changes

2024-03-07 14:51 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +		history(`?page=${page}`, { replace: true });
we have useEffect with a page dependency, and we set it here, after the set-state function. it looks strange. you need to leave it in one place

2024-03-07 15:33 UTC, fshabanov requested changes

2024-03-07 15:33 UTC, fshabanov commented on apps/frontend/src/libs/hooks/use-pagination/libs/helpers/get-pages-valid.helper.ts
> +	const isPageParameterExist = searchParameters.has("page");
It doesn't make any sense, you send `pageFromUrl` to this helper, which comes from URL, no need to check it again

2024-03-07 15:33 UTC, fshabanov commented on packages/shared/src/libs/enums/pagination-value.enum.ts
> +	PAGE_NOT_EXISTS: 0,
Do we need it? If the page is not specified, then we will use `DEFAULT_PAGE`

2024-03-07 15:48 UTC, Vfivew commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +		if (pageFromUrl <= pagesCount && isValidPage) {
Yes. I redirect to 1-th page. I will show gif a bit later, when i resolve all fix

2024-03-07 18:26 UTC, Vfivew commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +		history(`?page=${page}`, { replace: true });
I will add another logic where there won't be handlePageChange. Instead of buttons in pagination, I would use links.

2024-03-07 21:06 UTC, Vfivew commented on packages/shared/src/libs/enums/pagination-value.enum.ts
> +	PAGE_NOT_EXISTS: 0,
When we have first render, i got total=0 in state .
So when we use `const pagesCount = Math.ceil(totalCount / pageSize);` - im got pagesCount=0.
I deliberately check for zero to avoid entering the 'else' block during the render.
So I need this constant. I can replace it with use-pagination.hook.ts if it is better.

2024-03-07 21:18 UTC, Oleksandra-Masiuk requested changes

2024-03-07 21:18 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/hooks/use-pagination/libs/helpers/get-pages-valid.helper.ts
> +const getPagesValid = ({
```suggestion
const checkIsPageValid = ({
```

2024-03-07 21:54 UTC, ShadowOfTheSpace requested changes

2024-03-07 21:54 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +		const searchParameters = new URLSearchParams(location.search);
Use `useSearchParams` hook instead

2024-03-07 21:54 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +	const history = useNavigate();
Rename variable `history` to `navigation`

2024-03-07 22:53 UTC, Vfivew commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +		if (pageFromUrl <= pagesCount && isValidPage) {
Well, here is a gif.
![pagin](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/f6ced2ad-7382-41eb-ba45-c066e4d77317)

2024-03-08 06:46 UTC, GEOFARL commented on apps/frontend/src/libs/components/pagination/libs/components/pagination-item/pagination-item.tsx
> +			<Link className={linkClasses} isDisabled={isDisabled ?? false} to={to}>
maybe, it'll be better to give to `isDisabled` a default parameter

2024-03-08 06:58 UTC, Sytnikovakatya approved these changes

2024-03-08 08:11 UTC, what1s1ove requested changes

2024-03-08 08:11 UTC, what1s1ove commented on apps/frontend/src/libs/components/link/link.tsx
> +		[activeClassName, className, isDisabled],
in case of disabled we need to render a span

2024-03-08 08:11 UTC, what1s1ove commented on apps/frontend/src/libs/components/link/styles.module.css
> +.disabled {
what about the keyboard and other devices? we need to render span instead

2024-03-08 08:11 UTC, what1s1ove commented on apps/frontend/src/libs/components/pagination/libs/components/pagination-item/pagination-item.tsx
> -			<button
it should be a button. you need to change it via handler

2024-03-08 08:58 UTC, Vfivew commented on apps/frontend/src/libs/components/pagination/libs/components/pagination-item/pagination-item.tsx
> -			<button
That is, all pagination items are buttons?
P.S. I just saw that links are used more often, so I changed it. This makes it easier to control what is in the query

2024-03-08 09:12 UTC, KrasKa2 approved these changes

2024-03-08 10:24 UTC, fshabanov requested changes

2024-03-08 10:24 UTC, fshabanov commented on apps/frontend/src/libs/components/pagination/libs/components/pagination-item/pagination-item.tsx
> +import { Link } from "../../../../link/link.js";
Fix the import route

2024-03-08 10:24 UTC, fshabanov commented on apps/frontend/src/libs/hooks/use-pagination/libs/helpers/cheak-is-vallid-page/cheak-is-vallid-page.helper.ts
> +	return pageFromUrl > PaginationValue.DEFAULT_PAGE;
It is a simple check and we use this helper only in 1 place, I don't think we need a separate helper for that

2024-03-08 14:56 UTC, Vfivew commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
>  	};
Now i use only UseEffect to control my url.

2024-03-08 15:50 UTC, fshabanov requested changes

2024-03-08 15:50 UTC, fshabanov commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +		if (pagesCount >= pageFromQuery) {
What if it is a negative page?

2024-03-08 15:54 UTC, YourTeaChan approved these changes

2024-03-08 16:19 UTC, Vfivew commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +		if (pagesCount >= pageFromQuery) {
Redirect to 1th page.
![redirect](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/1455aa59-a10b-4c08-9105-cb52ae829b4e)

2024-03-08 17:43 UTC, fshabanov approved these changes

2024-03-09 07:36 UTC, what1s1ove requested changes

2024-03-09 07:36 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +const QUERY_SECTION_SIZE = 1;
move to libs in this folder

2024-03-09 07:36 UTC, what1s1ove requested changes

2024-03-09 07:36 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +			pagesCount !== PaginationValue.PAGE_NOT_EXISTS ||
move this condition to variable

2024-03-09 10:36 UTC, Oleksandra-Masiuk requested changes

2024-03-09 10:36 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/hooks/use-pagination/libs/enums/query-section.enum.ts
> +const QuerySection = {
Why is it an enum? Will it have more properties, or is it meant to be used as a constant for checking conditions? 
Also, why is it named `QuerySection` and `SIZE`? From the name alone, its purpose isn't clear. Is it meant as a minimum or maximum query length for pagination? Please rename

2024-03-09 11:51 UTC, Ann-Maksay approved these changes

2024-03-09 15:18 UTC, fshabanov requested changes

2024-03-09 15:18 UTC, fshabanov commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +			queryParameters.size > QUERY_SECTION_MAX_SIZE;
Why do we need to check the size of query params? Maybe we will have other params?

2024-03-11 08:16 UTC, Vfivew commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +	const queryName = "page";
So, as part of this task, I have to add another hook for params?
Or should I just do it like in the screenshot for now?
![queryname](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/1651653c-3ee7-42f1-944c-ed927b40ff06)

2024-03-11 08:42 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +	const queryName = "page";
as on screenshot

2024-03-11 08:43 UTC, what1s1ove approved these changes

2024-03-11 08:43 UTC, merged