feat(frontend/backend/shared): add real time notifications tm-260
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #404
Opened 2024-03-07 17:05 UTC by Sytnikovakatya

Implement real-time notifications
![20240307_185348](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/ff758413-08b7-4450-b951-4cc80d8f5dd0)

2024-03-07 18:01 UTC, fshabanov requested changes

2024-03-07 18:01 UTC, fshabanov commented on packages/shared/src/modules/notifications/libs/types/notification-with-receiver-id-response-dto.type.ts
> +	Record<"notification", NotificationResponseDto>;
```suggestion
type NotificationWithReceiverIdResponseDto = {
  receiverId: number;
	notification: NotificationResponseDto>;
}
```
Why not like this?

2024-03-07 20:43 UTC, Oleksandra-Masiuk requested changes

2024-03-07 21:40 UTC, GEOFARL approved these changes

2024-03-08 06:39 UTC, Sytnikovakatya commented on apps/backend/src/libs/modules/socket/socket-service.module.ts
> +	private notificationsHandler(socket: Socket): void {
Yes, sure

2024-03-08 07:24 UTC, Oleksandra-Masiuk approved these changes

2024-03-08 08:07 UTC, MappariChan commented on apps/backend/src/modules/friends/friend.service.ts
> +
I think you should do this inside of the notification service and inject this socket service into it

2024-03-08 08:13 UTC, MappariChan commented on packages/shared/src/libs/modules/socket/libs/enums/socket-event.enum.ts
> +	NOTIFICATIONS_NEW_FOLLOWER: "notifications-new-follower",
```suggestion
	NEW_NOTIFICATION: "new-notification",
```
I think there will be only one socket message handler for all type of notifications, so I think this enum value would be better

2024-03-08 08:31 UTC, MappariChan commented on apps/frontend/src/libs/modules/store/middlewares/notifications-socket.middleware.ts
> +		);
I think you should retrieve notification from the payload of the socket message and set it to the state of the notification slice, but not sending new request on the data

2024-03-08 08:56 UTC, Sytnikovakatya commented on apps/backend/src/modules/friends/friend.service.ts
> +
Ok, I will move it to the notification service

2024-03-08 10:07 UTC, merged