feat(frontend/shared): Update the design of the "Chats" page tm-388
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #407
Opened 2024-03-07 21:20 UTC by GEOFARL

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/69dec6d8-bfc4-44b3-8802-06bce21db5b5)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/3881742c-504b-4381-a905-bad2dfc6759d)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/3a00713a-619f-47a5-84da-bce8097c5f7c)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/0a3b1ac6-9656-46a0-8d5d-3fb9420cf25d)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/ee1f160c-b288-49bd-b418-3c34c7b4523c)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/56ddfdec-d03f-496c-bee0-b1a87e26ad18)

2024-03-07 21:25 UTC, Ann-Maksay commented on apps/frontend/package.json
> +		"date-fns": "3.3.1",
I think all helpers that use `date-fns` should be in `shared`, we already have that package there

2024-03-07 21:30 UTC, GEOFARL commented on apps/frontend/package.json
> +		"date-fns": "3.3.1",
But does it make sense to put functions in the shared folder that will only be used on the frontend?

2024-03-07 21:38 UTC, Ann-Maksay commented on apps/frontend/package.json
> +		"date-fns": "3.3.1",
I guess [this](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/267#discussion_r1508827432) is also only used on the frontend, so it doesn't really matter

2024-03-07 21:42 UTC, GEOFARL commented on apps/frontend/package.json
> +		"date-fns": "3.3.1",
Thanks, i'll move it to shared

2024-03-08 07:30 UTC, what1s1ove requested changes

2024-03-08 07:30 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
> +import { actions } from "~/modules/chats/chats.js";
rename

2024-03-08 07:30 UTC, what1s1ove commented on apps/frontend/package.json
> +		"react-textarea-autosize": "8.5.3",
```suggestion
```
use just a html tag

2024-03-08 07:30 UTC, what1s1ove commented on apps/frontend/src/libs/components/textarea/textarea.tsx
> +	rows,
you do not have this component. you need to add a `rows` prop to the `Input` component. And if this props is passed you need to render a `textarea`

2024-03-08 07:30 UTC, what1s1ove commented on packages/shared/src/libs/helpers/get-formatted-chat-date/get-formatted-chat-date.ts
> +const getFormattedChatDate = (dateString: string): string => {
```suggestion
```
you need to use get formatted date instead. this is a frontend helper only, so move it there

2024-03-08 07:30 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
> +							<Fragment key={message.id}>
create a new component for message item

2024-03-08 07:30 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
> +	let lastDate = "";
```suggestion
```
bad solution. try to find a better solution

2024-03-08 07:44 UTC, GEOFARL commented on packages/shared/src/libs/helpers/get-formatted-chat-date/get-formatted-chat-date.ts
> +const getFormattedChatDate = (dateString: string): string => {
The getFormattedDate fn that we already have right now does not produce the result that we need to have in the chat window, needed to create a separate helper. Moved it to the shared folder, to not install 'date-fns' package on the frontend side as was pointed out [here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/407#discussion_r1516854005)

2024-03-08 07:49 UTC, GEOFARL commented on apps/frontend/package.json
> +		"react-textarea-autosize": "8.5.3",
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/6cb1a97d-1323-4de4-bdc6-0058c48e3c6c)
It just makes it possible for native textarea element to grow according to the amount of content

2024-03-08 07:54 UTC, GEOFARL commented on apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
> +							<Fragment key={message.id}>
We already have a component for message `ChatMessage`. In this case `ChatDate` is used to add date delimiter when a message starts from a new date
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/21799c22-f92b-4af3-8e0c-0281f533aa28)

Do not think that it makes sense to create a new component out of it

2024-03-08 07:58 UTC, Ann-Maksay commented on packages/shared/src/libs/helpers/get-formatted-chat-date/get-formatted-chat-date.ts
> +const getFormattedChatDate = (dateString: string): string => {
What is meant here is that you should leave all date-fsn-related functions in shared in wrappers and combine them in getFormattedChatDate on the frontend.  Take a look at the getFormattedChatDate helper in shared.
Sorry if I didn't explain it clearly enough in my comment

2024-03-08 10:21 UTC, what1s1ove requested changes

2024-03-08 10:21 UTC, what1s1ove commented on apps/frontend/package.json
> +		"react-textarea-autosize": "8.5.3",
give the static height. it will be enough

2024-03-08 15:51 UTC, YourTeaChan commented on packages/shared/src/libs/constants/constants.ts
> +export { LAST_ARRAY_ITEM } from "./last-array-item.js";
```suggestion
export { LAST_ARRAY_ITEM } from "./last-array-item.constant.js";
```

2024-03-08 15:51 UTC, YourTeaChan commented on packages/shared/src/libs/constants/constants.ts
> +export { PREVIOUS_INDEX_OFFSET } from "./previous-index-offset.js";
```suggestion
export { PREVIOUS_INDEX_OFFSET } from "./previous-index-offset.constant.js";
```

2024-03-08 15:51 UTC, YourTeaChan commented on packages/shared/src/libs/helpers/helpers.ts
> +export { checkIsDatePrecedesAnotherByOneDay } from "./check-is-date-precedes-another-by-one-day/check-is-date-precedes-another-by-one-day.js";
```suggestion
export { checkIsDatePrecedesAnotherByOneDay } from "./check-is-date-precedes-another-by-one-day/check-is-date-precedes-another-by-one-day.helper.js";
```

2024-03-08 15:52 UTC, what1s1ove requested changes

2024-03-08 15:52 UTC, what1s1ove commented on apps/frontend/src/libs/components/input/input.tsx
> +	const handleKeyDown = useCallback(
```suggestion
```
without any specific behaviour

2024-03-08 15:52 UTC, what1s1ove commented on apps/frontend/src/libs/components/input/input.tsx
> +	onSubmit?: (_event: React.BaseSyntheticEvent) => void;
```suggestion
```
textereat shouldn't know anything about submit

2024-03-08 15:52 UTC, what1s1ove commented on apps/frontend/src/libs/components/input/styles.module.css
> +.textarea {
you can use the same class name as for the input

2024-03-08 15:52 UTC, what1s1ove commented on apps/frontend/src/libs/components/input/input.tsx
> +	const handleKeyDown = useCallback(
you do not need to handle it at all this time

2024-03-08 15:52 UTC, what1s1ove commented on packages/shared/src/libs/helpers/helpers.ts
> +export { isThisYear, isToday, isYesterday } from "date-fns";
```suggestion
```
create yourown wrappers for these functions

2024-03-08 15:52 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
> +					const previousMessage = messages[index - PREVIOUS_INDEX_OFFSET];
it's really strange logic here. why we can't just map everything?

in render we should not have such logic

move calculation of messages (not components renders) to helper and then use it here

2024-03-08 15:52 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
> +import { AppRoute } from "~/libs/enums/app-route.enum.js";
import

2024-03-08 15:58 UTC, fshabanov requested changes

2024-03-08 15:58 UTC, fshabanov commented on packages/shared/src/libs/helpers/helpers.ts
> +export { isThisYear, isToday, isYesterday } from "date-fns";
Rename to be compatible with B20

2024-03-08 15:58 UTC, fshabanov commented on apps/frontend/src/pages/chats/libs/components/chat-date/chat-date.tsx
> +import { getFormattedChatDate } from "../../../libs/helpers/helpers.js";
Fix import path

2024-03-08 15:58 UTC, fshabanov commented on apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
> +import { AppRoute } from "~/libs/enums/app-route.enum.js";
```suggestion
import { AppRoute } from "~/libs/enums/enums.js";
```

2024-03-09 07:22 UTC, what1s1ove requested changes

2024-03-09 07:22 UTC, what1s1ove commented on apps/frontend/src/libs/components/input/input.tsx
> +	onKeyDown?: (_event: React.KeyboardEvent) => void;
```suggestion
```
you do not to handle any specific keys. remove this handler from common components

2024-03-09 07:22 UTC, what1s1ove commented on apps/frontend/src/libs/enums/event-code.enum.ts
> +const EventCode = {
```suggestion
```
do not handle this this time

2024-03-09 07:22 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/helpers/helpers.ts
> +export { getFormattedChatDate } from "./get-formatted-chat-date.helper.js";
each helper should be in a separate folder

2024-03-09 08:01 UTC, what1s1ove approved these changes
@GEOFARL resolve comments please

2024-03-09 10:57 UTC, Oleksandra-Masiuk requested changes

2024-03-09 10:57 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/chats/libs/helpers/get-formatted-chat-date/get-formatted-chat-date.helper.ts
> +	}
```suggestion
	if (checkIsToday(date)) {
		return DateValue.TODAY;
	} 
	if (checkIsYesterday(date)) {
		return DateValue.YESTERDAY;
	}
	if (checkIsThisYear(date)) {
		return getFormattedDate(dateString, FormatDateType.MMMM_DO).toLowerCase();
	} 
	return getFormattedDate(
			dateString,
			FormatDateType.MMMM_DO_YYYY,
		).toLowerCase();
```

2024-03-09 10:57 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/chats/libs/helpers/prepare-message-items/prepare-message-items.helper.ts
> +			previousMessage &&
Could you please, move this condition to a separate variable with a descriptive name?

2024-03-09 15:28 UTC, fshabanov requested changes

2024-03-09 15:28 UTC, fshabanov commented on apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
> +					>{`${receiver.firstName} ${receiver.lastName}`}</span>
```suggestion
					>{receiver.firstName} {receiver.lastName}</span>
```

2024-03-09 15:57 UTC, what1s1ove approved these changes

2024-03-09 15:57 UTC, merged