feat(frontend/shared): pronouns on feed page tm-344
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #418
Opened 2024-03-08 15:45 UTC by KrasKa2

<img width="1194" alt="Screenshot 2024-03-08 at 17 44 12" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/153290443/dcf7a986-4ca0-4737-9208-1ceb30dd2b61">

2024-03-08 15:51 UTC, fshabanov requested changes

2024-03-08 15:51 UTC, fshabanov commented on apps/frontend/src/modules/activities/libs/helpers/get-activity-title/get-activity-title.helper.ts
> +	const sex = activity.user.sex || UserSex.PREFER_NOT_TO_SAY;
```suggestion
	const sex = activity.user.sex ?? UserSex.PREFER_NOT_TO_SAY;
```

2024-03-08 17:47 UTC, fshabanov approved these changes

2024-03-08 20:54 UTC, Ann-Maksay approved these changes

2024-03-09 07:35 UTC, what1s1ove requested changes

2024-03-09 07:35 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/maps/user-sex-to-pronoun.map.ts
> +const UserSexToPronoun = {
> A map is a very useful and frequently used data structure in any programming language. For maps in the JavaScript world, there is a specific naming convention. The name should follow the pattern aToB, where a serves as the key for retrieving values from the map, followed by the preposition To, implying the mapping of two things, and then B, which is the mapped value for a.

https://dev.to/what1s1ove/javascript-naming-conventions-are-important-45n

2024-03-09 07:35 UTC, what1s1ove commented on apps/frontend/src/modules/activities/libs/helpers/get-activity-title/get-activity-title.helper.ts
> +	const pronoun = UserSexToPronoun[sex].OBJECTIVE;
```suggestion
	const { sex } = activity.user;
	const pronoun = UserSexToPronoun[sex ?? UserSex.PREFER_NOT_TO_SAY].OBJECTIVE;
```

2024-03-09 08:16 UTC, what1s1ove requested changes

2024-03-09 08:16 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/maps/user-sex-to-pronoun.map.ts
> +const UserSexToPronoun = {
is not resolved

2024-03-09 15:58 UTC, what1s1ove approved these changes

2024-03-09 15:58 UTC, what1s1ove commented
@KrasKa2 resolves conflicts please

2024-03-09 16:15 UTC, GEOFARL approved these changes

2024-03-09 16:46 UTC, merged