feat(frontend): add empty page placeholders tm-398
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #423
Opened 2024-03-08 18:14 UTC by tarmiel

![Screenshot_2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/9343e715-5a44-44e7-8d72-6442e7a4afa7)
![изображение](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/68f79224-09d5-4f9b-b9a5-3d83724857fd)

2024-03-08 18:50 UTC, fshabanov requested changes

2024-03-08 18:50 UTC, fshabanov commented on apps/frontend/src/pages/friends/friends.tsx
> +						emptyPlaceholder={"There aren't any potential friends"}
```suggestion
						emptyPlaceholder="There aren't any potential friends"
```

2024-03-08 19:25 UTC, fshabanov requested changes

2024-03-08 19:25 UTC, fshabanov commented on apps/frontend/src/pages/feed/feed.tsx
> +						</p>
I see you use the same thing in multiple places, maybe we should create a separate component for that?

2024-03-08 19:39 UTC, tarmiel commented on apps/frontend/src/pages/feed/feed.tsx
> +						</p>
That's actually what I thought at first, too. But technically speaking, this text can change on different pages when adapting or we can add pictures. Right now I've made it almost the same because at this stage it's enough, but I suppose that could change.

2024-03-08 23:15 UTC, Vfivew approved these changes

2024-03-08 23:34 UTC, GEOFARL approved these changes

2024-03-09 07:08 UTC, fshabanov commented on apps/frontend/src/pages/feed/feed.tsx
> +						</p>
You can send text as a prop. In case we decide to add pictures, we can use props again

2024-03-09 07:25 UTC, what1s1ove approved these changes
@fshabanov merge it once it done

2024-03-09 15:30 UTC, fshabanov approved these changes

2024-03-09 15:32 UTC, merged