fix(frontend): Comments from the newly opened comment section are displayed in the previously opened comment sections tm-417
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #430
Opened 2024-03-09 08:12 UTC by tarmiel

![demo-comments](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/dc50beee-62c4-40b4-80b4-9f5000cad1fe)

2024-03-09 08:16 UTC, Vfivew approved these changes

2024-03-09 08:18 UTC, what1s1ove requested changes

2024-03-09 08:18 UTC, what1s1ove commented on apps/frontend/src/modules/activities/slices/activities.slice.ts
> +const ZERO_INDEX = 0;
B28

2024-03-09 08:18 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +	const [comments, setComments] = useState<CommentWithRelationsResponseDto[]>(
```suggestion
```
you do not need to keep it in the state. you should use redux store instead

2024-03-09 08:18 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +	const [isLoadingCreateComment, setIsLoadingCreateComment] =
```suggestion
```
use data status from redux store

2024-03-09 08:24 UTC, tarmiel commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +	const [comments, setComments] = useState<CommentWithRelationsResponseDto[]>(
I need each comment section to be indepenedent, so when I open comments under one activity it should not effect others.

2024-03-09 08:24 UTC, tarmiel commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +	const [isLoadingCreateComment, setIsLoadingCreateComment] =
We do not want to share loading state between opened comment sections

2024-03-09 16:03 UTC, what1s1ove requested changes

2024-03-09 16:03 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +	const [isLoadingCreateComment, setIsLoadingCreateComment] =
got it, then do not use a boolean for loading. use a data status instead

2024-03-09 16:03 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +			});
```suggestion
```
you can not take it this way. take it from the store using the `useSelector`

2024-03-09 16:03 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +	const [comments, setComments] = useState<CommentWithRelationsResponseDto[]>(
you can not do it this way - 
```ts
			.then((response) => {
				setComments(response.items);
				setIsLoadingComments(false);
			});
```

2024-03-10 20:52 UTC, YourTeaChan approved these changes

2024-03-11 07:13 UTC, what1s1ove requested changes

2024-03-11 07:13 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +	const [comments, setComments] = useState<CommentWithRelationsResponseDto[]>(
it is not resolved

2024-03-11 07:13 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +			.then((response) => {
is not resolved

2024-03-11 09:50 UTC, what1s1ove requested changes

2024-03-11 09:50 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +					{comments?.map((comment) => (
at this stage you should be sure that there are comments

2024-03-11 10:03 UTC, what1s1ove approved these changes

2024-03-11 10:03 UTC, merged