feat(backend): add users own activity tm-420
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #431
Opened 2024-03-09 09:24 UTC by Ann-Maksay

![own-activitis](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/e36cd51f-ce70-4413-a5a6-f466d35d3ad2)

2024-03-09 09:25 UTC, Ann-Maksay commented on apps/backend/src/modules/activities/activity.repository.ts
> +						groups: [],
I was a little stuck trying to figure out how this situation is different from the ones where everything is working correctly. I figured, as we discussed, that we don't need to return this information anyway, but I'm still screwing around trying to figure out the difference.

Specifically, the activity query returns such a user, which caused the map method to fail:
![group-1](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/605a3b3c-7d78-4e6e-a81a-b31faf7cc25a)

When in work situations, this one
![group-2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/acc3e177-06eb-48be-b587-25dd2ddbd199)

2024-03-09 16:04 UTC, what1s1ove requested changes

2024-03-09 16:04 UTC, what1s1ove commented on apps/backend/src/modules/activities/activity.repository.ts
> +						groups: [],
investigate this. we can not delete this code just because

2024-03-09 17:29 UTC, YourTeaChan commented on apps/backend/src/modules/activities/activity.repository.ts
> +						groups: [],
If it's still a problem, try to add a relation `${RelationName.GROUPS}.${RelationName.PERMISSIONS}` in `withGraphJoined()` where you need to do `groups.map()`

2024-03-10 16:51 UTC, Vfivew approved these changes

2024-03-10 20:50 UTC, YourTeaChan approved these changes

2024-03-10 20:59 UTC, ShadowOfTheSpace approved these changes

2024-03-11 06:10 UTC, fshabanov approved these changes

2024-03-11 06:13 UTC, merged