feat(frontend): update pagination design tm-400
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #436
Opened 2024-03-09 15:25 UTC by KrasKa2

<img width="547" alt="Screenshot 2024-03-09 at 17 06 24" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/153290443/e5a3a16a-f439-43d9-9daf-62a26c107cd3">

2024-03-09 15:49 UTC, GEOFARL commented
I'm not sure, but it seems like chevron icons do not match the design

2024-03-09 15:51 UTC, GEOFARL commented on apps/frontend/src/libs/components/pagination/pagination.tsx
> +					label="<<"
Probably, you need to create two new icons for this arrows

2024-03-09 16:07 UTC, what1s1ove requested changes

2024-03-09 16:07 UTC, what1s1ove commented on apps/frontend/src/libs/components/pagination/pagination.tsx
> +					label="<<"
the label should be user-friendly. use icons instead

2024-03-09 17:14 UTC, YourTeaChan approved these changes

2024-03-09 20:34 UTC, Vfivew approved these changes

2024-03-10 05:42 UTC, fshabanov requested changes

2024-03-10 05:42 UTC, fshabanov commented on apps/frontend/src/libs/components/pagination/libs/components/pagination-item/pagination-item.tsx
> +	const content = iconName ? <Icon name={iconName} /> : label;
Always use label, add `hasVisuallyHiddenLabel` prop

2024-03-10 10:12 UTC, fshabanov approved these changes

2024-03-10 21:05 UTC, ShadowOfTheSpace approved these changes

2024-03-11 07:12 UTC, what1s1ove approved these changes

2024-03-11 07:12 UTC, merged