feat(frontend, shared): Send notification through PWA tm-442
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #449
Opened 2024-03-10 00:03 UTC by GEOFARL

![20240310_012057](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/630093f3-c4c0-4580-b1a6-ddb708a6e680)

2024-03-10 05:56 UTC, fshabanov requested changes

2024-03-10 05:56 UTC, fshabanov commented on apps/frontend/public/sw.js
> +const a = 5;
What's this?

2024-03-10 06:58 UTC, GEOFARL commented on apps/frontend/public/sw.js
> +const a = 5;
Needed to commit somehow this service worker file, couldn't leave it just empty 🙂

2024-03-10 17:57 UTC, Vfivew commented on apps/frontend/public/sw.js
> +const a = 5;
You ignore in knip.config.ts this file right? 
`ignore: ["**/sw.js/**"]`
And after this you still need this file?
What kind of error you got when you try push without this file?

2024-03-11 06:48 UTC, Sytnikovakatya approved these changes

2024-03-11 07:16 UTC, what1s1ove requested changes

2024-03-11 07:16 UTC, what1s1ove commented on apps/frontend/public/sw.js
> +const a = 5;
we have this file since the PWA vite plugin generates the service worker. remove it

2024-03-11 07:16 UTC, what1s1ove commented on apps/frontend/src/modules/user-notifications/slices/user-notifications.slice.ts
> +		sendUnreadNotifications(state): void {
reduces - is a pure function. remove any side effects

2024-03-11 07:16 UTC, what1s1ove commented on apps/frontend/src/libs/modules/pwa-notification/pwa-notification.module.ts
> +class PWANotification {
```suggestion
class PushNotification {
```
change it everywhere

2024-03-11 17:36 UTC, GEOFARL commented on apps/frontend/public/sw.js
> +});
Have not found better solution with our Vite PWA plugin then creating a separate service worker and injecting it in precache manifest. That's what official Vite PWA docs suggest [here](https://vite-pwa-org.netlify.app/guide/inject-manifest)

2024-03-11 17:38 UTC, GEOFARL commented on apps/frontend/eslint.config.js
> +	ignores: ["build", "dev-dist", "public/sw.js"],
I think that it is needed to be ignored by analogy with other service workers

2024-03-11 17:38 UTC, GEOFARL commented on apps/frontend/package.json
> +		"workbox-precaching": "7.0.0"
This dependency is needed to be able to inject service worker

2024-03-11 17:41 UTC, GEOFARL commented on apps/frontend/src/libs/modules/config/base-config.module.ts
> +			},
Need public key here

> to restrict the validity of a subscription to a specific application server (so, by using VAPID, only your server will be able to send notifications to a subscriber).
[good explanation](https://stackoverflow.com/questions/40392257/what-is-vapid-and-why-is-it-useful)

2024-03-11 17:53 UTC, GEOFARL commented on apps/frontend/src/libs/modules/store/libs/helpers/send-notifications.helper.ts
> +				},
Didn't know what kinds of notifications we will send, included this for now, probably, needs to be changed

2024-03-11 17:54 UTC, GEOFARL commented on apps/frontend/src/libs/modules/store/libs/maps/notification-type-to-title.map.ts
> +};
Expect this map to be extended in the future

2024-03-11 17:56 UTC, GEOFARL commented on apps/frontend/src/libs/modules/store/middlewares/notifications-socket.middleware.ts
>  		});
Probably, we don't need to send out all kinds of notifications to all of the subscribers of our app, left it so for now

2024-03-11 17:56 UTC, GEOFARL commented on apps/frontend/vite.config.ts
> +		strategies: "injectManifest",
To extend generated service worker

2024-03-11 17:57 UTC, GEOFARL commented on knip.config.ts
> +	ignoreDependencies: ["workbox-precaching"],
knip was complaining about them, was not sure what to do about that

2024-03-12 09:33 UTC, GEOFARL commented on apps/backend/.env.example
> +PUSH_NOTIFICATIONS_PRIVATE_KEY=YqPgqaxzdgDQZPkr3nIzRrt8r98R3YtaSLDObHD4xXo
[link](https://pushpad.xyz/blog/web-push-what-is-vapid)
> Basically, when you subscribe a user to the notifications, you can also pass a public key (cryptographic key) to the browser. Then all the notifications will need to be signed with the private key.
> These are the exact steps:
> 1. the website backend generates and stores in its own database a public key and private key (which will be called VAPID keys)
> 2. the website frontend calls PushManager.subscribe(options) ([documentation](https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe)) to subscribe the user to notifications and the options include an applicationServerKey, which is the public key downloaded from server
> 3. if the user accepts to receive the notifications (permission prompt), the browser needs to contact its own push service to generate a new push subscription
> 4. the new push subscription returned by the browser to the website is associated to that VAPID public key
> 5. the push subscription can be used only if you have the VAPID private key: you will need to sign all the future notifications sent from your backend (application server) with the VAPID private key.

2024-03-12 16:23 UTC, closed without merging