feat(backend/frontend/shared): implement counters for unread notifications and chats tm-395
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #455
Opened 2024-03-10 19:38 UTC by Sytnikovakatya

- Implement a counter for unread notifications on the "Notifications" icon on the header
- Implement a counter for unread chats on the "Chats" icon on the header
![Screenshot_3](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/618a258c-c855-41e1-ad24-64962063a2b0)

2024-03-10 20:08 UTC, ShadowOfTheSpace requested changes

2024-03-10 20:08 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/header/styles.module.css
> +	height: 11px;
Maybe this circle need to have same width and height?

2024-03-10 20:11 UTC, Sytnikovakatya commented on apps/backend/src/modules/chat-messages/chat-message.repository.ts
> +			.andWhereNot({ senderUserId: userId })
Without this check  it sets message as read when sender reads it

2024-03-10 20:16 UTC, Sytnikovakatya commented on apps/frontend/src/libs/components/header/styles.module.css
> +	height: 11px;
I used different because it looks better when we have more then 9

2024-03-10 20:23 UTC, Sytnikovakatya commented on apps/backend/src/modules/chat-messages/chat-message.service.ts
> +			items: readChatMessages.map((chatMessage) => chatMessage.toObject()),
But I guess it's ok because of:
The exceptions are single-line arrow functions, which can be used without the required blocks of code:
``const checkedCheckboxes = checkboxes.filter((checkbox) => checkbox.checked);``

2024-03-10 20:41 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/chat-messages/chat-message.service.ts
> +			items: readChatMessages.map((chatMessage) => chatMessage.toObject()),
Ye, but @what1s1ove said that we need to have same style at all project. So right now we have no exceptions for that rule

2024-03-10 20:42 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/chat-messages/chat-message.repository.ts
> +			.andWhereNot({ senderUserId: userId })
So my next question is why you send to backend all messages that user see on screen? Why not only messages of another user?

2024-03-10 20:43 UTC, Sytnikovakatya commented on apps/backend/src/modules/chat-messages/chat-message.service.ts
> +			items: readChatMessages.map((chatMessage) => chatMessage.toObject()),
thanks, I'll change it

2024-03-10 20:45 UTC, Sytnikovakatya commented on apps/backend/src/modules/chat-messages/chat-message.repository.ts
> +			.andWhereNot({ senderUserId: userId })
Good question)

2024-03-10 20:47 UTC, Sytnikovakatya commented on apps/backend/src/modules/chat-messages/chat-message.repository.ts
> +			.andWhereNot({ senderUserId: userId })
For me it looked easier just check it this way. But I'll think how I can change it in frontend

2024-03-10 20:53 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/chat-messages/chat-message.repository.ts
> +			.andWhereNot({ senderUserId: userId })
I think it should be changed. 
Imagine a situation when only you send 20 messages to your friend and all these 20 messages will be sent to the server to make them unread after you see them. But no one from them will be marked as unread.

2024-03-10 20:54 UTC, Sytnikovakatya commented on apps/backend/src/modules/chat-messages/chat-message.repository.ts
> +			.andWhereNot({ senderUserId: userId })
Yes, I agree

2024-03-10 20:55 UTC, ShadowOfTheSpace requested changes

2024-03-10 20:55 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/chats/libs/components/chat-message/chat-message.tsx
> +		if (inView) {
Add aditional check here. Like if it is not my message, then make it unread

2024-03-11 07:39 UTC, what1s1ove requested changes

2024-03-11 07:39 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/enums/enums.ts
> +export { MessageStatus } from "@trackmates/shared";
should be imported from the module. not from the page

2024-03-11 07:39 UTC, what1s1ove commented on apps/frontend/src/libs/components/app/app.tsx
> +			void dispatch(chatActions.getAllChats({ search: "" }));
you need to fetch only counters

2024-03-11 07:39 UTC, what1s1ove commented on apps/frontend/src/libs/components/header/header.tsx
> +	const unreadChatsCount = chats.reduce((total, chat) => {
create a helper for it. keep your components clean

2024-03-11 07:39 UTC, what1s1ove commented on apps/frontend/src/libs/components/header/libs/constants.ts
> +const MAXIMUM_DISPLAY_UNREAD_COUNT = 9;
set of constants = enum

2024-03-11 09:38 UTC, fshabanov requested changes

2024-03-11 09:38 UTC, fshabanov commented on apps/frontend/src/modules/chat-messages/slices/actions.ts
> +		void dispatch(chatsActions.getAllChats({ search: "" }));
Do we need to get all chats again?

2024-03-11 09:38 UTC, fshabanov commented on packages/shared/src/modules/chat-messages/libs/enums/chat-message-validation-message.enum.ts
> +	ARRAY_MINIMUM_SIZE: "Array should be not empty.",
Be more specific, what Array is it about?

2024-03-11 14:36 UTC, ShadowOfTheSpace requested changes

2024-03-11 14:36 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/chat-messages/slices/actions.ts
> +		void dispatch(chatsActions.getAllChats({ search: "" }));
Yes, I think there is no need to fetch all chats again. You should calculate a new value of unread messages in this action, based on number of messages, that you send as read. 
Maybe create a new action in chat slice for it, like `updateUnreadMessageCount(chatId, readMessageCount)` and dispatch it here

2024-03-12 09:01 UTC, what1s1ove requested changes

2024-03-12 09:01 UTC, what1s1ove commented on packages/shared/src/modules/chats/libs/enums/chats-api-path.enum.ts
> +	GET_UNREAD_MESSAGE_COUNTER: "/get-unread-message-counter",
```suggestion
	UNREAD_COUN: "/unread-count",
```

2024-03-12 09:01 UTC, what1s1ove commented on packages/shared/src/modules/user-notifications/enums/user-notifications-api-path.enum.ts
> +	GET_UNREAD_NOTIFICATION_COUNTER: "/get-unread-notification-counter",
```suggestion
	UNREAD_COUN: "/unread-count",
```

2024-03-12 16:07 UTC, what1s1ove requested changes

2024-03-12 16:07 UTC, what1s1ove commented on apps/backend/src/modules/chats/chat.repository.ts
> +import { calculateUnreadMessageCount } from "./libs/helpers/helpers.js";
```suggestion
```
you do not need this helper. use only counter on the db

2024-03-12 16:07 UTC, what1s1ove commented on apps/backend/src/modules/chats/libs/helpers/calculate-unread-message-count/calculate-unread-message-count.helper.ts
> +const calculateUnreadMessageCount = (counts: number[]): number => {
```suggestion
```
use the counter on the DB. that it

2024-03-12 16:37 UTC, fshabanov requested changes

2024-03-12 16:37 UTC, fshabanov commented on apps/backend/src/modules/chats/chat.controller.ts
> +	public async getUnreadMessageCounter(
```suggestion
	public async getUnreadMessageCount(
```
Change it everywhere

2024-03-12 16:37 UTC, fshabanov commented on apps/backend/src/modules/notifications/notification.service.ts
> +	public async getUnreadNotificationCounter(userId: number): Promise<number> {
```suggestion
	public async getUnreadNotificationCount(userId: number): Promise<number> {
```

2024-03-12 20:33 UTC, Oleksandra-Masiuk approved these changes

2024-03-12 21:57 UTC, ShadowOfTheSpace requested changes

2024-03-12 21:57 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/chat-messages/chat-message.repository.ts
> +			.returning("*")
```suggestion
			.updateAndFetch({ status: MessageStatus.READ })
			.withGraphFetched(
				`${RelationName.SENDER_USER}.[${RelationName.USER_DETAILS}.${RelationName.AVATAR_FILE}, ${RelationName.GROUPS}.${RelationName.PERMISSIONS}]`,
			)
```

Try updateAndFetch, so you will not need to use returning("*")

2024-03-12 21:57 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/chats/chat.controller.ts
> +	 *      description: Get a count of unread messages
```suggestion
	 *      description: Get a count of all user's unread messages
```

2024-03-13 07:08 UTC, what1s1ove requested changes

2024-03-13 07:08 UTC, what1s1ove commented on apps/backend/src/modules/notifications/notification.repository.ts
> +		return unreadNotifications.length;
```suggestion
```
take only `count` from the DB. Not all + length

2024-03-13 07:11 UTC, Vfivew approved these changes

2024-03-13 07:58 UTC, fshabanov requested changes

2024-03-13 07:58 UTC, fshabanov commented on packages/shared/src/modules/chat-messages/libs/enums/chat-message-validation-message.enum.ts
> +		"Array of messages IDs should be not empty",
```suggestion
	MESSAGE_IDS_ARRAY_MINIMUM_LENGTH:
		"Array of message IDs should be not empty",
```

2024-03-13 07:58 UTC, fshabanov commented on apps/backend/src/modules/notifications/notification.repository.ts
> +	public async getUnreadNotificationCount(userId: number): Promise<number> {
```suggestion
	public async getUnreadNotificationsCount(userId: number): Promise<number> {
```

2024-03-13 10:18 UTC, fshabanov approved these changes

2024-03-13 11:40 UTC, KrasKa2 requested changes

2024-03-13 11:40 UTC, KrasKa2 commented on apps/frontend/src/pages/chats/libs/components/chat-message/chat-message.tsx
> +	const { createdAt, id, senderUser, text } = message;
```suggestion
	const { createdAt, id, senderUser, status, text } = message;
```

2024-03-13 11:40 UTC, KrasKa2 commented on apps/frontend/src/pages/chats/libs/components/chat-message/chat-message.tsx
> +	const isRead = message.status === MessageStatus.READ;
```suggestion
	const isRead = status === MessageStatus.READ;
```

2024-03-13 12:04 UTC, what1s1ove approved these changes

2024-03-13 12:08 UTC, what1s1ove approved these changes

2024-03-13 12:08 UTC, merged