feat: get authenticated user tm-19
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #46
Opened 2024-02-10 21:54 UTC by Vfivew

Would appreciate feedback on the implementation of headers. Thank you!

2024-02-11 06:12 UTC, fshabanov requested changes

2024-02-11 06:12 UTC, fshabanov commented on apps/backend/src/modules/users/user.repository.ts
> +		throw new Error("Method not implemented.");
```suggestion
		return Promise.resolve(null);
```

2024-02-11 06:12 UTC, fshabanov commented on apps/backend/src/libs/modules/controller/libs/types/api-handler-options.type.ts
> +	};
```suggestion
```

2024-02-11 06:12 UTC, fshabanov commented on apps/backend/src/modules/auth/auth.controller.ts
> +	private async getAuthenticatedUser(
Contact Maxym, who works on implementing Protected routing in Backend (with authorization plugin)
He needs to inject the user to the request and you will need to use that injected user

2024-02-11 06:35 UTC, fshabanov requested changes

2024-02-11 06:35 UTC, fshabanov commented on apps/backend/src/modules/auth/auth.service.ts
> +class AuthService implements AuthServiceT {
```suggestion
class AuthService {
```
No need to create AuthService type

2024-02-11 06:35 UTC, fshabanov commented on apps/backend/src/modules/users/user.repository.ts
> +class UserRepository implements UserRepositoryT {
```suggestion
class UserRepository implements Repository {
```

2024-02-11 06:35 UTC, fshabanov commented on apps/backend/src/modules/users/user.service.ts
> +class UserService implements UserServiceT {
```suggestion
class UserService implements Service {
```

2024-02-11 09:34 UTC, Vfivew commented on apps/backend/src/modules/auth/auth.controller.ts
> +	private async getAuthenticatedUser(
If you can, answer the question please.
I need to remove headers from base-controller.module.ts and api-handler-options.type.ts because I should obtain the token from the request by using the implementation handled by Maxym (Protected routing #14 )?
Do I understand your suggest correctly?
Thank you.

2024-02-11 09:47 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/auth/auth.controller.ts
> +			const userId = (payload as { id?: number }).id;
Moving the `{ id?: number } `to a separate type can improve code readability

2024-02-11 10:01 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/users/user.service.ts
> +		return user || null;
```suggestion
		return user ?? null;
```

2024-02-11 12:11 UTC, what1s1ove requested changes

2024-02-11 12:11 UTC, what1s1ove commented on package.json
> +		"git:hook:precommit": "lint-staged --cwd .",
merge `main` into your branch

2024-02-11 12:11 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/types/user.type.ts
> +type User = {
all shared types can not be with so abstract name them should be as
<img width="705" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/42296182/5b798da6-a6df-4ada-a204-47de049392da">

2024-02-11 12:11 UTC, what1s1ove commented on apps/backend/src/modules/users/user.service.ts
> +class UserService implements UserServiceT {
yes, you do not need to create an additional type for service implementation

2024-02-11 12:11 UTC, what1s1ove commented on apps/backend/src/modules/users/libs/types/user-service.type.ts
> +type UserService = Pick<Service<UserEntity>, "delete" | "find" | "update"> & {
```suggestion
```
you do not a type for implementation

2024-02-11 12:19 UTC, fshabanov commented on apps/backend/src/modules/auth/auth.controller.ts
> +	private async getAuthenticatedUser(
The token part should be handled by Maxym. You will directly use the user that he injects into the request object

2024-02-12 05:57 UTC, fshabanov requested changes

2024-02-12 05:57 UTC, fshabanov commented on apps/backend/src/modules/auth/auth.controller.ts
> +			payload: user || null,
```suggestion
			payload: user ?? null,
```

2024-02-12 05:57 UTC, fshabanov commented on packages/shared/src/modules/auth/libs/enums/auth-api-path.enum.ts
> +	USER: "/authenticated-user",
```suggestion
	AUTHENTICATED_USER: "/authenticated-user",
```

2024-02-12 05:57 UTC, fshabanov commented on apps/backend/src/libs/modules/config/libs/types/environment-schema.type.ts
> +	};
Add this to .env.example file

2024-02-12 05:57 UTC, fshabanov commented on apps/backend/src/libs/modules/controller/libs/types/api-handler-options.type.ts
> +import { UserInfoResponse } from "shared/src/modules/users/users.js";
```suggestion
import { UserInfoResponse } from "~/modules/users/users.js";
```

2024-02-12 08:45 UTC, Vfivew commented on apps/backend/src/modules/auth/helpers/crypt/encrypt-token.ts
> +async function encryptToken(token: string) {
I resolve it becouse file is deleted. 
I excluded token parsing from my implementation for sending the user.

2024-02-12 08:45 UTC, Vfivew commented on apps/backend/src/modules/auth/helpers/crypt/encrypt-token.ts
> +		const secret = new TextEncoder().encode(config.ENV.JWT.SECRET_KEY);
I resolve it becouse file is deleted. 
I excluded token parsing from my implementation for sending the user.

2024-02-13 15:16 UTC, fshabanov commented on apps/backend/src/libs/modules/controller/libs/types/api-handler-options.type.ts
> +	};
Add it first to `DefaultApiHandlerOptions` and do the same as it is done with other types

2024-02-14 10:48 UTC, what1s1ove requested changes
the task is not implemented. you need to decode the user's token on the backend and send the current user to frontend

2024-02-14 10:48 UTC, what1s1ove commented on packages/shared/src/libs/modules/http/libs/enums/http-code.enum.ts
> +	NOT_FOUND: 404,
```suggestion
```
you do not use it

2024-02-14 10:48 UTC, what1s1ove commented on apps/backend/src/modules/users/user.entity.ts
> -		passwordHash: string;
we do not need to delete it

2024-02-14 11:53 UTC, GEOFARL approved these changes

2024-02-14 12:16 UTC, what1s1ove approved these changes

2024-02-14 12:17 UTC, merged