feat(backend): add like notification tm-445
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #466
Opened 2024-03-11 17:17 UTC by Ann-Maksay

![like-notification](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/dfbdcf21-6d20-4010-ab5f-0a296874787e)

2024-03-11 18:28 UTC, Vfivew approved these changes

2024-03-11 21:05 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/activities/activity.service.ts
> +		if (likeObject?.id) {
what is the point of replacing the ternary operator with `else if`?

2024-03-12 06:43 UTC, GEOFARL commented on apps/backend/src/modules/activities/activity.service.ts
> +		if (likeObject?.id) {
I saw Vlad requested that we do not call methods based on the ternary condition [here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/461#discussion_r1519929100)

2024-03-12 06:45 UTC, GEOFARL approved these changes

2024-03-12 07:11 UTC, Ann-Maksay commented on apps/backend/src/modules/activities/activity.service.ts
> +		if (likeObject?.id) {
Also, the logic here has become a little more complicated than just choosing one of two options

2024-03-12 09:12 UTC, what1s1ove requested changes
merge main into your branch please

2024-03-12 09:12 UTC, MappariChan approved these changes

2024-03-12 09:47 UTC, Ann-Maksay commented
I've done the merge, but I'm still working on adding [that](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/466#discussion_r1521050469).
@what1s1ove

2024-03-12 11:46 UTC, Ann-Maksay commented
Our notifications aren't particularly adaptable to deletion, so the best option I found was to create a notification for any likes, but only display to users the ones not personally caused by them.

2024-03-12 11:47 UTC, GEOFARL commented on apps/backend/src/db/migrations/20240312100649_add_notification_reference_to_likes.ts
> +	NOTIFICATIN_ID: "notification_id",
```suggestion
	NOTIFICATION_ID: "notification_id",
```

2024-03-12 11:47 UTC, GEOFARL commented on apps/backend/src/modules/notifications/notification.repository.ts
> +			.andWhereNot(`${DatabaseTableName.NOTIFICATIONS}.userId`, userId)
do we have notifications from ourselves?

2024-03-12 12:20 UTC, Ann-Maksay commented on apps/backend/src/db/migrations/20240312100649_add_notification_reference_to_likes.ts
> +			.integer(ColumnName.NOTIFICATION_ID)
We have no other way to get it, and it's needed for deletion along with the deletion of the likes

2024-03-12 12:20 UTC, KrasKa2 requested changes

2024-03-12 12:20 UTC, KrasKa2 commented on apps/backend/src/db/migrations/20240312100649_add_notification_reference_to_likes.ts
> +			.integer(ColumnName.NOTIFICATION_ID)
If only for deleting notification when delete like, I think it is better to add `paylod` or `action_id` field to `notifications` table

2024-03-12 12:24 UTC, KrasKa2 commented on apps/backend/src/db/migrations/20240312100649_add_notification_reference_to_likes.ts
> +			.integer(ColumnName.NOTIFICATION_ID)
@fshabanov , what do you think?

2024-03-12 12:25 UTC, Ann-Maksay commented on apps/backend/src/db/migrations/20240312100649_add_notification_reference_to_likes.ts
> +			.integer(ColumnName.NOTIFICATION_ID)
I understand what you're saying and that this is how it's implemented in activity. I considered this option, but it requires too many modifications to the notifications module, which is something I wanted to avoid

2024-03-12 12:31 UTC, KrasKa2 commented on apps/backend/src/db/migrations/20240312100649_add_notification_reference_to_likes.ts
> +			.integer(ColumnName.NOTIFICATION_ID)
In the other hand, we have already had hight coupling because of using notificationService (and activityService) inside other services instead of using events. So, maybe in this case it is ok

2024-03-12 12:39 UTC, KrasKa2 approved these changes

2024-03-12 16:09 UTC, what1s1ove requested changes
add DB changes to readme.md

2024-03-12 16:30 UTC, ShadowOfTheSpace commented on apps/backend/src/db/migrations/20240312100649_add_notification_reference_to_likes.ts
> +			.integer(ColumnName.NOTIFICATION_ID)
I agreed with @KrasKa2, I think it is better to add some `actionId` to payload like it was in SectionStatuses. It can be useful in future tasks without any additional tables. It requires one additional field (maybe it can be nullable) with id of entity that created notification.

2024-03-13 07:10 UTC, Sytnikovakatya approved these changes

2024-03-13 07:12 UTC, what1s1ove requested changes

2024-03-13 07:12 UTC, what1s1ove commented on apps/backend/src/db/migrations/20240312100649_add_notification_reference_to_likes.ts
> +			.integer(ColumnName.NOTIFICATION_ID)
agreed

2024-03-13 10:12 UTC, tarmiel commented on apps/backend/src/modules/notifications/notification.service.ts
> +		}
You use notificationService in Activity. Do you suppose that user who tries to delete his own like or comment should get an error message about someone else notification if we cannot find this notification in db?

2024-03-13 10:12 UTC, tarmiel commented on apps/backend/src/modules/notifications/notification.service.ts
> +			event: SocketEvent.NEW_NOTIFICATION,
Do you want to send new_notification event before deletion?

2024-03-13 10:15 UTC, Ann-Maksay commented on packages/shared/src/modules/notifications/libs/types/create-notification-request-dto.type.ts
> +	actionId: null | number;
Because we don't have deletion on unfollow and there is no action id there. So this field is nullable

2024-03-13 10:18 UTC, Ann-Maksay commented on apps/backend/src/modules/notifications/notification.service.ts
> +		}
I did it without the error from the beginning, but I decided to keep it. I just don't cause deletion of the notification if the user removes his own likes. As a consequence, there can only be an error if the user deletes comments that were created before the deletion was possible. But... I think that's where the error message should be.

2024-03-13 10:23 UTC, Ann-Maksay commented on apps/backend/src/modules/notifications/notification.service.ts
> +			event: SocketEvent.NEW_NOTIFICATION,
Yes, because this event just updates the notification list. But I agree that maybe it should be renamed.

2024-03-13 16:08 UTC, what1s1ove approved these changes

2024-03-13 16:08 UTC, merged