fix(frontend/shared): Update the design of the "Chats" page tm-388
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #467
Opened 2024-03-11 19:05 UTC by GEOFARL

Date format should be "Today", "March 7th", "March 4th"
<img width="159" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/0fe3220d-6c09-45be-9aa2-d5aa670ea25e">

Fix button position
<img width="258" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/a6f68935-9cbf-4be6-ae5d-f33166bafb15">

 Message background shouldn't depend of the user name and date
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/7cd0d641-4c2f-4466-a622-11d085f01601)

Messages with line breaks are sent on one row(fixed)
<img width="138" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/12f18226-5a2e-4c0d-9e8b-fcc00ff61f79">

Validation message shouldn't display, user can't send empty messages

2024-03-11 19:22 UTC, Vfivew commented on apps/frontend/src/pages/chats/libs/components/chat-form/styles.module.css
> +	height: 45.23px;
45.23 ?
I think it is bad any way.

2024-03-11 19:27 UTC, GEOFARL commented on apps/frontend/src/pages/chats/libs/components/chat-form/styles.module.css
> +	height: 45.23px;
Icon has absolute positioning and without exact height it looks like this
<img width="166" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/908318c9-4248-48e2-b2ab-256318e6087e">

2024-03-11 20:07 UTC, Vfivew commented on apps/frontend/src/pages/chats/libs/components/chat-form/styles.module.css
> +	height: 45.23px;
Try 46px height
And delete `justify-self: end;` we dont need it at all (optional)
Gif added. 
But check it in all browser.
![this](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/49702560-26e1-4d49-beb7-b718d9ea689b)

2024-03-11 20:12 UTC, GEOFARL commented on apps/frontend/src/pages/chats/libs/components/chat-form/styles.module.css
> +	height: 45.23px;
thks for justify-end, probably artifact of the past))

2024-03-11 20:20 UTC, Vfivew commented on apps/frontend/src/pages/chats/libs/components/chat-form/styles.module.css
> +	height: 45.23px;
.icon {
	position: absolute;
	right: 1;
	bottom: 1;
	justify-self: end;
	width: 40px;
	height: 44px;
	min-height: 30px;
	padding: 0;
	background-color: transparent;
	border: none;
	border-radius: 0 7px 7px 0;
	fill: currentcolor;
}

2024-03-11 20:23 UTC, GEOFARL commented on apps/frontend/src/pages/chats/libs/components/chat-form/styles.module.css
> +	height: 45.23px;
<img width="154" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/f22da93c-9ee7-4c6f-aa0a-508d95f58940">

2024-03-11 20:30 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_ARRAY_LENGTH) {
It is a bit unnecessary to compare to `EMPTY_ARRAY_LENGTH`
```suggestion
			if (!payload.message.trim().length) {
```

2024-03-11 20:31 UTC, Vfivew commented on apps/frontend/src/pages/chats/libs/components/chat-form/styles.module.css
> +	height: 45.23px;
I don't know how this happens for you. All media requests are processed correctly for me.
Any way we need to find solution and delete 45.23px
![example](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/405ee6ea-c546-4761-ac8b-a458a3e91e91)

2024-03-11 20:33 UTC, GEOFARL commented on apps/frontend/src/pages/chats/libs/components/chat-form/styles.module.css
> +	height: 45.23px;
okay, thanks for help, will try to do it the other way

2024-03-11 20:41 UTC, GEOFARL commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_ARRAY_LENGTH) {
<img width="783" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/f1392df7-ebba-43c3-a9dd-a79024f63d8a">

2024-03-11 22:00 UTC, Vfivew commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_ARRAY_LENGTH) {
You miss "!". Try it.
![hereTry](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/48e4fd98-aced-4d9a-be80-9e468465e791)

2024-03-12 06:24 UTC, GEOFARL commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_ARRAY_LENGTH) {
<img width="800" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/b1a8b142-de6d-4815-96d3-01f79f9659e9">

2024-03-12 07:07 UTC, Vfivew approved these changes

2024-03-12 07:33 UTC, Oleksandra-Masiuk approved these changes

2024-03-12 09:13 UTC, what1s1ove requested changes

2024-03-12 09:13 UTC, what1s1ove commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_ARRAY_LENGTH) {
you need to handle it with validation

2024-03-12 09:41 UTC, GEOFARL commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_ARRAY_LENGTH) {
I was asked to not show an arrow message when the input is empty. That's why I've removed validation rule and added this check.

String is technically an array of chars)) I'll create a separate constant for that

2024-03-12 09:43 UTC, GEOFARL commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_ARRAY_LENGTH) {
> you need to handle it with validation

<img width="757" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/ec63abc6-6daf-4950-beb7-adea5c5c0d72">

It was a part of my task to remove that, should I return it back?

2024-03-12 12:55 UTC, fshabanov requested changes

2024-03-12 12:55 UTC, fshabanov commented on packages/shared/src/libs/enums/empty-length.enum.ts
> +const EmptyLength = {
What about having just a constant EMPTY_LENGTH?

2024-03-12 16:10 UTC, what1s1ove requested changes

2024-03-12 16:10 UTC, what1s1ove commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_LENGTH) {
```suggestion
```
is not resolved

2024-03-12 16:38 UTC, Vfivew commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_LENGTH) {
Then there will be an error in the chat. 
The task is to avoid such a message, as it is not prettily.
Max has already found another solution, but do you agree that the error should not be in the chat, or should it be returned?
![here123](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/18d099cd-d2f6-4734-9ea2-029dfed9253d)

2024-03-12 18:32 UTC, what1s1ove approved these changes

2024-03-12 18:33 UTC, what1s1ove commented on apps/frontend/src/pages/chats/chats.tsx
> +			if (payload.message.trim().length === EMPTY_LENGTH) {
i guess we can use more that 1 validation in this case

2024-03-12 18:33 UTC, merged