feat(frontend/backend/shared): uam delete users tm-232
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #474
Opened 2024-03-12 09:05 UTC by KrasKa2

![task-232](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/153290443/6e60c666-e8c7-469c-a291-5b03fdfceb0a)

2024-03-12 09:10 UTC, Vfivew requested changes

2024-03-12 09:10 UTC, Vfivew commented on apps/backend/src/modules/users/user.controller.ts
> +			handler: (options) =>
B27

2024-03-12 09:10 UTC, Vfivew commented on apps/frontend/src/pages/management/libs/enums/management-dialogue-messages.ts
> +	DO_YOU_WANT_DELETE_USER: "Are you sure, that you want to delete user",
```suggestion
	DO_YOU_WANT_DELETE_USER: "Are you sure, that you want to delete user?",
```

2024-03-12 09:17 UTC, KrasKa2 commented on apps/frontend/src/pages/management/libs/enums/management-dialogue-messages.ts
> +	DO_YOU_WANT_DELETE_USER: "Are you sure, that you want to delete user",
@Vfivew , this is using in this way:

`const modalContent = `${ManagementDialogueMessages.DO_YOU_WANT_DELETE_USER} ${user.firstName} ${user.lastName}?`;
`

2024-03-12 09:46 UTC, MappariChan approved these changes

2024-03-12 09:47 UTC, fshabanov requested changes

2024-03-12 09:47 UTC, fshabanov commented on apps/backend/src/libs/hooks/check-user-permissions/check-user-permissions.hook.ts
> +import { PermissionError } from "~/modules/permissions/libs/exceptions/exceptions.js";
```suggestion
import { PermissionError } from "~/modules/permissions/permissions.js";
```

2024-03-12 09:47 UTC, fshabanov commented on apps/backend/src/modules/users/user.controller.ts
> +				status: HTTPCode.FORBIDDEN,
Maybe BAD_REQUEST? Forbidden is more about permissions, but deleting yourself I think is not because of permissions

2024-03-12 09:47 UTC, fshabanov commented on apps/frontend/src/modules/management/slices/management.slice.ts
> +import { remove } from "~/modules/users/slices/actions.js";
```suggestion
import { actions as userActions } from "~/modules/users/slices/users.js";
```

2024-03-12 09:47 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/delete-button/delete-button.tsx
> +	}, [setIsModalOpen]);
Those are doing the same thing, you can have only one of them

2024-03-12 09:47 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +import { DataStatus } from "~/libs/enums/data-status.enum.js";
```suggestion
import { DataStatus } from "~/libs/enums/enums.js";
```

2024-03-12 09:47 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +			void dispatch(remove(userId));
```suggestion
			void dispatch(usersActions.remove(userId));
```

2024-03-12 09:47 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +					isLoading={userToDataStatus[user.id] == DataStatus.PENDING}
```suggestion
					isLoading={userToDataStatus[user.id] === DataStatus.PENDING}
```

2024-03-12 12:52 UTC, fshabanov requested changes

2024-03-12 12:52 UTC, fshabanov commented on apps/backend/src/modules/users/user.controller.ts
> +		}
Should be a part of service

2024-03-12 12:52 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/delete-button/delete-button.tsx
> +	const closeModal = useCallback(() => {
```suggestion
	const handleOpenModal = useCallback(() => {
		setIsModalOpen(true);
	}, [setIsModalOpen]);

	const handleCloseModal = useCallback(() => {
```

2024-03-12 13:55 UTC, GEOFARL approved these changes

2024-03-12 16:41 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/confirmation-modal/confirmation-modal.tsx
> +				<div className={styles["confirm-modal-content"]}>{content}</div>
Add text inside of `p` tag (or other text tag)

2024-03-12 21:17 UTC, ShadowOfTheSpace requested changes

2024-03-12 21:17 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/users/user.controller.ts
> +	 *                    type: boolean
Do you return `{ success: boolean }` from service? I think you return only boolean value from service and swagger docs should be changed

2024-03-13 07:58 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/management/libs/components/delete-button/delete-button.tsx
Can we use our Button component here?

2024-03-13 08:18 UTC, KrasKa2 commented on apps/backend/src/modules/users/user.controller.ts
> +	 *                    type: boolean
@ShadowOfTheSpace No, I return `{ success: boolean }`

2024-03-13 08:20 UTC, KrasKa2 commented on apps/frontend/src/pages/management/libs/components/delete-button/delete-button.tsx
@ShadowOfTheSpace I am using our Button component inside `DeleteButton`

2024-03-13 08:21 UTC, ShadowOfTheSpace requested changes

2024-03-13 08:21 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/management/libs/enums/management-dialogue-messages.ts
> +const ManagementDialogueMessages = {
```suggestion
const ManagementDialogueMessage = {
```

2024-03-13 09:25 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/users/user.controller.ts
> +	 *                    type: boolean
I got it, you are right!

2024-03-13 15:28 UTC, fshabanov requested changes

2024-03-13 15:28 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/delete-button/delete-button.tsx
> +					// isOpen={isModalOpen}
Remove or uncomment

2024-03-13 15:28 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +					{/* <Button
Remove or uncomment

2024-03-13 20:13 UTC, YourTeaChan commented on apps/backend/src/modules/users/user.service.ts
> +		userId: number,
If you need only `admin id`, you can pass only `id` prop instead of full object

2024-03-13 20:23 UTC, KrasKa2 commented on apps/backend/src/modules/users/user.service.ts
> +		userId: number,
That what I did at first, but then decided to make this two params different types, in order to avoid switch places, because the consequences can be sad. Maybe it is better to use object as param:
```
{
   userId: number,
   adminId: number,  
}
```
But I decided, that there are not enough parameters here

2024-03-13 20:27 UTC, GEOFARL commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +	const [isDeleteModalOpen, setDeleteModalOpen] = useState<boolean>(false);
```suggestion
	const [isDeleteModalOpen, setIsDeleteModalOpen] = useState<boolean>(false);
```

2024-03-13 20:27 UTC, GEOFARL commented on apps/frontend/src/pages/management/libs/enums/management-dialogue-message.enum.ts
> +	DELETE_USER: "Are you sure, that you want to delete user",
not sure, but maybe let's add question marks?

2024-03-13 20:47 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/management/libs/enums/management-dialogue-message.enum.ts
> +	DELETE_USER: "Are you sure, that you want to delete user",
@GEOFARL [here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/474#discussion_r1521113681) is the answer

2024-03-14 07:37 UTC, Sytnikovakatya approved these changes

2024-03-14 14:19 UTC, Vfivew approved these changes

2024-03-15 22:14 UTC, YourTeaChan commented on apps/backend/src/modules/users/user.service.ts
> +		userId: number,
I think, passing an object with `userId` and `adminId` is better idea, than passing all `admin` object, when you need only `id` from it

2024-03-16 02:11 UTC, ShadowOfTheSpace requested changes

2024-03-16 02:11 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/users/slices/actions.ts
> +		await userApi.remove(id);
Why you don't handle situations when backend returns `success: false`? 

It can be strange when a user in DB is not deleted, but on the frontend, we will have a notification about the successful operation. 
Also, it will be wrong, if we remove this user from the redux store without depending on backend response.

I think it should be changed

2024-03-16 14:07 UTC, ShadowOfTheSpace requested changes

2024-03-16 14:07 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/users/slices/actions.ts
> +				status: HTTPCode.BAD_REQUEST,
Maybe would be better to use `notification.error` here and not to throw server side error on frontend?

2024-03-16 14:27 UTC, KrasKa2 commented on apps/frontend/src/modules/users/slices/actions.ts
> +				status: HTTPCode.BAD_REQUEST,
@ShadowOfTheSpace then I have to return `null` and handle this type of response in the slice (this complicates logic). If we throw error,  error toast is showing. If it was server-side error, it would be in `backend` package, not in  `shared`

2024-03-17 07:16 UTC, what1s1ove requested changes

2024-03-17 07:16 UTC, what1s1ove commented on apps/backend/src/modules/users/user.controller.ts
> +		const success = await this.userService.deleteUserByAdmin(user, userId);
```suggestion
		const success = await this.userService.delete(user, userId);
```
it should be just a delete. you need to handle permissions by the hook

2024-03-17 07:16 UTC, what1s1ove commented on apps/backend/src/modules/users/user.controller.ts
> +			payload: { success },
```suggestion
			payload: true or false,
```

2024-03-17 07:16 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +						onClick={handleOpenDeleteModal(user)}
```suggestion
						onClick={handleOpenDeleteModal}
```
we do not want to have currying functions

2024-03-18 08:09 UTC, what1s1ove requested changes

2024-03-18 08:09 UTC, what1s1ove commented on apps/backend/src/modules/users/user.controller.ts
> +				),
all this logic should be inside the hook. in parameters, you should pass only name of the query param

2024-03-18 08:09 UTC, what1s1ove commented on apps/backend/src/modules/users/user.controller.ts
> +			preHandler: combineHooks([
```suggestion
			preHandler: [
```
you do not need to add an addition hook for it. you need to change the logic of the `preHandler` key to allow it accepts an array

2024-03-18 08:09 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/item-button/item-button.tsx
it a bad to have this component. it would be better to create an `ActionsCell` where you will have all your handlers

2024-03-18 15:14 UTC, what1s1ove approved these changes

2024-03-18 15:14 UTC, merged