fix(frontend): The "Follow" / "Following" buttons on user components are not updated on the new tab after following / unfollowing the users tm-444
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #483
Opened 2024-03-12 14:27 UTC by GEOFARL

![20240312_162602](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/6cc64f7c-c5ab-4c26-b2a9-a44a6104aea1)

2024-03-12 14:44 UTC, GEOFARL commented on apps/frontend/src/pages/friends/friends.tsx
> +				);
Haven't found a better way with current implementation to update a stale followings data. We do not handle it client side as we do not want to remove friend cards after following or unfollowing them

2024-03-12 16:17 UTC, what1s1ove requested changes

2024-03-12 16:17 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +				);
you need t refetch friends on the each page after opening all the time. and you need to fetch friends for the opened page only

2024-03-12 20:54 UTC, ShadowOfTheSpace requested changes

2024-03-12 20:54 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/friends/slices/friends.slice.ts
> +				state.locallyUnfollowedFriendIds.filter((id) => id !== action.payload);
B27 here

2024-03-12 21:02 UTC, Oleksandra-Masiuk commented on apps/frontend/src/modules/friends/slices/friends.slice.ts
> +				state.locallyUnfollowedFriendIds.filter((id) => id !== action.payload);
@ShadowOfTheSpace 
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/99670702/9aa1da41-d123-4a58-9dd9-ce9b72fadabf)

2024-03-12 22:01 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/friends/slices/friends.slice.ts
> +				state.locallyUnfollowedFriendIds.filter((id) => id !== action.payload);
@what1s1ove said on one of the daily calls that we will not use that exception for our project right now, so even one-line arrow functions need to have curly braces

2024-03-13 07:06 UTC, Sytnikovakatya approved these changes

2024-03-13 07:10 UTC, what1s1ove commented on apps/frontend/src/modules/friends/slices/friends.slice.ts
> +				state.locallyUnfollowedFriendIds.filter((id) => id !== action.payload);
it's okay for only the one line function

2024-03-13 07:11 UTC, what1s1ove approved these changes

2024-03-13 07:11 UTC, merged