feat: header component tm-20
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #50
Opened 2024-02-12 02:15 UTC by YourTeaChan

### Overview:

- Added css variables
- Added `Header` and `Image` components
- Changed `Link` and `Button` components
- Added `PageWrapper` component with `Header` usage

### UI preview:

- `Header` if user **exists**
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/795cb19e-3c01-421a-afe6-027a0ed01f5c)

- `Header` if user **does not exist**
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/8538c998-c91d-402b-938f-878ae261da41)

2024-02-12 04:07 UTC, Ann-Maksay approved these changes

2024-02-12 05:43 UTC, fshabanov requested changes

2024-02-12 05:43 UTC, fshabanov commented on apps/frontend/src/assets/css/variables.css
> +	--color-background: #f5f7f7;
Add only those that you use

2024-02-12 05:43 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +		.join(" ");
Use `clsx` library for getting valid classNames

2024-02-12 05:43 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +import { AppRoute } from "~/libs/enums/app-route.enum.js";
```suggestion
import { AppRoute } from "~/libs/enums/enums.js";
```

2024-02-12 05:43 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +};
We already have User type. For avatar, you can just show a default one for now

2024-02-12 05:43 UTC, fshabanov commented on apps/frontend/src/index.tsx
> +import { PageWrapper } from "./libs/components/page-wrapper/page-wrapper.js";
```suggestion
import { PageWrapper } from "./libs/components/components.js";
```

2024-02-12 08:14 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/image/image.tsx
> +			className={`${styles["image"]} ${isCircular && styles["circular"]}`}
Please, use `clsx` here too

2024-02-12 08:22 UTC, what1s1ove requested changes

2024-02-12 08:22 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	isSmall?: boolean;
```suggestion
	size?: 'small' | regular;
```
default is `regular`

2024-02-12 08:22 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	isFluid?: boolean;
```suggestion
	style?: 'fullfiled' | 'outlined';
```
default is `fullfiled`

2024-02-12 08:22 UTC, what1s1ove commented on apps/frontend/src/libs/components/image/image.tsx
> +	isCircular?: boolean;
```suggestion
	shape?: 'default' | 'circle';
```
default is `default`

2024-02-12 08:45 UTC, what1s1ove requested changes

2024-02-12 08:45 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +				</Link>
```suggestion
				<Link to={href} className={buttonStyles}>
					{label}
				</Link>
```

2024-02-12 08:45 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +import { Link } from "../components.js";
```suggestion
import { Link } from "../link/link.js";
```
there can be a circle dependency

2024-02-12 11:26 UTC, YourTeaChan commented on apps/frontend/src/libs/components/button/button.tsx
> +	isFluid?: boolean;
I added filled and outlined styles. But isFluid flag was added for making button width 100% (by default width is auto). How can I set 100% width for button correctly? (it's not for my task, it's for others)
Or I can skip it on this task?

2024-02-12 14:25 UTC, fshabanov requested changes

2024-02-12 14:25 UTC, fshabanov commented on apps/frontend/src/libs/components/auth-wrapper/auth-wrapper.tsx
> +			<Header user={null} />
You should get the user from the store

2024-02-12 14:25 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +			<div className={styles["search"]}>Search input</div>
```suggestion
```

2024-02-12 14:25 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +			{user ? (
```suggestion
			{hasUser ? (
```

2024-02-12 14:25 UTC, fshabanov commented on apps/frontend/src/libs/components/link/link.tsx
> +import clsx from "clsx";
Create a separate helper for clsx

2024-02-12 14:39 UTC, YourTeaChan commented on apps/frontend/src/libs/components/header/header.tsx
> +			<div className={styles["search"]}>Search input</div>
Can I remove only "Search input" text, but keep this div? If I will remove div, header will not correctly displayed (because of justify-content:space-between)

2024-02-12 14:45 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +			<div className={styles["search"]}>Search input</div>
You can use justify-content: flex-end, would it work?

2024-02-12 14:58 UTC, YourTeaChan commented on apps/frontend/src/libs/components/header/header.tsx
> +			<div className={styles["search"]}>Search input</div>
Yes, but it will only works until someone adds input to header. After that, someone will have to edit styles again. Is this good practice? Or keeping empty div is worse?

2024-02-12 15:37 UTC, what1s1ove reviewed
Please, follow all changes by Farid and request me as you finish with them

2024-02-12 15:51 UTC, YourTeaChan commented
> Please, follow all changes by Farid and request me as you finish with them



> Please, follow all changes by Farid and request me as you finish with them

Do I need to request only you or Farid too?
And, if you can, please tell me, should I remove search div and change styles as Farid mentioned or just remove text in this div?

2024-02-12 16:30 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +			<div className={styles["search"]}>Search input</div>
TBH I don't like the approach of keeping an empty div. When someone will be adding an input, they will have to adjust styles so that a new component is correctly displayed, which is totally normal

2024-02-12 16:56 UTC, what1s1ove commented
> > Please, follow all changes by Farid and request me as you finish with them
> 
> Do I need to request only you or Farid too?

both of us

2024-02-12 17:26 UTC, fshabanov requested changes

2024-02-12 17:26 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +import { type UserAuthResponseDto } from "shared";
Do not import directly from the `shared` in component

2024-02-12 17:33 UTC, YourTeaChan commented on apps/frontend/src/libs/components/header/header.tsx
> +import { type UserAuthResponseDto } from "shared";
Can I import this type from "~/modules/auth/auth.js"?

2024-02-12 18:16 UTC, GEOFARL commented on apps/frontend/src/libs/components/auth-wrapper/auth-wrapper.tsx
> +const AuthWrapper: React.FC<Properties> = ({ children }: Properties) => {
You can specify Properties only once
`const AuthWrapper: React.FC<Properties> = ({ children }) => {`

2024-02-12 18:18 UTC, GEOFARL commented on apps/frontend/src/libs/components/button/button.tsx
> +}: Properties) => {
I think, here as well, you can do it only once

2024-02-12 18:21 UTC, GEOFARL reviewed
Great Job

2024-02-12 18:37 UTC, fshabanov requested changes

2024-02-12 18:37 UTC, fshabanov commented on apps/frontend/src/libs/components/header/header.tsx
> +const DEFAULT_USER_AVATAR =
Create ./libs/constants/constants.ts and move this value there

2024-02-12 18:37 UTC, fshabanov commented on apps/frontend/src/libs/helpers/get-valid-class-names/get-valid-class-names.helper.tsx
> +import { type ClassValue, clsx } from "clsx";
Should be .ts file, not tsx

2024-02-13 07:19 UTC, fshabanov approved these changes

2024-02-13 07:19 UTC, merged