feat: sing-in frontend tm-10
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #51
Opened 2024-02-12 05:00 UTC by Ann-Maksay

- Sign in form
- Sign in action flow
- Add user to redux store
-  Validation (shared)
- Design
- "Create an account" link should navigate to the sign up page

### UI
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/62a1396d-7f6a-4a59-a00c-3a796b51319b)

2024-02-12 05:52 UTC, fshabanov requested changes
Also check comments for #50 as you have similar issues

2024-02-12 05:52 UTC, fshabanov commented on apps/frontend/src/modules/auth/auth-api.ts
> +		await storage.set(StorageKey.TOKEN, result.token);
This should be done in action

2024-02-12 05:52 UTC, fshabanov commented on apps/frontend/src/pages/auth/auth.tsx
> +	let mainContainerClassName = "sign-in__container";
This should be handled separately within SignIn/SignUp components

2024-02-12 05:52 UTC, fshabanov commented on knip.config.ts
> +	stylelint: ["./stylelint.config.js"],
Pull the main branch

2024-02-12 05:52 UTC, fshabanov commented on apps/frontend/src/pages/auth/styles.module.css
> +	height: 100vh;
Let's not use `100vh`, this creates issues when working on responsive design

2024-02-12 05:52 UTC, fshabanov commented on apps/frontend/src/pages/auth/styles.module.css
> +		calc(50% + 750px) 484px;
Did you test this for different screen sizes?

2024-02-12 07:12 UTC, ShadowOfTheSpace requested changes

2024-02-12 07:12 UTC, ShadowOfTheSpace commented on packages/shared/src/modules/users/libs/validation-schemas/user-sign-in.validation-schema.ts
> +				message: UserValidationMessage.EMAIL_REQUIRE,
Maybe you should create UserValidationMessage.EMAIL_SHORT message for min length of email?

2024-02-12 08:36 UTC, Ann-Maksay commented on apps/frontend/src/pages/auth/styles.module.css
> +		calc(50% + 750px) 484px;
I specified fixed values so that the clouds would not overlap at smaller screen sizes. I thought it should be different for mobile devices anyway.
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/69ef1015-4c27-468c-a4af-f6825ee81744)

2024-02-12 08:43 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/link/link.tsx
> +	className?: string | undefined;
Here I'm using styles from the module so it can be passed as undefined in theory. 
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/744a6f50-e4dc-411f-894a-7a62c1225f37)

2024-02-12 08:44 UTC, what1s1ove requested changes
please take a look at PR https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/50

there are several changes that you need do also

2024-02-12 08:45 UTC, Ann-Maksay commented on packages/shared/src/modules/users/libs/validation-schemas/user-sign-in.validation-schema.ts
> +				message: UserValidationMessage.EMAIL_REQUIRE,
In fact, EMAIL_MINIMUM_LENGTH is equal to 1, so we are literally checking for anything in this field. All other checks are handled by the following rule

2024-02-12 09:02 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/link/link.tsx
> +	className?: string | undefined;
You are right, I got that!

2024-02-12 10:00 UTC, YourTeaChan commented on package.json
I installed clsx package in frontend workspace, not in root. Maybe you should do it there too

2024-02-12 13:35 UTC, ShadowOfTheSpace approved these changes

2024-02-12 15:39 UTC, fshabanov requested changes

2024-02-12 15:39 UTC, fshabanov commented on packages/shared/src/modules/users/libs/types/user.type.ts
> +type User = {
```suggestion
type UserAuthResponseDto = {
```
Don't forget about the file name

2024-02-12 15:43 UTC, fshabanov commented on apps/frontend/src/libs/helpers/get-valid-class-names/get-valid-class-names.helper.ts
> +const getValidClassNames = (...inputs: ClassValue[]): string => {
If you mean the helper name I think we should keep it

2024-02-12 15:46 UTC, fshabanov requested changes

2024-02-12 15:46 UTC, fshabanov commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +					</svg>
SVGs should be as separate files

2024-02-12 17:55 UTC, fshabanov requested changes

2024-02-12 17:55 UTC, fshabanov commented on apps/frontend/src/modules/auth/slices/actions.ts
> +import { StorageKey, storage } from "~/libs/modules/storage/storage.js";
Add `storage` as an extra argument for action

2024-02-12 17:55 UTC, fshabanov commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +import logo from "~/assets/img/svg/sing-logo.svg";
```suggestion
import logo from "~/assets/img/svg/auth-circle-logo.svg";
```
Or maybe some other name

2024-02-13 08:16 UTC, fshabanov requested changes

2024-02-13 08:17 UTC, what1s1ove requested changes
let's avoid this button for now
<img width="187" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/42296182/30cd9c41-cb46-4d78-b215-76c97dd648ca">

2024-02-13 08:17 UTC, what1s1ove commented on apps/frontend/src/libs/components/input/input.tsx
> +	children?: React.ReactNode;
```suggestion
```
we do not want to add children to form controls

2024-02-13 08:17 UTC, what1s1ove commented on apps/frontend/src/libs/components/link/link.tsx
> +
```suggestion
```

2024-02-13 08:17 UTC, what1s1ove commented on apps/frontend/src/modules/auth/slices/actions.ts
> +	return result;
```suggestion
	const result = await authApi.signIn(loginPayload);
	
	await storage.set(StorageKey.TOKEN, result.token);
	
	return result;
```

2024-02-13 08:17 UTC, what1s1ove commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +					></Input>
```suggestion
					/>
```

2024-02-13 08:17 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/enums/user-validation-message.enum.ts
> +	PASSWORD_SHORT: "Password is too short (8 characters at least).",
```suggestion
	PASSWORD_SHORT: "Password is too short (${UserValidationRule.PASSWORD_MINIMUM_LENGTH} characters at least).",
```

2024-02-13 11:04 UTC, what1s1ove requested changes

2024-02-13 11:04 UTC, what1s1ove commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +				className={getValidClassNames(
since most of this tags/class we should have on sign-up form also, let's move all the styles/tags to pages/auth/auth and we will render only the form by the current route

<img width="774" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/42296182/c46c6297-6566-4da4-865f-d689b8992c9d">

2024-02-13 11:48 UTC, Ann-Maksay commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +				className={getValidClassNames(
Did I understand correctly that I need to transfer all styles to pages/auth/styles.module.css and then I can import them into my form component?
Also a question about the page styles that are different on the login and registration page (clouds on the background and the picture next to the container). I was told that I should not add an additional class to the main container in auth using getScreen(). Can I do this or should I look for a way to implement this from the form component anyway?

2024-02-13 12:50 UTC, what1s1ove commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +				className={getValidClassNames(
hope I answered this question in PM

2024-02-13 13:01 UTC, what1s1ove requested changes

2024-02-13 13:01 UTC, what1s1ove commented on apps/frontend/src/pages/auth/auth.tsx
> +						: getValidClassNames(styles["form-container"], styles["sign-up"])
```suggestion
						getValidClassNames(styles["form-container"], styles[pathname])
```
keep it simple

2024-02-13 13:19 UTC, merged