feat(frontend/backend/shared): UAM (User Access Management) - Groups tm-230
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #536
Opened 2024-03-14 11:48 UTC by YourTeaChan

![2024-03-14 13-22-08](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/454b17a2-0111-4567-9c51-608454352383)

2024-03-14 13:46 UTC, Vfivew commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +						({ href, icon, label, pagePermissions }) =>
Probably B27

2024-03-14 16:10 UTC, what1s1ove requested changes

2024-03-14 16:10 UTC, what1s1ove commented on apps/frontend/src/libs/components/modal/modal.tsx
> +	centered?: boolean;
B19

2024-03-14 16:10 UTC, what1s1ove commented on apps/frontend/src/libs/components/modal/modal.tsx
> +	size?: "large" | "small";
```suggestion
```
by default, modal should have 0 width. width should be added my the children prop. so you do not need this props here

2024-03-14 16:10 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +	const checkPermissions = useCallback(
A10

2024-03-14 16:10 UTC, what1s1ove commented on apps/frontend/src/libs/helpers/check-if-user-has-permissions/check-if-user-has-permissions.helper.ts
> +			});
```suggestion
			return permission.key
```

2024-03-14 16:10 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/groups-tab/groups-tab.tsx
> +		defaultValues: {
move to constant

2024-03-14 16:10 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/groups-tab/groups-tab.tsx
> +	const tableHeaders = [
```suggestion
	const tableHeaders = getTableHeaders()
```
move to component's helpers

2024-03-14 16:10 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/table/libs/components/table-cell/table-cell.tsx
> +	centered?: boolean;
b19

2024-03-14 16:10 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +	const tableHeaders = [
move to component's helpers

2024-03-14 16:28 UTC, fshabanov requested changes

2024-03-14 16:28 UTC, fshabanov commented on apps/frontend/src/libs/components/modal/modal.tsx
> +	centered?: boolean;
```suggestion
	isCentered?: boolean;
```

2024-03-14 16:28 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +	const checkPermissions = useCallback(
```suggestion
	const checkHasPermissions = useCallback(
```

2024-03-14 16:28 UTC, fshabanov commented on apps/frontend/src/modules/permissions/slices/actions.ts
> +import { type AsyncThunkConfig } from "~/libs/types/async-thunk-config.type.js";
```suggestion
import { type AsyncThunkConfig } from "~/libs/types/types.js";
```

2024-03-14 16:28 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/groups-tab/groups-tab.tsx
> +		},
Create a constant for default values

2024-03-14 16:28 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/groups-tab/groups-tab.tsx
> +	const [isConfirmationModalOpen, setConfirmationModalOpen] =
```suggestion
	const [isConfirmationModalOpen, setIsConfirmationModalOpen] =
```

2024-03-14 16:28 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/table/libs/components/table-cell/table-cell.tsx
> +	centered?: boolean;
```suggestion
	isCentered?: boolean;
```

2024-03-14 16:28 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +	const [isEditModalOpen, setEditModalOpen] = useState<boolean>(false);
```suggestion
	const [isEditModalOpen, setIsEditModalOpen] = useState<boolean>(false);
```

2024-03-14 16:51 UTC, Oleksandra-Masiuk requested changes

2024-03-14 16:51 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +				: true;
```suggestion
			return !pagePermissions 
				|| checkIfUserHasPermissions(
						user,
						pagePermissions.permissions,
						pagePermissions.mode,
					);
```

2024-03-14 16:51 UTC, Oleksandra-Masiuk commented on apps/frontend/src/modules/groups/slices/actions.ts
> +	return groups;
```suggestion
	if (!isDeleted) {
	  return groups;
	}
	notification.success(NotificationMessage.GROUP_DELETED);

	return groups.filter((group) => {
		return group.id !== groupId;
	});

```

2024-03-14 16:51 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +								currentUser?.groups.some((userGroup) => {
```suggestion
								currentUser?.groups?.some((userGroup) => {
```

2024-03-14 16:51 UTC, Oleksandra-Masiuk commented on packages/shared/src/modules/groups/libs/enums/group-error-message.enum.ts
> +	DELETE_GROUP_FORBIDDEN: "Delete group forbidden.",
```suggestion
	GROUP_CHANGE_FORBIDDEN: "Group change forbidden.",
	PERMISSION_CHANGE_FORBIDDEN: "Permission change forbidden.",
	GROUP_DELETION_FORBIDDEN: "Group deletion forbidden.",
```

2024-03-14 22:05 UTC, Vfivew commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +								}) ?? false;
Can we use something else instead of `??`

2024-03-15 03:41 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/management/libs/components/groups-tab/groups-tab.tsx
> +	const tableHeaders = [
Can we use this array as a constant in libs here? 
I think this variable doesn't contain any reusable logic, it's used only for the right headers order.

2024-03-15 03:53 UTC, ShadowOfTheSpace commented on apps/backend/src/db/migrations/20240314015427_add_uam_admin_and_admins_group.ts
> +	}
Actually, in Knex every migration is pure transaction. Look [here](https://knexjs.org/guide/migrations.html#transactions-in-migrations).
But for transaction rollback, migration should be failed. Maybe it is better to use throw Error instead of the simple return statement. But never the less, great point here!

2024-03-15 06:13 UTC, GEOFARL commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +								}) ?? false;
I guess the same approach can be applied here [link](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/536#discussion_r1525294435)

2024-03-15 06:15 UTC, GEOFARL commented on apps/backend/src/db/migrations/20240314015427_add_uam_admin_and_admins_group.ts
> +	}
Thanks, didn't know that

2024-03-15 06:18 UTC, YourTeaChan commented on apps/frontend/src/pages/management/libs/components/users-tab/users-tab.tsx
> +								currentUser?.groups.some((userGroup) => {
I don't need to set `?` near `groups` because `groups` are an empty array by default. Groups can't be `null` or `undefined`

2024-03-15 06:19 UTC, YourTeaChan commented on apps/frontend/src/modules/groups/slices/groups.slice.ts
> +export { name };
I need this slice because I have groups actions. The same was in the `files.slice`

2024-03-15 06:20 UTC, YourTeaChan commented on apps/frontend/src/libs/helpers/check-if-user-has-permissions/check-if-user-has-permissions.helper.ts
> +			});
All permissions are in groups, I can't get them this way

2024-03-15 06:21 UTC, YourTeaChan commented on apps/frontend/src/libs/components/modal/modal.tsx
> +	size?: "large" | "small";
I agree with you, but this `Modal` component was created not by me. And if I would change `width` to `0`, it will be affected on the `AddCourseModal`. 
Or I need to change `width` to `0` and fix the `AddCourseModal`?

2024-03-15 08:57 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/groups-tab/groups-tab.tsx
> +	const tableHeaders = [
can be a constant

2024-03-15 08:57 UTC, what1s1ove commented on apps/frontend/src/libs/helpers/check-if-user-has-permissions/check-if-user-has-permissions.helper.ts
> +			});
but you use a flatMap

2024-03-15 08:58 UTC, what1s1ove commented on apps/frontend/src/libs/helpers/check-if-user-has-permissions/check-if-user-has-permissions.helper.ts
> +			});
got the logic, nevermind

2024-03-15 09:45 UTC, what1s1ove commented on apps/frontend/src/libs/components/modal/modal.tsx
> +	size?: "large" | "small";
Right, Modal should be width zero width/height be default. Fix the AddCourseModal component please

2024-03-15 10:36 UTC, what1s1ove requested changes

2024-03-15 10:36 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +	const user = useAppSelector(({ auth }) => {
pass the user through props

2024-03-15 10:36 UTC, what1s1ove commented on apps/frontend/src/modules/groups/slices/actions.ts
> +	} = getState();
```suggestion
```
you need to do it in reducer. remove all `getState`s from here

2024-03-15 10:36 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/groups-tab/groups-tab.tsx
> +		defaultValues: {
move the full object to default value. not the value of `name `

2024-03-15 10:36 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	style?: "icon" | "plain" | "primary" | "secondary";
we already have buttons as the icon but without this prop. why now we need to add this prop?

2024-03-15 18:48 UTC, fshabanov requested changes

2024-03-15 18:48 UTC, fshabanov commented on packages/shared/src/modules/groups/libs/types/all-groups-response-dto.type.ts
> +type AllGroupsResponseDto = {
```suggestion
type GroupsGetAllResponseDto = {
```

2024-03-15 18:48 UTC, fshabanov commented on apps/frontend/src/modules/permissions/slices/actions.ts
> +import { type AllPermissionsResponseDto } from "./../libs/types/types.js";
```suggestion
import { type AllPermissionsResponseDto } from "../libs/types/types.js";
```

2024-03-15 18:48 UTC, fshabanov commented on packages/shared/src/modules/permissions/libs/types/all-permissions-response-dto.type.ts
> +type AllPermissionsResponseDto = {
```suggestion
type PermissionsGetAllResponseDto = {
```

2024-03-16 07:10 UTC, what1s1ove approved these changes

2024-03-16 07:10 UTC, merged