fix(frontend): Hide previous state of the data from the store on all pages tm-506
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #539
Opened 2024-03-14 13:50 UTC by GEOFARL

Course Progress does not jump no more. It stays at 0 before progress data is loaded
![20240314_154555](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/e5be2282-5394-48ae-be28-483700e8a88b)

2024-03-14 16:14 UTC, what1s1ove approved these changes

2024-03-14 16:15 UTC, what1s1ove requested changes

2024-03-14 16:15 UTC, what1s1ove commented on apps/frontend/src/pages/course-description/course-description.tsx
> +		dispatch(courseSectionsActions.reset());
what if the user uses browser navigation? i thing we need to add this action on the page's unmount

2024-03-14 16:53 UTC, GEOFARL commented on apps/frontend/src/pages/course-description/course-description.tsx
> +		dispatch(courseSectionsActions.reset());
Yeah, great point. Missed that scenario

2024-03-15 06:25 UTC, ShadowOfTheSpace approved these changes

2024-03-15 09:46 UTC, what1s1ove approved these changes

2024-03-15 09:46 UTC, merged