feat: protected routing tm-14
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #54
Opened 2024-02-12 11:29 UTC by GEOFARL

2024-02-12 12:06 UTC, tarmiel commented on apps/backend/src/libs/modules/plugins/index.d.ts
> +import { UserSignUpResponseDto } from "~/modules/users/libs/types/types.js";
```suggestion
import { type UserSignUpResponseDto } from "~/modules/users/users.js";
```

2024-02-12 12:11 UTC, tarmiel commented on apps/backend/src/libs/modules/plugins/index.d.ts
> +import { FastifyRequest as BaseFastifyRequest } from "fastify";
```suggestion
import { type FastifyRequest as BaseFastifyRequest } from "fastify";
```

2024-02-12 12:11 UTC, tarmiel commented on apps/backend/src/libs/modules/plugins/auth.plugin.ts
> +import { FastifyInstance, FastifyRequest } from "fastify";
```suggestion
import type { FastifyInstance, FastifyRequest } from "fastify";
```

2024-02-12 12:11 UTC, tarmiel commented on apps/backend/src/libs/modules/controller/libs/types/api-handler-options.type.ts
> +import { UserSignUpResponseDto } from "~/modules/users/users.js";
```suggestion
import { type UserSignUpResponseDto } from "~/modules/users/users.js";
```

2024-02-12 12:44 UTC, fshabanov requested changes

2024-02-12 12:44 UTC, fshabanov commented on apps/backend/src/libs/modules/controller/base-controller.module.ts
> +			user: user ?? null,
It is already either user or null

2024-02-12 12:44 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/auth.plugin.ts
> +import type { AuthPluginOptions } from "./libs/types/types.js";
```suggestion
import { type AuthPluginOptions } from "./libs/types/types.js";
```

2024-02-12 12:44 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/auth.plugin.ts
> +	fastify.addHook("preHandler", async (request: FastifyRequest) => {
Let's user onRequest here. Also, move it to a separate enum

2024-02-12 12:44 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/auth.plugin.ts
> +		const isWhiteRoute = whiteRouteList.includes(apiEndpoint ?? "");
Let's create a separate helper to check if it is a white-route

2024-02-12 12:44 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/index.d.ts
> +declare module "fastify" {
Move this to src/

2024-02-12 12:44 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/auth.plugin.ts
> +		}
Throw HTTPCode.UNAUTHORIZED for all

2024-02-12 12:44 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/libs/enums/enums.ts
> +export { AuthPluginErrorMessage } from "shared";
We already have ExceptionMessage enum

2024-02-12 12:44 UTC, fshabanov commented on apps/backend/src/libs/modules/server-application/base-server-application.ts
> +			whiteRouteList: [
Create a separate constant with whiteRoutes

2024-02-12 12:44 UTC, fshabanov commented on apps/backend/src/libs/modules/token/base-token.module.ts
> +		const secret = new TextEncoder().encode("");
You already added JWT_SECRET in config module, just use it here

2024-02-12 12:46 UTC, GEOFARL commented on apps/backend/src/libs/modules/controller/base-controller.module.ts
> +			user: user ?? null,
If I'm not mistaken, ts showed that it could be undefined

2024-02-12 12:56 UTC, GEOFARL commented on apps/backend/src/libs/modules/plugins/index.d.ts
> +declare module "fastify" {
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/c1ce700b-be6c-43c2-99aa-fca742e0e1bb)
Then for some reason it does not work

2024-02-12 13:15 UTC, GEOFARL commented on apps/backend/src/libs/modules/plugins/auth.plugin.ts
> +		const apiEndpoint = getApiEndpoint(request.url);
This will also include '/api/v1', which I believe can be in the future '/api/v2'
I did not want to hardcode this values, so I created this helper function

2024-02-12 15:04 UTC, tarmiel requested changes

2024-02-12 15:04 UTC, tarmiel commented on packages/shared/src/libs/modules/config/libs/constants/white-routes.constant.ts
> +import { APIPath } from "../../../../enums/api-path.enum.js";
```suggestion
import { AuthApiPath } from "~/modules/auth/auth.js";
import { APIPath } from "~/libs/enums/enums.js";
```

2024-02-12 16:08 UTC, fshabanov requested changes

2024-02-12 16:08 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/libs/helpers/is-white-route.helper.ts
> +	const apiEndpoint = getApiEndpoint(request.url);
It is okay to add `/api/v1`, use `request.routeOptions.url`

2024-02-12 16:08 UTC, fshabanov commented on packages/shared/src/libs/modules/config/libs/constants/white-routes.constant.ts
> +const WHITE_ROUTES = [
Move this file to Backend

2024-02-12 16:59 UTC, what1s1ove requested changes

2024-02-12 16:59 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/types/user-sign-up-response-dto.type.ts
> +	createdAt: string;
it should be something like 
```
type UserSignUpResponseDto = {
  user: 
  token:
}
```

2024-02-12 17:16 UTC, GEOFARL commented on apps/backend/src/libs/modules/plugins/libs/helpers/is-white-route.helper.ts
> +	const apiEndpoint = getApiEndpoint(request.url);
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/c0de495e-2161-44a4-b0b8-be4381e4da83)
I'm not sure how to make this work, for almost all of the routes `request.routeOptions.url` is just '/*'

2024-02-12 17:18 UTC, GEOFARL commented on apps/backend/src/libs/modules/plugins/libs/helpers/is-white-route.helper.ts
> +	const apiEndpoint = getApiEndpoint(request.url);
By the way, I would also like to point out, that as of now, because of the plugin, unauthorized error is returned even for unmatched routes, not sure whether it is intended behavior

2024-02-12 18:42 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/libs/helpers/is-white-route.helper.ts
> +	const apiEndpoint = getApiEndpoint(request.url);
Okay, let's use `request.url` here
It's okay to receive unauthorized error for the routes that are not in whitelist

2024-02-13 13:34 UTC, fshabanov requested changes

2024-02-13 13:34 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/auth.plugin.ts
> +				message: ExceptionMessage.NO_AUTH_HEADER,
User NO_USER message for each case

2024-02-13 13:34 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/libs/helpers/is-white-route.helper.ts
> +	request: FastifyRequest,
```suggestion
	url: string,
```

2024-02-13 14:34 UTC, what1s1ove commented on apps/backend/src/libs/modules/plugins/index.d.ts
> +declare module "fastify" {
try to fix it

2024-02-13 14:37 UTC, what1s1ove commented on apps/backend/src/libs/modules/server-application/base-server-application.ts
> +import { WHITE_ROUTES } from "~/libs/modules/config/libs/constants/constants.js";
it should be a part of `apps/backend/src/libs/modules/server-application` not a part of config

2024-02-13 15:51 UTC, fshabanov requested changes

2024-02-13 15:51 UTC, fshabanov commented on apps/backend/src/libs/modules/controller/libs/types/api-handler-options.type.ts
> +	user: UserAuthResponseDto | null;
Add user type to `DefaultApiHandlerOptions` and use `T["user"];`

2024-02-13 15:51 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/auth.plugin.ts
> +				throw new HTTPError({
Throw `AuthError`

2024-02-13 15:51 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/auth.plugin.ts
> +import { type FastifyRequest } from "fastify";
Plugin is not a module. Move `plugins` folder out of `modules` folder

2024-02-13 15:51 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/libs/helpers/is-white-route.helper.ts
> +import { WHITE_ROUTES } from "~/libs/modules/server-application/libs/constants/constants.js";
```suggestion
import { WHITE_ROUTES } from "~/libs/modules/server-application/server-application.js";
```

2024-02-13 15:51 UTC, fshabanov commented on apps/backend/src/libs/modules/plugins/libs/helpers/is-white-route.helper.ts
> +const isWhiteRoute = (url: string) => {
Check rule B20

2024-02-13 15:51 UTC, fshabanov commented on packages/shared/src/libs/enums/exception-message.enum.ts
> +	NO_JWT: "JWT is required",
These values are not used anymore

2024-02-13 18:41 UTC, what1s1ove commented on apps/backend/src/globals.d.ts
> +import { type FastifyRequest as BaseFastifyRequest } from "fastify";
add this file to tsconfig.json into a "files" key

2024-02-13 18:43 UTC, what1s1ove commented on apps/backend/src/modules/auth/auth.service.ts
> +import { type Token } from "~/libs/modules/token/token.js";
```suggestion
import { Token } from "~/libs/modules/token/token.js";
```
do not add any unnecessary changes

2024-02-13 19:15 UTC, what1s1ove requested changes

2024-02-13 19:15 UTC, what1s1ove commented on apps/backend/src/globals.d.ts
> +import { type FastifyRequest as BaseFastifyRequest } from "fastify";
move it to `backend/globals.d.ts`

2024-02-13 19:16 UTC, GEOFARL commented on apps/backend/src/libs/plugins/auth.plugin.ts
> +	(fastify, { services: { userService } }, done) => {
Are you sure that we need to do that? I've recently removed them because Farid asked me to import them directly into the `checkIfWhiteRoute` helper fn

2024-02-13 20:07 UTC, Oleksandra-Masiuk commented on packages/shared/src/libs/enums/exception-message.enum.ts
> +	NO_FOUND: "User not found",
You need to add a `.` at the end to keep all error consistent

2024-02-13 20:22 UTC, Oleksandra-Masiuk commented on apps/backend/src/libs/plugins/libs/helpers/get-api-endpoint.helper.ts
> +const getApiEndpoint = (url: string): null | string | undefined => {
```suggestion
const getApiEndpoint = (url: string): null | string => {
```

2024-02-13 21:18 UTC, ShadowOfTheSpace commented on packages/shared/src/libs/enums/exception-message.enum.ts
> +	NO_USER: "User not found",
Maybe NOT_FOUND would be better?

2024-02-14 04:57 UTC, fshabanov requested changes

2024-02-14 04:57 UTC, fshabanov commented on apps/backend/src/libs/modules/controller/libs/types/api-handler-options.type.ts
> +	user?: unknown;
User is not unknown, we have a type for it

2024-02-14 04:57 UTC, fshabanov commented on apps/backend/src/libs/plugins/plugins.ts
> +export { authorization } from "./auth.plugin.js";
```suggestion
export { authorization } from "./authorization.plugin.js";
```

2024-02-14 04:57 UTC, fshabanov commented on packages/shared/src/libs/enums/exception-message.enum.ts
> +	NOT_FOUND: "User not found.",
```suggestion
	USER_NOT_FOUND: "User not found.",
```

2024-02-14 06:49 UTC, fshabanov requested changes

2024-02-14 06:49 UTC, fshabanov commented on apps/backend/src/modules/auth/auth.controller.ts
> +					options as APIHandlerOptions<Record<string, unknown>>,
```suggestion
					options as APIHandlerOptions<{ user: UserAuthResponseDto | null }>,
```

2024-02-14 07:23 UTC, what1s1ove requested changes

2024-02-14 07:23 UTC, what1s1ove commented on apps/backend/src/modules/auth/auth.controller.ts
> +		const user = options.user;
```suggestion
		const { user } = options;
```

2024-02-14 07:23 UTC, what1s1ove commented on apps/backend/src/libs/plugins/libs/helpers/check-if-white-route.helper.ts
> +const checkIfWhiteRoute = (url: string) => {
```suggestion
import { WHITE_ROUTES } from "~/libs/modules/server-application/server-application.js";

const checkIfWhiteRoute = (whiteRoutes, url: string) => {
```

2024-02-14 07:23 UTC, what1s1ove commented on apps/backend/src/libs/plugins/authorization.plugin.ts
> +	};
```suggestion
	services: {
		userService: UserService;
	}
	whiteRoutes
```
pass whiteRoutes via options to plugin

2024-02-14 08:06 UTC, fshabanov requested changes

2024-02-14 08:06 UTC, fshabanov commented on packages/shared/src/libs/modules/http/libs/enums/http-code.enum.ts
> +	NOT_FOUND: 404,
You don't use this code

2024-02-14 08:15 UTC, what1s1ove requested changes

2024-02-14 08:15 UTC, what1s1ove commented on apps/backend/src/libs/modules/server-application/base-server-application.ts
> +import { WHITE_ROUTES } from "./server-application.js";
```suggestion
import { WHITE_ROUTES } from "./libs/constants/constants.js";
```

2024-02-14 08:15 UTC, what1s1ove commented on apps/backend/src/libs/modules/server-application/server-application.ts
> +export { WHITE_ROUTES } from "./libs/constants/constants.js";
```suggestion
```

2024-02-14 08:15 UTC, what1s1ove commented on apps/backend/src/libs/plugins/authorization.plugin.ts
> +import { AuthError } from "~/modules/auth/libs/exceptions/exceptions.js";
```suggestion
import { AuthError } from "~/modules/auth/auth";
```

2024-02-14 08:15 UTC, what1s1ove commented on apps/backend/src/libs/plugins/authorization.plugin.ts
> +import { token as jwtToken } from "../modules/token/token.js";
```suggestion
```
pass it via `Options `

2024-02-14 08:33 UTC, Sytnikovakatya approved these changes

2024-02-14 08:38 UTC, fshabanov requested changes

2024-02-14 08:38 UTC, fshabanov commented on apps/backend/src/libs/modules/server-application/base-server-application.ts
> +import { token } from "../token/token.js";
Add those services in a constructor

2024-02-14 08:41 UTC, what1s1ove requested changes

2024-02-14 08:41 UTC, what1s1ove commented on apps/backend/src/libs/plugins/authorization.plugin.ts
> +	jwtToken: Token;
```suggestion
	token: Token;
```

2024-02-14 08:41 UTC, what1s1ove commented on apps/backend/src/libs/plugins/authorization.plugin.ts
> +import { type Token } from "../modules/token/token.js";
```suggestion
import { type Token } from "~/modules/token/token.js";
```

2024-02-14 09:13 UTC, fshabanov approved these changes

2024-02-14 09:17 UTC, what1s1ove approved these changes

2024-02-14 09:18 UTC, merged