feat(frontend/backend/shared): badge icon disappears on all devices of the user tm-503
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #545
Opened 2024-03-14 21:46 UTC by MappariChan

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/5476fd33-7ca3-4ae5-9a1c-41c5696473fe

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/80af93a2-93b2-423c-8f0a-d6c34ed747d2

2024-03-14 22:00 UTC, Vfivew approved these changes

2024-03-15 06:28 UTC, GEOFARL commented on apps/frontend/src/modules/chats/slices/chats.slice.ts
> +				});
```suggestion
				// Convert action.payload.items into an object for faster lookup
const payloadItemsMap = {};
action.payload.items.forEach(message => {
    payloadItemsMap[message.id] = message;
});

// Map over state.currentChat.messages and update if found in payloadItemsMap
state.currentChat.messages = state.currentChat.messages.map(value => payloadItemsMap[value.id] || value);
```

2024-03-15 06:28 UTC, GEOFARL commented on apps/frontend/src/modules/user-notifications/slices/user-notifications.slice.ts
> +
to constants

2024-03-15 09:51 UTC, what1s1ove requested changes

2024-03-15 09:51 UTC, what1s1ove commented on apps/frontend/src/modules/chat-messages/slices/actions.ts
> +		const response = await chatMessagesApi.setReadChatMessages(messagePayload);
bad name

2024-03-15 11:58 UTC, MappariChan commented on apps/frontend/src/modules/chats/slices/chats.slice.ts
> +				});
linter doesn't give opportunity to use forEach() method, so the exit is only one - to use for ... of expression which I don't want to use so I will leave it as it is

2024-03-15 13:33 UTC, GEOFARL commented on apps/frontend/src/modules/user-notifications/libs/constants/notifications-constants.constant.ts
> +export { NotificationConstants };
why do you have an enum in constants?

2024-03-15 13:45 UTC, MappariChan commented on apps/frontend/src/modules/user-notifications/libs/constants/notifications-constants.constant.ts
> +export { NotificationConstants };
because I think it is redundant to make another file for the constant which represent 1 item count, so i created the enum of the constants for the user-notifications module, to store that constants in one object, for the future constant, in the bd migrations where we have constants for the column names they are also grouped into the enum

2024-03-15 14:21 UTC, what1s1ove requested changes

2024-03-15 14:21 UTC, what1s1ove commented on apps/frontend/src/modules/user-notifications/libs/constants/one-item-count.constant.ts
> +const ONE_ITEM_COUNT = 1;
specify a name. it doesn't clarify anything

2024-03-15 18:55 UTC, Sytnikovakatya approved these changes

2024-03-15 20:12 UTC, Vfivew approved these changes

2024-03-15 22:07 UTC, YourTeaChan approved these changes

2024-03-15 22:35 UTC, GEOFARL approved these changes

2024-03-16 07:13 UTC, what1s1ove approved these changes

2024-03-16 07:13 UTC, merged