fix(frontend, shared): Input fields on "Chats" and "Activities" pages tm-546
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #551
Opened 2024-03-15 08:46 UTC by GEOFARL

![20240315_104509](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/0514cd4d-a33d-40ff-ad7a-39429b677951)
![20240315_104538](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/c0cabd34-0748-43bb-8302-93aebcb74c4d)

2024-03-15 09:40 UTC, tarmiel requested changes

2024-03-15 09:40 UTC, tarmiel commented on apps/frontend/src/pages/chats/libs/components/chat-form/chat-form.tsx
> +			}
You don't need that. Zod should handle that in form validation schema.

2024-03-15 09:40 UTC, tarmiel commented on apps/frontend/src/pages/feed/libs/components/activity-comment-form/activity-comment-form.tsx
> +			}
```suggestion
```

2024-03-15 09:54 UTC, what1s1ove requested changes

2024-03-15 09:54 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat-form/chat-form.tsx
> +			}
agreed. remove all watchers from the PR

2024-03-15 09:54 UTC, what1s1ove commented on packages/shared/src/libs/enums/validation-error-type.enum.ts
> +const ValidationErrorType = {
```suggestion
```

2024-03-15 09:54 UTC, GEOFARL commented on apps/frontend/src/pages/chats/libs/components/chat-form/chat-form.tsx
> +			}
It does that after the form submission

2024-03-15 13:31 UTC, GEOFARL commented on packages/shared/src/libs/enums/validation-error-type.enum.ts
> +const ValidationErrorType = {
Need to differentiate between zod error messages, because we call reset in the submitHandler on the component level, and we want to reset correctly entered values after submission or just when the user enters spaces or tabs, but leave the values that are too big

2024-03-15 14:19 UTC, what1s1ove requested changes

2024-03-15 14:19 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat-form/chat-form.tsx
> +		mode: "onBlur",
```suggestion
```
we should have only two modes. change and submit. that it

2024-03-15 14:19 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat-form/chat-form.tsx
> +			if (errors.message?.type === ValidationErrorType.TOO_BIG) {
handler it by zod

2024-03-15 14:19 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comment-form/activity-comment-form.tsx
> +			if (errors.text?.type === ValidationErrorType.TOO_BIG) {
handler it by zod

2024-03-15 18:42 UTC, Sytnikovakatya approved these changes

2024-03-17 07:18 UTC, what1s1ove requested changes

2024-03-17 07:18 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat-form/chat-form.tsx
> +			void trigger("message").then((isValid) => {
```suggestion
```
it should be `onSubmit` + validation. that it. without any additional logic. we discussed it with QAs

2024-03-17 07:18 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comment-form/activity-comment-form.tsx
> +			void trigger("text").then((isValid) => {
same

2024-03-17 07:18 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-app-form/use-app-form.hook.ts
> +		trigger,
```suggestion
```

2024-03-17 08:15 UTC, what1s1ove requested changes
This PR is not fixed these issues:

- The input field on the "Chats" page must not be cleared after trying to send a message longer than the maximum message length
- 
- The input field on the "Activities" page must not be cleared after trying to send a message longer than the maximum comment length

2024-03-17 11:17 UTC, GEOFARL commented on apps/frontend/src/pages/chats/libs/components/chat-form/chat-form.tsx
> +
<img width="636" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/8a20154f-e019-4d2d-b861-fe6e27a2d25f">

2024-03-17 13:31 UTC, Vfivew approved these changes

2024-03-18 07:17 UTC, what1s1ove approved these changes

2024-03-18 07:17 UTC, merged