feat(frontend): pagination should not be displayed if there is only one page tm-502
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #562
Opened 2024-03-15 16:07 UTC by Vfivew

2024-03-15 18:36 UTC, Sytnikovakatya approved these changes

2024-03-15 21:40 UTC, YourTeaChan commented on apps/frontend/src/libs/hooks/use-pagination/libs/helpers/check-is-valid-page/check-is-valid-page.helpers.ts
> +	const isPageExist = pagesCount >= pageFromQuery;
```suggestion
	const isPageExists = pageCount >= pageFromQuery;
```

2024-03-15 22:32 UTC, GEOFARL commented on apps/frontend/src/libs/hooks/use-pagination/libs/helpers/helpers.ts
> +export { checkIsValidPage } from "./check-is-valid-page/check-is-valid-page.helpers.js";
```suggestion
export { checkIsValidPage } from "./check-is-valid-page/check-is-valid-page.helper.js";
```

2024-03-16 07:17 UTC, what1s1ove requested changes

2024-03-16 07:17 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +	const currentPath = path || location.pathname;
A1

2024-03-16 07:17 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +	path?: string;
```suggestion
```
it should not be a part of useHook. this page should work on any page

2024-03-16 09:35 UTC, Vfivew commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +	path?: string;
I'll take another look now what I can come up with.
I used the path because we're calling the pagination hook three times in the Friends component. And I have to somehow check my current path against the path I'm making a request to. And only if they match, I should insert the query parameter.

2024-03-16 13:20 UTC, Vfivew commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +	path?: string;
The hook works everywhere.
However, on the friends page, there are tabs, and when we render it, we make requests for three routes (potential friends / followers / followings).
I use an additional parameter (path) to determine whether I need to set a query parameter (page) in the URL, or if this hook was called for a tab that is currently not displayed. If the hook was called only to retrieve information, it will not set the URL query parameter. If the tab is active, then we will set the query parameter.

The issue arises only with the friends page. There, the logic is slightly different from other parts of the application. Should I refactor whole logic in the friends page component to avoid passing "path" in hook?

2024-03-17 07:19 UTC, what1s1ove approved these changes

2024-03-17 07:19 UTC, merged