feat(backend/frontend/shared): UAM (User Access Management) - Courses tm-231
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #568
Opened 2024-03-16 03:55 UTC by ShadowOfTheSpace

![2024-03-16 05-32-29 (1)](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61262913/3a081b08-39fa-442f-9c2d-c646c05c7a0d)

2024-03-16 04:04 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/management/slices/management.slice.ts
> +	>;
Is it fine to have one state with loading statuses for update and delete in the same place or do I need to create two separate states - courseToUpdateDataStatus and courseToDeleteDataStatus?
I need this for displaying the loader instead of update/delete button in the table.

2024-03-16 16:03 UTC, KrasKa2 requested changes

2024-03-16 16:28 UTC, KrasKa2 reviewed
Also I think it can be useful to have ability to update course data from udemy/edEx API (endpoint on backend already exists)

2024-03-16 16:28 UTC, KrasKa2 commented on apps/frontend/src/pages/management/libs/components/courses-tab/libs/components/edit-course-modal/edit-course-modal.tsx
> +					/>
You can use here `isLoading` and `courseToDataStatus`

2024-03-16 19:21 UTC, fshabanov requested changes

2024-03-16 19:21 UTC, fshabanov commented on apps/backend/src/modules/courses/course.repository.ts
> +			.orderBy("id")
Specify order type (ASC, DESC)

2024-03-16 19:21 UTC, fshabanov commented on apps/frontend/src/modules/management/slices/management.slice.ts
> +	>;
I agree, we can have one status for both delete and update

2024-03-16 19:21 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/courses-tab/courses-tab.tsx
> +	const [isConfirmationModalOpen, setConfirmationModalOpen] =
```suggestion
	const [isConfirmationModalOpen, setIsConfirmationModalOpen] =
```

2024-03-16 19:21 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/courses-tab/courses-tab.tsx
> +	const [isEditModalOpen, setEditModalOpen] = useState<boolean>(false);
```suggestion
	const [isEditModalOpen, setIsEditModalOpen] = useState<boolean>(false);
```

2024-03-16 19:21 UTC, fshabanov commented on packages/shared/src/modules/courses/libs/enums/courses-api-path.enum.ts
> +	ALL: "/all",
We should use ROOT with no filters

2024-03-17 07:29 UTC, what1s1ove requested changes

2024-03-17 07:29 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +			method: "PATCH",
```suggestion
			method: "PUT",
```
let's implement put (update)

2024-03-17 07:29 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +				return this.updateByAdmin(
```suggestion
				return this.update(
```
you need to handle it by permissions

2024-03-17 07:29 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +	private async updateByAdmin({
```suggestion
	private async update({
```

2024-03-17 07:29 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +			payload: await this.courseService.updateByAdmin(Number(courseId), body),
```suggestion
			payload: await this.courseService.update(Number(courseId), body),
```

2024-03-17 07:29 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.service.ts
> +	public async updateByAdmin(
```suggestion
	public async update(
```

2024-03-17 07:29 UTC, what1s1ove commented on apps/frontend/src/modules/courses/slices/courses.ts
> +	getAllByFilter,
```suggestion
	deleteById,
	getAll,
```
getAll should be the same `getAllByFilter` but with nullises params. so you need to keep only one action

2024-03-17 07:29 UTC, what1s1ove commented on apps/frontend/src/modules/management/slices/management.slice.ts
> +	coursesDataStatus: ValueOf<typeof DataStatus>;
```suggestion
```
it should not be a part of this slice

2024-03-17 07:29 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/table/libs/components/table-cell/table-cell.tsx
> +	hasLongText?: boolean;
```suggestion
```
a bad prop. let's avoid it

2024-03-17 07:29 UTC, what1s1ove commented on packages/shared/src/modules/courses/libs/enums/courses-api-path.enum.ts
> +	ALL: "/all",
agreed

2024-03-17 07:42 UTC, ShadowOfTheSpace commented on packages/shared/src/modules/courses/libs/enums/courses-api-path.enum.ts
> +	ALL: "/all",
I asked about this on daily call, and we disscused about it. I think `/all` and `/` have different logic under the hood. Root returns courses by filter from vendors (fom Internet). /all returns courses whiched saved in our database. Is it good to combine this logic in one method?

2024-03-17 08:13 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/management/libs/components/courses-tab/libs/components/edit-course-modal/edit-course-modal.tsx
> +					/>
There is no reason to have a loading state for button in EditCourseModal because modal closes immediately after pressing Confitm button. Also to reach this loading functionality I need to use unwrap method of dispatch because I will need to change only after action is done.

2024-03-17 18:32 UTC, ShadowOfTheSpace commented on apps/frontend/src/modules/management/slices/management.slice.ts
> +				state.coursesDataStatus = DataStatus.FULFILLED;
Agreed, there is no need for that in those reducers

2024-03-17 19:08 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/courses/course.controller.ts
> +			method: "PATCH",
We already have put on `courses/:courseId` (update course from vendor). So there is conflict with it.

2024-03-18 07:45 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +			method: "PATCH",
courses/:courseId - should update the course

2024-03-18 07:46 UTC, what1s1ove requested changes

2024-03-18 07:46 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +			method: "PATCH",
courses/:courseId - should update the course

2024-03-18 07:54 UTC, fshabanov requested changes

2024-03-18 07:54 UTC, fshabanov commented on apps/backend/src/modules/courses/course.repository.ts
> +			.orderBy("id", "ASC")
```suggestion
			.orderBy("id", SortOrder.ASC)
```

2024-03-18 07:54 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/courses-tab/libs/components/course-columns/course-columns.tsx
> +	setIsEditModalOpen,
A9

2024-03-18 07:54 UTC, fshabanov commented on apps/frontend/src/pages/management/libs/components/courses-tab/libs/components/course-columns/course-columns.tsx
> +	editingIsLoading: boolean;
```suggestion
	isDeleting: boolean;
	isEditing: boolean;
```

2024-03-18 12:49 UTC, Vfivew approved these changes

2024-03-18 13:12 UTC, MappariChan approved these changes

2024-03-18 15:19 UTC, what1s1ove requested changes

2024-03-18 15:19 UTC, what1s1ove commented on apps/frontend/src/modules/courses/slices/actions.ts
> +const getAllByFilter = createAsyncThunk<
```suggestion
const getAllByVendor = createAsyncThunk<
```
I think it would be better. change names (reducer key, action name, etc)

2024-03-18 15:19 UTC, what1s1ove commented on apps/frontend/src/modules/courses/slices/actions.ts
> +	return courseApi.getAllByFilter(filterPayload);
```suggestion
	return courseApi.getAllByVendor(filterPayload);
```

2024-03-19 07:01 UTC, fshabanov requested changes

2024-03-19 07:01 UTC, fshabanov commented on apps/frontend/src/modules/management/slices/management.slice.ts
> +	>;
@ShadowOfTheSpace not resolved. Here I meant to have `courseToDataStatus: Record<number, ValueOf<typeof DataStatus>`

2024-03-19 07:11 UTC, what1s1ove requested changes

2024-03-19 07:11 UTC, what1s1ove commented on apps/frontend/src/modules/management/slices/management.slice.ts
> +	courseToDataStatus: Record<
```suggestion
```
it should be a part of courses slice

2024-03-19 07:11 UTC, what1s1ove commented on apps/frontend/src/modules/courses/slices/actions.ts
> +const getAllByFilter = createAsyncThunk<
```suggestion
const getAll = createAsyncThunk<
```

2024-03-19 07:11 UTC, what1s1ove commented on apps/frontend/src/modules/courses/courses-api.ts
> +	public async getAllByFilter(): Promise<CourseSearchGetAllResponseDto> {
```suggestion
	public async getAll(): Promise<CourseSearchGetAllResponseDto> {
```

2024-03-19 15:52 UTC, what1s1ove approved these changes

2024-03-19 15:52 UTC, merged