feat(frontend/shared): implement icons for each type of notifications tm-559
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #573
Opened 2024-03-16 17:46 UTC by Sytnikovakatya

The icons are shown at the All tab on the Notifications page to distinguish notifications' type
![Screenshot_13](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/5c3eb767-243a-4dea-8b59-f15401c9740e)

2024-03-16 19:43 UTC, fshabanov requested changes

2024-03-16 19:43 UTC, fshabanov commented on apps/frontend/src/pages/notifications/libs/components/notification-list-item/notification-list-item.tsx
> +	const isComment = iconName === "follower";
It is not a comment if the iconName is follower 🤔

2024-03-16 20:15 UTC, Oleksandra-Masiuk approved these changes

2024-03-16 20:47 UTC, Vfivew approved these changes

2024-03-16 21:33 UTC, Ann-Maksay approved these changes

2024-03-17 07:11 UTC, what1s1ove requested changes

2024-03-17 07:11 UTC, what1s1ove commented on apps/frontend/src/pages/notifications/libs/components/notification-list-item/libs/maps/notification-type-to-icon-name.map.ts
> +const notificationTypeToIconName = {
```suggestion
const notificationTypeToIconName: Record<NotificationType , Icon> = {
```

2024-03-17 07:11 UTC, what1s1ove commented on apps/frontend/src/pages/notifications/libs/components/notification-list-item/notification-list-item.tsx
> +	isNotificationFilterAll: boolean;
```suggestion
	hasIcon: boolean;
```

2024-03-17 07:11 UTC, what1s1ove commented on apps/frontend/src/pages/notifications/libs/components/notification-list-item/notification-list-item.tsx
> +		isFollower && styles["icon-follower"],
```suggestion
```
it's bad to have specific classes for icons. increase the size of the icon manually then

2024-03-17 07:11 UTC, what1s1ove commented on apps/frontend/src/pages/notifications/libs/components/notification-list/notification-list.tsx
> +	isNotificationFilterAll: boolean;
```suggestion
	hasIcon: boolean;
```

2024-03-17 07:54 UTC, YourTeaChan approved these changes

2024-03-17 11:40 UTC, GEOFARL approved these changes

2024-03-18 01:43 UTC, ShadowOfTheSpace approved these changes

2024-03-18 07:19 UTC, what1s1ove approved these changes

2024-03-18 07:19 UTC, merged