feat(frontend/backend/shared): stripe integration tm-456
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #580
Opened 2024-03-17 01:57 UTC by tarmiel

![Screenshot_4](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/8c57ef16-debd-4040-832c-d4eb16f0e6fa)   ![Screenshot_2](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/7a37fbb0-7404-43a5-a03d-55a42e80328d)
![Screenshot_5](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/91093431/31527e93-88a6-4fbf-b2b4-d0e19d7b0a77)

2024-03-17 08:12 UTC, what1s1ove requested changes

2024-03-17 08:12 UTC, what1s1ove commented on apps/backend/src/libs/modules/stripe/stripe.ts
> +const stripe = new StripeService({
we will use it only as a part of subscription module, so move it there

2024-03-17 08:12 UTC, what1s1ove commented on apps/backend/src/modules/subscriptions/subscription.service.ts
> +	public initCrone(): void {
where did you call it?

2024-03-17 11:38 UTC, GEOFARL reviewed
Great work!

2024-03-17 11:38 UTC, GEOFARL commented on apps/frontend/src/pages/subscription/components/checkout-form/checkout-form.tsx
> +} from "@stripe/react-stripe-js";
maybe you should reexport hooks from ~/libs/hooks/hooks.js

2024-03-17 11:38 UTC, GEOFARL commented on packages/shared/src/modules/subscriptions/libs/enums/subscription-plan.enum.ts
> +export { SubscriptionPlan };
will we have only one subscription plan?

2024-03-17 12:08 UTC, tarmiel commented on packages/shared/src/modules/subscriptions/libs/enums/subscription-plan.enum.ts
> +export { SubscriptionPlan };
yes

2024-03-17 19:52 UTC, Oleksandra-Masiuk requested changes

2024-03-17 19:52 UTC, Oleksandra-Masiuk commented on packages/shared/src/libs/helpers/get-shifted-date/get-shifted-date.helper.ts
> +	return date.toISOString();
```suggestion
	const date = new Date(baseDate);

	if (month) {
		return addMonths(date, month);
	}

	return date.toISOString();
```

2024-03-17 19:52 UTC, Oleksandra-Masiuk commented on apps/frontend/src/modules/subscriptions/slices/actions.ts
> +				error.type === StripeError.VALIDATION_ERROR)
Could you please move this to the separate variable?

2024-03-17 19:52 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/subscription/components/subscription-details/subscription-details.tsx
> +			<div className={styles["plan-title"]}>PRO</div>
The text should be placed in text tags and not div

2024-03-17 21:22 UTC, tarmiel commented on packages/shared/src/libs/helpers/get-shifted-date/get-shifted-date.helper.ts
> +	return date.toISOString();
This was done in case we need to make a shift not only by month, but also by day, for example. And I want to return the date in string

2024-03-18 07:11 UTC, what1s1ove commented on packages/shared/src/libs/helpers/get-shifted-date/get-shifted-date.helper.ts
> +	return date.toISOString();
Leave it as is

2024-03-18 07:13 UTC, what1s1ove approved these changes

2024-03-18 07:13 UTC, merged