feat(frontend): change buttons in the pagination to links tm-534
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #583
Opened 2024-03-17 13:28 UTC by Vfivew

2024-03-17 13:59 UTC, YourTeaChan approved these changes

2024-03-17 18:53 UTC, KrasKa2 requested changes

2024-03-17 18:53 UTC, KrasKa2 commented on apps/frontend/src/libs/components/pagination/pagination.tsx
> +					href={`?page=${ONE_ITEM_COUNT}` as ValueOf<typeof AppRoute>}
Is it valid operation? Do we have `"?page={count}"` in `AppRoute` ?

2024-03-17 19:33 UTC, Sytnikovakatya approved these changes

2024-03-17 20:02 UTC, Vfivew commented on apps/frontend/src/libs/components/pagination/pagination.tsx
> +					href={`?page=${ONE_ITEM_COUNT}` as ValueOf<typeof AppRoute>}
Yes, of course.
I'm just setting a query parameter in the URL.
it is impossible to set href without type casting
I don't think I need to add a query parameter to AppRoute. Or did you mean something else?

2024-03-18 07:22 UTC, what1s1ove requested changes

2024-03-18 07:22 UTC, what1s1ove commented on apps/frontend/src/libs/components/link/link.tsx
> +			tabIndex={isDisabled ? TAB_INDEX_DISABLED : undefined}
```suggestion
```
you need to render a `span` if the link is in the disabled state

2024-03-18 08:18 UTC, Vfivew commented on apps/frontend/src/libs/components/link/link.tsx
> +			tabIndex={isDisabled ? TAB_INDEX_DISABLED : undefined}
I'm rendering span.
I just don’t want the user to be able to interact with this span using the keyboard.
Thats why i did it.
I have another solution.
For example, if `isDisabled ` i can pass href=''. It will resolve my problem. 
But basically I saw the implementation through the tab index.

2024-03-18 11:28 UTC, what1s1ove commented on apps/frontend/src/libs/components/link/link.tsx
> +			tabIndex={isDisabled ? TAB_INDEX_DISABLED : undefined}
if the link is disabled you need to render a span instead
<img width="477" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/42296182/a7e1da84-b1f9-4e94-96ae-fd1dcc44b715">

2024-03-18 12:42 UTC, what1s1ove requested changes
you need to render a span in the `Link` component

2024-03-19 07:17 UTC, what1s1ove approved these changes

2024-03-19 07:17 UTC, merged