feat(backend/frontend/shared): pagination to the add course pop-up window tm-537
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #584
Opened 2024-03-17 13:31 UTC by Ann-Maksay

- Course uploading

![search-load-more](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/5670fc80-d25d-4f08-b782-c143007674f9)

- Changing the value in the search bar

![search-load-more-new-search](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/d4832e08-361a-4c72-ad7f-b372dc8baf79)

- Close and reopen the modal window

![search-load-more-new-window](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/10442046-3211-4239-b95c-f982ba6396ec)

- Adding a course makes the button disabled in all lists

![search-load-more-recomended](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/704bd963-4cf8-4054-8dfb-6ca6ea490f7d)

2024-03-17 13:53 UTC, Vfivew requested changes

2024-03-17 13:53 UTC, Vfivew commented on apps/frontend/src/libs/components/course/course.tsx
> +	const isDisabled = isLoading || isUserHasCourse;
A1

2024-03-17 13:56 UTC, YourTeaChan commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
>  										/>
I think a small button would look better

2024-03-17 13:56 UTC, YourTeaChan commented on packages/shared/src/modules/courses/libs/types/courses-search-response-dto.type.ts
> +type CoursesSearchResponseDto = {
```suggestion
type CourseSearchGetAllResponseDto = {
```

2024-03-17 14:23 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/course/course.tsx
> +	const isDisabled = isLoading || isUserHasCourse;
It is not a [Nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescingl). This checks whether a isLoading is true or false, not whether it exists.

2024-03-17 14:28 UTC, Vfivew commented on apps/frontend/src/libs/components/course/course.tsx
> +	const isDisabled = isLoading || isUserHasCourse;
My mistake. Sorry

2024-03-17 14:28 UTC, Vfivew approved these changes

2024-03-17 14:40 UTC, YourTeaChan approved these changes

2024-03-17 18:53 UTC, Oleksandra-Masiuk requested changes

2024-03-17 18:53 UTC, Oleksandra-Masiuk commented on apps/frontend/src/modules/courses/slices/courses.slice.ts
> +					: course;
```suggestion
				const hasUserCourse = course.vendorCourseId === vendorCourseId;
				return { ...course, hasUserCourse };
```

2024-03-17 18:53 UTC, Oleksandra-Masiuk commented on apps/frontend/src/modules/courses/slices/courses.slice.ts
> +					: course;
```suggestion
			state.recommendedCourses = state.recommendedCourses.map((course) => {
				const hasUserCourse = course.vendorCourseId === vendorCourseId;
				return { ...course, hasUserCourse };
```

2024-03-17 18:53 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/course/libs/helpers/check-is-searched-course.helper.ts
> +	return "isUserHasCourse" in dto;
```suggestion
	return "hasUserCourse" in dto;
```

2024-03-17 19:49 UTC, Sytnikovakatya approved these changes

2024-03-17 20:21 UTC, Ann-Maksay commented on apps/frontend/src/modules/courses/slices/courses.slice.ts
> +					: course;
We want to change hasUserCourse only in the target component, and this code will cause this value to become false in all other components besides it

2024-03-18 07:27 UTC, Oleksandra-Masiuk commented on apps/frontend/src/modules/courses/slices/courses.slice.ts
> +					: course;
In this case, can you do it like this?
```
const hasUserCourse = course.vendorCourseId === vendorCourseId;
return hasUserCourse
         ? { ...course, hasUserCourse }
	 : course;```

2024-03-18 07:55 UTC, what1s1ove requested changes

2024-03-18 07:55 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-app-form/use-app-form.hook.ts
> +	getValues: UseFormGetValues<T>;
```suggestion
```
you need to use onChange mode to get values

2024-03-18 09:38 UTC, Ann-Maksay commented on apps/frontend/src/libs/hooks/use-app-form/use-app-form.hook.ts
> +	getValues: UseFormGetValues<T>;
@what1s1ove 
I don't understand how to do this and why I can't use getValues.
I need it to load more courses for an existing search query. If onChange is triggered, there is a different logic. 
The only thing that comes to my mind is to write the value somewhere in the state onChange but that seems redundant.

2024-03-18 11:26 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-app-form/use-app-form.hook.ts
> +	getValues: UseFormGetValues<T>;
Got the problem. Merged

2024-03-18 11:26 UTC, what1s1ove approved these changes

2024-03-18 11:27 UTC, merged