feat(backend/frontend/shared): update design of activities page tm-555
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #589
Opened 2024-03-17 21:50 UTC by MappariChan

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/24e4d802-7300-4b20-890e-4c3a8e7c90de)

2024-03-17 22:16 UTC, tarmiel requested changes

2024-03-17 22:16 UTC, tarmiel commented on packages/shared/src/modules/activities/libs/types/activity-counts.type.ts
> +	isLikedByUser: null | number;
With is- prefix expected boolean

2024-03-17 22:16 UTC, tarmiel commented on apps/backend/src/modules/activities/activity.repository.ts
> +	private checkIsLikedByUserQuery(
Such name supposes to return boolean

2024-03-18 01:59 UTC, ShadowOfTheSpace approved these changes

2024-03-18 07:12 UTC, Vfivew approved these changes

2024-03-18 07:51 UTC, what1s1ove requested changes

2024-03-18 07:51 UTC, what1s1ove commented on packages/shared/src/modules/activities/libs/types/activity-response-dto.type.ts
> +	isLikedByUser: boolean | null;
```suggestion
	isLikedByUser: boolean;
```
should be `boolean`. add `?? false` in cases where we need to handle it

2024-03-18 07:51 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/feed-activity/feed-activity.tsx
> +		(activity.isLikedByUser as boolean) && styles["liked"],
but it is not a boolean

2024-03-18 08:26 UTC, merged