fix(frontend): "Chat" buttons on user components are shifted to the right outside the components [Mobile] tm-565
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #595
Opened 2024-03-18 13:26 UTC by GEOFARL

Corrected the chats icon in the header, that was affected by changing the size of the svg icon

<img width="186" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/a820e8b1-bfb5-4317-a0e5-4b9e6bfaae00">

2024-03-18 14:26 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/header/styles.module.css
> +
Can you change size of icon in friend component? As far as I know, you made that icon smaller in friend component by changing svg file. So can you revert that here and make that icon smaller in friend component where you need it?

2024-03-18 15:23 UTC, what1s1ove requested changes

2024-03-18 15:23 UTC, what1s1ove commented on apps/frontend/src/libs/components/header/styles.module.css
> +
request my once it's done

2024-03-19 07:19 UTC, what1s1ove approved these changes

2024-03-19 07:19 UTC, merged