feat(frontend/backend): add possibility to delete own comments tm-489
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #599
Opened 2024-03-18 15:07 UTC by tarmiel

2024-03-18 15:27 UTC, what1s1ove requested changes

2024-03-18 15:27 UTC, what1s1ove commented on apps/backend/src/libs/hooks/check-is-user-creator/check-is-user-creator.hook.ts
> +	getUserIdFromDto: (dto: T) => number;
```suggestion
```
provide only paths. not cbs

2024-03-18 18:23 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/notifications/notification.service.ts
> -			});
Why did you remove exception here?

2024-03-19 07:38 UTC, what1s1ove requested changes

2024-03-19 07:38 UTC, what1s1ove commented on apps/backend/src/libs/hooks/check-is-user-creator/check-is-user-creator.hook.ts
> +	getUserIdFromDto: (dto: T) => number;
> What if we have nesting more than one level in dto? Should I handle parsing pathInDto: "author.id" into dto[author][id]

yes, you should handle it

> And what if we need to get the dto id not from params but from the query or body?

pass it as an argument of hook

2024-03-19 07:38 UTC, what1s1ove commented on apps/backend/src/libs/hooks/check-is-user-creator/check-is-user-creator.hook.ts
> +const checkIsUserCreator =
it is not only for user. make it more generic

2024-03-19 07:38 UTC, what1s1ove commented on apps/frontend/src/modules/activities/slices/activities.ts
> +	deleteComment,
it's strange that we have comments here. move all things that are related to comments to `comments` module

2024-03-19 10:43 UTC, Sytnikovakatya approved these changes

2024-03-20 11:30 UTC, what1s1ove requested changes

2024-03-20 11:30 UTC, what1s1ove commented on packages/shared/src/libs/helpers/get-value-by-path/get-value-by-path.helper.ts
> +function getValueByPath<TData, TPath extends string>(
arrow function

2024-03-20 11:30 UTC, what1s1ove commented on apps/backend/src/libs/hooks/check-is-equal/check-is-equal.hook.ts
> +		) as number;
```suggestion
		const dtoId = getValueByPath<number>(
			request as RequestType,
			pathInRequestToDtoId,
		); // number or null
		
		if (!dtoId) {
		  // error
		}
```

2024-03-20 11:30 UTC, what1s1ove commented on apps/backend/src/libs/hooks/check-is-equal/check-is-equal.hook.ts
> +		const toCompareId = getValueByPath(
```suggestion
		const compareId = getValueByPath(
```

2024-03-20 11:30 UTC, what1s1ove commented on apps/backend/src/libs/hooks/check-is-equal/check-is-equal.hook.ts
> +		const dtoIdToCompare = getValueByPath(dto, pathInDtoToCompareId);
```suggestion
		const compareDtoId = getValueByPath(dto, pathInDtoToCompareId);
```

2024-03-20 11:30 UTC, what1s1ove commented on apps/backend/src/libs/hooks/check-is-equal/check-is-equal.hook.ts
> +const checkIsEqual =
do not like the name. should be something like this checkIsEqual<WHO> ?

2024-03-20 11:30 UTC, what1s1ove commented on apps/backend/src/libs/hooks/check-is-equal/check-is-equal.hook.ts
> +		) as number;
same check for compareId

2024-03-20 12:00 UTC, tarmiel commented on apps/backend/src/libs/hooks/check-is-equal/check-is-equal.hook.ts
> +const checkIsEqual =
I do not like it either, but I'm not completely sure what is the exact responsibility of this hook

2024-03-20 13:14 UTC, what1s1ove approved these changes

2024-03-20 13:19 UTC, merged