fix(frontend): PWA sidebar mobile responsiveness tm-563
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #607
Opened 2024-03-18 19:49 UTC by GEOFARL

![telegram-cloud-photo-size-2-5460990624569352231-y](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/e1fde433-e193-4dab-bd79-64ee81766431)
![telegram-cloud-photo-size-2-5460990624569352228-y](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/80c4eba0-fe55-435b-a9b8-c3a08d1c95c8)

2024-03-19 06:51 UTC, fshabanov requested changes

2024-03-19 06:51 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +	.log-out-btn > :first-child > :last-child {
B11

2024-03-19 07:40 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +	.log-out-btn > :first-child > :last-child {
@fshabanov merge it once it's done

2024-03-19 07:41 UTC, what1s1ove requested changes

2024-03-19 07:41 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +	.log-out-btn > :first-child > :last-child {
agreed

2024-03-19 11:29 UTC, what1s1ove requested changes

2024-03-19 11:29 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +	.log-out-icon ~ :last-child {
```suggestion
	.log-out-icon {
```
do not use this hard selector. add an additional classes or something

2024-03-19 11:29 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +.menu-item :first-child {
same

2024-03-19 15:57 UTC, what1s1ove requested changes
we should have label for all icons in PWA mode. discuss it with QA.

2024-03-19 15:57 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +					labelClassName={styles["log-out-label"]}
```suggestion
```
let's avoid adding new props for classes. i see that you use the same classes as for visuallly-hidden. we have a boolean prop for it

2024-03-20 04:09 UTC, fshabanov requested changes

2024-03-20 04:09 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +	labelClassName?: string | undefined;
```suggestion
```

2024-03-20 09:14 UTC, fshabanov requested changes

2024-03-20 09:14 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +	}).length;
Wrap it with `useMemo`

2024-03-20 13:14 UTC, what1s1ove requested changes

2024-03-20 13:17 UTC, GEOFARL commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +							"--number-of-menu-items": numberOfMenuItems,
@what1s1ove, but some users do not have access to uam page and that icon will not be displayed in the sidebar, how should I handle that?

2024-03-20 13:26 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +							"--number-of-menu-items": numberOfMenuItems,
go it. thanks
then the width of items should be flexible. flex-grow: 1 for flex/ 1fr - for grid

2024-03-20 18:33 UTC, GEOFARL commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +							"--number-of-menu-items": numberOfMenuItems,
@what1s1ove the problem is that the logout button is not the part of the menu. That's why I need to know how many items is inside of the menu to assign it appropriate flex-grow number. In case, when we have 3 items then 3, if 4 – 4.

2024-03-20 18:58 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +							"--number-of-menu-items": numberOfMenuItems,
@GEOFARL you can just add flex-grow: 1 to each element in the menu (not content-container), including the logout button

2024-03-20 19:29 UTC, GEOFARL commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +							"--number-of-menu-items": numberOfMenuItems,
@fshabanov 
<img width="828" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/8d8c4fc9-ade1-4aa7-a367-5f4f4d83515d">

I do not know how to make this work with just applying flex-grow

2024-03-21 07:22 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +							"--number-of-menu-items": numberOfMenuItems,
try https://developer.mozilla.org/en-US/docs/Web/CSS/display#display_contents

2024-03-21 10:49 UTC, GEOFARL commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +		display: contents;
cool trick, didn't know about it

2024-03-21 14:20 UTC, what1s1ove approved these changes

2024-03-21 14:20 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +		display: contents;
it is not a trick. it's just CSS 😁

2024-03-21 14:20 UTC, merged