feat(backend/frontend): add search functionality to friends page tm-561
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #618
Opened 2024-03-19 10:28 UTC by Sytnikovakatya

Made "Search" field on"Friends" page to perform a search among the users present on the page

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/d86598ca-320e-4ecf-8de2-0013e6c98968

2024-03-19 10:43 UTC, Ann-Maksay commented on apps/backend/src/modules/friends/friend.controller.ts
> +		query: { search: string | undefined } & PaginationRequestDto;
Why might it be undefined? We already do this check and send `search: searchQuery ? ""` from the frontend

2024-03-19 10:47 UTC, Sytnikovakatya commented on apps/backend/src/modules/friends/friend.controller.ts
> +		query: { search: string | undefined } & PaginationRequestDto;
I added to check when we use, for example, Swagger. And I also saw  the same checking  in the user course controller

2024-03-19 11:32 UTC, what1s1ove requested changes

2024-03-19 11:32 UTC, what1s1ove commented on apps/frontend/src/modules/friends/friends-api.ts
> +		query: { search: string } & PaginationRequestDto,
you duplicate this piece `{ search: string } & PaginationRequestDto` a lot. create a separate type for it

2024-03-19 15:58 UTC, what1s1ove requested changes

2024-03-19 15:58 UTC, what1s1ove commented on apps/backend/src/modules/friends/friend.controller.ts
> +						query: { search: string } & PaginationRequestDto;
use a new type in all places where you have added `{ search: string }`

2024-03-19 16:33 UTC, Vfivew commented
Test it with pagination hook.

2024-03-19 17:25 UTC, fshabanov requested changes

2024-03-19 17:25 UTC, fshabanov commented on packages/shared/src/modules/friends/libs/types/friend-list-request-dto.type.ts
> +type FriendListRequestDto = {
```suggestion
type FriendListRequestQueryDto = {
```

2024-03-19 18:42 UTC, fshabanov requested changes

2024-03-19 18:42 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.controller.ts
> +	 * 		   in: query
```suggestion
	 * 		- name: search
	 * 		in: query
```
In other places we have such indentation

2024-03-19 19:37 UTC, Oleksandra-Masiuk approved these changes

2024-03-20 04:11 UTC, fshabanov approved these changes

2024-03-20 07:11 UTC, what1s1ove approved these changes

2024-03-20 07:12 UTC, merged