feat(frontend): add actions title to button column of tables on the Management page tm-557
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #626
Opened 2024-03-19 13:11 UTC by Sytnikovakatya

Added "Actions" title to the Edit/Delete column to all tabs on the Management page

![Снимок экрана (9)](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/0abb2118-7bbd-4468-a52c-317507bc2911)

![Снимок экрана (10)](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/4d215221-bf97-4241-8ec0-830af8c21566)

2024-03-19 16:01 UTC, what1s1ove requested changes

2024-03-19 16:01 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/users-tab/libs/enums/users-table-header.enum.ts
> +	BUTTONS: "Actions",
```suggestion
	ACTIONS: "Actions",
```

2024-03-19 16:01 UTC, what1s1ove commented on apps/frontend/src/pages/management/libs/components/groups-tab/libs/enums/groups-table-header.enum.ts
> +	BUTTONS: "Actions",
```suggestion
	ACTIONS: "Actions",
```

2024-03-19 18:13 UTC, YourTeaChan approved these changes

2024-03-19 18:47 UTC, fshabanov approved these changes

2024-03-19 19:22 UTC, Oleksandra-Masiuk approved these changes

2024-03-20 06:20 UTC, Ann-Maksay approved these changes

2024-03-20 07:13 UTC, what1s1ove approved these changes

2024-03-20 07:13 UTC, merged