feat(backend): delete all notifcation which releted to users which fo…
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #628
Opened 2024-03-19 15:56 UTC by Vfivew

…llow another user tm-608

2024-03-19 16:01 UTC, ShadowOfTheSpace requested changes

2024-03-19 16:01 UTC, ShadowOfTheSpace commented on apps/backend/src/modules/notifications/notification.repository.ts
> +			.andWhere("type", type);
```suggestion
      .where({ receiverUserId, type, userId: id })
```

2024-03-19 16:01 UTC, what1s1ove requested changes

2024-03-19 16:01 UTC, what1s1ove commented on apps/backend/src/modules/notifications/notification.repository.ts
> +			.andWhere("type", type);
agreed

2024-03-19 17:20 UTC, fshabanov requested changes

2024-03-19 17:20 UTC, fshabanov commented on apps/backend/src/modules/friends/friend.service.ts
> +		await this.notificationService.deteleAllNotificationByUserId(
```suggestion
		await this.notificationService.deleteAllNotificationsByUserId(
```

2024-03-19 17:20 UTC, fshabanov commented on apps/backend/src/modules/notifications/notification.service.ts
> +	public async deteleAllNotificationByUserId(
```suggestion
	public async deleteAllNotificationsByUserId(
```

2024-03-19 18:24 UTC, YourTeaChan approved these changes

2024-03-19 18:50 UTC, fshabanov requested changes

2024-03-19 18:50 UTC, fshabanov commented on apps/backend/src/modules/notifications/notification.service.ts
> +		return await this.notificationRepository.deleteAllNotificationByParameters(
```suggestion
		return await this.notificationRepository.deleteAllNotificationsByParameters(
```
Now in some places you have Notification, in some places Notifications

2024-03-19 18:50 UTC, Oleksandra-Masiuk requested changes

2024-03-19 18:50 UTC, Oleksandra-Masiuk commented on apps/backend/src/modules/notifications/notification.repository.ts
> +	public async deleteAllNotificationByParameters(
```suggestion
	public async deleteAllNotificationsByParameters(
```

2024-03-20 04:12 UTC, fshabanov approved these changes

2024-03-20 06:24 UTC, Ann-Maksay approved these changes

2024-03-20 07:14 UTC, what1s1ove approved these changes

2024-03-20 07:14 UTC, merged