feat: add not found page tm-23
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #64
Opened 2024-02-12 17:45 UTC by MappariChan

2024-02-12 18:08 UTC, GEOFARL commented on apps/frontend/src/libs/components/button/button.tsx
I'm not sure whether it is a good idea, but in my personal projects I like to extend native component attributes
Probably, you can do sth like this
```react
type Properties = {
	color?: "primary";
	href?: ValueOf<typeof AppRoute>;
	label: string;
	size?: "regular" | "small";
	style?: "filled" | "outlined";
};
type ExtendedProperties = HTMLProps<HTMLButtonElement> & Properties;
```

2024-02-12 18:08 UTC, GEOFARL commented on apps/frontend/src/libs/components/button/button.tsx
> +}: Properties) => {
I think, it is not necessary to include Properties here, as you have them in `React.FC<Properties>`

2024-02-12 18:10 UTC, MappariChan commented on apps/frontend/src/libs/components/button/button.tsx
Its good idea

2024-02-12 18:31 UTC, fshabanov requested changes

2024-02-12 18:32 UTC, MappariChan commented on apps/frontend/src/libs/components/button/button.tsx
I don`t know why, but it calls linter error, react property validation error

2024-02-12 20:27 UTC, Oleksandra-Masiuk requested changes

2024-02-12 20:27 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/button/styles.module.css
> +	color: white;
I think we need to add a white color to the CSS variables. Do you agree @fshabanov @what1s1ove ?

2024-02-12 20:27 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/not-found/styles.module.css
> +.error-scene img {
B10

2024-02-12 20:27 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/not-found/not-found.tsx
> +									className={`${classes["error-sign-content"]} ${classes["octagon"]}`}
here too use `clsx` library

2024-02-12 20:27 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/not-found/not-found.tsx
> +										className={`${classes["error-sign-content-text"]} ${classes["octagon"]}`}
here too use `clsx` library

2024-02-13 08:27 UTC, what1s1ove requested changes

2024-02-13 08:27 UTC, what1s1ove commented on apps/frontend/src/assets/css/styles.css
> +@import url("./scaffolding.css");
try to avoid any unnecessary changes

2024-02-13 08:27 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +import { NavLink } from "react-router-dom";
```suggestion
```
use our link component

2024-02-13 08:33 UTC, fshabanov requested changes

2024-02-13 08:33 UTC, fshabanov commented on apps/frontend/src/pages/not-found/not-found.tsx
> +import classes from "./styles.module.css";
Not resolved

2024-02-13 09:31 UTC, MappariChan commented on apps/frontend/src/assets/css/styles.css
> +@import url("./scaffolding.css");
okay i will be more careful with that

2024-02-13 10:34 UTC, what1s1ove requested changes

2024-02-13 10:34 UTC, what1s1ove commented on apps/frontend/src/assets/css/styles.css
> +@import url("./scaffolding.css");
change it back in this pr

2024-02-13 10:34 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +import { Link } from "../components.js";
move it back because there can be circle dependencies

2024-02-13 10:48 UTC, what1s1ove approved these changes

2024-02-13 10:50 UTC, fshabanov approved these changes

2024-02-13 10:51 UTC, merged