feat(backend): aws ses for mails tm-611
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #641
Opened 2024-03-20 11:48 UTC by Ann-Maksay

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/1c40a60b-6891-42ec-b75c-3c7d7f6ce559)

2024-03-20 11:59 UTC, fshabanov requested changes

2024-03-20 11:59 UTC, fshabanov commented on apps/backend/src/libs/modules/mail/mail.module.ts
> +		const sendEmainCommand = new SendEmailCommand(parameters);
```suggestion
		const sendEmailCommand = new SendEmailCommand(parameters);
```

2024-03-20 13:09 UTC, what1s1ove requested changes

2024-03-20 14:21 UTC, what1s1ove requested changes

2024-03-20 14:21 UTC, what1s1ove commented on apps/backend/.env.example
>  S3_REGION=s3_region
```suggestion
AWS_REGION=s3_region
```
you now use it more that just for s3

2024-03-20 14:21 UTC, what1s1ove commented on apps/backend/.env.example
>  AWS_SECRET_ACCESS_KEY=aws_secret_access_key
```suggestion
AWS_ACCESS_KEY=aws_access_key
AWS_SECRET_KEY=aws_secret_key
```
let's simplify names

2024-03-20 14:21 UTC, what1s1ove commented on apps/backend/src/libs/modules/config/base-config.module.ts
>  				AWS_ACCESS_KEY_ID: {
```suggestion
				ACCESS_KEY: {
```
and others
ACCESS_KEY
REGION

2024-03-20 14:21 UTC, what1s1ove commented on apps/backend/src/libs/modules/mail/mail.module.ts
> +		accessKeyId: string;
```suggestion
		accessKey: string;
```

2024-03-20 14:21 UTC, what1s1ove commented on apps/backend/src/libs/modules/mail/mail.module.ts
> +		secretAccessKey: string;
```suggestion
		secretKey: string;
```

2024-03-20 14:21 UTC, what1s1ove commented on apps/backend/src/modules/files/files.ts
> +		secretAccessKey: config.ENV.AWS.AWS_SECRET_ACCESS_KEY,
```suggestion
		accessKey: config.ENV.AWS.AWS_ACCESS_KEY_ID,
		bucket: config.ENV.AWS.S3_BUCKET,
		region: config.ENV.AWS.S3_REGION,
		secretKey: config.ENV.AWS.AWS_SECRET_ACCESS_KEY,
```

2024-03-20 15:04 UTC, Ann-Maksay commented on apps/backend/src/libs/modules/mail/mail.module.ts
> +		accessKeyId: string;
AWS clients expect these key names for credentials, I'll change them here just to write the client call like this:
```
this.sesClient = new SESClient({
	credentials: {
		accessKeyId: accessKey,
		secretAccessKey: secretKey,
	},
	region,
});
```
Is that really worth doing? @what1s1ove

2024-03-20 15:09 UTC, Ann-Maksay commented on apps/backend/src/libs/modules/mail/mail.module.ts
> +		secretAccessKey: string;
Same [here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/641#discussion_r1532250270l)

2024-03-20 15:09 UTC, Ann-Maksay commented on apps/backend/src/modules/files/files.ts
> +		secretAccessKey: config.ENV.AWS.AWS_SECRET_ACCESS_KEY,
Same [here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/641#discussion_r1532250270l)

2024-03-20 16:08 UTC, what1s1ove requested changes

2024-03-20 16:08 UTC, what1s1ove commented on apps/backend/src/libs/modules/mail/mail.module.ts
> +		accessKeyId: string;
yes, do it

2024-03-20 16:08 UTC, what1s1ove commented on apps/backend/src/libs/modules/mail/mail.module.ts
> +		secretAccessKey: string;
do it

2024-03-20 18:55 UTC, fshabanov requested changes

2024-03-20 18:55 UTC, fshabanov commented on apps/backend/src/libs/modules/mail/mail.module.ts
> +		const parameters = {
No need to create a separate variable for that

2024-03-20 19:45 UTC, KrasKa2 requested changes

2024-03-20 19:45 UTC, KrasKa2 commented on apps/backend/src/libs/modules/mail/mail.module.ts
> +				ToAddresses: [to],
```suggestion
				ToAddresses: [email],
```
and remove renaming `email: to`

2024-03-21 07:19 UTC, what1s1ove approved these changes

2024-03-21 07:19 UTC, merged