feat(backend/frontend/shared): implement subscription features tm-630
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #657
Opened 2024-03-20 21:00 UTC by MappariChan

Without subscription:

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/797b5961-2c17-4d5a-8e68-70ba21bcec7a

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/9c0cd01c-001b-41f7-ac25-626d48022abe

With subscription:

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/bb8d695c-aaf2-43cf-b645-7e2e05c29f1e

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/cc948c65-5cee-4cbb-b674-5430d9d00a49

2024-03-21 04:17 UTC, fshabanov requested changes

2024-03-21 04:17 UTC, fshabanov commented on apps/backend/src/libs/hooks/check-user-subscription/check-user-subscription.hook.ts
> +	if (!user?.subscription) {
Use type casting here

2024-03-21 07:38 UTC, what1s1ove requested changes

2024-03-21 07:38 UTC, what1s1ove commented on apps/frontend/src/pages/user/user.tsx
> +	const isCommonCoursesShown =
you need to show this block all the time, but instead of the list of courses you need to design a placeholder. Something like "Wanna recommendations from AI? Then subscribe (+ link to profile)"

2024-03-22 11:10 UTC, MappariChan commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +									/>
Made "subscribe" link to be button which navigates on subscription description modal on profile page, because I need to close modal and to reset it's state before navigating

2024-03-22 11:12 UTC, MappariChan commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/3420aa29-bdd9-4d11-a9c8-5829c0395e27)

2024-03-22 11:44 UTC, what1s1ove requested changes

2024-03-22 11:44 UTC, what1s1ove commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +									/>
yes, it should be a link

2024-03-22 11:44 UTC, what1s1ove commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +											<Courses
you need to prettify the view of recommendation courses. Add folder borders and similar. Ask QA and team about suggestions

2024-03-22 11:44 UTC, what1s1ove commented on apps/frontend/src/pages/overview/libs/components/add-course-modal/add-course-modal.tsx
> +								<p className={styles["subscription-ad"]}>
my comment was only a suggestion. I think it can be implemented prettier. ask QA and team about suggestions

2024-03-22 16:25 UTC, MappariChan commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/a941530a-9a2a-4227-8e47-2dc0816cc233)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/74aec161-cd04-49ff-b8e9-ccaaf4ab36f3)

2024-03-22 16:30 UTC, MappariChan commented
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/fa97eb17-052a-4183-bcb4-6e0ae599e739)

2024-03-22 16:36 UTC, what1s1ove approved these changes

2024-03-22 16:36 UTC, merged