feat(frontend/backend/shared): read/unread messages tm-501
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #660
Opened 2024-03-21 06:20 UTC by YourTeaChan

Messages are marked as read when the window is in focus

![read-unread-messages](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/2b846ae5-092a-4be8-8a39-868264d841d1)

2024-03-21 07:49 UTC, what1s1ove requested changes

2024-03-21 07:49 UTC, what1s1ove commented on apps/frontend/src/modules/chats/libs/constants/one-unread-message.constant.ts
> +const ONE_UNREAD_MESSAGE = 1;
specify a name. it is not clear what is should do

2024-03-21 07:49 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-window-has-focus/use-window-has-focus.hook.tsx
> +const useWindowHasFocus = (): boolean => {
```suggestion
```
you do not need to handler realtime for two windows

2024-03-21 14:19 UTC, what1s1ove requested changes

2024-03-21 14:19 UTC, what1s1ove commented on apps/frontend/src/pages/chats/libs/components/chat/chat.tsx
> +				<span ref={lastMessageReference} />
only `li` element can be inside `ul`

https://caninclude.glitch.me/

2024-03-21 20:50 UTC, Oleksandra-Masiuk commented on apps/frontend/src/modules/chats/slices/chats.slice.ts
> +						: chat;
what about writing like this?
```suggestion
					if(chat.id !== newMessage.chatId){
					return chat;
					}
					return {
								...chat,
								lastMessage: newMessage,
								unreadMessageCount:
									chat.interlocutor.id === newMessage.senderUser.id
										? Number(chat.unreadMessageCount) + NEW_MESSAGE_COUNT
										: chat.unreadMessageCount,
							};
```

2024-03-22 07:19 UTC, what1s1ove approved these changes

2024-03-22 07:19 UTC, merged