feat(frontend/backend): recommended courses tm-624
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #662
Opened 2024-03-21 08:10 UTC by Ann-Maksay

![recommended](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/9d44a038-b715-4bc7-b21b-a05ad12ae3ff)

2024-03-21 14:21 UTC, what1s1ove requested changes

2024-03-21 14:21 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.service.ts
> +		const topIndexes = sortedIndexes.slice(
just ask to return 4. that it

2024-03-21 18:02 UTC, fshabanov approved these changes

2024-03-21 18:58 UTC, GEOFARL approved these changes

2024-03-21 20:25 UTC, Oleksandra-Masiuk approved these changes

2024-03-21 21:29 UTC, YourTeaChan approved these changes

2024-03-22 07:20 UTC, what1s1ove approved these changes

2024-03-22 07:20 UTC, merged