fix(frontend): the default scrollbar is present on the "Add course" screen with the custom scrollbar tm-651
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #664
Opened 2024-03-21 08:42 UTC by Vfivew

![modalisopen](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/141722848/85b9c2b9-c2dd-403d-b542-1e7b34f284ce)

2024-03-21 14:23 UTC, what1s1ove requested changes

2024-03-21 14:23 UTC, what1s1ove commented on apps/frontend/src/libs/components/modal/modal.tsx
> +	useToggleScroll(isOpen);
to it just in `useEffect`, w/o a custom hook

2024-03-21 14:25 UTC, what1s1ove requested changes

2024-03-21 14:25 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-toggle-scroll/use-toggle-scroll.ts
> +function useToggleScroll(isOpen: boolean): void {
an arrow function

2024-03-21 16:23 UTC, what1s1ove requested changes

2024-03-21 16:23 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-toggle-scroll/use-toggle-scroll.ts
> +		}
```suggestion
			document.body.classList.toggle("no-overflow", isOpen);
```

2024-03-21 18:52 UTC, GEOFARL commented on apps/frontend/src/libs/hooks/hooks.ts
> +export { useToggleScroll } from "./use-toggle-scroll/use-toggle-scroll.js";
```suggestion
export { useToggleScroll } from "./use-toggle-scroll/use-toggle-scroll.hook.js";
```

2024-03-21 20:30 UTC, Oleksandra-Masiuk approved these changes

2024-03-22 07:20 UTC, what1s1ove approved these changes

2024-03-22 07:21 UTC, what1s1ove commented
@Vfivew resolve conflicts

2024-03-22 07:58 UTC, what1s1ove approved these changes

2024-03-22 07:58 UTC, merged