fix(frontend/backend): fix pagination search issues in the friends page tm-561
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #671
Opened 2024-03-21 12:58 UTC by Sytnikovakatya

- Fixed Pagination — going from the first page to another page doesn't cancel the search
- The "search" query parameter is present
- Fixed indentation issues in Swagger documentation

https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/18103e88-4a1f-41b9-b536-e872847e05fa

2024-03-21 14:29 UTC, what1s1ove requested changes

2024-03-21 16:10 UTC, Sytnikovakatya commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +			const url = new URL(
I can't do ``url.searchparams`` . Because I've got next error:
``Cannot assign to 'searchParams' because it is a read-only property``

2024-03-21 16:24 UTC, what1s1ove requested changes

2024-03-21 16:24 UTC, what1s1ove commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +			const url = new URL(
searchParams is https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams
fix it

2024-03-21 16:24 UTC, Sytnikovakatya commented on apps/frontend/src/libs/hooks/use-pagination/use-pagination.hook.ts
> +			const url = new URL(
I found method ``url.searchParams.set``. I wiil try it

2024-03-21 18:06 UTC, fshabanov requested changes

2024-03-21 18:06 UTC, fshabanov commented on apps/frontend/src/libs/components/pagination/pagination.tsx
> +						`?page=${ONE_ITEM_COUNT}${querySuffix}` as ValueOf<typeof AppRoute>
`ONE_ITEM_COUNT` is not the correct name/constant for this

2024-03-21 18:44 UTC, GEOFARL approved these changes

2024-03-21 20:18 UTC, Oleksandra-Masiuk approved these changes

2024-03-22 07:58 UTC, what1s1ove approved these changes

2024-03-22 07:59 UTC, merged