feat(backend/frontend/shared): indicate premium users tm-631
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #673
Opened 2024-03-21 13:23 UTC by Sytnikovakatya

Indicated premium users on all pages (Activities, Notifications, Friends, Friend profile...) a with gold crown icon and border. 

![Снимок экрана (24)](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/fb23f6e0-e4a7-4871-9de8-9085ef1ae97b)
![Снимок экрана (28)](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/00519f3c-5afd-4a09-a986-d1e0af1cb939)
![Снимок экрана (29)](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/b6708e3f-ffaf-4ffd-bac8-7a92c030a614)
![Снимок экрана (30)](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/c5d0b56e-f12e-4d3e-9130-b9cd2406d09d)
![Снимок экрана (31)](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/fbab9480-fd7c-4651-855f-a1260bd591e2)
![Снимок экрана (32)](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/118d967e-5063-4def-afbe-b04fa95c87df)

2024-03-21 14:34 UTC, what1s1ove requested changes

2024-03-21 14:34 UTC, what1s1ove commented on apps/frontend/src/pages/feed/libs/components/activity-comments/activity-comments.tsx
> +	}, [activities]);
```suggestion
```
take it directly in the `CommentCard` component as `user.subscription` (like in all other places)

2024-03-21 18:38 UTC, GEOFARL commented on apps/frontend/src/pages/friends/libs/components/friend/friend.tsx
> +				{" "}
```suggestion

```

2024-03-21 18:45 UTC, GEOFARL approved these changes

2024-03-21 20:14 UTC, Oleksandra-Masiuk approved these changes

2024-03-22 07:59 UTC, what1s1ove approved these changes

2024-03-22 07:59 UTC, what1s1ove commented
@Sytnikovakatya resolve comments please

2024-03-22 08:29 UTC, what1s1ove approved these changes

2024-03-22 08:29 UTC, merged