feat(frontend): update pop up window for downloading pwa tm-672
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #678
Opened 2024-03-21 18:23 UTC by Vfivew

2024-03-21 18:39 UTC, GEOFARL approved these changes

2024-03-21 19:00 UTC, fshabanov requested changes

2024-03-21 19:00 UTC, fshabanov commented on apps/frontend/public/assets/screen-desk-fourth.jpg
Isn't it the same with `screen-desk-first.jpg`?

2024-03-21 19:49 UTC, Vfivew commented on apps/frontend/public/assets/screen-desk-fourth.jpg
This screenshot has another dimensions. If we not added this one, the screenshot will not be available on devices with small screens.

2024-03-22 08:00 UTC, what1s1ove approved these changes

2024-03-22 08:00 UTC, merged