feat: add sidebar tm-21
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #68
Opened 2024-02-13 11:36 UTC by GEOFARL

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/7485cd39-f93a-4224-98a1-80db92e78299)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/13f506ec-0089-435b-8443-91e5a25d3224)

2024-02-13 14:44 UTC, what1s1ove requested changes
there should only be changes related to your PR

2024-02-13 15:52 UTC, fshabanov commented
> > there should only be changes related to your PR
> 
> How should I resolve this? Create new PR with only my changes, or remove changes that were not made by me from this pr?

Try with merging main branch into yours

2024-02-13 18:00 UTC, GEOFARL commented
> > > there should only be changes related to your PR
> > 
> > 
> > How should I resolve this? Create new PR with only my changes, or remove changes that were not made by me from this pr?
> 
> Try with merging main branch into yours

Merged main, It seems that I've merged before a branch `12-feat-add-sign-up-client`into mine whose PR is not merged in main yet

2024-02-14 05:08 UTC, fshabanov requested changes

2024-02-14 05:08 UTC, fshabanov commented on apps/frontend/src/libs/components/app/app.tsx
> +					<Sidebar className={styles["sidebar"] ?? ""} />
```suggestion
					<Sidebar className={styles["sidebar"]} />
```

2024-02-14 05:08 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +				<Image alt="website logo" className={styles["logo"] ?? ""} src={logo} />
```suggestion
			<Link className={styles["title-container"]} to="/">
				<Image alt="website logo" className={styles["logo"]} src={logo} />
```

2024-02-14 07:10 UTC, Sytnikovakatya commented on apps/frontend/src/assets/img/svg/logo.svg
We have added the same svg logo before: [auth-circle-logo.svg]

2024-02-14 07:14 UTC, Sytnikovakatya approved these changes

2024-02-14 08:14 UTC, MappariChan approved these changes

2024-02-14 08:28 UTC, Ann-Maksay approved these changes

2024-02-14 10:55 UTC, ShadowOfTheSpace approved these changes

2024-02-14 12:20 UTC, fshabanov requested changes

2024-02-14 12:20 UTC, fshabanov commented on apps/frontend/src/libs/helpers/is-sidebar-shown.helper.ts
> +import { AuthApiPath } from "~/modules/auth/libs/enums/enums.js";
Change file name

2024-02-14 14:27 UTC, fshabanov requested changes

2024-02-14 14:27 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +	icon?: React.ReactNode;
```suggestion
	iconName?: IconName;
```

2024-02-14 14:27 UTC, fshabanov commented on apps/frontend/src/libs/components/icon/icon.tsx
> +const Icon: React.FC<HTMLProps<SVGSVGElement> & Properties> = ({
Use only props that you need

2024-02-14 14:27 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +import { Button, Icon, Image, Link } from "../components.js";
This will result in circular dependencies

2024-02-14 14:27 UTC, fshabanov commented on apps/frontend/src/libs/helpers/check-if-sidebar-shown.helper.ts
> +const checkIfSidebarIsShown = (pathname: string): boolean => {
Create a separate folder for helper as it is with other helpers

2024-02-14 19:41 UTC, fshabanov requested changes

2024-02-15 01:36 UTC, ShadowOfTheSpace requested changes

2024-02-15 01:36 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +}
Styling svg tag breaks B10 rule

2024-02-15 01:36 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/app/styles.module.css
I would move sidebar styling to Sidebar component. But let discuss about that together after daily call

2024-02-15 02:25 UTC, YourTeaChan approved these changes

2024-02-15 08:01 UTC, fshabanov requested changes

2024-02-15 08:12 UTC, what1s1ove requested changes
merge main into your branch because you have a lot of changed that we already have in the main brach

2024-02-15 08:18 UTC, GEOFARL commented
> merge the main branch into your branch because you have a lot of changed that we already have in the main brach

Merged

2024-02-15 08:19 UTC, fshabanov requested changes

2024-02-15 08:19 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/libs/constants/menu-items.constant.ts
> +import { type IconName } from "../../../icon/libs/types/types.js";
Let's move this type to ~libs/types folder

2024-02-15 09:07 UTC, fshabanov requested changes

2024-02-15 09:07 UTC, fshabanov commented on apps/frontend/src/libs/helpers/check-if-sidebar-shown/check-if-sidebar-shown.helper.ts
> +
```suggestion
const checkIfSidebarIsShown = (pathname: AppRoute): boolean => {
	const pagesWithoutSidebar = [AppRoute.SIGN_IN, AppRoute.SIGN_UP];

```

2024-02-15 09:09 UTC, GEOFARL commented on apps/frontend/src/libs/helpers/check-if-sidebar-shown/check-if-sidebar-shown.helper.ts
> +
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/f2b9caf8-8780-4ac7-a4f0-997dd24fa849)

2024-02-15 09:38 UTC, fshabanov commented on apps/frontend/src/libs/helpers/check-if-sidebar-shown/check-if-sidebar-shown.helper.ts
> +
Change `pathName` type to `AppRoute`
`const checkIfSidebarIsShown = (pathname: AppRoute): boolean => {`

2024-02-15 09:40 UTC, GEOFARL commented on apps/frontend/src/libs/helpers/check-if-sidebar-shown/check-if-sidebar-shown.helper.ts
> +
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/d1785ac9-6e66-4ef8-9abf-fa6c90e1921c)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/9de03b7d-40da-45c4-bffb-9243b9a6f5d5)

2024-02-15 11:10 UTC, what1s1ove requested changes

2024-02-15 11:10 UTC, what1s1ove commented on apps/frontend/src/libs/helpers/helpers.ts
> +export { checkIfSidebarIsShown } from "./check-if-sidebar-shown/check-if-sidebar-shown.helper.js";
it is not a global helper

2024-02-15 11:10 UTC, what1s1ove commented on apps/frontend/src/libs/helpers/check-if-sidebar-shown/check-if-sidebar-shown.helper.ts
> +import { AppRoute } from "~/libs/enums/enums.js";
you do not need this helper at all. since side bar shoud be a part of auth wrapper as a header

2024-02-15 11:10 UTC, what1s1ove commented on apps/frontend/src/libs/enums/app-route.enum.ts
> +	OVERVIEW: "/overview",
```suggestion
```
you do not need a new paths

2024-02-15 11:10 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +				{MENU_ITEMS.map(({ href, icon, label }) => (
it should be a part of props

2024-02-15 11:10 UTC, what1s1ove commented on apps/frontend/src/libs/components/sidebar/libs/constants/menu-items.constant.ts
> +		href: "/overview",
```suggestion
		href: AppRoute.ROOT,
```

2024-02-15 11:10 UTC, what1s1ove commented on apps/frontend/src/libs/components/app/app.tsx
> +				{checkIfSidebarIsShown(pathname) ? (
sidebar should be a part of auth wrapper

2024-02-15 12:38 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/types/menu-item.type.ts
> +import { type IconName, type ValueOf } from "~/libs/types/types.js";
```suggestion
import { type IconName, type ValueOf } from "./types.js";
```

2024-02-15 12:45 UTC, fshabanov requested changes

2024-02-15 12:45 UTC, fshabanov commented on apps/frontend/src/libs/types/menu-item.type.ts
> +import { type IconName, type ValueOf } from "~/libs/types/types.js";
This will result in circular dependencies

2024-02-15 12:46 UTC, GEOFARL commented on apps/frontend/src/libs/types/menu-item.type.ts
> +import { type IconName, type ValueOf } from "~/libs/types/types.js";
should I import ValueOf directly from shared?

2024-02-15 13:07 UTC, fshabanov commented on apps/frontend/src/libs/types/menu-item.type.ts
> +import { type IconName, type ValueOf } from "~/libs/types/types.js";
Create a new file in libs/types folder (value-of.type.ts) and export ValueOf from shared in that file. Then use it here

2024-02-15 13:34 UTC, merged