22 feat enable pwa
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #69
Opened 2024-02-13 12:21 UTC by Vfivew

I'm a bit confused by package-lock.json.
From line 1700, there are a few changes that I find strange.
Most likely, I am wrong and everything is fine, but I wanted to draw your attention to this.

2024-02-13 13:11 UTC, GEOFARL approved these changes

2024-02-14 08:38 UTC, Sytnikovakatya approved these changes

2024-02-14 09:17 UTC, fshabanov requested changes

2024-02-14 09:17 UTC, fshabanov commented on apps/frontend/public/assets/android-chrome-512x512.png
Use a new logo here as well

2024-02-14 12:16 UTC, fshabanov requested changes

2024-02-14 12:20 UTC, what1s1ove commented on apps/frontend/public/site.webmanifest
> +{
do we really need a manifest since we create it in vite.config ?

2024-02-14 13:37 UTC, fshabanov approved these changes

2024-02-14 13:37 UTC, Vfivew commented on apps/frontend/public/site.webmanifest
> +	"short_name": "",
I set these fields in vite.config.ts.
I'm deleting this file, that's why im resolve this conversation.

2024-02-14 13:56 UTC, Ann-Maksay approved these changes

2024-02-14 14:23 UTC, what1s1ove approved these changes

2024-02-14 15:51 UTC, merged