feat: add welcome section header tm-25
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #74
Opened 2024-02-13 15:24 UTC by MappariChan

![Знімок екрана 2024-02-13 172200](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/a3c28f75-7145-4836-a07f-d5a0ed5c7c0d)

2024-02-13 17:39 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/button/button.tsx
> +	children?: ReactNode;
You should use React.ReactNode instead of ReactNode
[Another comment from Farid](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/38/commits/453ef168f2e583de6ca7a3b74f87f982f393a6b6#r1485209432)

2024-02-13 17:48 UTC, ShadowOfTheSpace commented on apps/frontend/src/pages/overview/components/welcome-section-header/styles.module.css
> +	color: white;
I think it should be taken from variable

2024-02-13 18:14 UTC, GEOFARL approved these changes

2024-02-13 18:49 UTC, what1s1ove requested changes

2024-02-13 18:49 UTC, what1s1ove commented on apps/frontend/src/pages/overview/components/welcome-section-header/welcom-section-header.tsx
> +import plusIcon from "~/assets/img/svg/plus-icon.svg";
let's create an icon component instead it

2024-02-13 19:21 UTC, fshabanov requested changes

2024-02-13 19:26 UTC, Sytnikovakatya approved these changes

2024-02-13 20:24 UTC, Sytnikovakatya approved these changes

2024-02-14 05:12 UTC, fshabanov requested changes

2024-02-14 05:12 UTC, fshabanov commented on apps/frontend/src/pages/overview/components/welcome-section-header/welcom-section-header.tsx
> +				>{`${firstName} ${lastName}`}</h3>
```suggestion
				>{firstName} {lastName}</h3>
```

2024-02-14 05:12 UTC, fshabanov commented on apps/frontend/src/pages/overview/overview.tsx
> +import { WelcomeHeader } from "./components/welcome-section-header/welcom-section-header.js";
```suggestion
import { WelcomeHeader } from "./components/welcome-section-header/welcome-section-header.js";
```

2024-02-14 06:31 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/icon/icon.tsx
I think it is better to make Icon component like it was in thread-js. You can create an additional file with icon imports from the font-awesome library (in this case you will import from local files) and also you can have a map or object with key=iconName and value=iconFile. So you won't need to write all that logic in Icon component.

2024-02-14 07:43 UTC, MappariChan commented on apps/frontend/src/libs/components/icon/icon.tsx
I get this component from the Max's PR to not resolve too much conflicts, but i get your point about removing the logic from the component, i will write Max about your idea.

2024-02-14 08:23 UTC, fshabanov requested changes

2024-02-14 08:24 UTC, what1s1ove requested changes

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/pages/overview/overview.tsx
> +import { WelcomeHeader } from "./components/welcome-section-header/welcome-section-header.js";
```suggestion
import { WelcomeHeader } from "./libs/components/components.js";
```

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/pages/overview/overview.tsx
> +	) : null;
```suggestion
		<WelcomeHeader user={user} />
```
we should always have user on this page

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/libs/components/icon/common.ts
apps/frontend/src/libs/components/icon/libs/map/icon-name-to-svg.ts

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/libs/components/icon/icon.tsx
> +import { iconNameToSvg } from "./common.js";
```suggestion
import { iconNameToSvg } from "./libs/maps/maps.js";
```

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/libs/components/icon/icon.tsx
> +const Icon: React.FC<ExtendedProperties> = ({
```suggestion
const Icon: React.FC<HTMLProps<SVGSVGElement> & Properties> = ({
```

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/libs/components/components.ts
> +export { Icon, IconName } from "./icon/icon.js";
```suggestion
export { Icon } from "./icon/icon.js";
```

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/libs/components/icon/icon.tsx
> +	name: ValueOf<typeof IconName>;
```suggestion
	name: IconName;
```
use union here

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +					{children}
```suggestion
```

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	className = "",
```suggestion
	className,
```

2024-02-14 08:24 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	children,
```suggestion
```
add new props `iconName`

2024-02-14 09:12 UTC, MappariChan commented on apps/frontend/src/pages/overview/overview.tsx
> +	) : null;
Hi, in the slice we have state user which is of type UserAuthResponseDto | null, so even if user will be authorized after the  page overview will select this state, the overview page wont know that the user already exist it'll obtain UserAuthResponseDto | null, Oleg give me advice to use non-null-assertion but it cause eslint error:
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/b31e0872-e574-4eb8-9698-a14765599f0a)
So can you give me advice how to be with that?

2024-02-14 09:13 UTC, MappariChan commented on apps/frontend/src/pages/overview/overview.tsx
> +	) : null;
Or i should simply pass empty strings to the firstName and lastName if user is null?

2024-02-14 10:18 UTC, ShadowOfTheSpace approved these changes

2024-02-14 12:14 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	icon?: React.ReactNode;
```suggestion
	iconName?: IconName;
```

2024-02-14 12:20 UTC, MappariChan commented on apps/frontend/src/libs/components/icon/libs/types/icon-name.type.ts
> +type IconName = ValueOf<typeof IconNames>;
So inside of the component i should write
`<Button iconName="plus"/>`?
Maybe it would better to leave this enum?

2024-02-14 13:36 UTC, Vfivew commented on apps/frontend/src/libs/components/button/button.tsx
> +	className?: string | undefined;
I'm not sure that an undefind is needed here.

2024-02-14 13:41 UTC, fshabanov requested changes

2024-02-14 13:41 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +import { Icon } from "../components.js";
It will result in circular dependencies

2024-02-14 13:41 UTC, fshabanov commented on apps/frontend/src/libs/components/icon/icon.tsx
> +const Icon: React.FC<HTMLProps<SVGSVGElement> & Properties> = ({
Use only properties that you need

2024-02-14 13:46 UTC, what1s1ove requested changes

2024-02-14 13:46 UTC, what1s1ove commented on apps/frontend/src/pages/overview/overview.tsx
> +import { UserAuthResponseDto } from "./libs/types/types.js";
```suggestion
import { UserAuthResponseDto } from "~/modules/users/users.js";
```

2024-02-14 14:18 UTC, ShadowOfTheSpace approved these changes

2024-02-14 14:22 UTC, what1s1ove approved these changes

2024-02-14 14:22 UTC, merged