feat: course component tm-26
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #79
Opened 2024-02-14 06:22 UTC by Ann-Maksay

Temporarily renders in app component to avoid Unused files error

-  Idle

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/2b01039d-23a3-494e-8145-935e2a1d1ead)

- Hover

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/b43e14fc-66c2-457e-a4fe-c27967a961ba)

2024-02-14 06:28 UTC, YourTeaChan commented on apps/frontend/src/libs/components/course/styles.module.css
> +	border: 1px solid #ffffff;
We already have a `--main-white` variable for this color

2024-02-14 06:28 UTC, YourTeaChan commented on apps/frontend/src/libs/components/course/styles.module.css
> +	background-color: #ffffff;
Same here

2024-02-14 06:42 UTC, fshabanov requested changes
Remove the empty space under the title

2024-02-14 06:49 UTC, Ann-Maksay commented
> Remove the empty space under the title

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/42fff5b4-112c-4749-8695-1ebb0d7b554a)

2024-02-14 07:02 UTC, Sytnikovakatya approved these changes

2024-02-14 07:54 UTC, GEOFARL approved these changes

2024-02-14 08:26 UTC, what1s1ove requested changes

2024-02-14 08:26 UTC, what1s1ove commented on apps/frontend/src/libs/components/course/course.tsx
> +		<div className={styles["container"]}>
```suggestion
		<article className={styles["container"]}>
```

2024-02-14 08:26 UTC, what1s1ove commented on apps/frontend/src/libs/components/course/course.tsx
> +const Course: React.FC = () => {
create a type in shared folder and pass all data via props

2024-02-14 09:22 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/course/course.tsx
> +const Course: React.FC = () => {
Do I need to create a courses module in shared or can I leave it in libs/types for now ?

2024-02-14 11:24 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/app/app.tsx
> +
@fshabanov If I remove everything unnecessary from the App component then users module is not used anywhere else. And with it some types from shared. Should I remove them as well?

2024-02-14 12:12 UTC, fshabanov commented on apps/frontend/src/libs/components/app/app.tsx
> +
@Ann-Maksay understood, keep it for now

2024-02-14 12:21 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/app/app.tsx
> +				))}
I left it for now, because I don't know if I should delete users actions that are only used here.

2024-02-14 12:24 UTC, Ann-Maksay commented on apps/frontend/src/pages/overview/components/courses-list/course-list.tsx
> +			<h2 className={styles["title"]}>Courses</h2>
In design, we have a filter like this. Should I skip it for now or implement it as stylised radio buttons?
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/d53ed1da-c53e-4a17-a8e9-7d6d97d0cefe)

2024-02-14 13:07 UTC, fshabanov requested changes

2024-02-14 13:07 UTC, fshabanov commented on apps/frontend/src/pages/overview/components/courses-list/course-list.tsx
> +			<h2 className={styles["title"]}>Courses</h2>
Skip for now

2024-02-14 13:07 UTC, fshabanov commented on apps/frontend/src/pages/overview/overview.tsx
> +			<CourseList courses={DEFAULT_COURSES_DATA} />
```suggestion
			<Courses courses={DEFAULT_COURSES_DATA} />
```

2024-02-14 13:07 UTC, fshabanov commented on packages/shared/src/modules/courses/libs/types/course-data.type.ts
> +type CourseData = {
```suggestion
type Course = {
```

2024-02-14 15:14 UTC, fshabanov requested changes

2024-02-14 15:14 UTC, fshabanov commented on apps/frontend/src/pages/overview/libs/components/courses/courses.tsx
> +import { Course as CourseData } from "~/libs/types/types.js";
Let's name the type CourseDto to not confuse with component

2024-02-14 15:56 UTC, Vfivew approved these changes

2024-02-14 20:02 UTC, GEOFARL approved these changes

2024-02-15 02:32 UTC, YourTeaChan approved these changes

2024-02-15 07:41 UTC, fshabanov requested changes

2024-02-15 07:41 UTC, fshabanov commented on apps/frontend/src/pages/overview/libs/components/course/course.tsx
> +import { Image } from "~/libs/components/components.js";
Move Course component to ~libs/components/components.js, this component will be used in other screens as well

2024-02-15 08:10 UTC, fshabanov requested changes

2024-02-15 08:10 UTC, fshabanov commented on apps/frontend/src/pages/overview/libs/components/courses/courses.tsx
> +				{courses.map((course: CourseDto) => {
```suggestion
				{courses.map((course) => {
```
Do we need to specify this type again? We already have it from Properties

2024-02-15 08:14 UTC, what1s1ove approved these changes
fix Farid's comment and then we ready to merge it

2024-02-15 08:34 UTC, what1s1ove approved these changes

2024-02-15 08:36 UTC, what1s1ove requested changes

2024-02-15 08:36 UTC, what1s1ove commented on package-lock.json
> -		"node_modules/@babel/helper-member-expression-to-functions": {
you have some conflict here. since you did not install any packages, this file should not be chnaged
this is a reason why CI action fails now

2024-02-15 08:37 UTC, Ann-Maksay commented on package-lock.json
> -		"node_modules/@babel/helper-member-expression-to-functions": {
yes, fixing this right now

2024-02-15 08:52 UTC, fshabanov approved these changes

2024-02-15 08:53 UTC, merged