feat: create friend component tm-82
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #84
Opened 2024-02-14 11:22 UTC by GEOFARL

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/110524091/5e5ea317-4353-472e-be43-9a8bdcb94643)

2024-02-14 12:11 UTC, fshabanov requested changes
Centralize button

2024-02-14 12:11 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +	icon?: React.ReactNode;
Create a new component ButtonWithIcon, instead of `React.ReactNode` receive iconName and display icon

2024-02-14 12:11 UTC, fshabanov commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +				</div>
Remove for now

2024-02-14 13:57 UTC, fshabanov requested changes

2024-02-14 13:57 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +	icon?: React.ReactNode;
```suggestion
	iconName?: IconName;
```

2024-02-14 14:02 UTC, Ann-Maksay approved these changes

2024-02-14 20:53 UTC, Oleksandra-Masiuk approved these changes

2024-02-15 07:43 UTC, YourTeaChan approved these changes

2024-02-15 07:47 UTC, fshabanov requested changes

2024-02-15 07:47 UTC, fshabanov commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +};
Receive `user` as a property

2024-02-15 08:15 UTC, what1s1ove requested changes
merge the main branch into your branch because you have a lot of changed that we already have in the main brach

2024-02-15 11:14 UTC, what1s1ove requested changes

2024-02-15 11:14 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +	user: { fullName: string; imageUrl: string };
```suggestion
	user: friend-type;
```
should be similar to "course" PR

2024-02-15 12:54 UTC, YourTeaChan commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +import { FriendDto } from "~/libs/types/types.js";
```suggestion
import { type FriendDto } from "~/libs/types/types.js";
```

2024-02-15 13:02 UTC, fshabanov requested changes

2024-02-15 13:02 UTC, fshabanov commented on packages/shared/src/modules/friends/libs/types/friend.type.ts
> +type FriendDto = {
File name should be the same as type name

2024-02-16 08:11 UTC, ShadowOfTheSpace approved these changes

2024-02-16 08:19 UTC, what1s1ove requested changes

2024-02-16 08:19 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +	user: { fullName, imageUrl },
```suggestion
	user,
```
avoid destruction in objects in props

2024-02-16 08:19 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +			<Friend
make an array of users.the same as on the `courses` page

2024-02-16 09:28 UTC, fshabanov requested changes

2024-02-16 09:28 UTC, fshabanov commented on apps/frontend/src/pages/friends/friends.tsx
> +import { DEFAULT_FRIENDS_DATA } from "~/libs/constants/friends.constants.js";
```suggestion
import { DEFAULT_FRIENDS_DATA } from "~/libs/constants/constants.js";
```

2024-02-16 09:28 UTC, fshabanov commented on apps/frontend/src/pages/friends/friends.tsx
> +			))}
```suggestion
			{DEFAULT_FRIENDS_DATA.map((user) => (
				<Friend
					key={user.id}
					user={user}
				/>
			))}
```

2024-02-16 10:13 UTC, Sytnikovakatya approved these changes

2024-02-16 12:27 UTC, MappariChan approved these changes

2024-02-16 14:04 UTC, what1s1ove requested changes

2024-02-16 14:04 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +			{DEFAULT_FRIENDS_DATA.map((user) => (
it should be an `ul` element

2024-02-16 14:04 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +		<div className={styles["card"]}>
```suggestion
		<article className={styles["card"]}>
```

2024-02-16 14:04 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +	const { fullName, imageUrl } = user;
```suggestion
```
use `user.keyName` where you need it

2024-02-16 14:04 UTC, what1s1ove commented on apps/frontend/src/pages/friends/components/friend/friend.tsx
> +	user: FriendDto;
```suggestion
	friend: FriendDto;
```

2024-02-16 19:25 UTC, Vfivew approved these changes

2024-02-17 07:20 UTC, what1s1ove requested changes

2024-02-17 07:20 UTC, what1s1ove commented on apps/frontend/src/pages/friends/friends.tsx
> +				<Friend friend={friend} key={friend.id} />
```suggestion
    <li>
				<Friend friend={friend} key={friend.id} />
				</li>
```
inside an `ul` element on an `li` element is allowed

2024-02-17 14:17 UTC, what1s1ove approved these changes

2024-02-17 14:17 UTC, merged