feat: add udemy module tm-65
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #88
Opened 2024-02-14 15:14 UTC by KrasKa2

All fixes about comments from prev PR are done  https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/80

2024-02-14 15:39 UTC, fshabanov requested changes

2024-02-14 15:39 UTC, fshabanov commented on apps/backend/src/libs/modules/http/base-http.module.ts
> +			}
```suggestion
			const queryParameters = new URLSearchParams(query);
```
Then use `queryParameters.toString()`

2024-02-14 15:39 UTC, fshabanov commented on apps/backend/src/libs/modules/udemy/libs/enums/api-paths.enum.ts
> +const ApiPath = {
```suggestion
const UdemyApiPath = {
```

2024-02-14 15:39 UTC, fshabanov commented on apps/backend/src/libs/modules/udemy/libs/enums/enums.ts
> +export { CourseFields } from "./course-fields.enum.js";
Enum names should be in singular forms

2024-02-14 15:39 UTC, fshabanov commented on apps/backend/src/libs/modules/udemy/libs/enums/api-paths.enum.ts
> +	COURSES: "",
Either use `ROOT: "/"` or remove it

2024-02-14 18:51 UTC, fshabanov requested changes

2024-02-14 18:51 UTC, fshabanov commented on knip.config.ts
> +	],
As discussed in a call, create controller and remove everything from `ignore`

2024-02-15 01:26 UTC, ShadowOfTheSpace approved these changes

2024-02-15 06:58 UTC, GEOFARL approved these changes

2024-02-15 07:54 UTC, tarmiel commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +};
This type will be useful on frontend. Add it to shared.

2024-02-15 07:54 UTC, tarmiel commented on apps/backend/src/modules/courses/coursses.controller.ts
keep file names consistent ( `courses.ts`, `courses.controller.ts`,` courses.service.ts` )

2024-02-15 08:01 UTC, KrasKa2 commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +};
@tarmiel , No, in share will be xxRequestDto, I think, I will remove this type at all in the future

2024-02-15 08:28 UTC, what1s1ove requested changes

2024-02-15 08:28 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.service.ts
> +	public search(): Promise<unknown> {
for now we need functionality to get course by slug

it means, that you need to write a logic, that you will receive a course url, for example https://www.udemy.com/course/aws-certified-cloud-practitioner-new/, that you need to understand the vendor (can be udemy, coursera,, etc) (propably, you need a switch/case to handle this logic), that you need to take a path (slug) and fetch + save (yes, you need to write new migration) course details in the db. that's all you need to do in this ticket

2024-02-15 09:11 UTC, KrasKa2 commented on apps/backend/src/modules/courses/course.service.ts
> +	public search(): Promise<unknown> {
Ok, now I get it. I thought, I will do this in [next task](https://github.com/orgs/BinaryStudioAcademy/projects/22/views/1?sliceBy%5Bvalue%5D=KrasKa2&pane=issue&itemId=52768721 ) ))

Thank you for detailed clarification!

2024-02-15 10:29 UTC, what1s1ove requested changes

2024-02-15 10:29 UTC, what1s1ove commented on apps/backend/src/libs/modules/udemy/libs/enums/course-field.enum.ts
> +	LEVEL: "instructional_level_simple", // values: 'All Levels', 'Beginner', ...
```suggestion
	LEVEL: "instructional_level_simple"
```

2024-02-15 10:29 UTC, what1s1ove commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +		let query = {
```suggestion
		const query = {
```

2024-02-15 10:29 UTC, what1s1ove commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +			// "fields[course]": "@all", - to see more fields
```suggestion
```

2024-02-15 10:29 UTC, what1s1ove commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +		 */
```suggestion
```

2024-02-15 10:29 UTC, what1s1ove commented on apps/backend/src/libs/modules/udemy/udemy.ts
> +	},
```suggestion
```
use it directly in class

2024-02-15 10:29 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +	private async search(): Promise<APIHandlerResponse> {
```suggestion
	private async findAllByVendor(): Promise<APIHandlerResponse> {
```

2024-02-15 10:29 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +			payload: await this.courseService.search(),
```suggestion
			payload: await this.courseService.findAllByVendor(),
```

2024-02-15 10:32 UTC, what1s1ove requested changes

2024-02-15 10:32 UTC, what1s1ove commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +		return await this.http.load(this.baseUrl, options);
```suggestion
		return await this.load(options);
```
create your load method in this class. it will be a wrapper for `http.load`

2024-02-15 10:47 UTC, KrasKa2 commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +		return await this.http.load(this.baseUrl, options);
What will this give us? in `getCourseDetails`  `const url = `${this.baseUrl}${id}`;`

2024-02-15 10:49 UTC, fshabanov requested changes

2024-02-15 10:49 UTC, fshabanov commented on apps/backend/src/modules/courses/course.service.ts
> +		return this.udemy.getCourses({}).then((result) => result.json());
```suggestion
		return this.udemy.getCourses().then((result) => result.json());
```

2024-02-15 11:03 UTC, what1s1ove commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +		return await this.http.load(this.baseUrl, options);
we can avoid createing it's own method, but you need to describe all options explicitly, as on the frontend

2024-02-15 11:16 UTC, KrasKa2 commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +		return await this.http.load(this.baseUrl, options);
I think I understand, but I am not sure... Can you check last commit - https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/88/commits/8ad53377788e20fbd4c01beb467565deb51b49e3 ?

2024-02-15 12:09 UTC, KrasKa2 commented on apps/backend/src/libs/modules/udemy/udemy.module.ts
> +		return await this.http.load(this.baseUrl, options);
done

2024-02-15 12:47 UTC, YourTeaChan commented on apps/backend/src/libs/modules/http/base-http.module.ts
> +import { HTTP } from "./libs/types/types.js";
```suggestion
import { type HTTP } from "./libs/types/types.js";
```

2024-02-15 12:53 UTC, fshabanov requested changes

2024-02-15 12:53 UTC, fshabanov commented on apps/backend/src/modules/courses/course.controller.ts
> +	private async findAllByVendor(): Promise<APIHandlerResponse> {
Since it is `byVendor` we should receive Vendor data as a parameter

2024-02-15 12:53 UTC, fshabanov commented on apps/backend/src/modules/courses/course.controller.ts
> +			payload: await this.courseService.search(),
Not resolved

2024-02-15 13:03 UTC, KrasKa2 commented on apps/backend/src/modules/courses/course.controller.ts
> +			payload: await this.courseService.search(),
Hmm... I can't understand. [Here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/blob/65-feat-udemy-module/apps/backend/src/modules/courses/course.controller.ts) - findAllByVendor

But [here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/88/files/76158f478fee51bc96aa58404a1bfc8f37007ac6#diff-1b2f9cca4eed7cb393b1e4f3256ab09caa76a1abe1bd7a2df03df9f879c13154) - search

2024-02-15 13:07 UTC, KrasKa2 commented on apps/backend/src/modules/courses/course.controller.ts
> +			payload: await this.courseService.search(),
@fshabanov  It was fixed in [this commit](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/commit/fa7c21c78cf5ddd5ef539954c0fe40dd059b7007)

2024-02-15 13:17 UTC, fshabanov commented on apps/backend/src/modules/courses/course.controller.ts
> +			payload: await this.courseService.search(),
@KrasKa2 the method name in course service is not changed though 🤔

2024-02-15 13:33 UTC, what1s1ove requested changes

2024-02-15 13:33 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +	private async findAllByVendor(): Promise<APIHandlerResponse> {
Right! We will do it text task

2024-02-15 13:33 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.controller.ts
> +			payload: await this.courseService.search(),
it's still `search`

2024-02-15 13:33 UTC, what1s1ove commented on apps/backend/src/modules/courses/course.service.ts
> +	public search(): Promise<unknown> {
```suggestion
	public findAllByVendor(): Promise<unknown> {
```

2024-02-15 14:13 UTC, KrasKa2 commented on apps/backend/src/modules/courses/course.service.ts
> +	public search(): Promise<unknown> {
@what1s1ove , Я не знаю, чому тут diff показує search. У мене локально - findAllByVendor, на gitHub якщо зайти в гілку - теж findAllByVendor

2024-02-15 14:20 UTC, KrasKa2 commented on apps/backend/src/modules/courses/course.controller.ts
> +			payload: await this.courseService.search(),
I'm sorry. I saw on controller

2024-02-15 14:27 UTC, fshabanov requested changes

2024-02-15 14:27 UTC, fshabanov commented on apps/backend/src/modules/courses/course.controller.ts
> +	private async findAllByVendor(): Promise<APIHandlerResponse> {
Add Swagger docs comment

2024-02-15 14:29 UTC, fshabanov approved these changes

2024-02-15 15:34 UTC, what1s1ove approved these changes

2024-02-15 15:35 UTC, merged