feat: hide/show password functionality on sign-in/up page tm-71
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #89
Opened 2024-02-15 02:10 UTC by YourTeaChan

- Password is shown

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/32448037-7e8b-4434-8eb7-f6e7d341d540)

- Password is hidden

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61264049/ef2c9cca-6a28-4f8e-b3a4-969c915eae29)

2024-02-15 06:25 UTC, Ann-Maksay approved these changes

2024-02-15 06:28 UTC, GEOFARL commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +	const [isPasswordVisible, setPasswordVisibility] = useState(false);
Probably we can extract this logic into a separate hook

2024-02-15 06:31 UTC, GEOFARL commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +
Probably we can extract this logic with password visibility into a separate hook

2024-02-15 07:35 UTC, MappariChan approved these changes

2024-02-15 07:52 UTC, fshabanov requested changes

2024-02-15 07:52 UTC, fshabanov commented on apps/frontend/src/libs/components/icon-button/icon-button.tsx
> +const IconButton: React.FC<Properties> = ({
Use Button component instead. Add a new prop to it `hasVisuallyHiddenLabel`, if it is true we hide the label and show only icon

2024-02-15 08:19 UTC, what1s1ove requested changes

2024-02-15 08:19 UTC, what1s1ove commented on apps/frontend/src/libs/components/icon-button/icon-button.tsx
> +const IconButton: React.FC<Properties> = ({
agreed

2024-02-15 08:19 UTC, what1s1ove commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +
let's do not do it this time. but thanks about suggestion

2024-02-15 08:19 UTC, what1s1ove commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +	const [isPasswordVisible, setPasswordVisibility] = useState(false);
always add type to useState

2024-02-15 08:19 UTC, what1s1ove commented on apps/frontend/src/pages/auth/components/sign-up-form/sign-up-form.tsx
> +	const [isPasswordVisible, setPasswordVisibility] = useState(false);
same

2024-02-15 12:59 UTC, fshabanov requested changes

2024-02-15 12:59 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +					{!hasVisuallyHiddenLabel && label}
If `hasVisuallyHiddenLabel` is true add `visually-hidden` class, label should always be in the markup

2024-02-15 12:59 UTC, fshabanov commented on apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx
> +	const handlePasswordVisibility = useCallback(() => {
```suggestion
	const handleChangePasswordVisibility = useCallback(() => {
```

2024-02-16 02:20 UTC, ShadowOfTheSpace approved these changes

2024-02-16 06:19 UTC, GEOFARL approved these changes

2024-02-16 08:17 UTC, what1s1ove approved these changes

2024-02-16 08:18 UTC, merged