feat: sidebar mobile responsiveness tm-59
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #90
Opened 2024-02-15 07:10 UTC by ShadowOfTheSpace

- Tablet view
![tablet-sidebar](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61262913/47aa7f57-a2b1-4cad-87eb-871c5893785f)

- Mobile view
![mobile-sidebar](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/61262913/afdf31f4-5e8f-4aed-8bb3-8285d791eadc)

2024-02-15 07:48 UTC, GEOFARL commented on apps/frontend/src/libs/components/icon/icon.tsx
> +const Icon: React.FC<HTMLProps<SVGSVGElement> & Properties> = ({
Farid asked to remove unnecessary props [here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/68#discussion_r1489558417)

2024-02-15 07:48 UTC, GEOFARL commented on apps/frontend/src/libs/components/icon/libs/maps/icon-name-to-svg.map.ts
> +import { IconName } from "../types/types.js";
```suggestion
import { type IconName } from "../types/types.js";
```

2024-02-15 07:48 UTC, GEOFARL commented on apps/frontend/src/libs/components/icon/libs/types/icon-name.type.ts
> +export { IconName };
```suggestion
export { type IconName };
```

2024-02-15 07:49 UTC, YourTeaChan requested changes

2024-02-15 07:49 UTC, YourTeaChan commented on apps/frontend/src/libs/components/app/app.tsx
> +} from "~/libs/components/components.js";
This imports should be from components themselves, not from components.js

2024-02-15 08:07 UTC, Oleksandra-Masiuk requested changes

2024-02-15 08:07 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/blurred-background/blurred-background.tsx
> +		<button
Why do you use html button and not the `Button` component?

2024-02-15 08:23 UTC, what1s1ove requested changes
merge the main branch into your branch because you have a lot of changed that we already have in the main brach

2024-02-15 11:34 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +	z-index: 100;
I make those indents (99, 100, 101) to be confident that no other elements in the future can be higher then those. Or you advice me to change these values to 1, 2, 3 or something like that?

2024-02-15 12:47 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +	z-index: 100;
I am talking about the spaces at the beginning of a code line

2024-02-15 14:04 UTC, Oleksandra-Masiuk commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +	z-index: 100;
yes, probably it is a view bug

2024-02-15 16:28 UTC, fshabanov requested changes

2024-02-15 16:28 UTC, fshabanov commented on apps/frontend/src/libs/components/app/app.tsx
> +import { checkIfSidebarIsShown } from "~/libs/helpers/helpers.js";
This helper was removed, check the implementation in the main branch

2024-02-15 16:28 UTC, fshabanov commented on apps/frontend/src/libs/components/button/button.tsx
> +	const labelStyle = hasVisuallyHiddenLabel ? "visually-hidden" : undefined;
```suggestion
	const labelStyle = getValidClassNames(hasVisuallyHiddenLabel && "visually-hidden");
```

2024-02-15 16:28 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +				onClick={handleCloseSidebar}
```suggestion
				onClick={handleToggleSidebar}
```
This component will be present only if `isOpen` is true, that means toggle will make it false

2024-02-15 16:28 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/styles.module.css
> +		z-index: 101;
Move z-index values to global variables. Use 10, 100, 1000

2024-02-15 16:28 UTC, fshabanov commented on apps/frontend/src/libs/enums/app-route.enum.ts
> +	OVERVIEW: "/overview",
We don't have /overview, the Overview screen is in ROOT (/)

2024-02-16 02:19 UTC, YourTeaChan approved these changes

2024-02-16 03:15 UTC, Ann-Maksay approved these changes

2024-02-16 06:25 UTC, GEOFARL commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
>  		setOpen(!isOpen);
```suggestion
		setOpen((previous) => !previous);
```

2024-02-16 08:21 UTC, what1s1ove requested changes

2024-02-16 08:21 UTC, what1s1ove commented on apps/frontend/src/libs/components/button/button.tsx
> +	hasVisuallyHiddenLabel?: boolean;
merge main into your branch to avoid unnecessary file changes in pr

2024-02-16 09:34 UTC, fshabanov requested changes

2024-02-16 09:34 UTC, fshabanov commented on apps/frontend/src/libs/components/sidebar/sidebar.tsx
> +import React from "react";
```suggestion
```

2024-02-16 09:59 UTC, Sytnikovakatya approved these changes

2024-02-16 10:32 UTC, GEOFARL commented on apps/frontend/src/libs/components/blurred-background/styles.module.css
> +	background-color: #004a40b3;
```suggestion
	background-color: var(--modal-container-background);
```

2024-02-16 10:32 UTC, GEOFARL commented on apps/frontend/src/libs/components/blurred-background/styles.module.css
> +	background-color: #004a40b3;
```suggestion
	background-color: var(--modal-container-background);
```

2024-02-16 12:35 UTC, MappariChan approved these changes

2024-02-16 14:05 UTC, what1s1ove approved these changes

2024-02-16 14:05 UTC, merged