fix: sign up client tm-12
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #93
Opened 2024-02-15 15:00 UTC by Sytnikovakatya

1. Update styles to fix form layout when errors appear
2. Update validation schema, rules, and messages
3. Fix logo title and logo image

![Screenshot_4](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/106179834/ec21297e-60b9-4c1c-867a-044bbbe085aa)

2024-02-15 15:37 UTC, what1s1ove requested changes

2024-02-15 15:37 UTC, what1s1ove commented on apps/frontend/src/pages/auth/auth.tsx
>  					<img alt="TrackMates logo" className={styles["logo"]} src={logo} />
we need to use `picture` element instead

2024-02-15 15:37 UTC, what1s1ove commented on package-lock.json
this file should not be changed since you did not install/any packages

2024-02-15 15:42 UTC, fshabanov requested changes

2024-02-15 15:42 UTC, fshabanov commented on packages/shared/src/modules/users/libs/enums/user-validation-message.enum.ts
> +	EMAIL_REQUIRE: "The field is required",
EMAIL_REQUIRE and FIELD_REQUIRE are now the same

2024-02-15 16:34 UTC, Sytnikovakatya commented on package-lock.json
I don't now why it has changed. I've just merged main branch. I didn't install anything
What shall I do with it now?

2024-02-15 18:44 UTC, Sytnikovakatya commented on package-lock.json
Coulld I just delete it?

2024-02-15 21:10 UTC, YourTeaChan approved these changes

2024-02-16 02:34 UTC, ShadowOfTheSpace commented on package-lock.json
I think, if you did not install or delete any packages, you should not commit `package-lock.json` while merging. So `package-lock.json` will not change on remote repo.

2024-02-16 02:34 UTC, ShadowOfTheSpace approved these changes

2024-02-16 06:22 UTC, GEOFARL approved these changes

2024-02-16 08:23 UTC, what1s1ove requested changes

2024-02-16 08:23 UTC, what1s1ove commented on package-lock.json
this file should not be changed since you did not change anything in package.jsons

2024-02-16 08:23 UTC, what1s1ove commented on apps/frontend/src/pages/auth/auth.tsx
> +					<Image alt="TrackMates logo" className={styles["logo"]} src={logo} />
we have 3 images here. it's not that we want. please, use `picture` tag here instead

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

2024-02-16 09:26 UTC, Sytnikovakatya commented on package-lock.json
Finally, I fixed it. Thanks a lot @ShadowOfTheSpace

2024-02-16 11:43 UTC, Ann-Maksay approved these changes

2024-02-16 12:24 UTC, MappariChan approved these changes

2024-02-16 14:06 UTC, what1s1ove commented on apps/frontend/src/pages/auth/auth.tsx
> +					<Image alt="TrackMates" src={logoName} />
why we need two images here? can we use only one here?

2024-02-16 15:21 UTC, Sytnikovakatya commented on apps/frontend/src/pages/auth/auth.tsx
> +					<Image alt="TrackMates" src={logoName} />
The second image we use for logo text ("TrackMates"). It was pointed by QA, because they wanted  pixel perfect logo like in Figma

2024-02-16 15:29 UTC, fshabanov commented on apps/frontend/src/pages/auth/auth.tsx
> +					<Image alt="TrackMates" src={logoName} />
I don't think that we should download this as a logo, because it's just a text
@what1s1ove what do you think?

2024-02-17 08:47 UTC, Vfivew approved these changes

2024-02-17 14:15 UTC, Oleksandra-Masiuk requested changes

2024-02-17 14:15 UTC, Oleksandra-Masiuk commented on apps/frontend/src/pages/auth/auth.tsx
> +							className={`${styles["logo"]} ${styles["mobile-logo"]}`}
there is already implemented clsx helper for this

2024-02-17 16:12 UTC, Oleksandra-Masiuk approved these changes

2024-02-17 16:23 UTC, what1s1ove approved these changes

2024-02-17 16:23 UTC, merged