25 feat welcome section header
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #96
Opened 2024-02-15 19:38 UTC by MappariChan

fix welcome section header subtitle line height and add overall overview page padding

2024-02-15 21:35 UTC, YourTeaChan approved these changes

2024-02-16 02:27 UTC, ShadowOfTheSpace requested changes

2024-02-16 02:27 UTC, ShadowOfTheSpace commented on apps/frontend/package.json
> +		"vite-plugin-svgr": "4.2.0"
```suggestion
		"shared": "*"
```
We have this package in devDependencies already (Vlad changed it recently [commit])(https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/commit/da822e6292963015a4c93b7cbfac6cce49d72dde)

2024-02-16 06:21 UTC, GEOFARL approved these changes

2024-02-16 08:24 UTC, what1s1ove requested changes

2024-02-16 08:24 UTC, what1s1ove commented on apps/frontend/package.json
> +		"vite-plugin-svgr": "4.2.0"
right

2024-02-16 09:44 UTC, fshabanov requested changes
Add the screenshot of a final result

2024-02-16 09:56 UTC, Sytnikovakatya approved these changes

2024-02-16 12:20 UTC, MappariChan commented
> Add the screenshot of a final result

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/04b279fe-1ce2-4d5b-b7d1-9895439940f1)

2024-02-16 14:05 UTC, what1s1ove approved these changes

2024-02-16 14:05 UTC, merged