feat: Overview screen mobile responsiveness tm-61
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #98
Opened 2024-02-16 10:29 UTC by Ann-Maksay

There's nothing to style in the header for now, as there's only an image 

- Mobile:
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/c40be490-7649-40ff-824d-0d34fb4e2827) 
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/9fab70fa-8579-4fc2-8cb4-456d7189df43)

- Tablets
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/ab8a697a-4cd0-44f1-bb79-68cc884d3379)

- 1024px

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/7d0ae5fa-8e3c-44d0-b346-40e0601bb12c)

-Desktop
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/9c277251-e605-450e-b6f5-517995a6a3c2)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/8a483e5f-3f77-4792-9e88-468a12c7e63e)

-Since we have a maximum length of 16 characters for the first name and 26 characters for the last name.
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/ecd5ab73-bc56-4c07-9d08-072543256c05)

![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/2696a148-ea49-460d-95f3-cc5c614a9608)
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/71721870/ac1ce585-6588-4b49-abe7-13cffbd03419)

2024-02-16 10:36 UTC, GEOFARL commented on apps/frontend/src/libs/components/blurred-background/styles.module.css
> +	background-color: #004a40b3;
```suggestion
	background-color: var(--modal-container-background);
```

2024-02-16 10:36 UTC, GEOFARL commented on apps/frontend/src/libs/components/blurred-background/styles.module.css
> +	background-color: #004a40b3;
```suggestion
	background-color: var(--modal-container-background);
```

2024-02-16 10:42 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/blurred-background/styles.module.css
> +	background-color: #004a40b3;
Це частина коду з пулл реквесту #90

2024-02-16 11:10 UTC, ShadowOfTheSpace commented on apps/frontend/src/libs/components/blurred-background/styles.module.css
> +	background-color: #004a40b3;
Зараз як раз виправляю)

2024-02-16 11:17 UTC, YourTeaChan commented on apps/frontend/src/libs/components/courses/styles.module.css
> +}
We have only 3 breakpoints: 1024px, 768px and 480px. It was mentioned in my PR https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/76#discussion_r1489078279

2024-02-16 11:21 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/courses/styles.module.css
> +}
I think there needs to be confirmation from the coaches if we are really limited to just these breakpoints. I can make the design look ok on them, but it breaks between

2024-02-16 14:07 UTC, what1s1ove requested changes
Please, merge `main` branch into your branch

2024-02-16 18:15 UTC, fshabanov reviewed
Why is there a strange white space above the sidebar?

2024-02-16 18:18 UTC, Ann-Maksay commented
> Why is there a strange white space above the sidebar?

This is the list of users that we temporarily render above all other content in the app component

2024-02-16 18:22 UTC, MappariChan commented
Maybe you can add `display: none` attribute to the list above sidebar, so it will use users slice and we won't be able to see it

2024-02-17 09:34 UTC, Vfivew approved these changes

2024-02-17 09:34 UTC, Vfivew commented on apps/frontend/src/libs/components/auth-wrapper/styles.module.css
> +@media screen and (width <= 1025px) {
You use 
(width <= 1025px)
But we used
(width <= 1024px)  in 
[here](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/blob/main/apps/frontend/src/pages/auth/styles.module.css)
Can't we use one checkpoint or is it necessary here?

2024-02-17 11:11 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/auth-wrapper/styles.module.css
> +@media screen and (width <= 1025px) {
Good point! I was mixed up and was sure our main breakpoint was 1025

2024-02-17 11:56 UTC, GEOFARL commented on apps/frontend/src/libs/components/auth-wrapper/styles.module.css
> +	height: 100%;
```suggestion
	min-height: 100vh;
```
Wouldn't it be better?

2024-02-17 12:25 UTC, Ann-Maksay commented on apps/frontend/src/libs/components/auth-wrapper/styles.module.css
> +	height: 100%;
We already have min-height for `body` so I think % it is fine there

2024-02-17 14:11 UTC, what1s1ove commented on apps/frontend/src/libs/components/app/app.tsx
> +			<ul className="visually-hidden">
we will remove it in a separate task

2024-02-17 14:18 UTC, what1s1ove approved these changes

2024-02-17 14:18 UTC, what1s1ove commented on apps/frontend/src/libs/components/app/app.tsx
> +			<ul className="visually-hidden">
Resolved in https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/109

2024-02-17 14:18 UTC, merged