feat: aws s3 integration tm-41
BinaryStudioAcademy/bsa-winter-2023-2024-trackmates pull request #99
Opened 2024-02-16 10:48 UTC by MappariChan

2024-02-16 10:53 UTC, GEOFARL approved these changes

2024-02-16 12:25 UTC, YourTeaChan commented on apps/backend/src/modules/profile/profile.repository.ts
> +import { Repository } from "~/libs/types/repository.type.js";
```suggestion
import { type Repository } from "~/libs/types/repository.type.js";
```

2024-02-16 12:26 UTC, YourTeaChan commented on apps/backend/src/modules/profile/profile.service.ts
> +import { AvatarUploadResponseDto } from "./libs/types/types.js";
```suggestion
import { type AvatarUploadResponseDto } from "./libs/types/types.js";
```

2024-02-16 12:27 UTC, YourTeaChan commented on apps/backend/src/modules/profile/profile.service.ts
> +import { Service } from "~/libs/types/service.type.js";
```suggestion
import { type Service } from "~/libs/types/service.type.js";
```

2024-02-16 13:04 UTC, fshabanov requested changes
Let's create a new Fastify plugin for file uploads. The plugin should receive the file, convert it to Buffer, also get file name and contentType. You should also check contentType so that the user cannot upload files other than images

2024-02-16 13:04 UTC, fshabanov commented on apps/backend/src/libs/modules/s3/base-s3.module.ts
> +import { Upload } from "@aws-sdk/lib-storage";
In `@aws-sdk/client-s3` there is `PutObjectCommand`. Let's use it and remove `@aws-sdk/lib-storage`

2024-02-16 13:04 UTC, fshabanov commented on apps/backend/src/libs/modules/s3/base-s3.module.ts
> +	async upload(file: Readable, fileName: string): Promise<null | string> {
```suggestion
	async upload(file: Buffer, fileName: string): Promise<null | string> {
```

2024-02-16 13:04 UTC, fshabanov commented on apps/backend/src/modules/profile/profile.repository.ts
> +import { type Repository } from "~/libs/types/repository.type.js";
```suggestion
import { type Repository } from "~/libs/types/types.js";
```

2024-02-16 20:22 UTC, MappariChan commented on apps/backend/src/libs/modules/s3/base-s3.module.ts
> +import { Upload } from "@aws-sdk/lib-storage";
I would like to leave Upload object, because `PutObjectCommandOutput` doesn't provide URL of the uploaded object, so we need to generate URL manually, so can i leave this approach?

2024-02-18 11:31 UTC, MappariChan commented on apps/backend/index.d.ts
> +		uploadedFile?: MultipartFile | null;
i can't rename it because instance of fastify request already has method of name file, so i cant overwrite it

2024-02-18 14:08 UTC, GEOFARL commented on apps/backend/src/modules/files/file.controller.ts
> +import { UserAuthResponseDto } from "shared";
not a type import and from shared

2024-02-18 14:08 UTC, GEOFARL commented on apps/backend/src/modules/files/files.ts
> +export { UploadedFile } from "./libs/types/types.js";
```suggestion
export { type UploadedFile } from "./libs/types/types.js";
```

2024-02-19 06:38 UTC, fshabanov commented on apps/backend/src/db/migrations/20240217102441_add_files_table.ts
> +				.references("id")
```suggestion
				.references(ColumnName.ID)
```

2024-02-19 06:47 UTC, fshabanov commented on apps/backend/src/libs/modules/file/file.module.ts
> +				throw new Error("error");
Fix this TODO comment

2024-02-19 06:50 UTC, fshabanov commented on apps/backend/src/libs/modules/file/file.module.ts
> +class BaseFile implements File {
It doesn't need to implement anything

2024-02-19 06:51 UTC, fshabanov commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +					buffer: buffer,
```suggestion
					buffer,
```

2024-02-19 06:52 UTC, fshabanov commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +		if (request.isMultipart()) {
```suggestion
		if (!request.isMultipart()) {
		  return;
		}
```
To avoid nested `if` statements

2024-02-19 06:53 UTC, fshabanov commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +			if (data && data.mimetype.includes("image")) {
Create a constant with allowed extensions, send it as an option to this plugin

2024-02-19 06:53 UTC, fshabanov commented on apps/backend/src/modules/files/file.entity.ts
> +		contentType: string;
Should be valueof enum

2024-02-19 06:54 UTC, fshabanov commented on apps/backend/src/modules/files/file.model.ts
> +					to: `${DatabaseTableName.USER_DETAILS}.file_id`,
But in migration you names the column avatar_file_id

2024-02-19 08:14 UTC, what1s1ove requested changes

2024-02-19 08:14 UTC, what1s1ove commented on .prettierignore
merge main into your branch

2024-02-19 08:14 UTC, what1s1ove commented on apps/backend/index.d.ts
> +		uploadedFile?: UploadedFile | null;
```suggestion
		file?: UploadedFile | null;
```

2024-02-19 08:14 UTC, what1s1ove commented on apps/backend/src/libs/modules/file/file.ts
> +const file = new BaseFile(config);
```suggestion
const file = new File(config);
```
base only for implementation things

2024-02-19 08:14 UTC, what1s1ove commented on apps/backend/src/modules/files/file.entity.ts
> +	private id: null | number;
id can not be null

2024-02-19 08:14 UTC, what1s1ove commented on packages/shared/src/modules/files/libs/enums/files-api-path.enum.ts
> +	UPLOAD: "/upload-avatar",
```suggestion
	UPLOAD_AVATAR: "/upload-avatar",
```

2024-02-19 10:20 UTC, MappariChan commented on apps/backend/src/modules/files/file.entity.ts
> +	private id: null | number;
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/3d66a62c-613a-406a-9236-205cdb67e9a6)
We have such thing in the UserEntity and it also has some logic, because of the method initializeNew() which creates UserEntity without id, same as FileEntity
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/45849406-cc6a-4df0-9df9-da2f44282e9a)

2024-02-19 10:27 UTC, MappariChan commented on apps/backend/index.d.ts
> +		uploadedFile?: UploadedFile | null;
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/99#discussion_r1493743943

2024-02-19 11:25 UTC, fshabanov commented on apps/backend/index.d.ts
> +		uploadedFile?: UploadedFile | null;
But [FastifyRequest](https://fastify.dev/docs/latest/Reference/Request/) doesn't have a property named file 🤔

2024-02-19 11:39 UTC, MappariChan commented on apps/backend/index.d.ts
> +		uploadedFile?: UploadedFile | null;
By default it doesn't have but it is extension added by @fastify/multipart, for getting file that was passed to the request body

2024-02-19 11:44 UTC, MappariChan commented on apps/backend/index.d.ts
> +		uploadedFile?: UploadedFile | null;
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/7357b00a-1893-41a8-b739-c2aa16bd1028)

2024-02-19 12:55 UTC, fshabanov requested changes

2024-02-19 12:55 UTC, fshabanov commented on apps/backend/src/libs/modules/file/file.module.ts
> +	}) {
`type Constructor = ...`

2024-02-19 12:55 UTC, fshabanov commented on apps/backend/src/modules/files/libs/enums/files-content-type.enum.ts
> +const FilesContentType = {
We already have `ContentType` enum, use it

2024-02-19 12:55 UTC, fshabanov commented on apps/backend/src/libs/plugins/file-upload/libs/types/types.ts
> +export { type ValueOf } from "shared";
We have it in `~/libs/types/types.js`

2024-02-19 12:55 UTC, fshabanov commented on apps/backend/src/modules/files/file.controller.ts
> +class FileController extends BaseController {
Add Swagger docs

2024-02-19 12:55 UTC, fshabanov commented on apps/backend/src/modules/files/libs/types/uploaded-file.type.ts
> +import { type ValueOf } from "shared";
Don't import directly from shared here

2024-02-19 12:55 UTC, fshabanov commented on apps/backend/src/modules/users/user-details/user-details.model.ts
> +import { FileModel } from "../../files/file.model.js";
```suggestion
import { FileModel } from "~/...";
```

2024-02-19 16:30 UTC, fshabanov requested changes

2024-02-19 16:30 UTC, fshabanov commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +			const data = await request.file();
Handle the case for a file of a big size

2024-02-19 19:02 UTC, fshabanov requested changes

2024-02-19 19:02 UTC, fshabanov commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +		});
Try to upload an image with a very big size, there will be an error that you don't handle

2024-02-19 20:04 UTC, MappariChan commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +		});
I tested with 30mb image, can you tell me exact size?

2024-02-19 20:23 UTC, MappariChan commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +		});
![image](https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/assets/126669822/636e8789-9e2e-43bc-add5-e75927466545)
I tested with 91mb image

2024-02-20 10:09 UTC, what1s1ove requested changes

2024-02-20 10:09 UTC, what1s1ove commented on packages/shared/src/libs/helpers/get-size-in-mb/get-size-in-mb.helper.ts
> +	return amount * kilo * kilo;
```suggestion
const YUORCONST = value;

const getSizeInMb = (amount: number): number => {
	
	return amount * YUORCONST * YUORCONST;
```

2024-02-20 10:09 UTC, what1s1ove commented on apps/backend/src/modules/files/file.service.ts
> +		return Promise.resolve(payload);
implement them

2024-02-20 10:09 UTC, what1s1ove commented on apps/backend/src/modules/files/file.repository.ts
> +		return Promise.resolve(true);
implement them

2024-02-20 10:09 UTC, what1s1ove commented on apps/backend/src/modules/files/file.entity.ts
> +	private id: null | number;
go it, thanks

2024-02-20 10:09 UTC, what1s1ove commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +				const maxFileSize = 5;
should be a constant

2024-02-20 10:09 UTC, what1s1ove commented on apps/backend/src/libs/modules/server-application/base-server-application.ts
> +		const sizeInMB = 100;
should be a constant

2024-02-20 10:09 UTC, what1s1ove commented on apps/backend/src/libs/modules/file/file.module.ts
> +import { S3Client } from "@aws-sdk/client-s3";
all this logic should be a part of `apps/backend/src/modules/files`

2024-02-20 10:20 UTC, MappariChan commented on apps/backend/src/modules/files/file.entity.ts
> +	private id: null | number;
it means i should leave this, or replace? I'm asking just to be certain)

2024-02-20 11:21 UTC, fshabanov requested changes

2024-02-20 11:21 UTC, fshabanov commented on apps/backend/src/db/migrations/20240217102441_add_files_table.ts
> +const DETAILS_TABLE_NAME = "user_details";
Rule B29

2024-02-20 11:21 UTC, fshabanov commented on apps/backend/src/modules/files/file.model.ts
> +					to: `${DatabaseTableName.USER_DETAILS}.avatar_file_id`,
Use camelCase here

2024-02-20 16:23 UTC, MappariChan commented on apps/backend/src/libs/modules/file/file.module.ts
> +import { S3Client } from "@aws-sdk/client-s3";
do you mean creating S3Client?

2024-02-20 16:39 UTC, MappariChan commented
I implemented changed service and repository, but i also needed to rewrite some logic in user service and repository, because after rewriting Service and Repository types there was errors, just you to know. And also, maybe we should create base repository, otherwise there will be a lot of duplicate logic in repositories.

2024-02-20 19:17 UTC, fshabanov requested changes

2024-02-20 19:17 UTC, fshabanov commented on apps/backend/src/libs/modules/server-application/libs/constants/max-form-data-file-size.constant.ts
> +const MAX_FORM_DATA_FILE_SIZE = 100;
I think 100 MB is too much

2024-02-20 19:17 UTC, fshabanov commented on apps/backend/tsconfig.json
> +	],
1. You can't change this file
2. Why would tsconfig in backend include a file from frontend?
3. There's no such file in frontend

2024-02-20 19:17 UTC, fshabanov commented on packages/shared/src/libs/helpers/get-size-in-mb/get-size-in-mb.helper.ts
> +const kilo = 1024;
1. Constants should be written in capital letters
2. The name kilo is not good in this case

2024-02-20 19:29 UTC, MappariChan commented on apps/backend/src/libs/modules/server-application/base-server-application.ts
> +	MAX_FORM_DATA_FILE_SIZE,
Previously you asked for the custom error, so I tried to handle fastifyMultipart error and after send mine, but it doesn't works well, so my decision was to configure multipart to handle all file which size is lower than 100 mb but in the upload plugin I'm checking byteLength of the buffer and if it is lower than 5 mb I throw an error.

2024-02-20 19:30 UTC, MappariChan commented on apps/backend/src/libs/modules/server-application/libs/constants/max-form-data-file-size.constant.ts
> +const MAX_FORM_DATA_FILE_SIZE = 100;
https://github.com/BinaryStudioAcademy/bsa-winter-2023-2024-trackmates/pull/99#discussion_r1496379858

2024-02-20 19:30 UTC, MappariChan commented on apps/backend/tsconfig.json
> +	],
Oh sorry, my bad

2024-02-20 19:49 UTC, MappariChan commented on apps/backend/src/libs/modules/server-application/base-server-application.ts
> +	MAX_FORM_DATA_FILE_SIZE,
If i remove limit in fastifyMultipart plugin, it will cause error all time when we will try to send file of size more than 1 mb, so this limit in 100 mb prevent fastifyMultipart to send error.

2024-02-20 21:56 UTC, Vfivew commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +import { ValueOf } from "~/libs/types/types.js";
```suggestion
import { type ValueOf } from "~/libs/types/types.js";
```

2024-02-21 06:27 UTC, fshabanov commented on apps/backend/src/libs/modules/server-application/base-server-application.ts
> +	MAX_FORM_DATA_FILE_SIZE,
Check [this](https://github.com/fastify/fastify-multipart#:~:text=or%20check%20at%20the%20end%20of%20the%20stream%20the%20property%20data.file.truncated)

2024-02-21 10:20 UTC, what1s1ove requested changes

2024-02-21 10:20 UTC, what1s1ove commented on apps/backend/src/libs/modules/file/file.module.ts
> +import { S3Client } from "@aws-sdk/client-s3";
right. we do not need to have this module add all – apps/backend/src/libs/modules/file/file.module.ts

2024-02-21 10:20 UTC, what1s1ove commented on apps/backend/src/libs/types/repository.type.ts
> +	delete(id: number): Promise<number>;
```suggestion
	delete(id: number): Promise<boolean>;
```

2024-02-21 10:20 UTC, what1s1ove commented on apps/backend/src/libs/types/service.type.ts
> +	delete(id: number): Promise<number>;
```suggestion
	delete(id: number): Promise<boolean>;
```

2024-02-21 10:20 UTC, what1s1ove commented on apps/backend/src/modules/users/user.repository.ts
> +			avatarUrl: "",
```suggestion
			avatarUrl: null,
```

2024-02-21 10:20 UTC, what1s1ove commented on apps/backend/src/modules/users/user.service.ts
> +			throw new HTTPError({
should be users-error

2024-02-21 11:16 UTC, YourTeaChan approved these changes

2024-02-21 14:54 UTC, GEOFARL commented on packages/shared/src/modules/users/libs/exceptions/user-error.ts
> +import { ValueOf } from "../../../../libs/types/value-of.type.js";
```suggestion
import { type ValueOf } from "../../../../libs/types/types.js";
```

2024-02-21 15:50 UTC, what1s1ove requested changes

2024-02-21 15:50 UTC, what1s1ove commented on apps/backend/src/libs/types/service.type.ts
> +	findAll(): Promise<T[]>;
should be as an object with `items`

2024-02-21 15:50 UTC, what1s1ove commented on apps/backend/src/modules/files/file.module.ts
we do not have `module` prefix. i think it should be a part of a service

2024-02-21 15:50 UTC, what1s1ove commented on apps/backend/src/modules/users/user.repository.ts
> +			avatarUrl: "",
is not resolved

2024-02-21 19:03 UTC, fshabanov requested changes

2024-02-21 19:03 UTC, fshabanov commented on packages/shared/src/libs/constants/max-file-size.constant.ts
> +const MAX_FILE_SIZE = 5;
```suggestion
const MAX_FILE_SIZE_IN_MB = 5;
```

2024-02-21 19:03 UTC, fshabanov commented on packages/shared/src/libs/enums/exception-message.enum.ts
> +	FILE_IS_TO_LARGE: "File is too large.",
```suggestion
	FILE_IS_TOO_LARGE: "File is too large.",
```

2024-02-21 19:03 UTC, fshabanov commented on packages/shared/src/libs/helpers/get-size-in-mb/get-size-in-mb.helper.ts
> +};
But this helper gets size in bytes, not in megabytes

2024-02-21 19:34 UTC, Sytnikovakatya approved these changes

2024-02-22 08:17 UTC, what1s1ove requested changes

2024-02-22 08:17 UTC, what1s1ove commented on packages/shared/src/modules/users/libs/exceptions/user-error.ts
> +	public constructor(message: string, status: ValueOf<typeof HTTPCode>) {
should be object of params (see HTTPError)

2024-02-22 08:17 UTC, what1s1ove commented on packages/shared/src/modules/files/libs/exceptions/file-error.ts
> +	public constructor(message: string, status: ValueOf<typeof HTTPCode>) {
same

2024-02-22 16:21 UTC, fshabanov requested changes

2024-02-22 16:21 UTC, fshabanov commented on apps/backend/src/db/migrations/20240217102441_add_files_table.ts
> +
```suggestion
	UPDATED_AT: "updated_at",
	URL: "url",
	AVATAR_FILE_ID: "avatar_file_id",
} as const;

```

2024-02-22 16:21 UTC, fshabanov commented on apps/backend/src/modules/files/file.controller.ts
> +			throw new HTTPError({
Not resolved

2024-02-22 18:01 UTC, fshabanov requested changes

2024-02-22 18:01 UTC, fshabanov commented on apps/backend/src/libs/plugins/file-upload/file-upload.plugin.ts
> +					throw new HTTPError({
```suggestion
					throw new FileError({
```
Check your code again and fix if you have the same issue in other places

2024-02-22 20:06 UTC, fshabanov approved these changes

2024-02-22 21:20 UTC, Vfivew approved these changes

2024-02-23 07:01 UTC, what1s1ove approved these changes

2024-02-23 07:01 UTC, merged